// map-data/middle-earth/Forlindon.js

export const forlindonData = {
    pointsOfInterest: [
        // --- Forlindon POIs (North-West) ---
        {
            id: 'poi_me_forlond',
            x: 17.41, y: 19.71,
            type: 'port',
            subRegion: 'forlindon',
            name: "The Grey Havens of Forlond",
            description: "The primary Elven haven in the north, a city of serene beauty where grey ships with swan-prows wait to sail the Straight Road into the West. It is a place of longing and farewells, echoing with the sound of the sea and the songs of the Eldar. Gil-Galad once ruled here.",
            factionId: 'elves_of_lindon',
            intelReq: 5,
            political_influence: 9,
            economic_value: 8,
            military_strength: 7,
            population: 3000,
            age_of_antiquity: 10,
            magical_resonance: 9,
            crime_rate: 1,
        },
        {
            id: 'poi_me_himring',
            x: 15.07, y: 15.51,
            type: 'ruins',
            subRegion: 'forlindon',
            name: "The Isle of Himring",
            description: "A cold, windswept island that was once the site of Maedhros's mighty fortress. Now, only shattered foundations and a sense of profound sorrow remain, a testament to the long-forgotten wars against the first Dark Lord.",
            factionId: 'unaligned',
            intelReq: 25,
            political_influence: 2,
            economic_value: 2,
            military_strength: 3,
            population: 0,
            age_of_antiquity: 10,
            magical_resonance: 7,
            crime_rate: 2,
        },
        {
            id: 'poi_me_gilgalad_watch',
            x: 18.42, y: 18.03,
            type: 'watchtower',
            subRegion: 'forlindon',
            name: "Ruins of Gil-Galad's Watch",
            description: "The crumbling remains of a tall, elegant watchtower from the Second Age, where the High King Gil-Galad once lived and kept watch over the western seas. A powerful sense of history and loss pervades the ruins.",
            factionId: 'unaligned',
            intelReq: 15,
            political_influence: 2,
            economic_value: 1,
            military_strength: 3,
            population: 0,
            age_of_antiquity: 10,
            magical_resonance: 6,
            crime_rate: 1,
        },
        {
            id: 'poi_me_internet_portal',
            x: 18.08, y: 20.55,
            type: 'portal',
            subRegion: 'forlindon',
            name: "The First Datastream Estuary",
            description: "A strange, shimmering anomaly near the shores of Forlond where the fabric of reality thins. It is a stable, navigable estuary into the digital dimension of The Internet, often used by 'web-surfing' Elves and other dimensional travelers. It is monitored by both the Elves and the Internet Federation.",
            factionId: 'internet_federation',
            intelReq: 40,
            political_influence: 5,
            economic_value: 6,
            military_strength: 4,
            population: 20,
            age_of_antiquity: 1,
            magical_resonance: 10,
            crime_rate: 4,
        },

        // --- Harlindon POIs (South-West) ---
        {
            id: 'poi_me_harlond',
            x: 16.41, y: 28.10,
            type: 'port',
            subRegion: 'forlindon',
            name: "The Havens of Harlond",
            description: "The southern Elven haven of Lindon. It is smaller and quieter than Forlond, a green and peaceful land where many Elves lived before departing over the sea.",
            factionId: 'elves_of_lindon',
            intelReq: 10,
            political_influence: 7,
            economic_value: 6,
            military_strength: 5,
            population: 2000,
            age_of_antiquity: 10,
            magical_resonance: 8,
            crime_rate: 1,
        },
        {
            id: 'poi_me_elven_villas',
            x: 17.41, y: 28.94,
            type: 'village',
            subRegion: 'forlindon',
            name: "Elven Villas of Harlindon",
            description: "A series of beautiful villas and gardens dotting the green hills of southern Lindon. While many are now empty, a small population of Elves remains, tending to the last vestiges of their once-great realm.",
            factionId: 'elves_of_lindon',
            intelReq: 15,
            political_influence: 5,
            economic_value: 4,
            military_strength: 3,
            population: 800,
            age_of_antiquity: 10,
            magical_resonance: 7,
            crime_rate: 1,
        },
        {
            id: 'poi_me_harlindon_grove',
            x: 17.75, y: 27.26,
            type: 'forest',
            subRegion: 'forlindon',
            name: "The Singing Grove of Harlindon",
            description: "A small, beautiful grove of Mallorn trees, a rarity in this part of the world. The Elves of Harlindon tend to it, and the sound of their singing can often be heard among the golden leaves.",
            factionId: 'elves_of_lindon',
            intelReq: 20,
            political_influence: 4,
            economic_value: 2,
            military_strength: 3,
            population: 100,
            age_of_antiquity: 10,
            magical_resonance: 9,
            crime_rate: 1,
        },
    ],
    fogOfWar: []
};