// map-data/middle-earth/NorthernAureanPole.js

export const northernAureanPoleData = {
    pointsOfInterest: [
        { id: 'poi_np_frozen_base', x: 26.39, y: 8.43, type: 'ruins', name: "Frozen Research Base 'Aurora'", description: "An abandoned, high-tech research base from a precursor civilization, half-buried in the ice. Its systems are still powered, but the crew is long gone.", factionId: 'unaligned', intelReq: 40, political_influence: 1, economic_value: 7, military_strength: 4 },
        { id: 'poi_np_gateway_anomaly', x: 41.32, y: 7.10, type: 'portal', name: "The Gateway Anomaly", description: "A stable, shimmering rift in reality that hangs in the sky over the pole. Its destination is unknown, and it emits a constant, low hum of energy.", factionId: 'unaligned', intelReq: 80, political_influence: 2, economic_value: 5, military_strength: 5 },
        { id: 'poi_np_crystal_caves', x: 54.34, y: 9.50, type: 'cave_entrance', name: "The Ice Caves of Crystal", description: "A network of caves filled with massive, perfectly clear ice crystals that focus the polar light into strange and beautiful patterns. They possess unique magical properties.", factionId: 'unaligned', intelReq: 30, political_influence: 1, economic_value: 6, military_strength: 2 },
        { id: 'poi_np_wreck_polaris', x: 17.58, y: 7.77, type: 'shipwreck', name: "Wreckage of the 'Polaris'", description: "The crashed remains of a massive, unknown starship. Its advanced alloys are highly sought after by scavenger crews.", factionId: 'unaligned', intelReq: 35, political_influence: 1, economic_value: 8, military_strength: 2 },
        { id: 'poi_np_heat_vent_colony', x: 2.15, y: 8.76, type: 'lair', name: "Sub-glacial Heat Vent Colony", description: "A network of geothermal vents beneath the ice that supports a strange ecosystem of extremophile creatures. A unique and dangerous environment.", factionId: 'unaligned', intelReq: 25, political_influence: 1, economic_value: 4, military_strength: 4 },
        { id: 'poi_np_magnetic_pole', x: 46.08, y: 6.43, type: 'ley_line', name: "The True Magnetic Pole", description: "The geographic and magnetic pole of the world. Compasses spin wildly here, and the area is a nexus of powerful geomagnetic energy.", factionId: 'unaligned', intelReq: 15, political_influence: 2, economic_value: 3, military_strength: 1 },
        { id: 'poi_np_ice_worm_tunnels', x: 67.96, y: 7.27, type: 'dungeon_entrance', name: "Ice Worm Tunnels", description: "A vast network of tunnels bored through the glaciers by colossal, territorial Ice Worms. A perilous but direct route across the polar cap.", factionId: 'unaligned', intelReq: 30, political_influence: 1, economic_value: 2, military_strength: 6 },
        { id: 'poi_np_iron_legion_outpost', x: 72.29, y: 6.77, type: 'outpost', name: "Iron Legion Listening Post", description: "A small, heavily insulated Iron Legion outpost tasked with observing the Gateway Anomaly and ensuring no hostile forces emerge.", factionId: 'iron_legion', intelReq: 50, political_influence: 3, economic_value: 1, military_strength: 5 },
        { id: 'poi_np_ancient_monolith', x: 51.31, y: 9.59, type: 'shrine', name: "The Ancient Monolith", description: "A single, perfectly smooth black monolith of unknown origin that stands in the middle of the ice sheet. It is impervious to all damage and radiates a faint, cold energy.", factionId: 'unaligned', intelReq: 60, political_influence: 2, economic_value: 3, military_strength: 1 },
        { id: 'poi_np_frozen_mammoth', x: 6.47, y: 7.60, type: 'landmark', name: "The Frozen Mammoth Graveyard", description: "A site where dozens of colossal, prehistoric mammoths are perfectly preserved in the ice. A treasure trove for paleontologists and necromancers alike.", factionId: 'unaligned', intelReq: 20, political_influence: 1, economic_value: 4, military_strength: 2 },
    ],
    fogOfWar: []
};
