// map-data/middle-earth/Silbaarstadt.js

export const silbaarstadtData = {
    pointsOfInterest: [
        { id: 'poi_sb_silver_mines', x: 17.79, y: 43.25, type: 'mine', name: "The Great Silver Mines", description: "The legendary mines that give the region its name. They are said to be bottomless, a source of immense wealth but also home to deep, ancient dangers.", factionId: 'unaligned', intelReq: 15, political_influence: 4, economic_value: 10, military_strength: 4 },
        { id: 'poi_sb_clocktower', x: 20.31, y: 39.77, type: 'landmark', name: "The Great Clocktower", description: "A marvel of engineering, this colossal clocktower not only tells time but also tracks celestial movements with uncanny accuracy. A symbol of the city's ingenuity.", factionId: 'unaligned', intelReq: 10, political_influence: 5, economic_value: 3, military_strength: 2 },
        { id: 'poi_sb_iron_chancellor_keep', x: 24.35, y: 36.12, type: 'fortress', name: "The Iron Chancellor's Keep", description: "The seat of the region's autocratic ruler. A grim, iron-bound fortress that projects an aura of uncompromising order and industrial might.", factionId: 'iron_legion', intelReq: 30, political_influence: 9, economic_value: 5, military_strength: 9 },
        { id: 'poi_sb_alpine_pass', x: 27.89, y: 29.48, type: 'mountain_pass', name: "The Treacherous Alpine Pass", description: "The only year-round passable route through the high mountains. It is a vital trade route, but is often beset by avalanches and mountain predators.", factionId: 'unaligned', intelReq: 10, political_influence: 2, economic_value: 5, military_strength: 3 },
        { id: 'poi_sb_metallurgy_guild', x: 19.31, y: 40.60, type: 'workshop', name: "The Metallurgy Guildhall", description: "The powerful guild of master blacksmiths and engineers. They forge the finest steel in the land and jealously guard their techniques.", factionId: 'unaligned', intelReq: 20, political_influence: 6, economic_value: 8, military_strength: 4 },
        { id: 'poi_sb_black_forest', x: 14.19, y: 14.59, type: 'forest', name: "The Black Forest's Edge", description: "A dark and foreboding forest of ancient pines. It is said to be home to werewolves and other creatures of the night.", factionId: 'moonfang_pack', intelReq: 25, political_influence: 2, economic_value: 2, military_strength: 5 },
        { id: 'poi_sb_beer_hall', x: 13.81, y: 20.04, type: 'inn', name: "The Great Beer Hall", description: "The social heart of the region. A massive, boisterous hall where miners and smiths gather to drink legendary stout and sing songs of their ancestors.", factionId: 'unaligned', intelReq: 5, political_influence: 3, economic_value: 5, military_strength: 2 },
        { id: 'poi_sb_mountain_monastery', x: 24.07, y: 15.08, type: 'monastery', name: "Mountain Monastery", description: "A secluded monastery perched on a high cliff. Its monks are a silent, contemplative order who are said to be guardians of an ancient and dangerous secret.", factionId: 'unaligned', intelReq: 40, political_influence: 2, economic_value: 1, military_strength: 3 },
        { id: 'poi_sb_yodelers_peak', x: 28.52, y: 18.05, type: 'landmark', name: "Yodeler's Peak", description: "A mountain peak known for its incredible echo. Local tradition involves a yearly yodeling contest, which sometimes accidentally starts avalanches.", factionId: 'unaligned', intelReq: 5, political_influence: 1, economic_value: 1, military_strength: 1 },
        { id: 'poi_sb_wyvern_nest', x: 24.72, y: 24.50, type: 'lair', name: "Wyvern Nest", description: "The high, inaccessible nests of a flock of territorial Wyverns. Their venom is a valuable alchemical component, but harvesting it is a deadly profession.", factionId: 'unaligned', intelReq: 35, political_influence: 1, economic_value: 4, military_strength: 6 },
        { id: 'poi_sb_cable_car', x: 15.49, y: 44.91, type: 'trade_post', name: "The Great Cable Car", description: "A feat of engineering, this cable car system transports ore from the high mines down to the city for processing.", factionId: 'unaligned', intelReq: 10, political_influence: 2, economic_value: 7, military_strength: 2 },
        { id: 'poi_sb_ice_caves', x: 12.03, y: 48.06, type: 'cave_entrance', name: "Glacial Ice Caves", description: "A network of shimmering caves formed by an ancient glacier. They are beautiful but unstable, and are rumored to hold a perfectly preserved creature from a bygone age.", factionId: 'unaligned', intelReq: 20, political_influence: 1, economic_value: 3, military_strength: 2 },
        { id: 'poi_sb_hunting_lodge', x: 11.29, y: 29.32, type: 'village', name: "The Royal Hunting Lodge", description: "An opulent lodge used by the Iron Chancellor and his nobles for hunting expeditions into the Black Forest.", factionId: 'iron_legion', intelReq: 25, political_influence: 3, economic_value: 2, military_strength: 4 },
        { id: 'poi_sb_river_fort', x: 21.46, y: 38.77, type: 'fortress', name: "River Guard Fort", description: "A small but strong fort guarding the main river that flows from the mountains, controlling trade and travel by water.", factionId: 'iron_legion', intelReq: 20, political_influence: 4, economic_value: 4, military_strength: 7 },
        { id: 'poi_sb_ruined_hold', x: 19.96, y: 21.19, type: 'ruins', name: "Ruined Dwarven Hold", description: "The ancient, crumbling ruins of a Dwarven hold from before the arrival of Men. A potential source of lost treasures and forgotten smithing techniques.", factionId: 'unaligned', intelReq: 45, political_influence: 2, economic_value: 5, military_strength: 3 },
    ],
    fogOfWar: []
};
