// map-data/animatopia-pois.js
import { BUILDING_TYPES } from './building-types.js';

const pointsOfInterest = [
    // --- TUNDRATOWN (Predator Stronghold) ---
    { id: 'poi_an_predator_hq', subRegion: "TUNDRATOWN", x: 70.50, y: 20.00, type: 'fortress', name: "Predator Alliance HQ (The Frostfang Citadel)", description: "The military command center for the Predator Alliance, carved into a glacier. From here, they plan their conquest.", factionId: 'animatopia_predator_alliance', intelReq: 40, political_influence: 9, economic_value: 6, military_strength: 10, population: 3000 },
    { id: 'poi_an_tundratown_foundry', subRegion: "TUNDRATOWN", x: 68.00, y: 28.00, type: 'workshop', name: "Tundratown Foundry", description: "The primary weapons factory for the Predator Alliance, churning out arms and armor for the war effort.", factionId: 'animatopia_predator_alliance', intelReq: 35, political_influence: 4, economic_value: 8, military_strength: 7, population: 2000 },
    { id: 'poi_an_ice_wall_checkpoint', subRegion: "TUNDRATOWN", x: 61.50, y: 39.50, type: 'watchtower', name: "The Ice Wall Checkpoint", description: "A heavily armed checkpoint controlling the main route into Tundratown from the south. A key defensive position.", factionId: 'animatopia_predator_alliance', intelReq: 20, political_influence: 3, economic_value: 3, military_strength: 8, population: 200 },
    { id: 'poi_an_polar_bear_mafia', subRegion: "TUNDRATOWN", x: 75.00, y: 15.00, type: 'lair', name: "Polar Bear Mafia Den", description: "The headquarters of a powerful polar bear crime syndicate, who act as the Predator Alliance's unofficial enforcers and black marketeers.", factionId: 'freelancer_underworld', intelReq: 50, political_influence: 5, economic_value: 7, military_strength: 6, population: 500 },
    { id: 'poi_an_wolf_pack_den', subRegion: "TUNDRATOWN", x: 80.00, y: 40.00, type: 'lair', name: "Wolf Pack Forward Den", description: "A forward operating base for a particularly aggressive wolf pack aligned with the Predator Alliance.", factionId: 'animatopia_predator_alliance', intelReq: 30, political_influence: 3, economic_value: 2, military_strength: 6 },
    { id: 'poi_an_arctic_research_station', subRegion: "TUNDRATOWN", x: 65.00, y: 8.00, type: 'academy', name: "Arctic Research Station", description: "An old research station, now repurposed by the Predator Alliance to develop cold-weather warfare technologies.", factionId: 'animatopia_predator_alliance', intelReq: 45, political_influence: 4, economic_value: 5, military_strength: 5 },
    { id: 'poi_an_frozen_port', subRegion: "TUNDRATOWN", x: 58.00, y: 25.00, type: 'port', name: "The Frozen Port", description: "A port kept open by icebreaker ships, used to smuggle weapons and supplies to the Predator Alliance.", factionId: 'freelancer_underworld', intelReq: 35, political_influence: 3, economic_value: 7, military_strength: 4 },

    // --- SAVANNA CENTRAL (The Capital) ---
    { id: 'poi_an_capitol', subRegion: "SAVANNA CENTRAL", x: 45.00, y: 75.00, type: 'capital_city', name: "Animatopia Central Capitol", description: "The embattled seat of the central government. A symbol of unity now surrounded by conflict.", factionId: 'animatopia_prey_congress', intelReq: 10, political_influence: 10, economic_value: 8, military_strength: 7, population: 50000 },
    { id: 'poi_an_grand_central_station', subRegion: "SAVANNA CENTRAL", x: 53.00, y: 68.00, type: 'landmark', name: "Grand Central Station", description: "The main transit hub for the entire continent. Control of the station is critical for moving troops and supplies.", factionId: 'unaligned', intelReq: 5, political_influence: 6, economic_value: 9, military_strength: 5, population: 10000 },
    { id: 'poi_an_unity_plaza', subRegion: "SAVANNA CENTRAL", x: 48.00, y: 72.00, type: 'landmark', name: "Unity Plaza", description: "A once-bustling plaza meant to celebrate inter-species harmony. Now it's a heavily fortified 'Green Zone' and the site of frequent protests.", factionId: 'animatopia_prey_congress', intelReq: 15, political_influence: 7, economic_value: 4, military_strength: 6, population: 1000 },
    { id: 'poi_an_earth_land_embassy', subRegion: "SAVANNA CENTRAL", x: 50.00, y: 65.00, type: 'landmark', name: "Earth Land Federation Embassy", description: "The heavily fortified embassy of the powerful human-centric federation. They are here to 'observe' and protect their economic interests.", factionId: 'earth_land_federation', intelReq: 35, political_influence: 8, economic_value: 7, military_strength: 6, population: 200 },
    { id: 'poi_an_connectopia_consulate', subRegion: "SAVANNA CENTRAL", x: 48.00, y: 67.00, type: 'landmark', name: "Connectopia Pioneers' Guild Consulate", description: "A rugged, functional consulate representing the pioneer factions of Connectopia. They are here to establish trade routes and recruit mercenaries.", factionId: 'connectopia_pioneers_guild', intelReq: 30, political_influence: 5, economic_value: 8, military_strength: 4, population: 100 },
    { id: 'poi_an_liminal_consulate', subRegion: "SAVANNA CENTRAL", x: 46.00, y: 63.00, type: 'cosmic_anomaly', name: "The Shifting Consulate (Almost at the Edge)", description: "This 'consulate' is not a fixed building but a localized reality distortion. Its appearance changes daily. Its inhabitants, when they appear, speak in riddles.", factionId: 'liminal_observers', intelReq: 75, political_influence: 3, economic_value: 1, military_strength: 5, population: 13 },
    { id: 'poi_an_rodentia_district', subRegion: "SAVANNA CENTRAL", x: 40.00, y: 85.00, type: 'town', name: "Little Rodentia", description: "A miniature district within Savanna Central, scaled for the city's smallest inhabitants. A hotbed of espionage due to its easily overlooked nature.", factionId: 'unaligned', intelReq: 10, political_influence: 3, economic_value: 5, military_strength: 2 },
    { id: 'poi_an_gazelle_stadium', subRegion: "SAVANNA CENTRAL", x: 58.00, y: 72.00, type: 'landmark', name: "Gazelle Memorial Stadium", description: "A massive stadium where the pop star Gazelle holds concerts. One of the few places where predators and prey still gather peacefully.", factionId: 'unaligned', intelReq: 5, political_influence: 5, economic_value: 6, military_strength: 2 },

    // --- DOWN TOWN ---
    { id: 'poi_an_meadowlands_hospital', subRegion: "DOWN TOWN", x: 50.00, y: 50.00, type: 'landmark', name: "The Meadowlands General Hospital", description: "The largest hospital on the continent. It operates as a neutral zone under a fragile truce, treating wounded from all factions.", factionId: 'unaligned', intelReq: 10, political_influence: 4, economic_value: 5, military_strength: 3, population: 2000 },
    { id: 'poi_an_fox_den_inn', subRegion: "DOWN TOWN", x: 58.00, y: 45.00, type: 'inn', name: "The Fox's Den Inn", description: "A known neutral-ground inn run by a sly fox, where information is the real currency.", factionId: 'freelancer_underworld', intelReq: 20, political_influence: 5, economic_value: 6, military_strength: 3 },
    { id: 'poi_an_abandoned_amusement_park', subRegion: "DOWN TOWN", x: 55.00, y: 58.00, type: 'ruins', name: "Abandoned Amusement Park", description: "A derelict theme park that now serves as a neutral, lawless zone where deals are made and scores are settled.", factionId: 'freelancer_underworld', intelReq: 30, political_influence: 3, economic_value: 4, military_strength: 5 },

    // --- Rainforest District ---
    { id: 'poi_an_prey_bunker', subRegion: "Rainforest District", x: 30.00, y: 40.00, type: 'dungeon_entrance', name: "Prey Congress Command Bunker", description: "A secret, underground bunker deep within the rainforest, where the Prey Congress's leaders coordinate their defensive and guerilla operations.", factionId: 'animatopia_prey_congress', intelReq: 40, political_influence: 9, economic_value: 5, military_strength: 9, population: 1000 },
    { id: 'poi_an_canopy_village', subRegion: "Rainforest District", x: 35.00, y: 45.00, type: 'village', name: "Canopy Village", description: "A village built in the high canopy of the rainforest, accessible only by a network of rope bridges. A key stronghold for Prey Congress guerilla fighters.", factionId: 'animatopia_prey_congress', intelReq: 20, political_influence: 4, economic_value: 3, military_strength: 6, population: 1500 },
    { id: 'poi_an_ambush_point_alpha', subRegion: "Rainforest District", x: 38.00, y: 35.00, type: 'ambush', name: "Ambush Point Alpha", description: "A strategically important chokepoint on the main path through the Rainforest, frequently used by Prey Congress fighters to ambush Predator patrols.", factionId: 'animatopia_prey_congress', intelReq: 30, political_influence: 1, economic_value: 1, military_strength: 7, population: 0 },
    { id: 'poi_an_ancient_tree_shrine', subRegion: "Rainforest District", x: 45.00, y: 25.00, type: 'shrine', name: "Ancient Tree Shrine", description: "A sacred site for many herbivore species. It is considered neutral ground, but both sides accuse the other of using it for intelligence gathering.", factionId: 'unaligned', intelReq: 15, political_influence: 3, economic_value: 2, military_strength: 2, population: 20 },
    { id: 'poi_an_snake_temple', subRegion: "Rainforest District", x: 50.00, y: 30.00, type: 'temple', name: "The Serpent's Temple", description: "An ancient, vine-covered temple housing a reclusive clan of snakes. They are masters of poison and information, trading secrets for tribute.", factionId: 'freelancer_underworld', intelReq: 55, political_influence: 5, economic_value: 6, military_strength: 5 },

    // --- Nocturnal ranges ---
    { id: 'poi_an_midnight_market', subRegion: "Nocturnal ranges", x: 15.00, y: 80.00, type: 'market', name: "The Midnight Market", description: "A market that only opens after dark. It's the primary hub for spies, informants, and assassins from all factions.", factionId: 'freelancer_underworld', intelReq: 35, political_influence: 6, economic_value: 8, military_strength: 5, population: 2000 },
    { id: 'poi_an_owl_watchtower', subRegion: "Nocturnal ranges", x: 10.00, y: 70.00, type: 'watchtower', name: "The Owl's Watchtower", description: "A high peak used by a neutral guild of owl information brokers to observe the entire continent.", factionId: 'freelancer_underworld', intelReq: 60, political_influence: 7, economic_value: 5, military_strength: 3, population: 100 },
    { id: 'poi_an_bat_colony_roost', subRegion: "Nocturnal ranges", x: 18.00, y: 65.00, type: 'lair', name: "The Bat Colony Roost", description: "An abandoned cave system that now houses a massive colony of bats. They serve as covert messengers for the highest bidder.", factionId: 'unaligned', intelReq: 30, political_influence: 2, economic_value: 4, military_strength: 3, population: 1000 },

    // --- Out back isle ---
    { id: 'poi_an_vulture_aerie', subRegion: "Out back isle", x: 97.00, y: 90.00, type: 'lair', name: "Vulture Aerie", description: "A high cliffside roost for vultures who act as battlefield scavengers and informants, selling information about troop movements.", factionId: 'unaligned', intelReq: 25, political_influence: 3, economic_value: 4, military_strength: 2 },
    { id: 'poi_an_kangaroo_boxing_ring', subRegion: "Out back isle", x: 97.00, y: 86.00, type: 'battlefield', name: "Kangaroo Boxing Ring", description: "An illegal, bare-knuckle boxing ring run by a mob of kangaroos. A place to settle scores or lose money.", factionId: 'freelancer_underworld', intelReq: 30, political_influence: 2, economic_value: 5, military_strength: 4 },

    // --- Western Border ---
    { id: 'poi_an_boar_biker_clubhouse', subRegion: "Western Border", x: 10.00, y: 40.00, type: 'lair', name: "Boar Biker Clubhouse", description: "A rough-and-tumble clubhouse for a biker gang of wild boars. They act as mercenaries, currently on contract with the Prey Congress.", factionId: 'animatopia_prey_congress', intelReq: 25, political_influence: 3, economic_value: 4, military_strength: 5 },
    { id: 'poi_an_badger_bunker', subRegion: "Western Border", x: 12.00, y: 25.00, type: 'fortress', name: "The Badger's Bunker", description: "A heavily fortified, underground bunker built by a reclusive and highly paranoid badger. Rumored to contain a massive arsenal.", factionId: 'unaligned', intelReq: 45, political_influence: 2, economic_value: 5, military_strength: 7 },

    // --- Eastern Border ---
    { id: 'poi_an_sahara_market', subRegion: "Eastern Border", x: 98.00, y: 40.00, type: 'market', name: "Sahara Square Black Market", description: "A sprawling, lawless market where anything can be bought or sold. A major source of supplies for the Prey Congress.", factionId: 'freelancer_underworld', intelReq: 25, political_influence: 5, economic_value: 9, military_strength: 4, population: 6000 },
    { id: 'poi_an_oasis_refuge', subRegion: "Eastern Border", x: 98.00, y: 60.00, type: 'village', name: "The Oasis Refuge", description: "A hidden settlement built around a large oasis, serving as a refuge for prey species fleeing the conflict.", factionId: 'animatopia_prey_congress', intelReq: 15, political_influence: 4, economic_value: 5, military_strength: 3, population: 4000 },
    { id: 'poi_an_sand_cat_smugglers', subRegion: "Eastern Border", x: 95.00, y: 50.00, type: 'lair', name: "Sand Cat Smuggler's Den", description: "A network of tunnels used by a cunning gang of sand cats to smuggle goods and information across the desert.", factionId: 'freelancer_underworld', intelReq: 45, political_influence: 3, economic_value: 6, military_strength: 4, population: 150 },
    { id: 'poi_an_camel_caravan_depot', subRegion: "Eastern Border", x: 84.00, y: 25.00, type: 'trade_post', name: "Camel Caravan Depot", description: "The main staging ground for the camel caravans that transport goods across the vast desert, vital for the Prey Congress's supply lines.", factionId: 'animatopia_prey_congress', intelReq: 20, political_influence: 3, economic_value: 7, military_strength: 3, population: 500 }
];

const fogOfWar = []; // No fog for the full map view, as requested.

export const animatopiaData = { pointsOfInterest, fogOfWar };
