// map-data/autumnwood-pois.js

export const autumnwoodData = {
    pointsOfInterest: [
        {
            id: 'poi_aw_mages_spire',
            x: 35.00,
            y: 65.00,
            type: 'mages_tower',
            name: "Spire of the Mages' Guild",
            description: "The provincial headquarters of the Mages' Guild. A gleaming, impossibly tall tower that serves as a center for arcane research, learning, and the enforcement of 'The Autumnwood Accords,' the strict magical laws that supersede all Imperial statutes in this region.",
            factionId: 'mages_guild',
            intelReq: { faction: 'mages_guild', level: 10 },
            political_influence: 9,
            economic_value: 6,
            military_strength: 8,
            population: 2500,
            age_of_antiquity: 8,
            crime_rate: 2
        },
        {
            id: 'poi_aw_golden_grove',
            x: 30.00,
            y: 62.00,
            type: 'forest',
            name: "The Golden Grove",
            description: "A vast forest where all the trees have perpetually golden leaves. The grove is a place of immense, tranquil magic, but its beauty hides ancient and powerful fey guardians who act as the ultimate enforcers of the local Accords.",
            factionId: 'unaligned',
            intelReq: { faction: 'rakasha_clans', level: 25 },
            political_influence: 2,
            economic_value: 5,
            military_strength: 4,
            population: 0,
            age_of_antiquity: 10,
            crime_rate: 3
        },
        {
            id: 'poi_aw_conservator_archive',
            x: 38.00,
            y: 68.00,
            type: 'library',
            name: "The Conservator's Archive",
            description: "A hidden, magically-sealed library containing the Mages' Guild's most dangerous texts. It is the seat of power for the traditionalist Conservator faction, who interpret the Autumnwood Accords in the most rigid and unforgiving manner.",
            factionId: 'mages_guild',
            intelReq: { faction: 'mages_guild', level: 60 },
            political_influence: 7,
            economic_value: 3,
            military_strength: 6,
            population: 100,
            library_summary: "This is not a public library, but a magically-sealed vault containing the Mages' Guild's most dangerous and forbidden texts. The books here are considered weapons, detailing demonic pacts, soul-trapping, and catastrophic spells. Access is forbidden to all but the highest-ranking Conservators.",
            libraryStockKey: 'conservator_archive',
            age_of_antiquity: 8,
            crime_rate: 1
        },
        {
            id: 'poi_aw_innovator_workshop',
            x: 32.00,
            y: 59.00,
            type: 'workshop',
            name: "Innovator's Unstable Workshop",
            description: "The chaotic workshop of Janna Brightspark and the Innovator faction. Here, they push the boundaries of magic, often operating in the grey areas of the Autumnwood Accords, much to the Conservators' fury.",
            factionId: 'mages_guild',
            intelReq: { faction: 'mages_guild', level: 45 },
            political_influence: 5,
            economic_value: 5,
            military_strength: 6,
            population: 80,
            age_of_antiquity: 2,
            crime_rate: 5
        },
        {
            id: 'poi_aw_fey_crossing',
            x: 27.00,
            y: 67.00,
            type: 'portal',
            name: "Fey Crossing",
            description: "A shimmering curtain of light where the veil between worlds is thin. The Mages' Guild heavily monitors this area, as unsanctioned planar travel is a capital offense under the Accords.",
            factionId: 'unaligned',
            intelReq: { faction: 'mages_guild', level: 50 },
            political_influence: 2,
            economic_value: 3,
            military_strength: 3,
            population: 0,
            age_of_antiquity: 10,
            crime_rate: 4
        },
        {
            id: 'poi_aw_silent_pool',
            x: 34.00,
            y: 73.00,
            type: 'ley_line',
            name: "The Silent Pool",
            description: "A perfectly still pool that reflects the stars even during the day. It is a powerful scrying focus, and its use is strictly regulated by the Guild's Divination Council.",
            factionId: 'unaligned',
            intelReq: { faction: 'mages_guild', level: 40 },
            political_influence: 3,
            economic_value: 2,
            military_strength: 1,
            population: 0,
            age_of_antiquity: 10,
            crime_rate: 1
        },
        {
            id: 'poi_aw_amber_river',
            x: 39.00,
            y: 60.00,
            type: 'river',
            name: "The Amber River",
            description: "A slow-moving river whose waters flow with the color of liquid amber. It is a potent source of magical ingredients, and the Guild claims ownership of all resources within it, a frequent point of contention with outsiders.",
            factionId: 'unaligned',
            intelReq: { faction: 'rakasha_clans', level: 15 },
            political_influence: 1,
            economic_value: 7,
            military_strength: 2,
            population: 0,
            age_of_antiquity: 10,
            crime_rate: 3
        },
        {
            id: 'poi_aw_witchs_hovel',
            x: 25.00,
            y: 60.00,
            type: 'village',
            name: "The Witch's Hovel",
            description: "The secluded home of a powerful hedge witch who operates outside the Mages' Guild's laws. The Guild considers her an unsanctioned practitioner and a threat to their authority, but has so far been unable to apprehend her.",
            factionId: 'unaligned',
            intelReq: { faction: 'freelancer_underworld', level: 35 },
            political_influence: 2,
            economic_value: 4,
            military_strength: 3,
            population: 1,
            age_of_antiquity: 4,
            crime_rate: 6
        },
        {
            id: 'poi_aw_sunken_temple',
            x: 28.00,
            y: 72.00,
            type: 'ruins',
            name: "Sunken Temple of the Moon",
            description: "The ruins of a temple dedicated to a moon deity. The Guild has declared it a protected archaeological site, forbidding any from entering without a permit while they study its lunar magic.",
            factionId: 'unaligned',
            intelReq: { faction: 'moonfang_pack', level: 55 },
            political_influence: 2,
            economic_value: 5,
            military_strength: 3,
            population: 0,
            age_of_antiquity: 9,
            crime_rate: 2
        },
        {
            id: 'poi_aw_silver_flame_outpost',
            x: 39.50,
            y: 72.00,
            type: 'outpost',
            name: "Silver Flame Outpost",
            description: "An outpost of the Order of the Silver Flame. They operate under their own divine authority, viewing the Mages' Guild with suspicion and openly defying the Autumnwood Accords when it conflicts with their holy mission to purge supernatural evil.",
            factionId: 'silver_flame',
            intelReq: { faction: 'silver_flame', level: 40 },
            political_influence: 3,
            economic_value: 1,
            military_strength: 6,
            population: 60,
            age_of_antiquity: 3,
            crime_rate: 1
        },
        // #161
        {
            id: 'poi_aw_mana_springs',
            x: 36.0,
            y: 62.0,
            type: 'ley_line',
            name: "The Volatile Mana-Springs",
            description: "A series of hot springs where raw magical energy bubbles to the surface. The area is highly restricted under the Accords, as the Innovators and Conservators wage a bitter political battle over whether to harness or seal this dangerous power.",
            factionId: 'mages_guild',
            intelReq: { faction: 'mages_guild', level: 40 },
            political_influence: 4,
            economic_value: 5,
            military_strength: 3,
            population: 5,
            age_of_antiquity: 10,
            crime_rate: 2
        }
    ]
};