// map-data/midlands-pois.js

const midlandsData = {
    pointsOfInterest: [
        // #66
        {
            id: 'poi_mid_capital_district',
            x: 81.28,
            y: 4.29,
            type: 'capital_city',
            name: "Imperial District of Mighdural",
            description: "The administrative and symbolic heart of the Regal Empire. This central district houses the ministries, high courts, and the residences of the most powerful non-noble bureaucrats.",
            factionId: 'regal_empire',
            intelReq: { faction: 'regal_empire', level: 5 },
            political_influence: 10,
            economic_value: 8,
            military_strength: 7,
            population: 25000
        },
        // #67
        {
            id: 'poi_mid_imperial_palace',
            x: 84.50,
            y: 3.50,
            type: 'castle',
            name: "The Imperial Palace",
            description: "The magnificent, sprawling palace of Emperor Elagabalus. A city within a city, protected by the elite Imperial Guard and powerful magical wards. The seat of all power in the Empire.",
            factionId: 'regal_empire',
            intelReq: { faction: 'regal_empire', level: 70 },
            political_influence: 10,
            economic_value: 6,
            military_strength: 8,
            population: 5000
        },
        // #68
        {
            id: 'poi_mid_aegis_command',
            x: 78.5,
            y: 2.5,
            type: 'barracks',
            articleId: 'aegis_command',
            name: "Aegis Command",
            description: "The central command and grand barracks for the Iron Legion's home guard. A massive, imposing fortress where thousands of soldiers are garrisoned and trained.",
            factionId: 'iron_legion',
            intelReq: { faction: 'iron_legion', level: 30 },
            political_influence: 5,
            economic_value: 3,
            military_strength: 10,
            population: 10000
        },
        // #69
        {
            id: 'poi_mid_magitek_foundries',
            x: 75.0,
            y: 8.0,
            type: 'workshop',
            name: "Magitek Foundries",
            description: "A district of immense forges and workshops that produce the Empire's magitek war machines. The sky above is perpetually choked with arcane smog and the sound of ethereal hammers.",
            factionId: 'regal_empire',
            intelReq: { faction: 'regal_empire', level: 40 },
            political_influence: 3,
            economic_value: 10,
            military_strength: 6,
            population: 8000
        },
        // #70
        {
            id: 'poi_mid_silent_service_hq',
            x: 87.0,
            y: 6.0,
            type: 'prison',
            name: "The Obsidian Spire (Silent Service HQ)",
            description: "A windowless, black monolith that serves as the headquarters for the Silent Service, the Empire's feared intelligence agency. It is said to be one of the most secure buildings in the world, holding the Empire's darkest secrets.",
            factionId: 'regal_empire',
            intelReq: { faction: 'regal_empire', level: 90 },
            political_influence: 9,
            economic_value: 4,
            military_strength: 8,
            population: 1500
        },
        // #71

        {
            id: 'poi_mid_internet_embassy',
            x: 87.0,
            y: 10.0,
            type: 'landmark',
            name: "The Internet Embassy",
            description: "A strange, shimmering building that seems to flicker at the edge of vision. It is the diplomatic node for The Internet Federation, a place of data-brokers and digital envoys from another dimension.",
            factionId: 'internet_federation',
            intelReq: 50,
            political_influence: 6,
            economic_value: 6,
            military_strength: 5,
            population: 30
        },
        // --- NEW POINT OF INTEREST ---
        {
            id: 'poi_mid_raventree_manor',
            x: 73.5,
            y: 12.0,
            type: 'landmark',
            name: "Raventree Manor",
            description: "A decaying, haunted manor located in the misty woods southwest of the capital. It is the domain of the enigmatic Oracle and is currently being used by Waluigi and Bowser as a hideout to stash their 'relocated' treasures. The estate is known to have strange temporal properties and is a nexus of powerful, unpredictable magic.",
            factionId: 'unaligned',
            intelReq: { faction: 'mages_guild', level: 40 },
            political_influence: 4,
            economic_value: 3,
            military_strength: 2,
            population: 10, // Represents the current occupiers and spectral residents
            articleId: 'raventree_manor',
            plane: 'material'
        },
        // #72
        {
            id: 'poi_mid_great_orrery',
            x: 82.0,
            y: 7.0,
            type: 'observatory',
            name: "The Great Orrery",
            description: "A colossal, magical orrery that maps the movements of celestial bodies in real-time. A symbol of the Empire's mastery over science and magic, used for both navigation and astrological prophecy.",
            factionId: 'regal_empire',
            intelReq: { faction: 'mages_guild', level: 50 },
            political_influence: 6,
            economic_value: 5,
            military_strength: 2,
            population: 200
        },
        // #73
        {
            id: 'poi_mid_undercroft',
            x: 76.5,
            y: 11.0,
            type: 'dungeon_entrance',
            name: "The Undercroft",
            description: "The entrance to the capital's ancient sewer system, which has become the domain of the Freelancer Underworld. A hidden city of black markets, smugglers' dens, and secret guild halls.",
            factionId: 'freelancer_underworld',
            intelReq: { faction: 'freelancer_underworld', level: 35 },
            political_influence: 2,
            economic_value: 7,
            military_strength: 4,
            population: 2500
        },
        // #74
        {
            id: 'poi_mid_sunstone_gate',
            x: 83.0,
            y: 15.0,
            type: 'watchtower',
            name: "The Sunstone Gate",
            description: "The main southern gate of the capital city. A massive fortification manned by the Iron Legion, it controls all traffic along the great southern road.",
            factionId: 'iron_legion',
            intelReq: { faction: 'iron_legion', level: 15 },
            political_influence: 3,
            economic_value: 4,
            military_strength: 8,
            population: 500
        },
        // #75
        {
            id: 'poi_mid_imperial_university',
            x: 85.5,
            y: 9.0,
            type: 'academy',
            name: "Imperial University",
            description: "The premier institution of learning in the Empire, where the children of nobility and promising commoners are educated in law, history, and the state-sanctioned arcane arts.",
            factionId: 'regal_empire',
            intelReq: { faction: 'regal_empire', level: 25 },
            political_influence: 7,
            economic_value: 5,
            military_strength: 3,
            population: 4000
        },
        // #76
        {
            id: 'poi_mid_cathedral_flame',
            x: 89.0,
            y: 14.0,
            type: 'temple',
            name: "Cathedral of the Cleansing Flame",
            description: "The grand cathedral of the Order of the Silver Flame. A bastion of faith and martial power, from which the Order coordinates its crusades against supernatural threats across the Midlands.",
            factionId: 'silver_flame',
            intelReq: { faction: 'silver_flame', level: 30 },
            political_influence: 6,
            economic_value: 3,
            military_strength: 6,
            population: 1000
        },
        // #77
        {
            id: 'poi_mid_imperial_diet',
            x: 82.5,
            y: 2.0,
            type: 'capital_city',
            articleId: 'imperial_diet',
            name: "The Imperial Diet",
            description: "The grand parliamentary building where representatives from all Imperial provinces convene. A place of political intrigue, debate, and the formal passing of Imperial law under the Emperor's watchful eye.",
            factionId: 'regal_empire',
            intelReq: { faction: 'regal_empire', level: 20 },
            political_influence: 10,
            economic_value: 5,
            military_strength: 5,
            population: 1000
        },
        // #78
        {
            id: 'poi_mid_noble_district',
            x: 86.5,
            y: 2.5,
            type: 'town',
            name: "The Gilded Quarter (Noble District)",
            description: "An opulent district of lavish estates and manicured gardens, home to the most powerful noble families of the Empire. The air is thick with wealth, privilege, and political conspiracy.",
            factionId: 'regal_empire',
            intelReq: { faction: 'regal_empire', level: 30 },
            political_influence: 8,
            economic_value: 7,
            military_strength: 4,
            population: 3000
        },
        // #79
        {
            id: 'poi_mid_mages_guild_spire',
            x: 77.0,
            y: 5.0,
            type: 'mages_tower',
            name: "Mages' Guild Spire",
            description: "The officially sanctioned headquarters of the Mages' Guild within the capital. A gleaming white tower that serves as a library, laboratory, and embassy for the powerful arcane faction.",
            factionId: 'mages_guild',
            intelReq: { faction: 'mages_guild', level: 35 },
            political_influence: 5,
            economic_value: 4,
            military_strength: 6,
            population: 500
        },
        // #80
        {
            id: 'poi_mid_onyx_embassy',
            x: 88.5,
            y: 10.0,
            type: 'landmark',
            name: "The Onyx Embassy",
            description: "The 'diplomatic' presence of the Onyx Hand vampires. A dark, gothic manor that is an open secret in the capital. No business is conducted in the light of day, and invitations are rare and dangerous.",
            factionId: 'onyx_hand',
            intelReq: { faction: 'onyx_hand', level: 60 },
            political_influence: 7,
            economic_value: 5,
            military_strength: 6,
            population: 100
        },
        // #81
        {
            id: 'poi_mid_fighting_pit',
            x: 74.5,
            y: 13.0,
            type: 'lair',
            name: "The Grinder (Underworld Fighting Pit)",
            description: "A notorious, illegal fighting pit deep in the Undercroft, run by the Iron Fists. A place where disputes are settled with fists and fortunes are made and lost on brutal contests.",
            factionId: 'iron_fists',
            intelReq: { faction: 'iron_fists', level: 45 },
            political_influence: 2,
            economic_value: 6,
            military_strength: 5,
            population: 300
        },
        // #82
        {
            id: 'poi_mid_imperial_mint',
            x: 73.0,
            y: 5.0,
            type: 'workshop',
            name: "The Imperial Mint",
            description: "A heavily fortified facility where the Empire's currency is minted. Guarded by the Iron Legion, it is said to be as secure as the Imperial Palace itself.",
            factionId: 'regal_empire',
            intelReq: { faction: 'regal_empire', level: 55 },
            political_influence: 4,
            economic_value: 10,
            military_strength: 8,
            population: 400
        },
        {
            id: 'poi_mid_grand_library',
            x: 79.5,
            y: 13.5,
            type: 'library',
            name: "Grand Library of Mighdural",
            description: "The largest repository of knowledge in the Midlands, containing centuries of Imperial history, law, and censored literature. It is managed by an order of stoic, Imperial scribes.",
            factionId: 'regal_empire',
            intelReq: { faction: 'regal_empire', level: 30 },
            political_influence: 6,
            economic_value: 4,
            military_strength: 3,
            population: 300,
            library_summary: "The largest public library in the Regal Empire. While its collection is vast, many texts concerning the Empire's more questionable history or forbidden magic have been heavily redacted or are kept in locked vaults, accessible only to the Silent Service.",
            libraryStockKey: 'midlands'
        },
        // #84
        {
            id: 'poi_mid_diplomatic_quarter',
            x: 90.5,
            y: 8.5,
            type: 'village',
            name: "The Diplomatic Quarter",
            description: "A walled district where ambassadors from allied and vassal states reside. A beautiful but heavily monitored area, where the Silent Service watches every move.",
            factionId: 'regal_empire',
            intelReq: { faction: 'regal_empire', level: 25 },
            political_influence: 7,
            economic_value: 5,
            military_strength: 6,
            population: 1200
        },
        // #85
        {
            id: 'poi_mid_artificers_guild',
            x: 73.5,
            y: 10.5,
            type: 'academy',
            name: "Artificer's Guildhall",
            description: "The guildhall for civilian magitek engineers and inventors. While they often work on Imperial contracts, they maintain a degree of independence and are a source of non-military technological innovation.",
            factionId: 'regal_empire',
            intelReq: { faction: 'regal_empire', level: 30 },
            political_influence: 4,
            economic_value: 8,
            military_strength: 3,
            population: 1800
        },
        // #86
        {
            id: 'poi_mid_citadel_of_law',
            x: 84.5,
            y: 12.0,
            type: 'temple',
            name: "Citadel of Law",
            description: "The austere and imposing headquarters of the Oathbound Judges in the capital. From here, they dispense cosmic justice, their authority respected even by the Emperor.",
            factionId: 'oathbound_judges',
            intelReq: { faction: 'oathbound_judges', level: 40 },
            political_influence: 8,
            economic_value: 2,
            military_strength: 7,
            population: 600
        },
        // #87
        {
            id: 'poi_mid_imperial_menagerie',
            x: 92.0,
            y: 12.5,
            type: 'landmark',
            name: "The Imperial Menagerie",
            description: "A vast, enchanted park that houses exotic and magical creatures captured from across the world. A symbol of the Empire's reach and power, though some see it as a cruel prison.",
            factionId: 'regal_empire',
            intelReq: { faction: 'regal_empire', level: 20 },
            political_influence: 3,
            economic_value: 4,
            military_strength: 4,
            population: 300
        },
        // #88
        {
            id: 'poi_mid_gilded_gryphon_barracks',
            x: 77.5,
            y: 15.0,
            type: 'barracks',
            name: "Gilded Gryphon Barracks",
            description: "The urban barracks for the Gilded Gryphon Mercenary Company. When not on contract, they can be found here, training, gambling, and spending their coin.",
            factionId: 'unaligned',
            intelReq: { faction: 'unaligned', level: 25 },
            political_influence: 3,
            economic_value: 5,
            military_strength: 6,
            population: 600
        },
        // #89
        {
            id: 'poi_mid_wayfinders_guildhall',
            x: 71.0,
            y: 14.5,
            type: 'academy',
            name: "Wayfinders' Guildhall",
            description: "The capital chapterhouse of the Wayfinders' Guild. A place filled with maps, artifacts, and adventurers planning their next expedition into the unknown.",
            factionId: 'unaligned',
            intelReq: { faction: 'unaligned', level: 20 },
            political_influence: 4,
            economic_value: 4,
            military_strength: 2,
            population: 200
        },
        // #90
        {
            id: 'poi_mid_cosmic_jester_shrine',
            x: 93.0,
            y: 4.0,
            type: 'shrine',
            name: "Hidden Shrine to the Jester",
            description: "A secret, nonsensical shrine to the Cosmic Jester, hidden in the attic of a noble's estate. It is maintained by a small, influential cult of aristocrats who find Imperial order dreadfully boring.",
            factionId: 'cosmic_jesters',
            intelReq: { faction: 'cosmic_jesters', level: 85 },
            political_influence: 4,
            economic_value: 1,
            military_strength: 1,
            population: 15
        },
        // #158
        {
            id: 'poi_mid_heralds_plaza',
            x: 80.5,
            y: 2.0,
            type: 'landmark',
            name: "Imperial Herald's Plaza",
            description: "A grand plaza where Imperial Heralds make public proclamations and post official news bulletins. It is a key tool for state propaganda, and a place where the Silent Service subtly monitors public opinion.",
            factionId: 'regal_empire',
            intelReq: { faction: 'regal_empire', level: 15 },
            political_influence: 6,
            economic_value: 2,
            military_strength: 3,
            population: 500
        },
        {
            id: 'poi_mid_mk_embassy',
            x: 91.5,
            y: 7.0,
            type: 'landmark',
            name: "Mushroom Kingdom Embassy",
            description: "A cheerful, toadstool-shaped building that stands in stark contrast to the severe Imperial architecture. It serves as the Mushroom Regency's diplomatic mission, promoting trade and seeking allies in the chaotic Midlands.",
            factionId: 'mushroom_regency',
            intelReq: 20,
            political_influence: 5,
            economic_value: 4,
            military_strength: 3,
            population: 50
        },
        {
            id: 'poi_mid_midearth_embassy',
            x: 89.5,
            y: 7.0,
            type: 'landmark',
            name: "Middle-Earth Embassy",
            description: "An embassy of stone and ancient wood, representing the far-western kingdoms of Middle-Earth. Its diplomats are known for their wisdom, patience, and deep distrust of industrial magitek.",
            factionId: 'kingdom_of_gondor',
            intelReq: 50,
            political_influence: 4,
            economic_value: 3,
            military_strength: 4,
            population: 40
        },
        {
            id: 'poi_mid_internet_embassy',
            x: 92.0,
            y: 10.0,
            type: 'landmark',
            name: "The Internet Embassy",
            description: "A strange, shimmering building that seems to flicker at the edge of vision. It is the diplomatic node for The Internet Federation, a place of data-brokers and digital envoys from another dimension.",
            factionId: 'internet_federation',
            intelReq: 50,
            political_influence: 6,
            economic_value: 6,
            military_strength: 5,
            population: 30
        },
        // --- Location-article pins ---
        // Filed with the Waluipedia map-preview pass: every entry carries an
        // `articleId` so a location article can show its own pin on the painted
        // map. Planar reflections (Shadowfell / Feywild / Mirror / Feyward) sit
        // where their Material anchor — Raventree Manor — sits, offset just
        // enough that the pins do not stack into one unreadable dot.
        //
        // Planar layers: pins in the Raventree cluster carry an explicit
        // `plane` — 'material', 'shadow' (Shadeward/Shadowfell), 'fey'
        // (Feyward/Feywild) or 'mirror' (Deep Mirror). A pin WITHOUT the tag
        // is Material by convention, so older sheets need no edits; the
        // cartography desk (#/maps) filters this one sheet by that tag.
        // Checked by tools/classify-location-planes.py --check.
        {
            id: 'poi_mid_shadow_estate',
            x: 72.9,
            y: 13.1,
            type: 'lair',
            name: "The Shadow Estate",
            description: "The Shadowfell's reflection of Raventree Manor: same architecture, same layout, drained of colour and warmth. Held by the Onyx Hand's vampiric court. Plotted at its Material anchor — the two estates occupy the same ground on different planes.",
            factionId: 'onyx_hand',
            intelReq: { faction: 'onyx_hand', level: 30 },
            political_influence: 5,
            economic_value: 3,
            military_strength: 6,
            population: 40,
            articleId: 'shadow_estate',
            plane: 'shadow'
        },
        {
            id: 'poi_mid_shadow_estate_gardens',
            x: 73.1,
            y: 12.5,
            type: 'landmark',
            name: "Shadow Estate Gardens",
            description: "The ruined gardens of the Shadow Estate, once a sanctuary of peace and beauty on the Raventree grounds. Now ash-grey beds under an entropic perimeter, kept only by habit and grief.",
            factionId: 'onyx_hand',
            intelReq: { faction: 'onyx_hand', level: 25 },
            political_influence: 1,
            economic_value: 1,
            military_strength: 2,
            population: 6,
            articleId: 'shadow_estate_gardens',
            plane: 'shadow'
        },
        {
            id: 'poi_mid_mazebound_grove',
            x: 72.2,
            y: 13.4,
            type: 'forest',
            name: "The Mazebound Grove",
            description: "A petrified hedge maze on the Shadow Estate grounds: dead flora, fountains of warm blood, and a skull-tree draped in corpses. Infested with the Mazebound.",
            factionId: 'onyx_hand',
            intelReq: { faction: 'onyx_hand', level: 35 },
            political_influence: 1,
            economic_value: 1,
            military_strength: 4,
            population: 0,
            articleId: 'mazebound_grove',
            plane: 'shadow'
        },
        {
            id: 'poi_mid_orange_deer_shrine',
            x: 71.9,
            y: 12.6,
            type: 'shrine',
            name: "The Orange Deer Shrine",
            description: "A rare pocket of colour deep in the Shadow Estate grove: a deer-headed statue with glowing orange eyes, said to hold the memories of the grounds themselves.",
            factionId: 'onyx_hand',
            intelReq: { faction: 'onyx_hand', level: 40 },
            political_influence: 2,
            economic_value: 1,
            military_strength: 1,
            population: 0,
            articleId: 'orange_deer_shrine',
            plane: 'shadow'
        },
        {
            id: 'poi_mid_tymnas_cottage',
            x: 74.4,
            y: 11.2,
            type: 'farm',
            name: "Tymnas's Cottage & The Hedge Maze",
            description: "The Groundskeeper's stone homestead at the entropic perimeter of Raventree Manor, ringed by the grey hedge maze. In the Shadowfell's ash wastes the cottage alone keeps its colour.",
            factionId: 'unaligned',
            intelReq: 20,
            political_influence: 1,
            economic_value: 2,
            military_strength: 2,
            population: 3,
            articleId: 'tymnas_cottage_and_hedge_maze',
            plane: 'shadow'
        },
        {
            id: 'poi_mid_skittering_grove',
            x: 74.9,
            y: 10.7,
            type: 'forest',
            name: "The Skittering Grove",
            description: "The grove inside the Scorncrow's tree, past Tymnas's cottage on the Shadow Estate grounds: ettercaps, giant green spiders, and voices that answer back from within.",
            factionId: 'onyx_hand',
            intelReq: { faction: 'onyx_hand', level: 35 },
            political_influence: 1,
            economic_value: 1,
            military_strength: 4,
            population: 0,
            articleId: 'skittering_grove',
            plane: 'shadow'
        },
        {
            id: 'poi_mid_silent_grove',
            x: 72.7,
            y: 11.4,
            type: 'forest',
            name: "The Silent Grove",
            description: "A web-choked forest on Raventree Manor's Material grounds, former seat of the Arachnid Matriarch until her banishment. Sound does not carry here; neither do screams.",
            factionId: 'unaligned',
            intelReq: 25,
            political_influence: 1,
            economic_value: 2,
            military_strength: 3,
            population: 0,
            articleId: 'silent_grove',
            plane: 'material'
        },
        {
            id: 'poi_mid_overgrown_manor',
            x: 74.1,
            y: 13.0,
            type: 'haunted_place',
            name: "The Overgrown Manor",
            description: "Raventree Manor's Feywild reflection: the same structure consumed by impossible vegetation. Where Waluigi landed during the Planar Fracture, and filed extensively about afterwards.",
            factionId: 'unaligned',
            intelReq: 30,
            political_influence: 2,
            economic_value: 2,
            military_strength: 3,
            population: 25,
            articleId: 'overgrown_manor',
            plane: 'fey'
        },
        {
            id: 'poi_mid_overgrown_library',
            x: 74.5,
            y: 13.3,
            type: 'library',
            name: "The Overgrown Library",
            description: "The Feywild reflection of Raventree's library, propped up by giant tree roots. The head librarian is an immobile tree with a humanoid face that grows books like fruit.",
            factionId: 'unaligned',
            intelReq: 30,
            political_influence: 2,
            economic_value: 3,
            military_strength: 2,
            population: 12,
            articleId: 'overgrown_library',
            plane: 'fey'
        },
        {
            id: 'poi_mid_dreaming_tree_grove',
            x: 74.6,
            y: 12.2,
            type: 'forest',
            name: "The Dreaming Tree Grove",
            description: "The gold-and-orange Feyward reflection of the Raventree grounds, looping on bliss and revelry. Home of the Dreaming Tree and a fairy village that pays in Weird Fish.",
            factionId: 'unaligned',
            intelReq: 35,
            political_influence: 2,
            economic_value: 2,
            military_strength: 2,
            population: 60,
            articleId: 'feyward_grove',
            plane: 'fey'
        },
        {
            id: 'poi_mid_deep_mirror',
            x: 73.5,
            y: 13.7,
            type: 'portal',
            name: "The Deep Mirror (Fractured Atrium)",
            description: "The Mirror Dimension's reflection of Raventree Manor: crystalline corridors where reality fractures along every pane. Waluigi's official position is that his luck held by not ending up here.",
            factionId: 'unaligned',
            intelReq: 45,
            political_influence: 1,
            economic_value: 1,
            military_strength: 4,
            population: 0,
            articleId: 'deep_mirror',
            plane: 'mirror'
        },
        {
            id: 'poi_mid_alpine_bank_raventree',
            x: 74.9,
            y: 12.8,
            type: 'trade_post',
            name: "Alpine Bank (Raventree Outskirts Branch)",
            description: "The Alpine Bank branch just outside the Raventree grounds, bank of choice for werewolf nobility and human merchants who prefer their vaults away from the capital's paperwork.",
            factionId: 'regal_empire',
            intelReq: 15,
            political_influence: 3,
            economic_value: 7,
            military_strength: 3,
            population: 18,
            articleId: 'alpine_bank_raventree_outskirts',
            plane: 'material'
        },
        {
            id: 'poi_mid_ironhold',
            x: 80.6,
            y: 5.4,
            type: 'capital_city',
            name: "Ironhold",
            description: "Capital of the Regal Empire and heart of Iron Legion power: grey stone, straight lines, absolute order. Efficiency replaced aesthetics here; documentation replaced culture.",
            factionId: 'iron_legion',
            intelReq: { faction: 'iron_legion', level: 10 },
            political_influence: 10,
            economic_value: 8,
            military_strength: 10,
            population: 42000,
            articleId: 'ironhold'
        },
        {
            id: 'poi_mid_alpine_bank',
            x: 82.2,
            y: 6.2,
            type: 'trade_post',
            name: "Alpine Bank (Regal Capital Branch)",
            description: "An elite financial house built high in the mountains above Midgrual. Enforces the Regal standard, rejects Mushroom Kingdom coin, and keeps the Empire's ledgers colder than its vaults.",
            factionId: 'regal_empire',
            intelReq: 20,
            political_influence: 6,
            economic_value: 9,
            military_strength: 4,
            population: 60,
            articleId: 'alpine_bank'
        },
        {
            id: 'poi_mid_alpine_bank_chambers',
            x: 82.5,
            y: 6.6,
            type: 'dungeon_entrance',
            name: "Alpine Bank Subterranean Chambers",
            description: "The hidden floors beneath the Regal Capital branch, where the bank's true operations unfold away from public counters and imperial audit.",
            factionId: 'regal_empire',
            intelReq: 55,
            political_influence: 4,
            economic_value: 8,
            military_strength: 5,
            population: 12,
            articleId: 'alpine_bank_subterranean_chambers'
        },
        {
            id: 'poi_mid_alpine_mountain_inn',
            x: 79.2,
            y: 8.6,
            type: 'inn',
            name: "The Alpine Mountain Inn",
            description: "A warm timbered refuge on the freezing slopes outside the Regal Capital. Three Midland Ducats for an upstairs room; espionage apparently not included in the rate.",
            factionId: 'unaligned',
            intelReq: 10,
            political_influence: 1,
            economic_value: 4,
            military_strength: 1,
            population: 9,
            articleId: 'alpine_mountain_inn'
        },
        {
            id: 'poi_mid_arunedeal_camp',
            x: 78.3,
            y: 7.1,
            type: 'village',
            name: "The Arunedeal Goblin Camp",
            description: "A snow-swept encampment of the Snow Tribe of Arunedeal in the high Midgruals, pitched between the Alpine Mountain Inn and the Legion's checkpoint wall.",
            factionId: 'unaligned',
            intelReq: 15,
            political_influence: 1,
            economic_value: 2,
            military_strength: 3,
            population: 34,
            articleId: 'arunedeal_goblin_camp'
        },
        {
            id: 'poi_mid_legion_wall',
            x: 77.4,
            y: 5.5,
            type: 'fortress',
            name: "The Legion Wall Checkpoint (Midgrual Pass)",
            description: "A colossal stone checkpoint cutting clean across the Midgrual pass, garrisoned under Order 120. The banners snap; the wall does not open.",
            factionId: 'iron_legion',
            intelReq: { faction: 'iron_legion', level: 25 },
            political_influence: 5,
            economic_value: 2,
            military_strength: 10,
            population: 800,
            articleId: 'legion_wall_checkpoint'
        },
        {
            id: 'poi_mid_gamma_spire',
            x: 85.9,
            y: 5.1,
            type: 'barracks',
            name: "Gamma High Command Spire",
            description: "The black command facility of Gamma High Command. The route to it should require days of border crossings; the helicopter arrives almost immediately. Approach vector classified.",
            factionId: 'iron_legion',
            intelReq: { faction: 'iron_legion', level: 70 },
            political_influence: 8,
            economic_value: 3,
            military_strength: 9,
            population: 150,
            articleId: 'gamma_high_command_spire'
        },
        {
            id: 'poi_mid_vellanet_rise',
            x: 70.6,
            y: 9.2,
            type: 'castle',
            name: "Vellanet Rise",
            description: "Jack Miser's granted holding on the Midlands periphery, upriver of the Midgrual foothill roads: a fortified manor, three villages, a mill, a quarry and the tolls between them. Eleven miles, give or take the moor.",
            factionId: 'regal_empire',
            intelReq: 15,
            political_influence: 4,
            economic_value: 5,
            military_strength: 4,
            population: 620,
            articleId: 'vellanet_rise'
        },
        {
            id: 'poi_mid_darius_sanctum',
            x: 73.3,
            y: 14.0,
            type: 'portal',
            name: "Darius's Planar Sanctum (Fractured Atrium)",
            description: "A sanctum folded into the Deep Mirror layer above the Raventree reflection. Its fractured atrium is the only stable footing in a dimension of moving panes.",
            factionId: 'unaligned',
            intelReq: 50,
            political_influence: 3,
            economic_value: 2,
            military_strength: 3,
            population: 2,
            articleId: 'darius_sanctum',
            plane: 'mirror'
        },
        {
            id: 'poi_mid_planar_sanctum_belfry',
            x: 73.7,
            y: 14.0,
            type: 'observatory',
            name: "Planar Sanctum Belfry & Central Chamber",
            description: "The belfry and central chamber of the Corvinarus sanctum, reached through the Deep Mirror layer. The bells ring in planes that have no air.",
            factionId: 'unaligned',
            intelReq: 50,
            political_influence: 3,
            economic_value: 2,
            military_strength: 3,
            population: 1,
            articleId: 'planar_sanctum_belfry_and_atrium',
            plane: 'mirror'
        },
        {
            id: 'poi_mid_alpine_bay_ranch',
            x: 75.5,
            y: 10.5,
            type: 'farm',
            name: "Alpine Bay Ranch",
            description: "A sprawling ranch complex at the edge of the grassland below the Midgruals, serene retreat of Rohan's cavalry units when the capital lets them rest.",
            factionId: 'unaligned',
            intelReq: 10,
            political_influence: 1,
            economic_value: 4,
            military_strength: 2,
            population: 22,
            articleId: 'alpine_bay_ranch'
        }
    ],
    fogOfWar: [
  
    ]
};

export default midlandsData;