// This file defines the provinces for all maps.

export const PROVINCES = {
    // Mushroom Kingdom
    mk_plains: { name: 'Mushroom Plains', color: '#77dd77' },
    mk_north: { name: 'The North', color: '#b2cefe' },
    mk_city: { name: 'Mushroom City', color: '#fdfd96' },
    mk_beanbean: { name: 'Beanbean Kingdom', color: '#87ceeb' },
    mk_mountain: { name: 'Mountain Enclave', color: '#c2b280' },
    mk_desert: { name: 'Dry Dry Desert', color: '#f0e68c' },
    mk_bandits: { name: 'Bandit\'s Way', color: '#d2b48c' },
    mk_wario: { name: 'Wario Woods', color: '#ffac1c' },
    mk_coast: { name: 'The Arid Coast', color: '#ffb347' },
    mk_boo: { name: 'Boo\'s Woods', color: '#e6e6fa' },
    mk_pianta: { name: 'The Pianta Sea', color: '#77b5fe' },
    mk_yale: { name: 'Yale Shores', color: '#aec6cf' },
    mk_volcano: { name: 'Barrel Volcano', color: '#ff6961' },
    mk_seven: { name: 'The Seven Kingdoms', color: '#f49ac2' },
    mk_sunshine: { name: 'Sunshine Isles', color: '#ffdfba' },
    mk_flower: { name: 'Flower Kingdom', color: '#ffb7c5' },
    mk_yoshidk: { name: 'Yoshi & DK\'s Islands', color: '#c1e1c1' },
    mk_waffle: { name: 'Waffle & Chestnut', color: '#f5deb3' },
    mk_neobowser: { name: 'Neo Bowser City', color: '#4c516d' },
    mk_ice: { name: 'Ice Ice Outpost', color: '#cce5ff' },
    mk_chramalot: { name: 'Chramalot Kingdom', color: '#98fb98' },

    // Midlands
    mid_capital: { name: 'Capital Province', color: '#ffd700' },
    mid_belanor: { name: 'Yal Belanor', color: '#e0e0e0' },
    mid_vemillia: { name: 'Vemilia', color: '#d2b48c' },
    mid_ironwood: { name: 'Ironwood & Isle of Burbary', color: '#8b4513' },
    mid_lockerwood: { name: 'Lockerwood', color: '#556b2f' },
    mid_dragon: { name: 'Dragon Mountain', color: '#b22222' },
    mid_autumn: { name: 'Autumnwood', color: '#daa520' },
    mid_dry: { name: 'Dry County', color: '#ffdb58' },
    mid_ludor: { name: 'Ludor Isles', color: '#4682b4' },
    mid_theghdural: { name: 'Theghdural', color: '#a0522d' },
    mid_thorns: { name: 'Jungle of Thorns', color: '#006400' },
    mid_baldora: { name: 'Baldora Plains', color: '#9acd32' },
    mid_hills: { name: 'Lower Hills', color: '#bdb76b' },
    mid_central: { name: 'Yal Central', color: '#f5f5dc' },
    mid_north: { name: 'The Northern Lands', color: '#add8e6' },

    // The Internet
    inet_border: { name: 'The Border', color: '#6a737d' },
    inet_surface: { name: 'The Surface Web', color: '#58a6ff' },
    inet_deviant: { name: 'The Deviant Web', color: '#a371f7' },
    inet_criminal: { name: 'The Criminal Web', color: '#f85149' },
    inet_deep: { name: 'The Deep Web', color: '#480607' },
    inet_archives: { name: 'Sea of Archives', color: '#7fffd4' },
    inet_capitol: { name: 'The Capitol', color: '#f0e68c' },
    inet_bigtech: { name: 'Big Tech Region', color: '#e0e0e0' },
    inet_apple: { name: 'Apple Island', color: '#f5f5f5' },
    inet_intel: { name: 'Intel Corp. Zone', color: '#0071c5' },
    inet_waste: { name: 'Great Southern Wastefill', color: '#a9a9a9' },

    // Middle-earth
    me_forlindon: { name: 'Forlindon', color: '#a2d2ff' },
    me_eriador: { name: 'Eriador', color: '#b3e283' },
    me_haradwaith: { name: 'Haradwaith', color: '#ffb347' },
    me_umbar: { name: 'Umbar', color: '#8b0000' },
    me_gondor: { name: 'Gondor', color: '#e0e0e0' },
    me_rhovanion: { name: 'Rhovanion', color: '#90ee90' },
    me_mordor: { name: 'Mordor', color: '#4c0000' },
    me_minhiriath: { name: 'Minhiriath', color: '#c4a484' },

    // Warhammer
    wh_empire: { name: 'The Empire', color: '#c81d25' },
    wh_worlds_edge: { name: 'Worlds Edge Mountains', color: '#adb5bd' },
    wh_sylvania: { name: 'Sylvania', color: '#800f2f' },
    wh_badlands: { name: 'The Badlands', color: '#d2691e' },
    wh_ulthuan: { name: 'Ulthuan', color: '#ade8f4' },
    wh_naggaroth: { name: 'Naggaroth', color: '#5a189a' },
    wh_lustria: { name: 'Lustria', color: '#48bfe3' },
    wh_lotd: { name: 'Land of the Dead', color: '#f0ead2' },
    wh_araby: { name: 'Araby', color: '#ffd60a' },
    wh_southlands: { name: 'The Southlands', color: '#ffb347' },
    wh_bretonnia: { name: 'Bretonnia', color: '#00509d' },
    wh_darklands: { name: 'The Darklands', color: '#b21e35' },
    wh_albion: { name: 'Albion', color: '#b0c4de' },
    wh_cathay: { name: 'Grand Cathay', color: '#52b788' },
    wh_steppes: { name: 'Eastern Steppes', color: '#8d6e63' },
    wh_bastion: { name: 'The Great Bastion', color: '#f0f8ff' },
    
    // Kivotos
    kv_central: { name: 'Kivotos Central District', color: '#4a86e8' },
    kv_trinity: { name: 'Trinity District (Grand Latin)', color: '#f1c232' },
    kv_gehenna: { name: 'Gehenna District (Austelarassia)', color: '#cc0000' },
    kv_millennium: { name: 'Millennium District (Silbaarstadt)', color: '#674ea7' },
    kv_shanhaijing: { name: 'Shanhaijing District (AL-haoung)', color: '#93c47d' },
    kv_red_winter: { name: 'Red Winter District (N. Aurean Pole)', color: '#a61c00' },
    kv_abydos: { name: 'Abydos District (New Cairo)', color: '#e69138' },
    kv_srt: { name: 'SRT District (New America)', color: '#6c757d' },
    kv_anomaly: { name: 'Anomaly Zone (S. Aurean Pole)', color: '#8e7cc3' },
};
