import { Character, CharacterFaction } from './types';

export const CHARACTER_DATA_S2: Character[] = [
    {
        name: "EighthHalo (Jack)",
        description: "A player with a penchant for massive explosives. After a brief but violent turn as an antagonist, he has rejoined the team. His allegiance and mental state remain highly questionable, highlighted by his bizarre consumption of a bar of soap, which preceded a violent massacre, and his decision to blow up the team's own ship as an 'escape plan.' This culminated in him rigging the Titanic's engine room and helping lead the frantic escape from their sinking ship. He is last seen adrift in the lifeboat with Mike.",
        faction: CharacterFaction.PROTAGONISTS,
        importance: 3,
        firstAppearanceEpisode: 33,
        lastAppearanceEpisode: 72,
    },
    {
        name: "Reese (bestyrelse)",
        description: "A mysterious man in a red Hawaiian shirt whose plane is shot down by the team. He introduces himself as a member of a powerful PMC called 'the Alpones' and claims to be from their medical division. He possesses unsettling knowledge of the team's past, including their prison escape and their connection to Bloodless.",
        faction: CharacterFaction.THE_ALPONES,
        importance: 2,
        firstAppearanceEpisode: 35,
        lastAppearanceEpisode: 36,
    },
    {
        name: "AdmiralStewie",
        description: "A heavily armored, high-ranking guard of 'The Authority' in the snowy city. He confronts and captures the players after they are discovered in the weapons shop.",
        faction: CharacterFaction.THE_AUTHORITY,
        importance: 2,
        firstAppearanceEpisode: 33,
        lastAppearanceEpisode: 33,
    },
    {
        name: "Canadian Border Patrol",
        description: "Hostile, organized guards stationed at the Canadian border checkpoint. They are suspicious of outsiders and use lethal force to maintain control of the border.",
        faction: CharacterFaction.THE_AUTHORITY,
        importance: 1,
        firstAppearanceEpisode: 61,
        lastAppearanceEpisode: 63,
    },
    {
        name: "The Forgotten Guard",
        description: "A weary, forgotten guard of a desolate city who has been on duty for years. Seemingly disoriented and unable to read, he joins the team on their journey after directing them to a mysterious bridge.",
        faction: CharacterFaction.ALLIES,
        importance: 2,
        firstAppearanceEpisode: 64,
        lastAppearanceEpisode: 66,
    },
    {
        name: "Mega X Army Soldier",
        description: "A heavily-armored soldier and the sole survivor of the city's destruction. He is incredibly durable, tanking multiple bullets with ease. His presence confirms the continued existence of a 'Mega X Army,' posing a new threat.",
        faction: CharacterFaction.MEGA_X_ARMY,
        importance: 2,
        firstAppearanceEpisode: 34,
        lastAppearanceEpisode: 40,
    },
    {
        name: "Aboveriar (The Miner)",
        description: "A silent, voiceless miner encountered in a cave after a disastrous tunnel flood. He communicates using signs and attempts to guide the survivors to a village, but is killed in a sudden ambush. He is later seen and killed again during the massacre at Ned's safe house.",
        faction: CharacterFaction.ALLIES,
        importance: 1,
        firstAppearanceEpisode: 37,
        lastAppearanceEpisode: 41,
    },
    {
        name: "Friendly Miner",
        description: "A friendly NPC miner found under attack in the Golden Cave system. After being saved by the team, he coexists peacefully with them as they gather resources.",
        faction: CharacterFaction.ALLIES,
        importance: 1,
        firstAppearanceEpisode: 38,
        lastAppearanceEpisode: 38,
    },
    {
        name: "El muchacho",
        description: "A new player character seen briefly in a cutscene, riding through a forest. His role in the main story is not yet clear.",
        faction: CharacterFaction.PROTAGONISTS,
        importance: 1,
        firstAppearanceEpisode: 33,
        lastAppearanceEpisode: 33,
    },
    {
        name: "darkphan",
        description: "A mysterious player who appears at the very end of the SCP Facility incident, joining the team after they escape the complex. He is killed shortly after in a highway ambush.",
        faction: CharacterFaction.ALLIES,
        importance: 1,
        firstAppearanceEpisode: 34,
        lastAppearanceEpisode: 35,
    },
    {
        name: "Camouflaged Soldier",
        description: "A new female ally in military camouflage who joins the survivors at the church. Her origins and allegiances are unknown, but she aids them in the fight against the skeletal boss monster on the roof.",
        faction: CharacterFaction.ALLIES,
        importance: 2,
        firstAppearanceEpisode: 39,
        lastAppearanceEpisode: 39,
    },
    {
        name: "plattealle",
        description: "A guide who leads the team through the Waterfront City. After having lost his voice, he mysteriously regains it and leads the team to a supposed safe house, which turns out to be a deathtrap when his friends are slaughtered.",
        faction: CharacterFaction.ALLIES,
        importance: 1,
        firstAppearanceEpisode: 41,
        lastAppearanceEpisode: 41,
    },
    {
        name: "Ned",
        description: "A survivor in the Waterfront City and a friend of the team's guide, plattealle. He offers the team sanctuary, but he and his group are quickly slaughtered by a monstrous creature.",
        faction: CharacterFaction.ALLIES,
        importance: 1,
        firstAppearanceEpisode: 41,
        lastAppearanceEpisode: 41,
    },
    {
        name: "The Dealer (munchforobama)",
        description: "The eccentric and treacherous proprietor of a car dealership in the abandoned city. He speaks with a synthesized voice, makes bizarre deals, and ultimately betrays the team by withholding the keys to their vehicle after they completed his task.",
        faction: CharacterFaction.ANTAGONISTS,
        importance: 1,
        firstAppearanceEpisode: 41,
        lastAppearanceEpisode: 41,
    },
    {
        name: "Mega X Scientist",
        description: "A female scientist discovered in a basement who is revealed to be a double agent for a rival organization. She manipulates the team by providing critical intel: Mega X's true goal isn't to kill them, but to ruin their 'popularity' by capturing their friends. She provides the location of Noone's facility—a trap 200 miles west—before departing.",
        faction: CharacterFaction.ANTAGONISTS,
        importance: 2,
        firstAppearanceEpisode: 42,
        lastAppearanceEpisode: 59,
    },
    {
        name: "Bill",
        description: "A mysterious guide who led the team into multiple traps. His treachery was fully revealed when he attacked the team alongside Sid, and was later confirmed to have brutally tortured Jack. His involvement in the campaign ended when he abruptly 'left the game' after leading the team into another monster-infested town.",
        faction: CharacterFaction.ANTAGONISTS,
        importance: 2,
        firstAppearanceEpisode: 45,
        lastAppearanceEpisode: 49,
    },
    {
        name: "King Bill",
        description: "The apparent leader of the hostile 'Greeters' encountered at the coastal city. His shared name with the guide, Bill, created intense suspicion and foreshadowed the eventual betrayal.",
        faction: CharacterFaction.ANTAGONISTS,
        importance: 1,
        firstAppearanceEpisode: 47,
        lastAppearanceEpisode: 47,
    },
    {
        name: "Sid",
        description: "A powerful and mysterious antagonist disguised as Spider-Man. Allied with Bill, he served as a boss-level threat, using strange web-like abilities. After a difficult battle, he was defeated by the team but vanished without a trace, leaving behind a note from Mega X.",
        faction: CharacterFaction.ANTAGONISTS,
        importance: 2,
        firstAppearanceEpisode: 47,
        lastAppearanceEpisode: 47,
    },
    {
        name: "Gen_Deathrow",
        description: "A mysterious and cryptic informant discovered hiding within the ruined church complex. He possesses critical intelligence about a Mega X splinter group and provides the team with a contact number for an operative named 'Nurse Mayor' before theatrically vanishing. He also has strange abilities, including teleporting others out of fatal situations.",
        faction: CharacterFaction.ALLIES,
        importance: 2,
        firstAppearanceEpisode: 50,
        lastAppearanceEpisode: 52,
    },
    {
        name: "The Scientist (Spy)",
        description: "A Mega X scientist discovered in a basement, who is quickly revealed to be a double agent for a rival organization. She manipulates the team by revealing Mega X's true goal—to ruin their reputation by kidnapping their friends—before leading them directly into a deadly ambush.",
        faction: CharacterFaction.ANTAGONISTS,
        importance: 3,
        firstAppearanceEpisode: 50,
        lastAppearanceEpisode: 50,
    },
    {
        name: "Mega X Scientist (Basement)",
        description: "A lone scientist found hiding in a sterile basement in a ruined town. Believing she was caught by her own side, she was initially resigned to death until the team decided to feign friendship to extract information from her.",
        faction: CharacterFaction.ANTAGONISTS,
        importance: 2,
        firstAppearanceEpisode: 52,
        lastAppearanceEpisode: 52,
    },
    {
        name: "BenF",
        description: "A cryptic individual who makes deals with the team. He provided the initial intel on the Mayor and Doctor and later revealed a critical piece of lore: a planetary force field, erected after 'the nukes,' is preventing any escape to space.",
        faction: CharacterFaction.ALLIES,
        importance: 2,
        firstAppearanceEpisode: 53,
        lastAppearanceEpisode: 55,
    },
    {
        name: "Doctor",
        description: "An antagonist working with the Mayor. He warns the team of an incoming helicopter before initiating the ambush with a TNT explosion.",
        faction: CharacterFaction.ANTAGONISTS,
        importance: 2,
        firstAppearanceEpisode: 56,
        lastAppearanceEpisode: 56,
    },
    {
        name: "Mayor",
        description: "A high-ranking antagonist and leader who orchestrates the helicopter ambush. He communicates with the team directly, mocking their attempt to surrender.",
        faction: CharacterFaction.ANTAGONISTS,
        importance: 3,
        firstAppearanceEpisode: 56,
        lastAppearanceEpisode: 56,
    },
    {
        name: "Mischief",
        description: "A formidable antagonist and a key combatant in the helicopter ambush. He wields a massive, glowing blue sword and proves to be an incredibly durable and dangerous opponent.",
        faction: CharacterFaction.ANTAGONISTS,
        importance: 2,
        firstAppearanceEpisode: 56,
        lastAppearanceEpisode: 56,
    },
    {
        name: "FlakyFries",
        description: "A new combatant who fought alongside the protagonists during the chaotic helicopter ambush in the red brick courtyard.",
        faction: CharacterFaction.PROTAGONISTS,
        importance: 1,
        firstAppearanceEpisode: 56,
        lastAppearanceEpisode: 56,
    },
    {
        name: "noone",
        description: "A combatant who fought alongside the protagonists. After being captured and subjected to a horrific age regression experiment, she was rescued from mondad only to mysteriously vanish after Mike fired a 'scatter missile' from a tank. Her current status and whereabouts are unknown.",
        faction: CharacterFaction.PROTAGONISTS,
        importance: 2,
        firstAppearanceEpisode: 56,
        lastAppearanceEpisode: 58,
    },
    {
        name: "mondad",
        description: "A sinister antagonist who captured 'noone' and performed a horrific age regression experiment on her. After a tense standoff, he was killed, but respawned shortly after. He was finally killed for good by Mike, who used a powerful sword to end his threat permanently.",
        faction: CharacterFaction.ANTAGONISTS,
        importance: 3,
        firstAppearanceEpisode: 57,
        lastAppearanceEpisode: 58,
    },
    {
        name: "Mechanic",
        description: "An unnamed mechanic who was killed during a chaotic minecart ride in the Mega X Biodome, falling off the track into an abyss.",
        faction: CharacterFaction.ANTAGONISTS,
        importance: 1,
        firstAppearanceEpisode: 60,
        lastAppearanceEpisode: 60,
    },
    {
        name: "Captain_Schmitty",
        description: "The salty, no-nonsense captain of the vessel that transports the team after they escape the frozen wilderness. He agrees to help them on their quest, guiding them to the mysterious RMS Titanic.",
        faction: CharacterFaction.ALLIES,
        importance: 1,
        firstAppearanceEpisode: 69,
        lastAppearanceEpisode: 70,
    },
    {
        name: "The Guide (Canadian)",
        description: "A mysterious Canadian tour guide dressed entirely in black with a peculiar mask. He was captured and held aboard the RMS Titanic before being rescued by the team.",
        faction: CharacterFaction.ALLIES,
        importance: 1,
        firstAppearanceEpisode: 69,
        lastAppearanceEpisode: 70,
    },
    {
        name: "Cat (The Talking Dog)",
        description: "A giant, talking dog who, for some reason, is named Cat. He was captured alongside the Canadian tour guide and held aboard the RMS Titanic before being rescued.",
        faction: CharacterFaction.ALLIES,
        importance: 1,
        firstAppearanceEpisode: 69,
        lastAppearanceEpisode: 70,
    },
];