
import { Character, CharacterFaction } from './types';

export const CHARACTER_DATA_S2: Character[] = [
    {
        name: "EighthHalo",
        description: "A new player character in Season 2 with a penchant for massive explosives. He sacrifices himself with a bomb during a prison break and later uses a 'comically large missile' to obliterate an entire city, showing a casual disregard for collateral damage.",
        faction: CharacterFaction.PROTAGONISTS,
        importance: 2,
        firstAppearanceEpisode: 33,
        lastAppearanceEpisode: 37,
    },
    {
        name: "Reese (bestyrelse)",
        description: "A mysterious man in a red Hawaiian shirt whose plane is shot down by the team. He introduces himself as a member of a powerful PMC called 'the Alpones' and claims to be from their medical division. He possesses unsettling knowledge of the team's past, including their prison escape and their connection to Bloodless.",
        faction: CharacterFaction.THE_ALPONES,
        importance: 2,
        firstAppearanceEpisode: 35,
        lastAppearanceEpisode: 36,
    },
    {
        name: "AdmiralStewie",
        description: "A heavily armored, high-ranking guard of 'The Authority' in the snowy city. He confronts and captures the players after they are discovered in the weapons shop.",
        faction: CharacterFaction.THE_AUTHORITY,
        importance: 2,
        firstAppearanceEpisode: 33,
        lastAppearanceEpisode: 33,
    },
    {
        name: "Mega X Army Soldier",
        description: "A heavily-armored soldier and the sole survivor of the city's destruction. He is incredibly durable, tanking multiple bullets with ease. His presence confirms the continued existence of a 'Mega X Army,' posing a new threat.",
        faction: CharacterFaction.MEGA_X_ARMY,
        importance: 2,
        firstAppearanceEpisode: 34,
        lastAppearanceEpisode: 41,
    },
    {
        name: "Aboveriar (The Miner)",
        description: "A silent, voiceless miner encountered in a cave after a disastrous tunnel flood. He communicates using signs and attempts to guide the survivors to a village, but is killed in a sudden ambush.",
        faction: CharacterFaction.ALLIES,
        importance: 1,
        firstAppearanceEpisode: 37,
        lastAppearanceEpisode: 37,
    },
    {
        name: "Friendly Miner",
        description: "A friendly NPC miner found under attack in the Golden Cave system. After being saved by the team, he coexists peacefully with them as they gather resources.",
        faction: CharacterFaction.ALLIES,
        importance: 1,
        firstAppearanceEpisode: 38,
        lastAppearanceEpisode: 38,
    },
    {
        name: "El muchacho",
        description: "A new player character seen briefly in a cutscene, riding through a forest. His role in the main story is not yet clear.",
        faction: CharacterFaction.PROTAGONISTS,
        importance: 1,
        firstAppearanceEpisode: 33,
        lastAppearanceEpisode: 33,
    },
    {
        name: "darkphan",
        description: "A mysterious player who appears at the very end of the SCP Facility incident, joining the team after they escape the complex. He is killed shortly after in a highway ambush.",
        faction: CharacterFaction.ALLIES,
        importance: 1,
        firstAppearanceEpisode: 34,
        lastAppearanceEpisode: 35,
    },
    {
        name: "Camouflaged Soldier",
        description: "A new female ally in military camouflage who joins the survivors at the church. Her origins and allegiances are unknown, but she aids them in the fight against the skeletal boss monster on the roof.",
        faction: CharacterFaction.ALLIES,
        importance: 2,
        firstAppearanceEpisode: 39,
        lastAppearanceEpisode: 39,
    },
    {
        name: "plattealle (The Worker)",
        description: "A civilian worker coerced by the Mega X Crew into trapping the team. After his betrayal is revealed, he agrees to help the team escape in exchange for a golden sword, only to abandon them on a runaway boat.",
        faction: CharacterFaction.ANTAGONISTS,
        importance: 2,
        firstAppearanceEpisode: 41,
        lastAppearanceEpisode: 41,
    },
];
