// FIX: Corrected import path for types to './types' to match the flat project structure.
import { EpisodeSummary } from './types';

export const EPISODES_DATA: EpisodeSummary[] = [
    { episode: 1, title: "The Raid", summary: "The team infiltrates Mega X's Castle for revenge, rescuing the prisoner 'No One' in a loud and destructive assault." },
    { episode: 2, title: "The Escape", summary: "Mega X escapes to a ship. The team pursues, finds his associate 'Bloodless,' and rigs the ship to explode." },
    { episode: 3, title: "The Labyrinth", summary: "The team is trapped in a bizarre, looping backrooms-style prison, shifting their goal from vengeance to survival." },
    { episode: 4, title: "The Descent", summary: "The labyrinth begins to collapse, forcing a frantic descent. Tensions rise as Grape gets separated and clues about 'Bloodless' emerge." },
    { episode: 5, title: "The War and The Betrayal", summary: "Doctor Valeneria announces a wider war against Mega X. The team is betrayed from within, ending in a shocking cliffhanger." },
    { episode: 6, title: "The Researchers", summary: "The group enters a creepy new level inhabited by 'researchers' and gains a suspicious new ally after a tense encounter." },
    { episode: 8, title: "Pipe Dreams", summary: "In the dangerous Level 2, the team gets separated amidst new auditory threats and dwindling water supplies." },
    { episode: 9, title: "The FNAF Zone", summary: "A level resembling 'Five Nights at Freddy's' raises tensions as Rose's past betrayal is revealed, leading to a horrific ambush by 'Skin-Takers'." },
    { episode: 10, title: "The Industrial Zone", summary: "Mike and Kymar search a creepy industrial building, fighting off a semi-transparent red monster that inflicts blindness." },
    { episode: 11, title: "The Office", summary: "Mike, now alone, finds a camp of scientists in an office level and is given a map and armor by their untrustworthy guide." },
    { episode: 12, title: "The Event Hall", summary: "An elevator leads to a bizarre event hall with a red carpet and a strange, echoing opera monologue." },
    { episode: 13, title: "The Darkness", summary: "The team enters Level 6, a place of near-total darkness. In a stroke of luck, they find Rose, missing since Episode 9, alive." },
    { episode: 14, title: "The Snack Rooms", summary: "In a hazardous level with slippery floors, the team faces new 'human face dog creatures.' The scientist guide is shot and disappears." },
    { episode: 15, title: "The Endless Hallway", summary: "Trapped in a deceptively pleasant but looping hallway, the team makes a dangerous gamble on an untested teleporter." },
    { episode: 16, title: "The Titanic", summary: "The teleporter works, sending the group to a frozen ocean containing the RMS Titanic, where they learn Bloodless trapped Mega X soldiers." },
    { episode: 17, title: "Lost at Sea", summary: "While exploring the flooded Titanic, both Rose and Grape get separated again, throwing the team into disarray." },
    { episode: 18, title: "The Spider Gauntlet", summary: "Fleeing the Titanic, the team is pursued by an entity called 'God' and ambushed by giant spiders. They rescue a trapped Doctor Valeneria." },
    { episode: 19, title: "The Ascent", summary: "In the dark Level !, the team sees monsters falling from the sky. They use a massive supply of ladders to build their way up and escape." },
    { episode: 20, title: "The Ravine of Slaughter", summary: "After a hallway ambush, the team is teleported to a ravine swarming with monsters. Many are killed before the survivors find Lando's bizarre shop." },
    { episode: 21, title: "The Circus", summary: "The team battles through a surreal circus village and faces a gigantic clown boss. The escape is marked by internal betrayal." },
    { episode: 22, title: "The Endless Train", summary: "After another slaughter in the ravine, the survivors escape to an impossibly long train car where the entire team is unexpectedly reunited." },
    { episode: 23, title: "The Station", summary: "Kymar is reunited with Mike and Grape. They use TNT to escape a barn and find themselves trapped in a familiar train station." },
    { episode: 24, title: "The Endless Mall", summary: "The train takes them to a vast, empty shopping mall where they receive a new quest: craft 'Rocky Road' ice cream for a troll." },
    { episode: 25, title: "The Manifesto", summary: "While exploring the mall, the team finds books written by Bloodless, revealing she trapped them to stop them from uploading their videos." },
    { episode: 26, title: "The False Friend", summary: "The team meets Jeremy, a deceptive trickster who claims to be a good guy. He leads them to a high bridge where he reveals his betrayal." },
    { episode: 27, title: "The Frostbite Pursuit", summary: "The team chases Jeremy through a watery passage that inflicts 'Frostbite' damage, leading to a massive library where they are ambushed." },
    { episode: 28, title: "The Keys", summary: "After a rooftop ambush by Mega X forces, the team finds the first two of three keys needed to escape. A new, silent figure, 'Faceless,' appears." },
    { episode: 29, "title": "A World of Flesh", "summary": "After more explosions and another death, the team is teleported to a hellish dimension made of red flesh to continue their troll quest." },
    { episode: 30, title: "The Two Jeremys", summary: "In the flesh dimension, the team is trolled by a skeleton guide and confused by two versions of Jeremy before finding the final quest item in a TNT crater." },
    { episode: 31, title: "The Troll's Trap", summary: "The team delivers the items to Lando the Troll, who betrays them with a deadly trap before a disorienting chase leads to a final teleporter." },
    { episode: 32, title: "The Conspiracy", summary: "Ejected from the backrooms into a warzone, the team is hired by a priest for a suicide mission and learns they are to be executed afterwards." }
];
