import { Location } from './types';

export const LOCATIONS_DATA_S2: Location[] = [
    {
        id: 'snowy_city',
        name: "Snowy Post-Apocalyptic City",
        description: "The primary setting for the start of Season 2. A ruined, snow-covered city patrolled by hostile mobs and 'The Authority.' It is completely obliterated by a massive missile in Episode 34.",
        firstAppearanceEpisode: 33,
        lastAppearanceEpisode: 34,
    },
    {
        id: 'weapons_shop',
        name: "Weapons Smith Shop",
        description: "A derelict shop in the snowy city where the team finds a cache of guns and ammunition, triggering an alarm that leads to their capture.",
        firstAppearanceEpisode: 33,
        lastAppearanceEpisode: 33,
    },
    {
        id: 'city_prison',
        name: "The City Prison",
        description: "A fortified prison where 'The Authority' holds the players and other villagers captive. It becomes the site of a chaotic and deadly escape attempt.",
        firstAppearanceEpisode: 33,
        lastAppearanceEpisode: 33,
    },
    {
        id: 'the_crater',
        name: "The Crater",
        description: "The massive, smoking crater left behind after EighthHalo's 'comically large missile' completely destroyed the snowy city. The team respawns here and finds a lone survivor.",
        firstAppearanceEpisode: 34,
        lastAppearanceEpisode: 34,
    },
    {
        id: 'secret_facility',
        name: "Secret Facility",
        description: "A mysterious, top-secret building located next to the crater. The team breaks in to find it is a derelict SCP Foundation site, containing hostile anomalies like SCP-1507 (flamingos) and SCP-098 (crabs), and a network of surveillance cameras.",
        firstAppearanceEpisode: 34,
        lastAppearanceEpisode: 34,
    },
    {
        id: 'ruined_city',
        name: "Ruined Overgrown City",
        description: "A dilapidated modern city with overgrown streets and damaged buildings, located at the end of a long mountain tunnel. It becomes the site of a plane crash and a tense confrontation.",
        firstAppearanceEpisode: 35,
        lastAppearanceEpisode: 36,
    },
    {
        id: 'flooded_tunnel',
        name: "Flooded Minecart Tunnel",
        description: "A claustrophobic mine tunnel that becomes a deathtrap when a horn blares, plunging it into darkness and flooding it with water and hostile creatures.",
        firstAppearanceEpisode: 37,
        lastAppearanceEpisode: 37,
    },
    {
        id: 'miners_cave',
        name: "Miner's Escape Cave",
        description: "A small, rainy cave system that the survivors escape into from the flooded tunnel. It is here they meet the silent miner, Aboveriar.",
        firstAppearanceEpisode: 37,
        lastAppearanceEpisode: 37,
    },
    {
        id: 'monolith_bluff',
        name: "The Monolith Bluff",
        description: "A grassy bluff overlooking a large body of water from which a massive, impossibly tall black monolith rises. It serves as the site of the final, fatal ambush.",
        firstAppearanceEpisode: 37,
        lastAppearanceEpisode: 37,
    },
    {
        id: 'ambushed_village',
        name: "Ambushed Village",
        description: "A small, rustic village near the Monolith Bluff. The team is ambushed by a horde of monsters and wiped out before they can reach it.",
        firstAppearanceEpisode: 37,
        lastAppearanceEpisode: 37,
    },
    {
        id: 'golden_cave',
        name: "Golden Cave System",
        description: "A large, resource-rich cave system where the team respawns after the monolith ambush. It contains a massive, game-changing vein of gold ore, as well as friendly and hostile miners.",
        firstAppearanceEpisode: 38,
        lastAppearanceEpisode: 39,
    },
    {
        id: 'vine_covered_building',
        name: "Vine-Covered Building",
        description: "A dilapidated, vine-covered building near the church. The team discovers it is infested with a massive horde of zombies, leading to a desperate, claustrophobic fight.",
        firstAppearanceEpisode: 39,
        lastAppearanceEpisode: 39,
    },
    {
        id: 'waterfront_city',
        name: "The Waterfront City",
        description: "A large, modern city bordering the ocean, filled with hostile zombies. It contains strange pockets of civilization, like a fully functional car dealership run by an eccentric and treacherous dealer.",
        firstAppearanceEpisode: 41,
        lastAppearanceEpisode: 41,
    },
    {
        id: 'car_dealership',
        name: "The Car Dealership",
        description: "An improbably intact car dealership in the abandoned Waterfront City, run by a bizarre man who trades vehicles for violent favors and riddles.",
        firstAppearanceEpisode: 41,
        lastAppearanceEpisode: 41,
    },
    {
        id: 'jungle_outpost',
        name: "Jungle Outpost",
        description: "A ruined town surrounded by jungle, with a destroyed road. Contains a sterile concrete building with a basement where a Mega X scientist was hiding.",
        firstAppearanceEpisode: 42,
        lastAppearanceEpisode: 52,
    },
    {
        id: 'the_workshop',
        name: "The Workshop",
        description: "A grim, dark workshop within the Jungle Outpost. The interior contains cages with burning skeletons and a potion brewing stand. It becomes the site of a massive enemy ambush.",
        firstAppearanceEpisode: 43,
        lastAppearanceEpisode: 44,
    },
    {
        id: 'jungle_river_crossing',
        name: "Jungle River Crossing",
        description: "A wide, dark river in the middle of a dense jungle. The team is forced to build boats to cross it while being guided by the mysterious Bill, only to be ambushed before they can depart.",
        firstAppearanceEpisode: 45,
        lastAppearanceEpisode: 45,
    },
    {
        id: 'underwater_railway',
        name: "Underwater Railway Tunnel",
        description: "A submerged, glass-enclosed railway tunnel that Bill led the team into. It served as a deathtrap, flooding completely and trapping them with a monster.",
        firstAppearanceEpisode: 46,
        lastAppearanceEpisode: 46,
    },
    {
        id: 'greeter_city',
        name: "The Greeter City",
        description: "A coastal city inhabited by hostile blue-skinned humanoids who pose as welcoming 'greeters' before swarming their victims. The team's missing ally, EighthHalo, was seen among them.",
        firstAppearanceEpisode: 46,
        lastAppearanceEpisode: 46,
    },
    {
        id: 'sids_town',
        name: "Sid's Ambush Town",
        description: "A seemingly abandoned town where the team was led by Bill. It was the site of an ambush by the Doctor Mayor's forces and Bill's ultimate betrayal, culminating in a boss battle against Sid. The team was victorious, killing Bill, defeating Sid, and rescuing their tortured friend Jack from a basement before being ambushed again.",
        firstAppearanceEpisode: 47,
        lastAppearanceEpisode: 48,
    },
    {
        id: 'workshop_basement',
        name: "The Workshop Basement",
        description: "A grim basement within Sid's Town, filled with caged, burning skeletons. It served as the prison where Jack (EighthHalo) was tortured by Bill before being rescued by the team.",
        firstAppearanceEpisode: 48,
        lastAppearanceEpisode: 48,
    },
    {
        id: 'highway_town',
        name: "The Highway Town",
        description: "A dark, rainy coastal town connected to a highway, which the team paddled to after being stranded at sea. The town is infested with monsters and anomalous entities, forcing the team to find shelter immediately upon arrival.",
        firstAppearanceEpisode: 49,
        lastAppearanceEpisode: 50,
    },
    {
        id: 'grey_basement',
        name: "Grey Basement",
        description: "A sterile, grey basement in a dark building near the church, where the team discovered a lone Mega X scientist hiding.",
        firstAppearanceEpisode: 50,
        lastAppearanceEpisode: 50,
    },
    {
        id: 'grim_workshop',
        name: "The Grim Workshop",
        description: "A dark workshop filled with caged, burning skeletons and potion-making equipment. It was revealed to be a trap where the team was ambushed by a massive horde of enemies.",
        firstAppearanceEpisode: 50,
        lastAppearanceEpisode: 50,
    },
    {
        id: 'skeletal_bridge',
        name: "Skeletal Bridge",
        description: "A long, skeletal-looking bridge over a vast expanse of water. It was the site of a traumatic ambush where the team was attacked by both their former ally EighthHalo in a tank and the monstrous Reaper Twins.",
        firstAppearanceEpisode: 52,
        lastAppearanceEpisode: 52,
    },
    {
        id: 'raid_cave',
        name: "Flooded Raid Cave",
        description: "A dark, claustrophobic cave system where the team made a cryptic deal with BenF. It became the site of a 'Raid Difficulty 9' ambush, forcing the team to dig their way to the surface to escape.",
        firstAppearanceEpisode: 53,
        lastAppearanceEpisode: 53,
    },
    {
        id: 'flotilla_shore',
        name: "Flotilla Shore",
        description: "A sandy beach next to a vast ocean where the team emerged after escaping the raid cave. The area is littered with abandoned military boats and a massive battleship looms offshore.",
        firstAppearanceEpisode: 53,
        lastAppearanceEpisode: 54,
    },
    {
        id: 'battleship',
        name: "The Battleship",
        description: "A colossal, grey battleship discovered off the coast of the Flotilla Shore. The team commandeers the vessel, seizing a powerful new asset for their journey.",
        firstAppearanceEpisode: 53,
        lastAppearanceEpisode: 54,
    },
    {
        id: 'the_four_towns',
        name: "The Four Towns",
        description: "A cluster of four towns that become the team's primary objective after they receive intel that the Mayor and Doctor will be arriving in the area. The team splits up to scout each town.",
        firstAppearanceEpisode: 54,
        lastAppearanceEpisode: 55,
    },
    {
        id: 'blood_moon_sanctuary',
        name: "Blood Moon Sanctuary",
        description: "A small, hastily-dug dirt hole that the team used as a desperate sanctuary to survive the overwhelming horde of monsters spawned by the 'Blood Moon' event.",
        firstAppearanceEpisode: 55,
        lastAppearanceEpisode: 55,
    },
    {
        id: 'red_brick_courtyard',
        name: "Red Brick Courtyard",
        description: "A blood-stained courtyard in one of the Four Towns. It served as the site of a massive ambush initiated by the Mayor and Doctor, where the team was overwhelmed by a superior enemy force.",
        firstAppearanceEpisode: 56,
        lastAppearanceEpisode: 56,
    },
    {
        id: 'tank_crash_site',
        name: "Tank Crash Site",
        description: "A ruined city street and courtyard where Mike crashed a hijacked tank. The site includes a small cave where the team was cornered and later confronted the antagonist 'mondad'.",
        firstAppearanceEpisode: 57,
        lastAppearanceEpisode: 58,
    },
    {
        id: 'overpass_crash_site',
        name: "Overpass Crash Site",
        description: "A ruined city courtyard beneath a concrete overpass where the team's biplane crashed. The site of a bizarre argument and the discovery of a larger plane.",
        firstAppearanceEpisode: 59,
        lastAppearanceEpisode: 59,
    },
    {
        id: 'crater_town_outskirts',
        name: "Crater Town Outskirts",
        description: "The outskirts of a ruined town, marked by a massive crater that has destroyed the road, forcing the team to abandon their vehicle.",
        firstAppearanceEpisode: 59,
        lastAppearanceEpisode: 59,
    },
    {
        id: 'scientist_basement_courtyard',
        name: "Scientist's Basement (Courtyard)",
        description: "A sterile, grey basement beneath a concrete building where a second lone Mega X scientist was discovered and held at gunpoint.",
        firstAppearanceEpisode: 59,
        lastAppearanceEpisode: 59,
    },
    {
        id: 'mega_x_biodome',
        name: "Mega X Biodome",
        description: "A massive, self-contained glass dome housing multiple artificial biomes, including a lush forest and a vast desert. It serves as a major Mega X research facility that the team infiltrated in a past mission.",
        firstAppearanceEpisode: 60,
        lastAppearanceEpisode: 60,
    },
    {
        id: 'biodome_minecart_tunnels',
        name: "Biodome Minecart Tunnels",
        description: "A network of sterile, white tunnels beneath the Mega X Biodome, used for transportation via minecarts. The ride is perilous and leads to different biomes within the facility.",
        firstAppearanceEpisode: 60,
        lastAppearanceEpisode: 60,
    },
    {
        id: 'biodome_desert',
        name: "Biodome Desert Biome",
        description: "A vast, artificial desert landscape with orange sand, contained within the Mega X Biodome. It is patrolled by silent guards and features a massive, twisted black tower in the distance.",
        firstAppearanceEpisode: 60,
        lastAppearanceEpisode: 60,
    },
];