
import { Location } from './types';

export const LOCATIONS_DATA_S2: Location[] = [
    {
        id: 'snowy_city',
        name: "Snowy Post-Apocalyptic City",
        description: "The primary setting for the start of Season 2. A ruined, snow-covered city patrolled by hostile mobs and 'The Authority.' It is completely obliterated by a massive missile in Episode 34.",
        firstAppearanceEpisode: 33,
        lastAppearanceEpisode: 34,
    },
    {
        id: 'weapons_shop',
        name: "Weapons Smith Shop",
        description: "A derelict shop in the snowy city where the team finds a cache of guns and ammunition, triggering an alarm that leads to their capture.",
        firstAppearanceEpisode: 33,
        lastAppearanceEpisode: 33,
    },
    {
        id: 'city_prison',
        name: "The City Prison",
        description: "A fortified prison where 'The Authority' holds the players and other villagers captive. It becomes the site of a chaotic and deadly escape attempt.",
        firstAppearanceEpisode: 33,
        lastAppearanceEpisode: 33,
    },
    {
        id: 'the_crater',
        name: "The Crater",
        description: "The massive, smoking crater left behind after EighthHalo's 'comically large missile' completely destroyed the snowy city. The team respawns here and finds a lone survivor.",
        firstAppearanceEpisode: 34,
        lastAppearanceEpisode: 34,
    },
    {
        id: 'secret_facility',
        name: "Secret Facility",
        description: "A mysterious, top-secret building located next to the crater. The team breaks in to find it is a derelict SCP Foundation site, containing hostile anomalies like SCP-1507 (flamingos) and SCP-098 (crabs), and a network of surveillance cameras.",
        firstAppearanceEpisode: 34,
        lastAppearanceEpisode: 34,
    },
    {
        id: 'ruined_city',
        name: "Ruined Overgrown City",
        description: "A dilapidated modern city with overgrown streets and damaged buildings, located at the end of a long mountain tunnel. It becomes the site of a plane crash and a tense confrontation.",
        firstAppearanceEpisode: 35,
        lastAppearanceEpisode: 36,
    },
    {
        id: 'flooded_tunnel',
        name: "Flooded Minecart Tunnel",
        description: "A claustrophobic mine tunnel that becomes a deathtrap when a horn blares, plunging it into darkness and flooding it with water and hostile creatures.",
        firstAppearanceEpisode: 37,
        lastAppearanceEpisode: 37,
    },
    {
        id: 'miners_cave',
        name: "Miner's Escape Cave",
        description: "A small, rainy cave system that the survivors escape into from the flooded tunnel. It is here they meet the silent miner, Aboveriar.",
        firstAppearanceEpisode: 37,
        lastAppearanceEpisode: 37,
    },
    {
        id: 'monolith_bluff',
        name: "The Monolith Bluff",
        description: "A grassy bluff overlooking a large body of water from which a massive, impossibly tall black monolith rises. It serves as the site of the final, fatal ambush.",
        firstAppearanceEpisode: 37,
        lastAppearanceEpisode: 37,
    },
    {
        id: 'ambushed_village',
        name: "Ambushed Village",
        description: "A small, rustic village near the Monolith Bluff. The team is ambushed by a horde of monsters and wiped out before they can reach it.",
        firstAppearanceEpisode: 37,
        lastAppearanceEpisode: 37,
    },
    {
        id: 'golden_cave',
        name: "Golden Cave System",
        description: "A large, resource-rich cave system where the team respawns after the monolith ambush. It contains a massive, game-changing vein of gold ore, as well as friendly and hostile miners.",
        firstAppearanceEpisode: 38,
        lastAppearanceEpisode: 39,
    },
    {
        id: 'vine_covered_building',
        name: "Vine-Covered Building",
        description: "A dilapidated, vine-covered building near the church. The team discovers it is infested with a massive horde of zombies, leading to a desperate, claustrophobic fight.",
        firstAppearanceEpisode: 39,
        lastAppearanceEpisode: 39,
    },
    {
        id: 'broken_bridge',
        name: "The Broken Bridge",
        description: "A large bridge leading out of the abandoned city courtyard, destroyed by the Mega X Crew to trap the team. It becomes the site of a tense negotiation with the coerced worker, plattealle.",
        firstAppearanceEpisode: 41,
        lastAppearanceEpisode: 41,
    },
    {
        id: 'waterway',
        name: "The Waterway",
        description: "A dark body of water separating the city from the distant docks. The team traverses it on a stolen amphibious boat provided by plattealle.",
        firstAppearanceEpisode: 41,
        lastAppearanceEpisode: 41,
    },
    {
        id: 'distant_docks',
        name: "The Distant City Docks",
        description: "The apparent destination of the runaway amphibious boat after plattealle abandons the team. It is the entry point to a new, unknown city.",
        firstAppearanceEpisode: 41,
        lastAppearanceEpisode: 41,
    },
];
