// FIX: Corrected import path for types to './types' to match the flat project structure.
import { BackroomsLocationNode, BackroomsConnection } from './types';

export const BACKROOMS_MAP_DATA: BackroomsLocationNode[] = [
    { id: 'labyrinth', label: 'The Labyrinth', x: 100, y: 250, episode: 3 },
    { id: 'pipe_dreams', label: 'Pipe Dreams', x: 250, y: 150, episode: 8 },
    { id: 'fnaf_zone', label: 'FNAF Zone', x: 400, y: 250, episode: 9 },
    { id: 'office', label: 'The Office', x: 250, y: 350, episode: 11 },
    { id: 'event_hall', label: 'Event Hall', x: 250, y: 450, episode: 12 },
    { id: 'darkness', label: 'The Darkness', x: 550, y: 180, episode: 13 },
    { id: 'snack_rooms', label: 'Snack Rooms', x: 550, y: 320, episode: 14 },
    { id: 'hallway', label: 'Endless Hallway', x: 700, y: 250, episode: 15 },
    { id: 'titanic', label: 'The Titanic', x: 900, y: 100, episode: 16 },
    { id: 'spider_gauntlet', label: 'Spider Gauntlet', x: 900, y: 400, episode: 18 },
    { id: 'ambush_hallway', label: 'Ambush Hallway', x: 1050, y: 400, episode: 20 },
    { id: 'slaughter_ravine', label: 'Slaughter Ravine', x: 1200, y: 300, episode: 20 },
    { id: 'lando_shop', label: "Lando's Shop", x: 1200, y: 150, episode: 20 },
    { id: 'pool_room', label: 'The Pool Room', x: 1350, y: 150, episode: 20 },
    { id: 'circus_village', label: 'Circus Village', x: 1500, y: 150, episode: 21 },
    { id: 'circus_tent', label: 'Circus Tent', x: 1650, y: 150, episode: 21 },
    { id: 'hospital_ward', label: 'Hospital Ward', x: 1800, y: 250, episode: 21 },
    { id: 'circus_trailers', label: 'Circus Trailers', x: 1650, y: 300, episode: 21 },
    { id: 'surreal_cyan_forest', label: 'Surreal Forest', x: 100, y: 400, episode: 22 },
    { id: 'unfinished_barn', label: 'Unfinished Barn', x: 100, y: 550, episode: 23 },
    { id: 'highway_tunnel', label: 'Highway Tunnel', x: 300, y: 550, episode: 23 },
    { id: 'train_station', label: 'Train Station', x: 500, y: 550, episode: 23 },
    { id: 'endless_train_car', label: 'Endless Train', x: 800, y: 550, episode: 22 },
    { id: 'shopping_mall', label: 'Endless Mall', x: 1000, y: 550, episode: 24 },
    { id: 'marketplace', label: 'Marketplace', x: 1200, y: 550, episode: 26 },
    { id: 'quartz_bridge', label: 'Quartz Bridge', x: 1400, y: 550, episode: 26 },
    { id: 'prismarine_passage', label: 'Prismarine Passage', x: 1600, y: 550, episode: 27 },
    { id: 'grand_library', label: 'Grand Library', x: 1750, y: 450, episode: 27 },
    { id: 'sewer_system', label: 'Sewer System', x: 1900, y: 550, episode: 27 },
    { id: 'sterile_rooms', label: 'Sterile Complex', x: 2050, y: 450, episode: 28 },
    { id: 'rooftop_terrace', label: 'Rooftop Terrace', x: 2200, y: 350, episode: 28 },
    { id: 'airship', label: 'The Airship', x: 2400, y: 250, episode: 28 },
    { id: 'floating_city', label: 'Floating City', x: 2400, y: 450, episode: 29 },
    { id: 'crimson_dimension', label: 'Crimson Dimension', x: 2600, y: 550, episode: 29 },
];

export const BACKROOMS_CONNECTIONS_DATA: BackroomsConnection[] = [
    { from: 'labyrinth', to: 'pipe_dreams' },
    { from: 'pipe_dreams', to: 'fnaf_zone' },
    { from: 'labyrinth', to: 'office' },
    { from: 'office', to: 'event_hall' },
    { from: 'fnaf_zone', to: 'darkness' },
    { from: 'office', to: 'snack_rooms' },
    { from: 'darkness', to: 'hallway' },
    { from: 'snack_rooms', to: 'hallway' },
    { from: 'hallway', to: 'titanic' },
    { from: 'titanic', to: 'spider_gauntlet' },
    { from: 'spider_gauntlet', to: 'ambush_hallway' },
    { from: 'ambush_hallway', to: 'slaughter_ravine' },
    { from: 'slaughter_ravine', to: 'lando_shop' },
    { from: 'lando_shop', to: 'pool_room' },
    { from: 'pool_room', to: 'circus_village' },
    { from: 'circus_village', to: 'circus_tent' },
    { from: 'circus_tent', to: 'hospital_ward' },
    { from: 'circus_tent', to: 'circus_trailers' },
    { from: 'hospital_ward', to: 'labyrinth' },
    { from: 'labyrinth', to: 'surreal_cyan_forest' },
    { from: 'surreal_cyan_forest', to: 'slaughter_ravine' },
    { from: 'slaughter_ravine', to: 'unfinished_barn' },
    { from: 'unfinished_barn', to: 'highway_tunnel' },
    { from: 'highway_tunnel', to: 'train_station' },
    { from: 'train_station', to: 'endless_train_car' },
    { from: 'endless_train_car', to: 'shopping_mall' },
    { from: 'shopping_mall', to: 'marketplace' },
    { from: 'marketplace', to: 'quartz_bridge' },
    { from: 'quartz_bridge', to: 'prismarine_passage' },
    { from: 'prismarine_passage', to: 'grand_library' },
    { from: 'grand_library', to: 'sewer_system' },
    { from: 'sewer_system', to: 'sterile_rooms' },
    { from: 'sterile_rooms', to: 'rooftop_terrace' },
    { from: 'rooftop_terrace', to: 'floating_city' },
    { from: 'floating_city', to: 'crimson_dimension' },
    { from: 'crimson_dimension', to: 'pool_room' },
];
