// map-data/kivotos/GrandLatin.js
export const grandLatinPois = [
    { id: 'poi_gl_trinity_cathedral', x: 70.1, y: 55.2, type: 'temple', name: "Trinity Grand Cathedral", subRegion: 'grand_latin', description: "The magnificent centerpiece of the Trinity district. A place of quiet reflection, political maneuvering, and the headquarters of the Sisterhood.", factionId: 'trinity_general_school', intelReq: 10, political_influence: 9, economic_value: 5, military_strength: 7, population: 1000 },
    { id: 'poi_gl_tea_party_garden', x: 68.0, y: 51.5, type: 'landmark', name: "Tea Party Garden", subRegion: 'grand_latin', description: "The elegant gardens where Trinity's ruling council, the Tea Party, holds its meetings. A place of deceptive tranquility and intense political games.", factionId: 'trinity_general_school', intelReq: 25, political_influence: 10, economic_value: 3, military_strength: 5, population: 100 },
    { id: 'poi_gl_trinity_library', x: 71.5, y: 50.1, type: 'library', name: "Trinity Integrated Library", subRegion: 'grand_latin', description: "One of the oldest and most comprehensive libraries in Kivotos, containing countless ancient texts. It is managed by the Library Committee.", factionId: 'trinity_general_school', intelReq: 15, political_influence: 7, economic_value: 4, military_strength: 4, population: 300 },
    { id: 'poi_gl_justice_task_force_hq', x: 67.2, y: 59.8, type: 'barracks', name: "Justice Task Force HQ", subRegion: 'grand_latin', description: "The headquarters and training grounds for Trinity's primary peacekeeping force. They are known for their strict adherence to the rules and their formidable firepower.", factionId: 'trinity_general_school', intelReq: 20, political_influence: 6, economic_value: 3, military_strength: 8, population: 2000 },
    { id: 'poi_gl_remedial_knights_chapterhouse', x: 71.0, y: 62.1, type: 'monastery', name: "Remedial Knights Chapterhouse", subRegion: 'grand_latin', description: "A combination hospital and fortress that serves as the base for Trinity's dedicated combat medics.", factionId: 'trinity_general_school', intelReq: 20, political_influence: 5, economic_value: 4, military_strength: 6, population: 800 },
    { id: 'poi_gl_patisserie', x: 66.5, y: 50.0, type: 'market', name: "Patisserie 'La Trinity'", subRegion: 'grand_latin', description: "A famous pastry shop known for its exquisite roll cakes. A popular neutral meeting spot for students from all academies.", factionId: 'unaligned', intelReq: 5, political_influence: 2, economic_value: 6, military_strength: 1, population: 30 },
    { id: 'poi_gl_old_chapel_ruins', x: 63.2, y: 83.1, type: 'ruins', name: "Old Chapel Ruins", subRegion: 'grand_latin', description: "The ruins of a chapel from before Trinity's founding. It is now a quiet, forgotten place, often used for secret meetings by the Make-Up Work Club.", factionId: 'unaligned', intelReq: 25, political_influence: 2, economic_value: 2, military_strength: 2, population: 0 },
    { id: 'poi_gl_gehenna_border_checkpoint', x: 62.0, y: 79.9, type: 'watchtower', name: "Trinity-Gehenna Border Checkpoint", subRegion: 'grand_latin', description: "A heavily fortified checkpoint on the border with the Gehenna district. It is a place of constant tension and frequent skirmishes.", factionId: 'trinity_general_school', intelReq: 15, political_influence: 4, economic_value: 2, military_strength: 8, population: 200 },
    { id: 'poi_gl_vigilante_crew_hideout', x: 78.0, y: 82.0, type: 'lair', name: "Self-proclaimed Vigilante Crew Hideout", subRegion: 'grand_latin', description: "The hideout of a small but boisterous group of Trinity students who fancy themselves vigilantes, often causing more trouble than they solve.", factionId: 'unaligned', intelReq: 10, political_influence: 2, economic_value: 1, military_strength: 3, population: 20 },
    { id: 'poi_gl_trinity_docks', x: 85.0, y: 79.0, type: 'port', name: "Trinity Waterfront Docks", subRegion: 'grand_latin', description: "The main port for the Trinity district, handling shipments of supplies and luxury goods. It is heavily patrolled by the Justice Task Force.", factionId: 'trinity_general_school', intelReq: 15, political_influence: 5, economic_value: 8, military_strength: 6, population: 1500 },
    { id: 'poi_gl_sisterhood_priory', x: 69.0, y: 57.5, type: 'academy', name: "Sisterhood Priory", subRegion: 'grand_latin', description: "A quiet and cloistered section of the cathedral where the devout and formidable members of the Sisterhood reside and train.", factionId: 'trinity_general_school', intelReq: 30, political_influence: 7, economic_value: 3, military_strength: 7, population: 400 },
    { id: 'poi_gl_after_school_sweets_club', x: 69.5, y: 49.0, type: 'inn', name: "After School Sweets Club Room", subRegion: 'grand_latin', description: "The club room for a group dedicated to finding and enjoying the best desserts in Kivotos. They possess a surprising amount of intel on cafes and supply routes.", factionId: 'unaligned', intelReq: 10, political_influence: 3, economic_value: 4, military_strength: 1, population: 4 },
    { id: 'poi_gl_abandoned_dormitory', x: 64.0, y: 86.0, type: 'ruins', name: "Abandoned Dormitory", subRegion: 'grand_latin', description: "An old, supposedly haunted dormitory on the outskirts of the district. A popular spot for urban legends and dares.", factionId: 'unaligned', intelReq: 10, political_influence: 1, economic_value: 1, military_strength: 1, population: 0 },
    { id: 'poi_gl_training_grounds', x: 65.0, y: 62.0, type: 'barracks', name: "Trinity Combat Training Grounds", subRegion: 'grand_latin', description: "An expansive area with firing ranges and mock urban environments where Trinity students hone their combat skills.", factionId: 'trinity_general_school', intelReq: 15, political_influence: 3, economic_value: 2, military_strength: 7, population: 500 },
    { id: 'poi_gl_riveria_park', x: 66.0, y: 53.0, type: 'landmark', name: "Riveria Park", subRegion: 'grand_latin', description: "A beautifully manicured park with fountains and sculptures, often used for formal events and duels of honor.", factionId: 'unaligned', intelReq: 5, political_influence: 3, economic_value: 2, military_strength: 2, population: 200 },
];
export const grandLatinData = {
    pointsOfInterest: grandLatinPois,
    fogOfWar: []
};
