// map-data/pokemon/oore.js
export const oorePois = [
    {
        id: 'poi_oo_outskirt_stand',
        x: 42.20,
        y: 18.34,
        type: 'outpost',
        name: "Outskirt Stand",
        description: "A lonely service station in the middle of the desert. It serves as a neutral ground for trainers, mechanics, and shadowy figures, making it an invaluable listening post for any faction.",
        factionId: 'unaligned',
        intelReq: 5,
        political_influence: 2,
        economic_value: 4,
        military_strength: 1,
        population: 10
    },
    {
        id: 'poi_oo_phenac_city',
        x: 48.5,
        y: 24.0,
        type: 'major_city',
        name: "Phenac City",
        description: "A beautiful oasis city, its pristine white walls stand in stark contrast to the surrounding desert. It is a major stronghold for the Pokémon League, but its prosperity makes it a tempting target for criminal organizations.",
        factionId: 'pokemon_league',
        intelReq: 10,
        political_influence: 8,
        economic_value: 7,
        military_strength: 6,
        population: 12000
    },
    {
        id: 'poi_oo_pyrite_town',
        x: 41.5,
        y: 34.0,
        type: 'town',
        name: "Pyrite Town",
        description: "A rough, lawless town carved out of a canyon, perpetually covered in dust. It is a known haven for Team Snagem and other criminal elements, operating outside of the League's control.",
        factionId: 'freelancer_underworld',
        intelReq: 20,
        political_influence: 3,
        economic_value: 5,
        military_strength: 4,
        population: 2500
    },
    {
        id: 'poi_oo_the_under',
        x: 42.0,
        y: 36.0,
        type: 'dungeon_entrance',
        name: "The Under",
        description: "A secret, neon-lit city built in caverns beneath Pyrite. It is the true heart of the criminal underworld in Oore, home to the most dangerous individuals and a black market for illegally modified Pokémon.",
        factionId: 'freelancer_underworld',
        intelReq: 45,
        political_influence: 5,
        economic_value: 7,
        military_strength: 6,
        population: 1000
    },
    {
        id: 'poi_oo_agate_village',
        x: 50.0,
        y: 20.0,
        type: 'village',
        name: "Agate Village",
        description: "A peaceful, secluded village of elderly and retired Pokémon trainers. It is a place of great wisdom and is considered sacred ground by the Trainer Guild, who fiercely protect its tranquility.",
        factionId: 'trainer_guild',
        intelReq: 15,
        political_influence: 4,
        economic_value: 3,
        military_strength: 3,
        population: 300
    },
    {
        id: 'poi_oo_mt_battle',
        x: 58.0,
        y: 28.0,
        type: 'mountain_pass',
        name: "Mt. Battle",
        description: "A massive volcano converted into a 100-trainer challenge gauntlet. It is the premier training facility in Oore, operated by the Pokémon League to prepare trainers for the region's harsh realities.",
        factionId: 'pokemon_league',
        intelReq: 20,
        political_influence: 5,
        economic_value: 6,
        military_strength: 8,
        population: 500
    },
    {
        id: 'poi_oo_gateon_port',
        x: 36.0,
        y: 29.0,
        type: 'port',
        name: "Gateon Port",
        description: "A bustling port town known for its unique spinning lighthouse and bustling shipyard. While officially neutral, its docks are a hotbed for smuggling and pirate activity.",
        factionId: 'unaligned',
        intelReq: 10,
        political_influence: 4,
        economic_value: 8,
        military_strength: 4,
        population: 4000
    },
    {
        id: 'poi_oo_hq_lab',
        x: 38.0,
        y: 25.0,
        type: 'academy',
        name: "Pokémon HQ Lab",
        description: "The main research facility in Oore, dedicated to studying the phenomenon of Shadow Pokémon and developing a purification process. It is a high-security installation under the direct control of the Pokémon League.",
        factionId: 'pokemon_league',
        intelReq: 35,
        political_influence: 6,
        economic_value: 5,
        military_strength: 7,
        population: 200
    },
    {
        id: 'poi_oo_realgam_tower',
        x: 56.0,
        y: 42.0,
        type: 'fortress',
        name: "Realgam Tower",
        description: "A colossal, opulent tower in the desert that hosts a prestigious colosseum. It is secretly the main headquarters for the criminal syndicate Cipher, a place of immense power and dark secrets.",
        factionId: 'freelancer_underworld',
        intelReq: 60,
        political_influence: 8,
        economic_value: 7,
        military_strength: 9,
        population: 1500
    },
    {
        id: 'poi_oo_cipher_key_lair',
        x: 51.0,
        y: 48.0,
        type: 'workshop',
        name: "Cipher Key Lair",
        description: "A hidden, underground factory where Cipher mass-produces their Shadow Pokémon. The facility is heavily guarded and its location is a closely guarded secret.",
        factionId: 'freelancer_underworld',
        intelReq: 70,
        political_influence: 3,
        economic_value: 6,
        military_strength: 8,
        population: 400
    },
    {
        id: 'poi_oo_snagem_hideout',
        x: 40.5,
        y: 42.0,
        type: 'lair',
        name: "Team Snagem Hideout",
        description: "The dilapidated, trap-filled headquarters of Team Snagem, a group of Pokémon thieves who work as Cipher's primary enforcement arm.",
        factionId: 'freelancer_underworld',
        intelReq: 30,
        political_influence: 3,
        economic_value: 4,
        military_strength: 5,
        population: 150
    },
    {
        id: 'poi_oo_shadow_lab',
        x: 59.0,
        y: 35.0,
        type: 'workshop',
        name: "Shadow Pokémon Lab",
        description: "A secret laboratory where Cipher scientists conduct cruel experiments to create and perfect the process of turning Pokémon into mindless fighting machines.",
        factionId: 'freelancer_underworld',
        intelReq: 55,
        political_influence: 2,
        economic_value: 5,
        military_strength: 7,
        population: 50
    },
    { id: 'poi_oo_under_colosseum', x: 42.5, y: 38.0, type: 'landmark', name: "The Under Colosseum", description: "An illegal battle stadium in The Under where trainers pit their Shadow Pokémon against each other in no-holds-barred fights for prize money.", factionId: 'freelancer_underworld', intelReq: 50 },
    { id: 'poi_oo_relic_forest', x: 52.0, y: 18.0, type: 'forest', name: "Relic Forest", description: "A petrified forest from a bygone era, now a place of great spiritual power. A shrine deep within is said to be the only place to purify Shadow Pokémon.", factionId: 'trainer_guild', intelReq: 30 },
    { id: 'poi_oo_cipher_admin_villa', x: 54.0, y: 22.0, type: 'landmark', name: "Cipher Admin Villa", description: "The luxurious, heavily guarded private villa of a high-ranking Cipher administrator. A place of decadence and dark plotting.", factionId: 'freelancer_underworld', intelReq: 65 }
];