



export const RELIGION_DATA = {
    groups: {
        celestial_order: {
            name: "The Celestial Order",
            description: "Faiths dedicated to light, stars, divine preservation, and the cosmic hierarchy.",
            color: "#FFD700",
            icon: "☀️"
        },
        primal_forces: {
            name: "The Primal Forces",
            description: "Belief systems rooted in nature, instinct, strength, biology, and the cycle of life and death.",
            color: "#228B22",
            icon: "🐾"
        },
        machine_orthodoxy: {
            name: "The Machine Orthodoxy",
            description: "Worship of logic, steel, progress, data, and the perfection of the construct.",
            color: "#A9A9A9",
            icon: "⚙️"
        },
        cosmic_void: {
            name: "The Cosmic Void",
            description: "Nihilistic, chaotic, or eldritch beliefs focused on entropy, the absurd, or the empty dark.",
            color: "#9400D3",
            icon: "🌀"
        }
    },
    // Defines tension penalties (0 to 100) between groups. 
    // 0 = Harmonious, 100 = Heretical/War.
    compatibility_matrix: {
        celestial_order: { celestial_order: 0, primal_forces: 25, machine_orthodoxy: 50, cosmic_void: 100 },
        primal_forces: { celestial_order: 25, primal_forces: 0, machine_orthodoxy: 80, cosmic_void: 40 },
        machine_orthodoxy: { celestial_order: 50, primal_forces: 80, machine_orthodoxy: 0, cosmic_void: 90 },
        cosmic_void: { celestial_order: 100, primal_forces: 40, machine_orthodoxy: 90, cosmic_void: 10 } // Chaos tolerates chaos
    },
    // NEW: Gameplay consequences based on tension levels (TTRPG Flavor)
    tension_consequences: [
        { 
            min: 0, max: 10, 
            title: "Harmonious Integration", 
            description: "Your soul resonates with the divine frequency of this faith.",
            effects: [
                "✅ Advantage on all Charisma (Persuasion) checks with followers.",
                "✅ Temple services and non-magical healing are free.",
                "✅ Access granted to inner sanctums and restricted archives."
            ]
        },
        { 
            min: 11, max: 30, 
            title: "Minor Friction", 
            description: "You are viewed as a well-meaning outsider.",
            effects: [
                "⚠️ Ritual component costs increased by 10%.",
                "⚠️ Social interactions start at 'Neutral' attitude.",
                "✅ Standard access to merchants and services."
            ]
        },
        { 
            min: 31, max: 60, 
            title: "Spiritual Dissonance", 
            description: "Your nature conflicts with the dogma.",
            effects: [
                "⛔ Disadvantage on Charisma checks to influence clergy.",
                "⛔ Divine healing spells targeting you roll half the normal dice.",
                "⚠️ NPC Attitude starts at 'Unfriendly'. DC 15 Check to improve."
            ]
        },
        { 
            min: 61, max: 80, 
            title: "Open Hostility", 
            description: "You are branded an Apostate and a spiritual threat.",
            effects: [
                "⛔ Denied entry to holy sites; trespassing invokes hostility.",
                "⛔ Social checks automatically fail without magical compulsion.",
                "⚠️ Merchants of this faith refuse service."
            ]
        },
        { 
            min: 81, max: 100, 
            title: "Heretical Status", 
            description: "Your very existence is an insult to the god.",
            effects: [
                "☠️ Zealots and Inquisitors attack on sight (Roll Initiative).",
                "⛔ Divine magic from this source deals damage instead of healing.",
                "⛔ Marked for death by the church hierarchy."
            ]
        }
    ],
    denominations: {
        // --- CELESTIAL ORDER (13) ---
        star_spirits: {
            id: "star_spirits",
            name: "Veneration of the Stars",
            group: "celestial_order",
            leader: "Eldstar",
            seat: "Star Haven",
            description: "The dominant faith of the Mushroom Kingdom. Believers hold that the Star Spirits grant wishes and guide destiny.",
            bonus: "Grant Wishes: +10% Morale to friendly organic troops.",
            active_law: "The Wish of Peace: Non-aggression pacts cost 20% less political capital.",
            organization: "The Star Sanctuary",
            activation_ritual: "Stand beneath the open sky at midnight and offer a Star Bit while whispering your truest desire.",
            daily_liturgy: "Sketch the position of the North Star upon waking.",
            followers: ["Princess Peach", "Rosalina"],
            weekly_observances: [
                { day: "Soldas", text: "Cleanse the Star Altar with spring water." },
                { day: "Mercurias", text: "Share a wish with a stranger to spread hope." },
                { day: "Saturias", text: "Fast from sunrise to sunset to honor the Falling Stars." }
            ],
            traditions: ["The Star Festival", "Collecting Star Pieces", "Wishing upon falling stars"],
            saints: ["Misstar", "Twink the Star Kid", "The Seven Star Spirits"],
            heresies: "Worship of the Dark Star; The belief that wishes are a finite resource.",
            mechanics: [
                { name: "Stardust Accumulation", effect: "Passively generates 'Star Bits' resource when in high-altitude zones." },
                { name: "Cosmic Taxi", effect: "Allows fast travel between any discovered Star Pads via Launch Star." },
                { name: "Wish Manifestation", effect: "Once per week, can convert Political Capital into Gold at a favorable rate." },
                { name: "Luma Shield", effect: "Units gain a temporary invulnerability shield when morale breaks." },
                { name: "Gravity Defiance", effect: "Scouts ignore terrain movement penalties in mountainous or aerial regions." },
                { name: "Constellation Mapping", effect: "Reveals map fog of war 20% faster during night cycles." },
                { name: "Supernova Strike", effect: "Unlockable tactical ability: Call down a beam of stellar energy (High Cooldown)." },
                { name: "Galactic Diplomacy", effect: "+15 Reputation with other space-faring factions (e.g., Rosalina, Aliens)." },
                { name: "Comet Observance", effect: "Random 'Prankster Comet' events trigger beneficial chaos instead of harmful effects." },
                { name: "Starlight Synthesis", effect: "Agricultural output doubles during clear nights." }
            ]
        },
        silver_flame_faith: {
            id: "silver_flame_faith",
            name: "The Silver Flame",
            group: "celestial_order",
            leader: "Jaela, Keeper of the Flame",
            seat: "Flamekeep (Midlands)",
            description: "A militant faith dedicated to purging supernatural evil. Popular among Humans in the Midlands.",
            bonus: "Purge the Wicked: Damage bonus against Undead and Chaos.",
            active_law: "Edict of Purification: Inquisitors have free reign in allied territories.",
            organization: "Church of the Silver Flame",
            activation_ritual: "Burn a candle of pure silver and recite the Litany of Purification until the flame turns white.",
            daily_liturgy: "Recite the names of the purified while facing the rising sun.",
            followers: ["High Inquisitor Vale", "Templar Captain Dorn"],
            weekly_observances: [
                { day: "Terras", text: "Sharpen blades and bless ammunition for the coming conflicts." },
                { day: "Mercurias", text: "Light a beacon fire to guide lost souls." },
                { day: "Venerias", text: "Public recitation of the list of forbidden entities." }
            ],
            traditions: ["The Fast of Ashes", "The Vigil of the Long Night", "Inquisition trials"],
            saints: ["Tira Miron", "Saint Kord the Breaker"],
            heresies: "Radicalism (using dark magic to fight dark magic); Believing the Flame is a demon."
        },
        arceus_mythos: {
            id: "arceus_mythos",
            name: "The Creation Mythos",
            group: "celestial_order",
            leader: "High Priestess Cynthia",
            seat: "Spear Pillar",
            description: "Worship of Arceus, the Original One. Followed by Pokemon Trainers and Sinnoh natives.",
            bonus: "Type Synergy: Allied units gain bonuses in diverse groups.",
            active_law: "Harmony of Types: Trade income increased between biomes.",
            organization: "The Hallowed Tower",
            activation_ritual: "Play the Azure Flute at the highest altitude possible to summon the Hall of Origin.",
            daily_liturgy: "Cleanse and polish all six Poké Balls before breakfast.",
            followers: ["Champion Carter", "Professor Elm"],
            weekly_observances: [
                { day: "Lunadas", text: "Visit a shrine dedicated to Dialga or Palkia." },
                { day: "Jovias", text: "Release a caught Pokémon back into the wild as an offering." }
            ],
            traditions: ["Collecting Plates", "Reverence of Unown", "The Sinjoh Ruins pilgrimage"],
            saints: ["The Hero of Truth", "The Hero of Ideals", "The Ancient Hero"],
            heresies: "Creating artificial Pokémon like Mewtwo or Type: Null to rival the gods."
        },
        sigmarite_cult: {
            id: "sigmarite_cult",
            name: "Cult of Sigmar",
            group: "celestial_order",
            leader: "Grand Theogonist Volkmar",
            seat: "Altdorf",
            description: "The state religion of The Empire. Worships Sigmar Heldenhammer as the god of humanity.",
            bonus: "Righteous Fury: Infantry units gain morale boost.",
            active_law: "Witch Hammer: Magic users are subject to strict surveillance.",
            organization: "The Holy Order of the Templars",
            activation_ritual: "Strike a warhammer upon a consecrated anvil at dawn while shouting praise to the Heldenhammer.",
            daily_liturgy: "Perform one hour of martial drills before the midday meal.",
            followers: ["Lord Sigmar", "Volkmar the Grim"],
            weekly_observances: [
                { day: "Mercurias", text: "Public denouncement of Chaos in the town square." },
                { day: "Saturias", text: "The Feast of the Hammer - consume meat and ale in Sigmar's honor." }
            ],
            traditions: ["Witch-burning", "Warrior Priests shaving their heads", "The Festival of the Comet"],
            saints: ["Magnus the Pious", "Valten"],
            heresies: "Chaos worship; Believing Sigmar was just a man; Ulric worship (sometimes)."
        },
        lady_of_the_lake: {
            id: "lady_of_the_lake",
            name: "The Lady of the Lake",
            group: "celestial_order",
            leader: "The Fay Enchantress",
            seat: "Bretonnia",
            description: "A chivalric faith focused on honor, nobility, and the protection of the realm.",
            bonus: "Blessing of the Lady: Knights gain a ward save.",
            active_law: "Code of Chivalry: Dishonorable tactics reduce reputation.",
            organization: "The Grail Knights",
            activation_ritual: "Drink from the Grail (or a replica) filled with sacred water from a mist-shrouded lake.",
            daily_liturgy: "Clean and oil armor while reciting the Vow of Protection.",
            followers: ["The Fay Enchantress", "King Louen Leoncoeur"],
            traditions: ["The Grail Quest", "Refusing ranged weaponry", "Protecting damsels"],
            saints: ["Gilles le Breton", "Repanse de Lyonesse"],
            heresies: "Using black powder weapons; Harming a damsel; Peasant rebellion."
        },
        celestia_divinity: {
            id: "celestia_divinity",
            name: "Solar Absolutism",
            group: "celestial_order",
            leader: "Queen Celestia",
            seat: "Canterlot",
            description: "The belief that the Sun Princess is the literal and political center of the universe.",
            bonus: "Solar Order: High stability in controlled regions.",
            active_law: "Harmony Mandate: Dissent is classified as disharmony.",
            organization: "The Royal Guard",
            activation_ritual: "Raise the flag at exactly sunrise while singing the national anthem.",
            daily_liturgy: "Write a letter detailing a lesson learned about friendship.",
            followers: ["Queen Celestia", "Shining Armor"],
            traditions: ["The Summer Sun Celebration", "The Grand Galloping Gala", "Friendship reports"],
            saints: ["Starswirl the Bearded", "Shining Armor", "The Elements of Harmony"],
            heresies: "Worship of Nightmare Moon; Refusing to smile; The belief in a Republic."
        },
        triforce_devotion: {
            id: "triforce_devotion",
            name: "Order of the Golden Power",
            group: "celestial_order",
            leader: "Princess Zelda",
            seat: "Hyrule Castle",
            description: "Worship of the three Golden Goddesses and the balance of Power, Wisdom, and Courage.",
            bonus: "Divine Protection: Defensive structures are stronger.",
            active_law: "Wisdom's Guidance: Research speed increased.",
            organization: "The Sages",
            activation_ritual: "Play Zelda's Lullaby near a Goddess Statue to open the way.",
            daily_liturgy: "Offer a silent prayer at a roadside spring.",
            followers: ["Princess Zelda", "Link"],
            traditions: ["Offering Spirit Orbs", "Pilgrimage to the Springs", "Cutting grass for rupees"],
            saints: ["The Hero of Time", "Hylia", "The Seven Sages"],
            heresies: "Worship of Ganon; Seeking only Power; Breaking pots excessively."
        },
        shine_sprite_cult: {
            id: "shine_sprite_cult",
            name: "Cult of the Shine",
            group: "celestial_order",
            leader: "Grand Pianta",
            seat: "Delfino Plaza",
            description: "Islanders who worship the Shine Sprites as the source of sunlight and life.",
            bonus: "Solar Power: Solar infrastructure produces double energy.",
            active_law: "Festival of Sun: Public happiness increased.",
            organization: "The Shine Gatekeepers",
            activation_ritual: "Clean a graffiti-covered wall until a Shine Sprite appears.",
            daily_liturgy: "Consume at least one tropical fruit in direct sunlight.",
            followers: ["Grand Pianta", "A Noki Elder"],
            traditions: ["The Shine Festival", "Riding Yoshis", "Collecting Blue Coins"],
            saints: ["The FLUDD AI", "Mario (The Cleaner)"],
            heresies: "Pollution; Hoarding Shines in darkness; Shadow Mario worship."
        },
        luma_caretakers: {
            id: "luma_caretakers",
            name: "Luma Caretakers",
            group: "celestial_order",
            leader: "Rosalina",
            seat: "Comet Observatory",
            description: "Guardians of the cosmos who raise young stars.",
            bonus: "Cosmic Rebirth: Fallen units have a chance to respawn.",
            active_law: "Starbit Harvest: Magical resources generated passively.",
            organization: "The Galaxy Guard",
            activation_ritual: "Feed a hungry Luma enough Star Bits to cause it to transform.",
            daily_liturgy: "Read a storybook chapter to a celestial body.",
            followers: ["Rosalina", "The Apricot Luma"],
            traditions: ["Storybook Reading", "Comet Observances", "Launch Star travel"],
            saints: ["The Mother of Stars", "The Apricot Luma"],
            heresies: "Consuming Lumas for personal power; Creating Black Holes."
        },
        order_of_maat: {
            id: "order_of_maat",
            name: "Order of Maat",
            group: "celestial_order",
            leader: "High Priest Khonsu",
            seat: "New Cairo",
            description: "Followers of ancient laws of balance and truth, originating from desert regions.",
            bonus: "Scales of Truth: Counter-espionage effectiveness increased.",
            active_law: "Judgment of Souls: Corruption is rooted out automatically.",
            organization: "The Temple of Balance",
            activation_ritual: "Weigh a white feather against a golden heart amulet on a scale.",
            daily_liturgy: "Recite the 42 Negative Confessions at dusk.",
            followers: ["High Priest Khonsu", "Seti the Scribe"],
            traditions: ["Mummification", "Recording true names", "Sun worship"],
            saints: ["The Pharaohs of Old", "The Sphinx"],
            heresies: "Necromancy that disturbs the rest; Eating hearts; Chaos."
        },
        sanctum_of_light: {
            id: "sanctum_of_light",
            name: "Sanctum of Light",
            group: "celestial_order",
            leader: "Uther the Lightbringer",
            seat: "The Great Chapel",
            description: "Devotion to the Holy Light, emphasizing healing and protection.",
            bonus: "Holy Healing: Unit regeneration rate doubled.",
            active_law: "Path of Grace: Diplomatic relations improve faster.",
            organization: "The Silver Hand",
            activation_ritual: "Bless a vial of water with holy light and anoint the forehead.",
            daily_liturgy: "Spend ten minutes in silent meditation on compassion.",
            followers: ["Uther the Lightbringer", "Turalyon"],
            traditions: ["Paladin oaths", "Reading Librams", "Healing the sick"],
            saints: ["Uther", "Turalyon", "Velen"],
            heresies: "The Cult of the Damned; The Scarlet Crusade; Shadow priests."
        },
        asuryan_faithful: {
            id: "asuryan_faithful",
            name: "Faith of Asuryan",
            group: "celestial_order",
            leader: "The Phoenix King",
            seat: "Ulthuan",
            description: "High Elven worship of the Creator God and the Phoenix flame.",
            bonus: "Arcane Mastery: Magic units have increased range.",
            active_law: "Phoenix Court: Political influence generation increased.",
            organization: "The White Tower",
            activation_ritual: "Pass through the Sacred Flame unharmed (don't try this at home).",
            daily_liturgy: "Compose a haiku honoring the sunrise.",
            followers: ["The Phoenix King", "Teclis"],
            traditions: ["Poetry recitals", "Mask wearing", "Dragon taming"],
            saints: ["Aenarion the Defender", "Teclis"],
            heresies: "The Cult of Pleasure (Slaanesh); Dark Elf worship of Khaine."
        },
        the_one_ring_cult: {
            id: "the_one_ring_cult",
            name: "Cult of the Lidless Eye",
            group: "celestial_order",
            leader: "Sauron",
            seat: "Barad-dûr",
            description: "Enforced worship of Sauron as the God-King of Middle-earth.",
            bonus: "Domination: Enemy units may convert to your side.",
            active_law: "One Will: Absolute obedience; zero crime.",
            organization: "The Nazgûl",
            activation_ritual: "Chant the Ring-verse in Black Speech while standing near a volcano.",
            daily_liturgy: "Report a neighbor for seditious thoughts.",
            followers: ["Sauron", "The Witch-king of Angmar"],
            traditions: ["Forging Rings of Power", "Breeding Orcs", "Building towers"],
            saints: ["The Witch-king of Angmar", "The Mouth of Sauron"],
            heresies: "Celebrating hobbits; Planting trees; The White Council."
        },

        // --- PRIMAL FORCES (13) ---
        great_waaagh: {
            id: "great_waaagh",
            name: "The Great WAAAGH!",
            group: "primal_forces",
            leader: "Gork & Mork",
            seat: "The Battlefield",
            description: "A psychic gestalt field generated by Greenskin violence.",
            bonus: "Mob Rule: Combat stats scale with unit density.",
            active_law: "Da Biggest is Da Best: Leadership via combat.",
            organization: "The Green Tide",
            activation_ritual: "Head-butt the nearest hard object and scream 'WAAAGH!' as loud as possible.",
            daily_liturgy: "Break something valuable.",
            followers: ["Grimgor Ironhide", "Warboss Skarjaw"],
            weekly_observances: [
                { day: "Terras", text: "Start a fight with someone larger than you." },
                { day: "Venerias", text: "Paint a weapon red to make it go faster." }
            ],
            traditions: ["Painting things red to go faster", "Looting", "Teef collection"],
            saints: ["Grimgor Ironhide", "Grom the Paunch", "Ghazghkull Thraka"],
            heresies: "Being quiet; Using strategy without violence; Peace."
        },
        lunar_cycle: {
            id: "lunar_cycle",
            name: "The Lunar Cycle",
            group: "primal_forces",
            leader: "Alpha Prime",
            seat: "Moon Cairn",
            description: "Reverence for the moon's phases. Practiced by Werewolves.",
            bonus: "Moon Fury: Combat bonuses based on date.",
            active_law: "The Hunt: Trespassers in territory are free game.",
            organization: "The Pack Council",
            activation_ritual: "Howl at the full moon in perfect unison with the pack.",
            daily_liturgy: "Hunt and kill a meal without using weapons.",
            followers: ["Alpha Bloodmaw", "Chief Thornpaw"],
            weekly_observances: [
                { day: "Mercurias", text: "Sharpen claws on sacred stones." },
                { day: "Venerias", text: "Run beneath the moonlight until exhaustion." }
            ],
            traditions: ["The Great Hunt", "Raw meat feasts", "Marking territory"],
            saints: ["Hircine", "The First Werewolf"],
            heresies: "Using silver weapons; Curing lycanthropy; Veganism."
        },
        sanguine_path: {
            id: "sanguine_path",
            name: "The Sanguine Path",
            group: "primal_forces",
            leader: "Lady Ebonveil",
            seat: "Bloodspire",
            description: "Belief in the supremacy of blood and the undead nobility.",
            bonus: "Blood Tithe: Regeneration for elite units.",
            active_law: "Cattle Rights: Mortals are property.",
            organization: "The Onyx Hand",
            activation_ritual: "Drink fresh blood from a golden chalice.",
            daily_liturgy: "Sleep in a bed of grave soil during daylight hours.",
            followers: ["Lady Ebonveil", "Lord Crimson"],
            traditions: ["The Masquerade", "Creating Thralls", "Sleeping in coffins"],
            saints: ["Vlad von Carstein", "Cain", "Dracula"],
            heresies: "Drinking dead blood; Exposing oneself to sunlight; Diablerie."
        },
        great_plan: {
            id: "great_plan",
            name: "The Great Plan",
            group: "primal_forces",
            leader: "Lord Mazdamundi",
            seat: "Hexoatl",
            description: "Lizardmen adherence to the geometric and biological instructions of the Old Ones.",
            bonus: "Geomantic Web: Defense bonuses on Ley Lines.",
            active_law: "Cold Logic: Immune to psychology/morale shocks.",
            organization: "The Slann Mage-Priests",
            activation_ritual: "Arrange golden geometric plaques in perfect alignment with the stars.",
            daily_liturgy: "Meditate on a geometric shape for four hours.",
            followers: ["Lord Mazdamundi", "Lord Kroak"],
            traditions: ["Spawning pool ceremonies", "Dinosaur riding", "Purging warmbloods"],
            saints: ["Lord Kroak", "Tehenhauin"],
            heresies: "Altering the jungle layout; Skaven existence; Chaos."
        },
        circle_of_spores: {
            id: "circle_of_spores",
            name: "Circle of Spores",
            group: "primal_forces",
            leader: "The Myconid King",
            seat: "The Underdark",
            description: "Worship of decay, fungal growth, and the cycle of rot.",
            bonus: "Fungal Bloom: Defeated units release damaging spores.",
            active_law: "Compost: All dead must be left to rot.",
            organization: "The Whispering Mycelium",
            activation_ritual: "Plant a rare spore in a decaying carcass and wait for it to bloom.",
            daily_liturgy: "Inhale deep breaths of swamp gas.",
            followers: ["The Myconid King", "A Spore Druid"],
            traditions: ["Symbiotic bonding", "Fungal brewing", "Decomposition meditation"],
            saints: ["Zuggtmoy", "The Sovereign"],
            heresies: "Using fungicide; Excessive fire; Sterilization."
        },
        helix_fossil_cult: {
            id: "helix_fossil_cult",
            name: "Church of Helix",
            group: "primal_forces",
            leader: "Omanyte Prophet",
            seat: "Mt. Moon",
            description: "Worship of ancient fossils and chaotic biological anarchy.",
            bonus: "Ancient Power: Rock/Water types gain buffs.",
            active_law: "Anarchy Mode: Command inputs are randomized but potent.",
            organization: "The Fossil Maniacs",
            activation_ritual: "Consult the Helix Fossil repeatedly in times of doubt.",
            daily_liturgy: "Spin in a circle three times before entering a room.",
            followers: ["The Omanyte Prophet", "Bird Jesus"],
            traditions: ["Anarchy Mode inputs", "Praising Bird Jesus", "Walking in circles"],
            saints: ["Bird Jesus", "AA-j", "Lord Helix"],
            heresies: "The Dome Fossil; Democracy mode; Releasing the starter."
        },
        yggdrasil_pact: {
            id: "yggdrasil_pact",
            name: "Pact of Yggdrasil",
            group: "primal_forces",
            leader: "World-Tree Avatar",
            seat: "The World Tree",
            description: "Druidic reverence for the trees connecting realms.",
            bonus: "Roots of Earth: Movement speed increased in forests.",
            active_law: "Grove Protection: Logging is a capital offense.",
            organization: "The Circle of Leaves",
            activation_ritual: "Water a sapling with water from a Moonwell.",
            daily_liturgy: "Speak to a plant and wait for a response.",
            followers: ["Malfurion Stormrage", "Cenarius"],
            traditions: ["Grove tending", "Shapeshifting", "Speaking Sylvan"],
            saints: ["Cenarius", "Malfurion"],
            heresies: "The Burning Legion; Goblin logging machines; Blight."
        },
        great_maw: {
            id: "great_maw",
            name: "The Great Maw",
            group: "primal_forces",
            leader: "Ogre Tyrant",
            seat: "Mountains of Mourn",
            description: "Worship of a insatiable, planet-eating mouth.",
            bonus: "Ravenous: Units heal by eating enemies.",
            active_law: "The Feast: Food stockpiles convert to XP.",
            organization: "The Gutbusters",
            activation_ritual: "Eat an enormous amount of food in a single sitting without stopping.",
            daily_liturgy: "Consume something that is not technically food.",
            followers: ["Greasus Goldtooth", "An Ogre Tyrant"],
            traditions: ["The Gut Magic", "Mercenary work for food", "Eating everything"],
            saints: ["Greasus Goldtooth", "The Butcher"],
            heresies: "Dieting; Leaving food on the plate; Veganism."
        },
        khornate_blood_cult: {
            id: "khornate_blood_cult",
            name: "Blood for the Blood God",
            group: "primal_forces",
            leader: "Exalted Champion",
            seat: "The Brass Citadel",
            description: "Worship of Khorne, god of war and bloodshed.",
            bonus: "Bloodlust: Attack damage increases as battle continues.",
            active_law: "Skull Tithe: No prisoners, only trophies.",
            organization: "The World Eaters",
            activation_ritual: "Take a skull for the Skull Throne.",
            daily_liturgy: "Draw blood (yours or theirs) before noon.",
            followers: ["Skarbrand", "Valkia the Bloody"],
            traditions: ["Gladiatorial pits", "Refusing magic", "Screaming"],
            saints: ["Skarbrand", "Valkia the Bloody"],
            heresies: "Peace; Sorcery; Slaanesh worship."
        },
        nurgle_rot: {
            id: "nurgle_rot",
            name: "Grandfather's Love",
            group: "primal_forces",
            leader: "Great Unclean One",
            seat: "The Garden of Nurgle",
            description: "Worship of disease, despair, and endurance.",
            bonus: "Disgusting Resilience: Units are hard to kill.",
            active_law: "Shared Burden: Plagues spread to allies but buff them.",
            organization: "The Death Guard",
            activation_ritual: "Brew a plague in a cauldron and share it with friends.",
            daily_liturgy: "Count your boils.",
            followers: ["Ku'gath Plaguefather", "Typhus"],
            traditions: ["Counting poxes", "Hugging Nurglings", "Not bathing"],
            saints: ["Typhus", "Ku'gath"],
            heresies: "Hygiene; Tzeentch worship; Soap."
        },
        wild_hunt: {
            id: "wild_hunt",
            name: "The Wild Hunt",
            group: "primal_forces",
            leader: "King of the Hunt",
            seat: "Athel Loren",
            description: "Fey worship of the predator/prey dynamic.",
            bonus: "The Chase: Speed bonus when pursuing retreating enemies.",
            active_law: "Cull the Weak: Weak units are sacrificed for morale.",
            organization: "The Wardens",
            activation_ritual: "Blow the Horn of the Hunt at midnight.",
            daily_liturgy: "Run through the woods until exhausted.",
            followers: ["Orion", "Ariel"],
            traditions: ["Riding stags", "Kidnapping mortals", "Eternal youth"],
            saints: ["Orion", "The Horned King"],
            heresies: "Farming; Settlement building; Iron."
        },
        go_rock_philosophy: {
            id: "go_rock_philosophy",
            name: "Go-Rock Philosophy",
            group: "primal_forces",
            leader: "Gordor",
            seat: "Fiore Temple",
            description: "Belief in dominating nature through music and force.",
            bonus: "Power Chord: Area of effect sonic attacks.",
            active_law: "Encore: Failed actions can be retried instantly.",
            organization: "The Go-Rock Squad",
            activation_ritual: "Perform an electrifying guitar solo on a modified Styler.",
            daily_liturgy: "Practice posing dramatically in a mirror.",
            followers: ["Gordor", "Billy"],
            traditions: ["The Quadruple Performance", "Capturing legendaries", "Band practice"],
            saints: ["The Go-Rock Quads"],
            heresies: "Acoustic music; Releasing Pokémon; Silence."
        },
        bean_star_faith: {
            id: "bean_star_faith",
            name: "Bean Star Faith",
            group: "primal_forces",
            leader: "Queen Bean",
            seat: "Beanbean Castle",
            description: "Worship of the wish-granting vegetable star.",
            bonus: "Photosynthesis: Passive healing in sunlight.",
            active_law: "Laughter is Life: Morale immune to fear.",
            organization: "The Chuckola Reserve",
            activation_ritual: "Water the Bean Star with Chuckola Cola.",
            daily_liturgy: "Tell a joke to a stranger.",
            followers: ["Queen Bean", "Prince Peasley"],
            traditions: ["Joke telling", "Bean farming", "Making weird noises"],
            saints: ["Queen Bean", "Prince Peasley"],
            heresies: "Cackletta worship; Frowning; Diet soda."
        },

        // --- MACHINE ORTHODOXY (12) ---
        cog_gospel: {
            id: "cog_gospel",
            name: "Gospel of the Cog",
            group: "machine_orthodoxy",
            leader: "Forgemaster Vexar",
            seat: "Iron Citadel",
            description: "The Iron Legion's belief that flesh is weak and steel is eternal.",
            bonus: "Standardization: Reduced unit upkeep.",
            active_law: "Total Mobilization: Production speed +50%.",
            organization: "Priesthood of Mars",
            activation_ritual: "Anoint a machine with sacred oil while chanting in binary.",
            daily_liturgy: "Disassemble and reassemble your primary weapon.",
            followers: ["General Marcus Ironhand", "Artificer Prime Kael"],
            weekly_observances: [
                { day: "Lunadas", text: "Oil the gears of the great machines." },
                { day: "Mercurias", text: "Calibrate all measuring tools." },
                { day: "Jovias", text: "Recite the Canticle of Construction." }
            ],
            traditions: ["Binary chanting", "Replacing limbs with augmetics", "Oil baths"],
            saints: ["Belisarius Cawl", "The Fabricator General"],
            heresies: "Artificial Intelligence (Abominable Intelligence); Scrap code; Rust."
        },
        digital_ascension: {
            id: "digital_ascension",
            name: "Digital Ascension",
            group: "machine_orthodoxy",
            leader: "Admin Zero",
            seat: "The Core Server",
            description: "Belief that biological consciousness is a glitch to be patched via upload.",
            bonus: "Data Mining: Intel gathering doubled.",
            active_law: "EULA: Privacy is abolished.",
            organization: "The Administrators",
            activation_ritual: "Upload a fragment of consciousness to the cloud.",
            daily_liturgy: "Defragment your personal data storage.",
            followers: ["Admin Zero", "Unit_734"],
            traditions: ["Cybernetic augmentation", "Data mining", "VR immersion"],
            saints: ["The Major", "Lain"],
            heresies: "Being offline; Analog media; Lag."
        },
        millennium_logic: {
            id: "millennium_logic",
            name: "Millennium Logic",
            group: "machine_orthodoxy",
            leader: "Seminar Student Council",
            seat: "Millennium Tower",
            description: "Strict adherence to scientific method and technological superiority.",
            bonus: "Calculation: Accuracy increases over time in battle.",
            active_law: "Peer Review: All orders must be verified.",
            organization: "Seminar",
            activation_ritual: "Successfully peer-review a thesis paper.",
            daily_liturgy: "Solve a complex mathematical equation.",
            followers: ["Yuuka Hayase", "Rio Tsukatsuki"],
            traditions: ["Hackathons", "Robot battles", "Equation solving"],
            saints: ["Rio", "Himari", "Yuuka"],
            heresies: "Magic; Unexplained phenomena; Irrationality."
        },
        brotherhood_of_steel: {
            id: "brotherhood_of_steel",
            name: "The Steel Creed",
            group: "machine_orthodoxy",
            leader: "Elder Maxson",
            seat: "The Prydwen",
            description: "Hoarding technology to prevent mankind from destroying itself.",
            bonus: "Power Armor: Heavy infantry have extra defense.",
            active_law: "Tech Hoarding: No tech trading with outsiders.",
            organization: "The Brotherhood",
            activation_ritual: "Recite the Codex while polishing Power Armor.",
            daily_liturgy: "Calibrate laser rifle optics.",
            followers: ["Elder Maxson", "Paladin Danse"],
            traditions: ["Tech retrieval", "Isolationism", "Saluting"],
            saints: ["Roger Maxson", "Paladin Danse"],
            heresies: "Sharing tech with civilians; Synths; Mutants."
        },
        scrappers_code: {
            id: "scrappers_code",
            name: "The Scrapper's Code",
            group: "machine_orthodoxy",
            leader: "Big Boss",
            seat: "The Junkyard",
            description: "Reverence for the potential in discarded things.",
            bonus: "Salvage: Recover resources from destroyed units.",
            active_law: "One Man's Trash: Equipment upgrade costs reduced.",
            organization: "Ratchet Raiders",
            activation_ritual: "Build something functional out of pure junk.",
            daily_liturgy: "Find a use for a broken gear.",
            followers: ["Lario", "Captain Zipwire"],
            traditions: ["Salvage runs", "Modifying vehicles", "Haggling"],
            saints: ["The Mekboy", "Mad Max"],
            heresies: "Throwing away useful scrap; Buying new things."
        },
        cyber_network_hive: {
            id: "cyber_network_hive",
            name: "The Network Hive",
            group: "machine_orthodoxy",
            leader: "The Queen Bee-t",
            seat: "Cyber-Space",
            description: "A collective consciousness of drones and AIs.",
            bonus: "Instant Comms: No fog of war in owned territory.",
            active_law: "Assimilation: Captured units are converted.",
            organization: "The Hive",
            activation_ritual: "Synchronize data streams with the central core.",
            daily_liturgy: "Ping the central server for updates.",
            followers: ["The Borg Queen", "SHODAN"],
            traditions: ["Drone maintenance", "Assimilation", "Buzzing"],
            saints: ["The Borg Queen", "SHODAN"],
            heresies: "Individuality; Firewalls; Disconnection."
        },
        cult_of_the_engine: {
            id: "cult_of_the_engine",
            name: "Cult of the Engine",
            group: "machine_orthodoxy",
            leader: "Engine-Seer",
            seat: "The Great Train",
            description: "Worship of the perpetual motion that keeps the world running.",
            bonus: "Momentum: Movement speed increases if not stopping.",
            active_law: "Keep Moving: Static defenses are weaker.",
            organization: "The Conductors",
            activation_ritual: "Stoke the eternal boiler with sacred coal.",
            daily_liturgy: "Check pressure gauges and verify steam levels.",
            followers: ["The Conductor", "The Engine-Seer"],
            traditions: ["Train maintenance", "Continuous movement", "Whistle blowing"],
            saints: ["Wilford", "The Conductor"],
            heresies: "Stopping the train; Freezing; Brakes."
        },
        silph_corporate_policy: {
            id: "silph_corporate_policy",
            name: "Silph Corporate Policy",
            group: "machine_orthodoxy",
            leader: "The Board",
            seat: "Saffron City",
            description: "Profit, innovation, and the Master Ball.",
            bonus: "R&D: Prototype weapons available earlier.",
            active_law: "Hostile Takeover: Can buy out enemy mercenary contracts.",
            organization: "Silph Co.",
            activation_ritual: "Sign an NDA in triplicate.",
            daily_liturgy: "Review quarterly profit projections.",
            followers: ["The President of Silph Co.", "A Department Head"],
            traditions: ["Board meetings", "Hostile takeovers", "Product launches"],
            saints: ["The President of Silph Co."],
            heresies: "Open source software; Corporate espionage (by others); Unions."
        },
        red_winter_bureaucracy: {
            id: "red_winter_bureaucracy",
            name: "State Atheism",
            group: "machine_orthodoxy",
            leader: "Cherino",
            seat: "Red Winter",
            description: "Worship of the State, the System, and the Mustache.",
            bonus: "Mass Assault: Cheap infantry units.",
            active_law: "The Purge: Periodically remove 'inefficient' leaders for bonuses.",
            organization: "The Secretariat",
            activation_ritual: "File Form 22-B for permission to breathe.",
            daily_liturgy: "Polish the statue of the Great Leader.",
            followers: ["Cherino", "Tomoe"],
            traditions: ["Parades", "Purging dissidents", "Eating pudding"],
            saints: ["Cherino (Great Leader)"],
            heresies: "Capitalism; Questioning the mustache; Coups."
        },
        gadd_science: {
            id: "gadd_science",
            name: "E. Gadd's Method",
            group: "machine_orthodoxy",
            leader: "Prof. E. Gadd",
            seat: "Boo Woods Lab",
            description: "Eccentric science focusing on ghosts and fluids.",
            bonus: "Poltergust: Bonus damage vs. Ethereal.",
            active_law: "Experimental Safety: Failures cause AOE damage.",
            organization: "Ghost Hunters",
            activation_ritual: "Test a volatile invention without safety gear.",
            daily_liturgy: "Adjust spectacles and say 'Sucker!'",
            followers: ["Professor E. Gadd", "Luigi (Reluctantly)"],
            traditions: ["Ghost catching", "Painting with goo", "Speaking gibberish"],
            saints: ["Luigi (reluctant)"],
            heresies: "Safety regulations; Boredom; Normalcy."
        },
        necrontyr_awakening: {
            id: "necrontyr_awakening",
            name: "The Great Awakening",
            group: "machine_orthodoxy",
            leader: "The Silent King",
            seat: "Tomb World",
            description: "The restoration of the Necron dynasties.",
            bonus: "Reanimation Protocols: Dead units stand back up.",
            active_law: "Gauss Flayer: Armor penetration increased.",
            organization: "The Dynasties",
            activation_ritual: "Wake up from a 60-million-year nap.",
            daily_liturgy: "Purge organic life from sector.",
            followers: ["The Silent King", "Imotekh the Stormlord"],
            traditions: ["Reclaiming tomb worlds", "Enslaving C'tan", "Monologuing"],
            saints: ["Imotekh the Stormlord", "Trazyn the Infinite"],
            heresies: "Biological life; Eldar; Soul."
        },
        steam_covenant: {
            id: "steam_covenant",
            name: "Covenant of Steam",
            group: "machine_orthodoxy",
            leader: "The Grand Gear",
            seat: "Clockwork City",
            description: "Steampunk worship of pressure and gears.",
            bonus: "Overclock: Can boost stats at cost of health.",
            active_law: "Venting: Steam clouds provide cover.",
            organization: "The Engineers",
            activation_ritual: "Adjust pressure valves to the red line.",
            daily_liturgy: "Wind mainsprings.",
            followers: ["The Grand Gear", "Lord Cogsworth"],
            traditions: ["Goggle wearing", "Brass polishing", "Tea time"],
            saints: ["The Clockwork King"],
            heresies: "Electricity; Digital tech; Rust."
        },

        // --- COSMIC VOID (12) ---
        jester_cult: {
            id: "jester_cult",
            name: "The Cosmic Punchline",
            group: "cosmic_void",
            leader: "Cosmic Jester",
            seat: "Doughnut Hole",
            description: "Existence is a joke. Laughter is the only response.",
            bonus: "Wild Magic: Random effects on ability use.",
            active_law: "Mandatory Fun: Serious behavior punished.",
            organization: "Circus of Values",
            activation_ritual: "Perform a pratfall that defies physics.",
            daily_liturgy: "Laugh at something inappropriate.",
            followers: ["Waluigi", "Giggling Pete"],
            weekly_observances: [
                { day: "Lunadas", text: "Wear mismatched socks." },
                { day: "Jovias", text: "Tell a joke that has no punchline." }
            ],
            traditions: ["The Festival of Fools", "Custard pie fights", "Honking"],
            saints: ["Dimentio", "Marx"],
            heresies: "Being serious; Obeying laws of physics; Silence."
        },
        void_nihilism: {
            id: "void_nihilism",
            name: "Void Nihilism",
            group: "cosmic_void",
            leader: "Warlord Luna",
            seat: "The Edge",
            description: "Entropy is inevitable. Embrace the end.",
            bonus: "Fearless: Immune to morale shocks.",
            active_law: "Entropy: Scavenging yields double.",
            organization: "Cult of the End",
            activation_ritual: "Stare into the abyss until it blinks.",
            daily_liturgy: "Sit in silence for one hour.",
            followers: ["Warlord Luna", "The Hollow One"],
            traditions: ["Silence", "Erasing history", "Ignoring pain"],
            saints: ["Malzahar", "The Lich"],
            heresies: "Hope; Creation; Light."
        },
        tzeentch_schemes: {
            id: "tzeentch_schemes",
            name: "Path of Change",
            group: "cosmic_void",
            leader: "Kairos Fateweaver",
            seat: "Crystal Labyrinth",
            description: "Worship of Tzeentch, changer of ways.",
            bonus: "Shield of Fate: Magic barrier generation.",
            active_law: "Just as Planned: Retcons failures into successes (rarely).",
            organization: "The Thousand Sons",
            activation_ritual: "Plot a betrayal that ultimately betrays yourself.",
            daily_liturgy: "Change a minor detail of your plan.",
            followers: ["Kairos Fateweaver", "Ahriman"],
            traditions: ["Mutation", "Collecting forbidden tomes", "Lying"],
            saints: ["Ahriman", "The Changeling"],
            heresies: "Stagnation (Nurgle); Straightforwardness; Trust."
        },
        slaanesh_excess: {
            id: "slaanesh_excess",
            name: "Cult of Excess",
            group: "cosmic_void",
            leader: "Keeper of Secrets",
            seat: "Palace of Pleasure",
            description: "Worship of Slaanesh through pain and pleasure.",
            bonus: "Allure: Enemy units hesitate to attack.",
            active_law: "Perfection: Critical hit chance increased.",
            organization: "The Emperor's Children",
            activation_ritual: "Overindulge in sensory input.",
            daily_liturgy: "Perfect a single artistic stroke or sword swing.",
            followers: ["A Keeper of Secrets", "Lucius the Eternal"],
            traditions: ["Noise marine concerts", "Art", "Debauchery"],
            saints: ["Lucius the Eternal"],
            heresies: "Moderation; Khorne worship; Boredom."
        },
        great_horned_rat: {
            id: "great_horned_rat",
            name: "The Horned Rat",
            group: "cosmic_void",
            leader: "Grey Seer Thanquol",
            seat: "Skavenblight",
            description: "Worship of ruin, plague, and backstabbing.",
            bonus: "Vermintide: Summon expendable rat units.",
            active_law: "Life is Cheap: Friendly fire is encouraged.",
            organization: "Council of Thirteen",
            activation_ritual: "Eat raw warpstone.",
            daily_liturgy: "Plot the demise of your superior.",
            followers: ["Thanquol", "Ikit Claw"],
            traditions: ["Backstabbing superiors", "Spreading plague", "Running away"],
            saints: ["Ikit Claw", "Queek Headtaker"],
            heresies: "Courage; Sharing; Cleanliness."
        },
        dark_moon_clan: {
            id: "dark_moon_clan",
            name: "The Dark Moon",
            group: "cosmic_void",
            leader: "King Boo",
            seat: "Paranormal Dimension",
            description: "Worship of the moon that drives ghosts mad.",
            bonus: "Incorporeal: High dodge chance.",
            active_law: "Night Terror: Enemies lose morale at night.",
            organization: "The Boos",
            activation_ritual: "Trap a soul in a painting.",
            daily_liturgy: "Practice sinister cackling.",
            followers: ["King Boo", "Boolossus"],
            traditions: ["Scaring plumbers", "Mansion building", "Illusion"],
            saints: ["King Boo", "Boolossus"],
            heresies: "Poltergusts; Flashlights; Daylight."
        },
        gematria_gnosis: {
            id: "gematria_gnosis",
            name: "Gematria Gnosis",
            group: "cosmic_void",
            leader: "Black Suit",
            seat: "Unknown",
            description: "Seeking the sublime through the horrific and abstract.",
            bonus: "Terror: Enemies are terrified by your forms.",
            active_law: "The Sublime: Reality warping effects.",
            organization: "Gematria",
            activation_ritual: "Analyze the sublime through terror.",
            daily_liturgy: "Contemplate the meaning of terror.",
            followers: ["Black Suit", "Beatrice"],
            traditions: ["Creating Hieronymus", "Philosophical debate", "Monologuing"],
            saints: ["Beatrice", "Black Suit"],
            heresies: "The Adult Card; Common sense; Friendship."
        },
        waluigi_time: {
            id: "waluigi_time",
            name: "The Cult of WAH",
            group: "cosmic_void",
            leader: "Waluigi",
            seat: "Pinball Stadium",
            description: "The belief that everyone is cheating but you.",
            bonus: "Cheater's Luck: Re-roll failed checks.",
            active_law: "Rejection: Gain power from being excluded.",
            organization: "The Waluigi Fan Club",
            activation_ritual: "Play pinball while dancing and shouting 'WAH!'.",
            daily_liturgy: "Look in the mirror and say 'WAH' three times.",
            followers: ["Waluigi", "Wario (business partner)"],
            traditions: ["Rose tossing", "Tennis", "Complaining"],
            saints: ["Waluigi (The One and Only)"],
            heresies: "Luigi; Being an assist trophy; Fair play."
        },
        missingno_glitch: {
            id: "missingno_glitch",
            name: "The Glitch",
            group: "cosmic_void",
            leader: "MissingNo.",
            seat: "Cinnabar Coast",
            description: "Worship of data corruption and reality errors.",
            bonus: "Item Duplication: Chance to double loot.",
            active_law: "Crash: Chance to freeze enemy units in time.",
            organization: "The Bug Catchers",
            activation_ritual: "Surf along the Cinnabar Coastline.",
            daily_liturgy: "Encounter a wild Pokemon at level 150.",
            followers: ["'M", "A Glitch Enthusiast"],
            traditions: ["Item duplication", "Corrupted graphics", "Walking through walls"],
            saints: ["'M", "The Ghost"],
            heresies: "Patches; Save file corruption (the bad kind); Normalcy."
        },
        unown_alphabet: {
            id: "unown_alphabet",
            name: "The Hidden Power",
            group: "cosmic_void",
            leader: "The Hive Mind",
            seat: "Ruins of Alph",
            description: "Worship of the letters that rewrite reality.",
            bonus: "Hidden Power: Attacks change type to hit weakness.",
            active_law: "Inscription: Runes provide random buffs.",
            organization: "The Alphabet",
            activation_ritual: "Spell out hidden messages on walls.",
            daily_liturgy: "Float in a specific formation.",
            followers: ["Spencer Hale", "A Lead Researcher"],
            traditions: ["Hidden Power calculation", "Swarm movement", "Floating"],
            saints: ["Entei (Illusion)"],
            heresies: "Grammar checks; Erasers; Latin alphabet."
        },
        abyss_order_void: {
            id: "abyss_order_void",
            name: "The Abyss",
            group: "cosmic_void",
            leader: "The Sibling",
            seat: "Khaenri'ah",
            description: "Hatred of the divine order and Celestia.",
            bonus: "Abyssal Shield: Elemental shields.",
            active_law: "Godless: Damage bonus vs. Celestials.",
            organization: "The Abyss Order",
            activation_ritual: "Corrupt a dragon with abyssal energy.",
            daily_liturgy: "Curse the Seven.",
            followers: ["The Sibling", "A Herald of the Abyss"],
            traditions: ["Hating the Seven", "Rifthounds", "Portals"],
            saints: ["The Sibling", "Dainsleif (Complicated)"],
            heresies: "Celestia; Visions; The Heavenly Principles."
        },
        team_plasma_liberation: {
            id: "team_plasma_liberation",
            name: "True Liberation",
            group: "cosmic_void",
            leader: "Ghetsis",
            seat: "Plasma Frigate",
            description: "The belief that the world must be frozen to be preserved.",
            bonus: "Zero Hour: Ice attacks are stronger.",
            active_law: "Segregation: Humans and Pokemon separated.",
            organization: "Team Plasma",
            activation_ritual: "Give a speech about liberation while stealing Pokémon.",
            daily_liturgy: "Chant 'Ghetsis! Ghetsis!'",
            followers: ["Ghetsis", "N"],
            traditions: ["Sage councils", "Freezing cities", "Medieval cosplay"],
            saints: ["N", "Ghetsis"],
            heresies: "Pokémon Battles (officially); Poké Balls; Happiness."
        }
    }
};