// map-data/doughnut-hole/weavers_tapestry.js

export const weaversTapestryPois = [
    { id: 'poi_dh_starlight_loom', x: 75.0, y: 65.0, type: 'ley_line', name: "The Starlight Loom", subRegion: "The Weaver's Tapestry", description: "A magnificent nebula where the Starlight Weavers spin cosmic dust and light into new stars. A place of intense creation and incomprehensible beauty.", factionId: 'starlight_weavers', intelReq: 60, political_influence: 7, economic_value: 6, military_strength: 6, population: 100 },
    { id: 'poi_dh_weavers_nursery', x: 78.0, y: 63.0, type: 'star_nursery', name: "Starlight Nursery", subRegion: "The Weaver's Tapestry", description: "A quiet, warm nebula where the Starlight Weavers tend to infant, proto-stars. A place of immense peace and life-giving energy.", factionId: 'starlight_weavers', intelReq: 55, political_influence: 5, economic_value: 4, military_strength: 5, population: 50 },
    { id: 'poi_dh_weavers_song', x: 77.2, y: 67.1, type: 'cosmic_anomaly', name: "The Weaver's Song", subRegion: "The Weaver's Tapestry", description: "A region where the background radiation of space forms complex, beautiful harmonies. Starlight Weavers gather here to meditate.", factionId: 'starlight_weavers', intelReq: 58 },
    { id: 'poi_dh_crystal_gardens', x: 80.4, y: 60.3, type: 'crystal_entity', name: "The Crystal Gardens", subRegion: "The Weaver's Tapestry", description: "Asteroids covered in delicate, light-catching crystals cultivated by the Weavers. The gardens chime softly as they drift.", factionId: 'starlight_weavers', intelReq: 63 },
    { id: 'poi_dh_solar_flare_conduit', x: 72.8, y: 72.8, type: 'ley_line', name: "Solar Flare Conduit", subRegion: "The Weaver's Tapestry", description: "A stable magnetic conduit that channels solar flares from a nearby star. The Weavers use this raw energy to power their creations.", factionId: 'starlight_weavers', intelReq: 69 },
    { id: 'poi_dh_tapestry_of_worlds', x: 82.1, y: 70.5, type: 'nebula', name: "Tapestry of Worlds", subRegion: "The Weaver's Tapestry", description: "A nebula whose swirling gases have been woven into intricate patterns depicting the birth and death of galaxies.", factionId: 'starlight_weavers', intelReq: 74 },
    { id: 'poi_dh_silent_oracle', x: 70.9, y: 62.6, type: 'shrine', name: "The Silent Oracle", subRegion: "The Weaver's Tapestry", description: "A perfectly spherical, featureless orb of light that answers questions not with words, but by implanting pure understanding into a visitor's mind.", factionId: 'starlight_weavers', intelReq: 85 },
    { id: 'poi_dh_constellation_forge', x: 73.0, y: 68.0, type: 'workshop', name: "Constellation Forge", subRegion: "The Weaver's Tapestry", description: "Where Starlight Weavers shape new constellations, arranging fledgling stars into patterns of myth and meaning.", factionId: 'starlight_weavers', intelReq: 67 },
    { id: 'poi_dh_pool_of_memories', x: 79.0, y: 58.0, type: 'landmark', name: "Pool of Liquid Light", subRegion: "The Weaver's Tapestry", description: "A stable pocket of liquid starlight that reflects not what is, but what could be. Weavers gaze into it for inspiration.", factionId: 'starlight_weavers', intelReq: 71 },
    { id: 'poi_dh_light_eater_trap', x: 85.0, y: 75.0, type: 'lair', name: "Light-Eater's Trap", subRegion: "The Weaver's Tapestry", description: "A region of false light created by the Weavers to lure and contain 'Light-Eaters', parasitic creatures from the void.", factionId: 'starlight_weavers', intelReq: 66 },
    { id: 'poi_dh_color_storm', x: 68.0, y: 75.0, type: 'nebula', name: "The Color Storm", subRegion: "The Weaver's Tapestry", description: "A chaotic but beautiful nebula where raw colors drift like clouds. The Weavers harvest them as pigments.", factionId: 'starlight_weavers', intelReq: 56 },
    { id: 'poi_dh_weavers_spindle', x: 76.0, y: 60.0, type: 'space_station', name: "The Great Spindle", subRegion: "The Weaver's Tapestry", description: "A central hub where the Weavers gather to share patterns and coordinate their cosmic works.", factionId: 'starlight_weavers', intelReq: 61 },
    { id: 'poi_dh_echoing_chimes', x: 71.0, y: 66.0, type: 'cosmic_anomaly', name: "The Echoing Chimes", subRegion: "The Weaver's Tapestry", description: "Crystalline formations that ring with a silent music, resonating with the birth of new stars miles away.", factionId: 'starlight_weavers', intelReq: 59 },
    { id: 'poi_dh_gravity_harp', x: 81.0, y: 73.0, type: 'landmark', name: "The Gravity Harp", subRegion: "The Weaver's Tapestry", description: "Strands of cosmic dust strung between two asteroids, which vibrate with the gravitational waves of the cosmos, creating a deep, powerful hum.", factionId: 'starlight_weavers', intelReq: 73 },
    { id: 'poi_dh_healing_nebula', x: 69.0, y: 58.0, type: 'nebula', name: "The Healing Nebula", subRegion: "The Weaver's Tapestry", description: "A nebula of warm, gentle light whose radiation can mend broken ships and heal wounded travelers.", factionId: 'starlight_weavers', intelReq: 52 },
    { id: 'poi_dh_fading_star', x: 88.0, y: 68.0, type: 'ruins', name: "The Fading Star", subRegion: "The Weaver's Tapestry", description: "A dying star that the Weavers are tending to, attempting to ease its passing and preserve its last light.", factionId: 'starlight_weavers', intelReq: 77 },
    { id: 'poi_dh_dream_catcher', x: 74.0, y: 78.0, type: 'landmark', name: "The Dream-Catcher", subRegion: "The Weaver's Tapestry", description: "A massive web of woven light designed to catch the stray dreams of sleeping mortals across all dimensions.", factionId: 'starlight_weavers', intelReq: 81 },
    { id: 'poi_dh_celestial_menagerie', x: 79.5, y: 66.5, type: 'lair', name: "Celestial Menagerie", subRegion: "The Weaver's Tapestry", description: "A sanctuary where the Weavers care for gentle beasts made of pure starlight.", factionId: 'starlight_weavers', intelReq: 64 },
    { id: 'poi_dh_prismatic_core', x: 84.2, y: 62.1, type: 'crystal_entity', name: "The Prismatic Core", subRegion: "The Weaver's Tapestry", description: "The heart of a crystallized planet, which refracts starlight into its component ideas and emotions.", factionId: 'starlight_weavers', intelReq: 79 },
    { id: 'poi_dh_song_of_creation', x: 72.3, y: 59.9, type: 'ley_line', name: "The Song of Creation", subRegion: "The Weaver's Tapestry", description: "A powerful ley line where the fundamental vibrations of the universe are audible as a faint, beautiful choir.", factionId: 'starlight_weavers', intelReq: 88 },
    { id: 'poi_dh_weavers_archive', x: 77.0, y: 71.0, type: 'library', name: "The Archive of Light", subRegion: "The Weaver's Tapestry", description: "An archive where the history of the cosmos is written not in books, but in patterns of captured light.", factionId: 'starlight_weavers', intelReq: 83 },
    { id: 'poi_dh_aurora_ribbons', x: 86.0, y: 58.0, type: 'nebula', name: "The Aurora Ribbons", subRegion: "The Weaver's Tapestry", description: "Vast, shimmering curtains of light that dance and flow through space, woven by the youngest of the Weavers.", factionId: 'starlight_weavers', intelReq: 54 }
];
