#!/usr/bin/env python3
"""One-time lore expansion for the Snowdin Bone-Line from the supplied family chart."""
import json
from pathlib import Path
p=Path(__file__).resolve().parents[1]/'data'/'characters.json'
data=json.loads(p.read_text(encoding='utf8'))
entries=[
('papyrus','Papyrus','The Great Brother of Snowdin','Snowdin Puzzle Guard','Sans’s taller brother and Snowdin’s irrepressible puzzle guard. He treats every visitor as a future friend, every hallway as a stage, and every pot of pasta as a diplomatic instrument. Papyrus is the family’s visible heart: loud, earnest, and impossible to mistake for anyone else. He answers Sans’s silences by setting another place at the table.'),
('grandpa_semi','Grandpa Semi','Keeper of the Half-Told Tale','Bone-Line Registry','A bent, soft-spoken elder who remembers family history in fragments and insists the missing pieces are sometimes the important part. Grandpa Semi keeps weathered registry cards, old recipes, and half-finished jokes in a cedar chest. He taught Sans to listen before speaking and Papyrus to save every invitation.'),
('lazybones','Lazybones','The Reclining Cousin','Snowdin Household','A couch-bound cousin whose apparent idleness conceals a startling awareness of every family movement. From a nest of blankets beside the heater, Lazybones coordinates emergency snacks, spare scarves, and quiet cover stories for relatives who need a day without questions. Their advice is usually delivered with eyes closed and unnerving accuracy.'),
('baby_bones','Baby Bones','The Smallest Rattle','Snowdin Household','The youngest bone in the house, a fearless little skeleton whose rattling steps can interrupt even the most solemn family meeting. Baby Bones treats every adult as a potential carrier and every puzzle piece as a toy. The household treats them as a promise to build something gentler than the world it inherited.'),
('dirty_brother','Dirty Brother','The Ash-Stained Brother','Snowdin Maintenance Crew','A soot-covered relation who repairs boiler shafts, chimneys, and old puzzle mechanisms. The green sparks around Dirty Brother are residue from ancient heating runes, not a curse—though he enjoys letting visitors think otherwise. His practical work keeps Snowdin warm when the magic in its infrastructure misbehaves.'),
('will','Will','Will of the Bone-Line','Family Quartermaster','A broad-shouldered cousin who keeps blankets, medicine, lantern oil, and emergency noodles organized with military focus. His household motto is feed first, worry later. Will mediates between Sans’s evasions and Papyrus’s declarations by asking what the family actually needs tonight.'),
('cursive','Cursive','Cursive of the Longhand','Snowdin Correspondence Circle','A dapper relation whose looping handwriting turns family gossip, official notices, and apologies into minor works of art. Cursive writes invitations for Baby Bones, repair requests for Dirty Brother, and peaceable replies to people rude to Papyrus. He takes every recipient seriously, even when Sans supplies only three words.'),
('times_new_roman','Times New Roman','The Family Typesetter','Snowdin Chronicle Office','A formal historian who believes every family story deserves dates, sources, and a respectable typeface. Times New Roman documents Bone-Line events in a carefully indexed chronicle and distrusts any story introduced with “you had to be there.” His severe presentation conceals a deep affection for embarrassing childhood anecdotes.'),
('prunsel','Prunsel','The Watching Eye','Bone-Line Registry Anomaly','A colossal eye-shaped relative or omen recorded in the margins of the family archive. Some entries call Prunsel a cousin transformed by unfinished science; others call it a guardian that learned the Bone-Line name. Sans treats the subject with unusual care, and Grandpa Semi refuses to classify it as a monster.'),
('real_star','A Real Star','The Adopted Stellar Cousin','Snowdin Skywatch','A brilliant, star-shaped family eccentric who claims the Bone-Line adopted him by cheering loudly enough at the night sky. Papyrus accepted the claim immediately. A Real Star performs with radiant arms, navigates by private constellations, and brings warmth to Snowdin’s longest nights despite being terrible for the curtains.'),
('wing_gaster','Wing Gaster','The Missing Wing','Underground Science Remnant','A shadowed elder whose experiments and absence still shape the family’s caution around impossible doors. Family records identify Wing Gaster as a brilliant scientist studying darkness and the architecture between worlds before vanishing from ordinary history. Sans knows more than he shares; Grandpa Semi keeps a sealed folder marked with a wing-shaped sigil.'),
('helvetica','Helvetica','The Clean-Lined Cousin','Snowdin Signmakers Guild','A sharply dressed cousin who believes clarity is mercy. Helvetica designs signs, patrol notices, and puzzle instructions readable through a snowstorm. His friendly typographic rivalry with Cursive produces Snowdin’s best public notices. Sans consults Helvetica whenever a message must be understood the first time.'),
('garbage_brother','Garbage Brother','The Smiley Trashbag','Snowdin Recycling Crew','A bag-wrapped brother who salvages bent puzzle parts, cracked toys, and almost-useful cookware. Baby Bones’s favorite rattle and Papyrus’s emergency spaghetti strainer both came from his workbench. He dislikes the nickname, but accepts it because it reminds Snowdin that discarded does not mean worthless.'),
('quantity','Quantity','The Many-Boned Cousin','Snowdin Household','A cooperative cluster of skeletons sharing one rolling chassis, several opinions, and an impeccable sense of timing. Quantity handles work requiring many hands: moving furniture, building puzzles, and carrying soup for crowds. Their family status began as a joke when Baby Bones called every skull uncle; the registry made it official.'),
('mystery_man','Mysteryman','The Unfiled Relative','Bone-Line Registry','A pale figure in black whose relationship to the family is documented only by sightings, sketches, and absence. Mysteryman appears near sealed rooms, broken save points, and old photographs. The household policy is simple: leave a seat, ask no cruel questions, and do not pretend an unfinished person is erased.'),
('sans_deltarune','Sans of the Dark World','The Other Sentry','Parallel Snowdin Contact','A parallel counterpart who runs a familiar storefront, tells familiar jokes, and carries a different map of impossible roads. The household treats him as a cousin from a neighboring story, not a replacement. His visits let Sans speak plainly about paths and choices that cannot be unwound.'),
('has_a_very_special_attack','Has A Very Special Attack','The Special-Attack Cousin','Snowdin Puzzle Guard','A purple-clad cousin who announces every entrance as though it were the last act of an opera. His “very special attack” is a family legend with so many versions that nobody agrees whether it is a spell, a dance, or an exceptionally difficult puzzle. Papyrus encourages him; Sans keeps a safe distance when the announcements begin.'),
('brother_killer','Brother Killer','The Estranged Protector','Snowdin Perimeter Watch','An intense, red-eyed relation carrying the consequences of a conflict nobody summarizes the same way twice. Brother Killer does not let his title become an excuse for cruelty: in Snowdin, he directs his anger toward threats at the perimeter and is slowly learning that repair requires more than standing guard.'),
('my_little_brother','My Little Brother','The Junior Runner','Snowdin Household','A blue-hooded younger relation who takes “little brother” as a job description rather than a comparison. He delivers messages, finds misplaced gloves, and follows older relatives on patrol until someone notices. He is not related to every person who calls him brother, which he considers proof the household is working correctly.'),
('ness','Ness','The Purple-Capped Guest','Snowdin Guest Circle','A human friend in a striped shirt whose calm courage earned him a place at the Bone-Line table. Ness brings a traveler’s perspective to family arguments and is one of the few people willing to tell Sans when a joke has gone too far. He remains a guest on paper and family in practice.'),
('my_brother','My Brother?','The Question-Mark Kin','Bone-Line Registry','A white-armored skeleton whose registry entry begins with a question mark because nobody can agree which branch he belongs to. My Brother? finds the uncertainty liberating: he offers help before credentials and treats every reunion as an opportunity to discover a new sibling. Papyrus admires his confidence; Times New Roman demands footnotes.'),
('pretty_soon','Pretty Soon','The Impatient Cousin','Snowdin Household','A small green-scarfed cousin who promises that every delayed plan will happen “pretty soon.” The phrase has become a family signal for hopeful patience rather than an actual deadline. Pretty Soon is excellent at making people wait without feeling abandoned, particularly when Baby Bones asks whether an absent relative is coming home.'),
('gee_lady','Gee Lady','The G-Shaped Aunt','Snowdin Household','A jubilant aunt whose letter-shaped silhouette appears at every birthday and victory dinner. Nobody agrees what the G originally stood for, but everyone agrees that Gee Lady can spot who is standing apart from the group. She brings frosting, ribbon, and an aggressively encouraging speech before anyone can claim they are fine.'),
('starman','Starman','The Quiet Visitor','Snowdin Guest Circle','A silent gray visitor connected to the family by old favors and a talent for arriving when the sky changes. Starman guided several relatives through a whiteout using a light that did not cast shadows. Will leaves a chair for him at dinner, and Sans watches the horizon rather than the guest whenever he appears.'),
('speen_kind_of_down_lately','Speen Kind of Down Lately','The Low-Spirited Cousin','Snowdin Household','A tired-looking relative in a violet coat whose name began as an honest status update and became a family promise to check in. Speen is not defined by sadness; he is a careful observer who notices when other people are performing happiness. Lazybones keeps tea ready for him, and Papyrus never lets a quiet seat stay empty for long.'),
('pet_rock','Pet Rock','The Smallest Dependent','Snowdin Household','A tiny stone with no verified movement, no visible face, and an unquestioned place in the family. Pet Rock became kin when Baby Bones named it and Papyrus prepared it a tiny dinner plate. It travels in a padded pocket, attends major meals, and has a place in Will’s emergency evacuation plan.'),
('dedan','Dedan','The Bone-Line Bouncer','Snowdin Perimeter Watch','A formidable striped guardian who treats every entrance as a question of responsibility. Dedan is intimidating by profession and unexpectedly patient by choice, especially with children and nervous visitors. He does not call himself family, but he has stood watch through too many household emergencies for anyone else to believe him.'),
]
ids=[]
for ident,name,title,affiliation,description in entries:
 ids.append(ident)
 if not any(c['id']==ident for c in data):
  data.append({'id':ident,'name':name,'title':title,'race':'Skeleton / Bone-Line Kin','status':'Active — recorded in the Snowdin household registry','affiliation':affiliation,'summary':description,'description':description,'keyEvents':['mount_ebott_survey_mission','snowdin_bone_line_registry'],'relatedArticles':['sans','papyrus','snowdin_town','sans_family']})
if not any(c['id']=='sans_family' for c in data):
 data.append({'id':'sans_family','name':'The Sans Family / Snowdin Bone-Line','title':'The Bone-Line Registry','race':'Extended Skeleton Household and Adopted Kin','status':'Active — centered in Snowdin Town','affiliation':'Snowdin Household / Monster Underground','summary':'An extended Snowdin household of siblings, cousins, adopted guests, and unresolved anomalies held together by care rather than strict genealogy.','description':'## A Family Larger Than a Bloodline\n\nThe Bone-Line Registry uses family more broadly than genealogy. Sans and Papyrus are its best-known brothers, but the household includes elders, working cousins, young dependents, adopted guests, and several unresolved figures connected to Underground science.\n\n## Snowdin’s Safety Net\n\nPapyrus welcomes strangers, Will keeps supplies, Dirty Brother maintains the heat, and the wider household keeps food and beds ready when Snowdin’s roads become unsafe. Their humor is not a refusal to take danger seriously; it is how they make danger survivable.\n\n## Sans’s Place\n\nSans is not the official leader. He is the quiet sentry who notices danger before it reaches the door and trusts the rest of the Bone-Line to make the home worth defending.','keyEvents':['mount_ebott_survey_mission','snowdin_bone_line_registry'],'relatedArticles':['sans','papyrus','snowdin_town',*ids]})
for c in data:
 if c['id']=='sans_family':
  c['relatedArticles']=list(dict.fromkeys(c.get('relatedArticles',[])+ids))
 if c['id']=='sans':
  c['summary']+=' He is a central member of the Snowdin Bone-Line, an extended household documented in the Sans Family registry.'
  c['description']+='\n\n## The Snowdin Bone-Line\n\nSans’s guarded humor makes more sense in the context of his enormous household. Papyrus is his brother, but the family also includes practical cousins, young dependents, adopted guests, and unresolved figures from the old Underground science branch. Sans rarely calls himself responsible for anyone; nevertheless, his sentry routes, spare meals, and careful silences protect the entire Bone-Line. For the complete registry, see **The Sans Family / Snowdin Bone-Line**.'
  c['relatedArticles']=list(dict.fromkeys(c.get('relatedArticles',[])+['sans_family',*ids]))
p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
print(f'Added/expanded {len(entries)} Bone-Line members plus overview.')
