#!/usr/bin/env python3
"""Propagate data/brosAttacks.json to every system that consumes it.

`data/brosAttacks.json` is the single source of truth for bros attacks. It
carries the lore (description, participants, source event), the school, and
the `drill` block that drives the Foundry mini-game. Everything else is
generated from it, so adding an attack means editing ONE file and running
this script.

Consumers
---------
  Foundry/bros_attacks/bros-definitions.js   generated; the VTT module reads
                                             BROS_DEFINITIONS from here
  data/brosAttacks.schools.json              generated; the storefront's Bros
                                             Training Yard reads the schools
                                             and the per-attack summaries

Usage from Reputation-Matrix2/:
  python tools/sync_bros_attacks.py            # write the generated files
  python tools/sync_bros_attacks.py --check    # verify they are up to date
                                               # (exit 1 if stale) — for CI

The --check mode is the important one: it makes "someone edited the module by
hand" and "someone added an attack but forgot to sync" both loud failures
instead of a technique that silently exists in one system and not the others.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data" / "brosAttacks.json"
CHARACTERS = ROOT / "data" / "characters.json"
MODULE_DEFS = ROOT / "Foundry" / "bros_attacks" / "bros-definitions.js"
SHOP_SCHOOLS = ROOT / "data" / "brosAttacks.schools.json"

# Some participant ids are article slugs rather than short character ids, and
# a few characters have no page at all. Title-casing the id is only correct for
# the simple cases, so resolve against characters.json first and keep a small
# table for the ids that legitimately have no entry.
_MANUAL_NAMES = {
    "dan_original": "Dan (Original)",
    "dan_feyward": "Dan (Feyward)",
    "mushroom_regency": "The Mushroom Regency",
    "koopa_trooper": "Koopa Trooper",
    "diddy_kong": "Diddy Kong",
    "chunky_kong_junimus_gorolini_bongo_jr": "Chunky Kong",
    "corporal_reyes": "Corporal 'Ghost' Reyes",
    "sergeant_stone": "Sergeant 'Brick' Stone",
    "specialist_miller": "Specialist 'Viper' Miller",
    "michael_afton": "Michael Afton",
    "remi": "Remi Akamatsu",
}

_NAME_CACHE: dict[str, str] = {}


def _character_names() -> dict[str, str]:
    if _NAME_CACHE:
        return _NAME_CACHE
    try:
        raw = json.loads(CHARACTERS.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        raw = []
    entries = raw.get("characters", []) if isinstance(raw, dict) else raw
    for entry in entries if isinstance(entries, list) else []:
        if isinstance(entry, dict) and entry.get("id"):
            name = str(entry.get("name") or entry.get("title") or "").strip()
            if name:
                _NAME_CACHE[str(entry["id"])] = name
    return _NAME_CACHE


def _display_name(participant_id: Any) -> str:
    pid = str(participant_id or "")
    if not pid:
        return ""
    name = _character_names().get(pid) or _MANUAL_NAMES.get(pid)
    if name:
        return name
    return pid.replace("_", " ").title()

BANNER = "/* GENERATED by tools/sync_bros_attacks.py — do not edit by hand.\n   Source of truth: data/brosAttacks.json. Run the script after changing it. */\n"

# A drill step needs all of these to be playable in the VTT.
STEP_FIELDS = ("actor", "title", "instruction", "gesture", "icon")
# Gestures the module knows how to score. Adding one here means adding a
# CHALLENGE entry and key binding in bros-attacks.js too.
KNOWN_GESTURES = {"up", "down", "right", "aim", "tap"}


def load_source() -> dict[str, Any]:
    return json.loads(SOURCE.read_text(encoding="utf-8"))


def validate(data: dict[str, Any]) -> list[str]:
    """Structural problems that would produce a broken drill or an orphan school."""
    problems: list[str] = []
    schools = data.get("schools") or {}
    if not schools:
        problems.append("no schools defined")

    seen_ids: set[str] = set()
    for attack in data.get("attacks", []):
        aid = attack.get("id", "<missing id>")
        if aid in seen_ids:
            problems.append(f"{aid}: duplicate id")
        seen_ids.add(aid)

        school = attack.get("school")
        if not school:
            problems.append(f"{aid}: no school")
        elif school not in schools:
            problems.append(f"{aid}: unknown school {school!r} (have: {', '.join(sorted(schools))})")

        drill = attack.get("drill")
        if not drill:
            # Lore-only attacks are legal — they just do not reach Foundry.
            continue
        for field in ("partnerA", "partnerB"):
            if not drill.get(field):
                problems.append(f"{aid}: drill missing {field}")
        steps = drill.get("steps") or []
        if not steps:
            problems.append(f"{aid}: drill has no steps")
        for i, step in enumerate(steps):
            for field in STEP_FIELDS:
                if not step.get(field):
                    problems.append(f"{aid}: drill step {i + 1} missing {field}")
            gesture = step.get("gesture")
            if gesture and gesture not in KNOWN_GESTURES:
                problems.append(
                    f"{aid}: drill step {i + 1} uses gesture {gesture!r}, which bros-attacks.js "
                    f"cannot score (known: {', '.join(sorted(KNOWN_GESTURES))})"
                )
            actor = step.get("actor")
            if actor and actor not in ("A", "B"):
                problems.append(f"{aid}: drill step {i + 1} actor must be 'A' or 'B', got {actor!r}")
    return problems


def render_module_defs(data: dict[str, Any]) -> str:
    """The Foundry module's BROS_DEFINITIONS, plus the school metadata it shows."""
    playable = [a for a in data.get("attacks", []) if a.get("drill")]
    defs = []
    for attack in playable:
        drill = attack["drill"]
        defs.append(
            {
                "id": attack["id"],
                "name": attack["name"],
                "school": attack.get("school", ""),
                "partnerA": drill["partnerA"],
                "partnerB": drill["partnerB"],
                # The drill prompt is the terse "what you are about to mash"
                # line; the full prose stays available for the sheet.
                "description": drill.get("promptDescription", attack.get("description", "")),
                "brief": attack.get("description", ""),
                "steps": [{f: s[f] for f in STEP_FIELDS} for s in drill["steps"]],
            }
        )
    schools = {
        key: {"name": s.get("name", key), "icon": s.get("icon", ""), "color": s.get("color", "#888"),
              "summary": s.get("summary", ""), "doctrine": s.get("doctrine", "")}
        for key, s in (data.get("schools") or {}).items()
    }
    return (
        BANNER
        + "\nconst BROS_SCHOOLS = "
        + json.dumps(schools, indent=2, ensure_ascii=False)
        + ";\n\nconst BROS_DEFINITIONS = "
        + json.dumps(defs, indent=2, ensure_ascii=False)
        + ";\n"
    )


def render_shop_schools(data: dict[str, Any]) -> str:
    """What the storefront's Bros Training Yard needs: schools + attack summaries.

    Kept deliberately small — the shop does not need drill choreography or
    Waluigi's notes, and shipping them would bloat every page load. It does
    need `description`: the yard used to render only `subtitle`, which is a
    single caption line, so every technique looked like an unwritten stub even
    though the prose was sitting in data/brosAttacks.json all along.
    """
    out = {
        "_README": "GENERATED by tools/sync_bros_attacks.py from data/brosAttacks.json. Do not edit.",
        "schools": data.get("schools", {}),
        "attacks": [
            {
                "id": a["id"],
                "name": a["name"],
                "school": a.get("school", ""),
                "subtitle": a.get("subtitle", ""),
                "description": a.get("description", ""),
                "risks": a.get("risks", ""),
                "difficulty": a.get("difficulty", "medium"),
                "participants": a.get("participants", []),
                # Display names resolved here so the shop does not have to
                # title-case raw ids — that turned the article slug
                # "remi_akamatsu_full_backstory" into the on-page name
                # "Remi Akamatsu Full Backstory".
                "participantNames": [_display_name(p) for p in a.get("participants", [])],
                "status": a.get("status", ""),
                "playable": bool(a.get("drill")),
            }
            for a in data.get("attacks", [])
        ],
    }
    return json.dumps(out, indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="verify generated files are current; do not write")
    args = parser.parse_args()

    data = load_source()
    problems = validate(data)
    if problems:
        print("brosAttacks.json has problems:", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 2

    targets = [(MODULE_DEFS, render_module_defs(data)), (SHOP_SCHOOLS, render_shop_schools(data))]

    if args.check:
        stale = [
            path.relative_to(ROOT)
            for path, content in targets
            if not path.exists() or path.read_text(encoding="utf-8") != content
        ]
        if stale:
            print("STALE — run: python tools/sync_bros_attacks.py", file=sys.stderr)
            for s in stale:
                print(f"  - {s}", file=sys.stderr)
            return 1
        print(f"up to date ({len(data.get('attacks', []))} attacks, {len(data.get('schools', {}))} schools)")
        return 0

    for path, content in targets:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")

    playable = sum(1 for a in data.get("attacks", []) if a.get("drill"))
    print(f"{len(data.get('attacks', []))} attacks ({playable} playable in Foundry), {len(data.get('schools', {}))} schools")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
