// map-data/abyssinia-pois.js

export const abyssiniaData = {
    pointsOfInterest: [
        {
            id: 'poi_ab_shadow_palace',
            x: 79.0,
            y: 85.0,
            type: 'capital_city',
            name: "Nyx, The Shadow Capital",
            description: "A city built into the walls of a massive ravine. Sunlight only reaches the bottom for one hour a day. Ruled by the Matriarch of Night.",
            factionId: 'abyssal_court',
            intelReq: 20,
            political_influence: 9,
            economic_value: 6,
            military_strength: 8,
            population: 3500
        },
        {
            id: 'poi_ab_claw_market',
            x: 76.0,
            y: 79.0,
            type: 'market',
            name: "The Velvet Bazaar",
            description: "A quiet market where silence is currency. Spies, assassins, and information brokers trade secrets here alongside exotic silks.",
            factionId: 'freelancer_underworld',
            intelReq: 30,
            political_influence: 7,
            economic_value: 9,
            military_strength: 4,
            population: 1000
        },
        {
            id: 'poi_ab_void_rift',
            x: 80.0,
            y: 73.0,
            type: 'dungeon_entrance',
            name: "The Gaping Maw",
            description: "A tear in reality where void energy seeps into the world. Strange, purple flora grows around it, and reality-bending monsters emerge at night.",
            factionId: 'void_entities',
            intelReq: 50,
            political_influence: 1,
            economic_value: 3,
            military_strength: 10,
            population: 0
        },
        {
            id: 'poi_ab_cat_statue',
            x: 74.0,
            y: 75.0,
            type: 'landmark',
            name: "The Great Sphynx of Sorrow",
            description: "A colossal statue of a weeping cat. It guards the entrance to the royal tombs. Riddles are required to pass.",
            factionId: 'abyssal_court',
            intelReq: 15,
            political_influence: 4,
            economic_value: 2,
            military_strength: 6,
            population: 50
        },
        {
            id: 'poi_ab_hunter_lodge',
            x: 75.0,
            y: 71.0,
            type: 'town',
            name: "Prowler's Rest",
            description: "A village of treehouses inhabited by elite hunters. They hunt the monstrosities that wander in from Ng'Amia.",
            factionId: 'abyssal_court',
            intelReq: 10,
            political_influence: 3,
            economic_value: 5,
            military_strength: 7,
            population: 400
        },
        {
            id: 'poi_ab_obsidian_mines',
            x: 79.5,
            y: 82.0,
            type: 'mine',
            name: "Blackglass Depths",
            description: "Mines that extract void-infused obsidian. The miners often go mad from the whispers in the stone.",
            factionId: 'abyssal_court',
            intelReq: 25,
            political_influence: 5,
            economic_value: 8,
            military_strength: 4,
            population: 300
        },
        {
            id: 'poi_ab_temple_darkness',
            x: 78.0,
            y: 86.0,
            type: 'temple',
            name: "Temple of the Eclipse",
            description: "A place of worship for those who revere the dark. The priests here can extinguish magical light sources.",
            factionId: 'void_cult',
            intelReq: 35,
            political_influence: 6,
            economic_value: 4,
            military_strength: 5,
            population: 150
        },
        {
            id: 'poi_ab_forgotten_library',
            x: 77.0,
            y: 80.0,
            type: 'library',
            name: "The Whispering Archives",
            description: "Books here are bound in shadow-leather. Read quickly, or the words will change before your eyes.",
            factionId: 'unaligned',
            intelReq: 40,
            political_influence: 5,
            economic_value: 5,
            military_strength: 2,
            population: 20,
            library_summary: "Forbidden texts regarding the nature of the Void and the history of the Cat-Lords.",
            libraryStockKey: 'abyssal_lore'
        },
        {
            id: 'poi_ab_jungle_ruins',
            x: 74.5,
            y: 73.0,
            type: 'ruins',
            name: "Ruins of Old Meow",
            description: "The overgrown remains of the First City. Now infested with displacer beasts.",
            factionId: 'monsters',
            intelReq: 20,
            political_influence: 1,
            economic_value: 3,
            military_strength: 8,
            population: 0
        },
        {
            id: 'poi_ab_border_gate',
            x: 81.0,
            y: 70.0,
            type: 'watchtower',
            name: "Gate of Fangs",
            description: "The fortified border between Abyssinia and Ng'Amia. Relations are tense.",
            factionId: 'abyssal_court',
            intelReq: 15,
            political_influence: 5,
            economic_value: 2,
            military_strength: 9,
            population: 200
        }
    ],
    fogOfWar: []
};