

export const hailbregPois = [
    { id: 'poi_eq_hail_keep', x: 15.0, y: 15.0, type: 'fortress', subRegion: 'Hailbreg', name: "Hailbreg Keep", description: "A stark, imposing fortress carved from black ice and stone, serving as the seat of the northern garrison.", factionId: 'equestrian_regime', intelReq: 20, political_influence: 6, economic_value: 3, military_strength: 9, population: 800 },
    { id: 'poi_eq_frost_forge', x: 12.0, y: 18.0, type: 'workshop', subRegion: 'Hailbreg', name: "The Frost Forge", description: "A massive foundry where weapons are tempered in magical cold fire, making them brittle but incredibly sharp.", factionId: 'equestrian_regime', intelReq: 15, political_influence: 2, economic_value: 5, military_strength: 6, population: 200 },
    { id: 'poi_eq_yeti_trading_post', x: 18.0, y: 22.0, type: 'trade_post', subRegion: 'Hailbreg', name: "Yeti Trading Post", description: "A neutral ground where ponies and yetis trade furs, gems, and stories. Tensions are often high.", factionId: 'unaligned', intelReq: 5, political_influence: 3, economic_value: 6, military_strength: 4, population: 150 },
    { id: 'poi_eq_hail_peak', x: 14.0, y: 10.0, type: 'mountain_pass', subRegion: 'Hailbreg', name: "Hail Peak", description: "The highest point in the region, constantly battered by hail storms. It is said a dragon sleeps near the summit.", factionId: 'unaligned', intelReq: 30, political_influence: 0, economic_value: 0, military_strength: 8, population: 0 },
    { id: 'poi_eq_frozen_lake_hail', x: 10.0, y: 25.0, type: 'landmark', subRegion: 'Hailbreg', name: "Mirror Lake", description: "A perfectly frozen lake that reflects the sky with unnatural clarity. Skaters claim to see glimpses of the future in the ice.", factionId: 'unaligned', intelReq: 10, political_influence: 1, economic_value: 2, military_strength: 0, population: 0 },
    { id: 'poi_eq_ice_crystal_cave', x: 8.0, y: 14.0, type: 'mine', subRegion: 'Hailbreg', name: "Crystal Vein Mine", description: "A mine extracting rare, blue-glowing crystals used for cold-weather enchantments.", factionId: 'pony_nobility', intelReq: 20, political_influence: 4, economic_value: 8, military_strength: 3, population: 300 },
    { id: 'poi_eq_exile_camp', x: 6.0, y: 20.0, type: 'village', subRegion: 'Hailbreg', name: "Camp of the Exiled", description: "A miserable collection of tents housing ponies exiled from Cenerlot. They are bitter and ripe for rebellion.", factionId: 'spark_of_rebellion', intelReq: 25, political_influence: 3, economic_value: 1, military_strength: 4, population: 100 },
    { id: 'poi_eq_snowy_owl_roost', x: 16.0, y: 12.0, type: 'lair', subRegion: 'Hailbreg', name: "Giant Owl Roost", description: "Nesting grounds for giant snowy owls. They are intelligent and sometimes carry messages for a price.", factionId: 'unaligned', intelReq: 15, political_influence: 1, economic_value: 3, military_strength: 5, population: 20 },
    { id: 'poi_eq_glacier_shrine', x: 20.0, y: 28.0, type: 'shrine', subRegion: 'Hailbreg', name: "Shrine of the Eternal Winter", description: "An ancient shrine dedicated to the Windigos, now forbidden by the Regime. Cultists still gather here in secret.", factionId: 'unaligned', intelReq: 50, political_influence: 2, economic_value: 0, military_strength: 3, population: 10 },
    { id: 'poi_eq_north_watch', x: 22.0, y: 30.0, type: 'watchtower', subRegion: 'Hailbreg', name: "The North Watch", description: "An isolated tower watching the northern wastes for signs of monster incursions.", factionId: 'equestrian_regime', intelReq: 15, political_influence: 2, economic_value: 1, military_strength: 5, population: 30 },
    { id: 'poi_eq_ice_sculpture_garden', x: 13.0, y: 20.0, type: 'landmark', subRegion: 'Hailbreg', name: "Garden of Frozen Forms", description: "A collection of incredibly lifelike ice sculptures. Rumor has it some are actually frozen creatures.", factionId: 'unaligned', intelReq: 10, political_influence: 1, economic_value: 4, military_strength: 0, population: 0 },
    { id: 'poi_eq_avalanche_ridge', x: 9.0, y: 16.0, type: 'mountain_pass', subRegion: 'Hailbreg', name: "Avalanche Ridge", description: "A treacherous path known for sudden, deadly avalanches. Only the most desperate or skilled travelers use it.", factionId: 'unaligned', intelReq: 20, political_influence: 0, economic_value: 0, military_strength: 2, population: 0 },
    { id: 'poi_eq_winter_wolf_den', x: 7.0, y: 28.0, type: 'lair', subRegion: 'Hailbreg', name: "Winter Wolf Den", description: "The lair of a pack of intelligent winter wolves. They hunt in coordinated groups and are a major threat to caravans.", factionId: 'unaligned', intelReq: 30, political_influence: 0, economic_value: 2, military_strength: 6, population: 0 },
    { id: 'poi_eq_herbalist_hut', x: 19.0, y: 25.0, type: 'village', subRegion: 'Hailbreg', name: "Nana's Hut", description: "The home of an old herbalist who makes potent remedies from arctic plants. She is neutral and heals anyone.", factionId: 'unaligned', intelReq: 10, political_influence: 2, economic_value: 3, military_strength: 0, population: 1 },
    { id: 'poi_eq_frozen_waterfall_cave', x: 11.0, y: 28.0, type: 'cave_entrance', subRegion: 'Hailbreg', name: "Cave Behind the Falls", description: "A hidden cave behind a frozen waterfall, used as a stash by smugglers.", factionId: 'freelancer_underworld', intelReq: 40, political_influence: 1, economic_value: 5, military_strength: 2, population: 5 },
    { id: 'poi_eq_aurora_view', x: 15.0, y: 8.0, type: 'observatory', subRegion: 'Hailbreg', name: "Aurora Viewing Platform", description: "A platform built for nobles to watch the northern lights in comfort. It sits empty most of the year.", factionId: 'pony_nobility', intelReq: 15, political_influence: 3, economic_value: 4, military_strength: 1, population: 0 },
    { id: 'poi_eq_ice_fishing_camp', x: 9.0, y: 26.0, type: 'village', subRegion: 'Hailbreg', name: "Ice Fisher's Camp", description: "A seasonal camp on the frozen lake where ponies fish for ice-fin tuna.", factionId: 'unaligned', intelReq: 5, political_influence: 1, economic_value: 3, military_strength: 1, population: 40 },
    { id: 'poi_eq_buried_ruins', x: 23.0, y: 25.0, type: 'ruins', subRegion: 'Hailbreg', name: "Buried Crystal Empire Ruins", description: "The tip of an ancient spire from the Crystal Empire, buried in snow. Relic hunters often dig here.", factionId: 'unaligned', intelReq: 45, political_influence: 1, economic_value: 6, military_strength: 0, population: 0 },
    { id: 'poi_eq_griffon_mercenary_camp', x: 21.0, y: 18.0, type: 'port', subRegion: 'Hailbreg', name: "Griffon Corsair Anchorage", description: "A hidden cove in the North Luna Ocean used by Griffon pirates and mercenaries as a base of operations. The water is freezing, but the loot is plentiful.", factionId: 'griffon_stone', intelReq: 25, political_influence: 2, economic_value: 4, military_strength: 7, population: 60 },
    { id: 'poi_eq_mystic_hot_spring', x: 17.0, y: 29.0, type: 'oasis', subRegion: 'Hailbreg', name: "Steam Vents", description: "Natural hot springs that provide warmth and healing. A neutral zone where fighting is forbidden.", factionId: 'unaligned', intelReq: 10, political_influence: 2, economic_value: 2, military_strength: 0, population: 0 },
    { id: 'poi_eq_smugglers_pass_hail', x: 5.5, y: 24.0, type: 'mountain_pass', subRegion: 'Hailbreg', name: "The White Pass", description: "A blindingly white, snow-covered pass used to smuggle goods out of the Regime's sight.", factionId: 'freelancer_underworld', intelReq: 35, political_influence: 1, economic_value: 5, military_strength: 2, population: 0 },
    { id: 'poi_eq_frozen_giant', x: 10.5, y: 13.0, type: 'landmark', subRegion: 'Hailbreg', name: "The Sleeping Giant", description: "A mountain formation that looks like a sleeping giant. Legends say it will wake up one day.", factionId: 'unaligned', intelReq: 5, political_influence: 0, economic_value: 1, military_strength: 8, population: 0 },
    { id: 'poi_eq_crystal_heart_fragment', x: 24.0, y: 27.0, type: 'ley_line', subRegion: 'Hailbreg', name: "Heart Shard Pulse", description: "A spot where a fragment of the Crystal Heart is buried, radiating waves of love and warmth that melt the snow.", factionId: 'unaligned', intelReq: 60, political_influence: 4, economic_value: 0, military_strength: 0, population: 0 },
    { id: 'poi_eq_regime_supply_depot', x: 14.0, y: 16.0, type: 'trade_post', subRegion: 'Hailbreg', name: "Supply Depot Alpha", description: "A heavily guarded depot storing food and fuel for the northern garrisons.", factionId: 'equestrian_regime', intelReq: 20, political_influence: 3, economic_value: 7, military_strength: 5, population: 50 },
    { id: 'poi_eq_yak_diplomatic_tent', x: 27.0, y: 29.0, type: 'landmark', subRegion: 'Hailbreg', name: "Yak Diplomatic Tent", description: "A large tent where Yak dignitaries meet with Pony officials. Arguments are frequent and loud.", factionId: 'unaligned', intelReq: 15, political_influence: 5, economic_value: 2, military_strength: 3, population: 10 },
    { id: 'poi_eq_ice_elemental_circle', x: 8.5, y: 11.0, type: 'ancient_circle', subRegion: 'Hailbreg', name: "Circle of Ice", description: "A circle of standing ice pillars where ice elementals congregate.", factionId: 'unaligned', intelReq: 30, political_influence: 0, economic_value: 0, military_strength: 6, population: 0 },
    { id: 'poi_eq_lost_library_hail', x: 19.5, y: 11.5, type: 'library', subRegion: 'Hailbreg', name: "The Frozen Athenaeum", description: "A library encased in ice, preserving pre-freeze history. Scholars risk frostbite to study here.", factionId: 'unaligned', intelReq: 55, political_influence: 2, economic_value: 5, military_strength: 1, population: 5, library_summary: "Preserved in perfect stasis by magical ice, this library contains the history of the northern tribes before the unification. The cold is intense, limiting study time.", libraryStockKey: 'equestria_archives' },
    { id: 'poi_eq_shadow_crevasse_hail', x: 23.5, y: 22.0, type: 'dungeon_entrance', subRegion: 'Hailbreg', name: "Abyssal Trench Entrance", description: "A deep, underwater fissure in the North Luna Ocean shelf. Rumored to lead to a sunken Changeling outpost or a path to the dark depths.", factionId: 'changeling_hive', intelReq: 65, political_influence: 1, economic_value: 1, military_strength: 4, population: 0 },
    { id: 'poi_eq_northern_lights_beacon', x: 12.5, y: 9.0, type: 'watchtower', subRegion: 'Hailbreg', name: "Aurora Beacon", description: "A magical beacon that pulses in rhythm with the aurora, guiding airships safely through the northern storms.", factionId: 'equestrian_regime', intelReq: 25, political_influence: 2, economic_value: 3, military_strength: 2, population: 5 },
    { id: 'poi_eq_snowball_field', x: 6.5, y: 23.0, type: 'battlefield', subRegion: 'Hailbreg', name: "The Snowball Fields", description: "A field where foals play, but also where local militias practice winter skirmish tactics.", factionId: 'unaligned', intelReq: 5, political_influence: 1, economic_value: 0, military_strength: 1, population: 0 }
];

export const hailbregData = {
    pointsOfInterest: hailbregPois,

};
