
export const jackalopeSlopesPois = [
    { id: 'poi_eq_js_jackalope_village', x: 25.0, y: 45.0, type: 'village', subRegion: 'Jackalope Slopes', name: "Jackalope Hollow", description: "A village of sentient, bipedal jackalopes. They are tricksters and traders who value wit over strength.", factionId: 'unaligned', intelReq: 10, political_influence: 3, economic_value: 5, military_strength: 3, population: 400 },
    { id: 'poi_eq_js_ski_resort', x: 28.0, y: 40.0, type: 'village', subRegion: 'Jackalope Slopes', name: "Pine Needle Ski Resort", description: "An abandoned ski resort, now occupied by a gang of Diamond Dogs.", factionId: 'freelancer_underworld', intelReq: 20, political_influence: 2, economic_value: 6, military_strength: 5, population: 100 },
    { id: 'poi_eq_js_avalanche_cannon', x: 30.0, y: 38.0, type: 'fortress', subRegion: 'Jackalope Slopes', name: "Avalanche Cannon Battery", description: "A Regime emplacement designed to trigger controlled avalanches to block passes, now used to extort travelers.", factionId: 'equestrian_regime', intelReq: 30, political_influence: 4, economic_value: 2, military_strength: 7, population: 50 },
    { id: 'poi_eq_js_hidden_mine', x: 22.0, y: 50.0, type: 'mine', subRegion: 'Jackalope Slopes', name: "Glittering Gem Mine", description: "A secret mine run by the jackalopes, extracting colorful gems used in illusion magic.", factionId: 'unaligned', intelReq: 40, political_influence: 2, economic_value: 8, military_strength: 2, population: 80 },
    { id: 'poi_eq_js_trickster_shrine', x: 26.0, y: 48.0, type: 'shrine', subRegion: 'Jackalope Slopes', name: "Shrine of the Laughing Hare", description: "A shrine dedicated to a trickster god. Offerings of carrots and pranks are left here.", factionId: 'unaligned', intelReq: 15, political_influence: 2, economic_value: 1, military_strength: 1, population: 0 },
    { id: 'poi_eq_js_snowboarding_ramp', x: 29.0, y: 42.0, type: 'landmark', subRegion: 'Jackalope Slopes', name: "The Big Air Ramp", description: "A massive natural ramp used for extreme sports. Locals hold competitions here.", factionId: 'unaligned', intelReq: 5, political_influence: 1, economic_value: 4, military_strength: 0, population: 0 },
    { id: 'poi_eq_js_regime_outpost', x: 31.0, y: 36.0, type: 'outpost', subRegion: 'Jackalope Slopes', name: "Slope Watch Outpost", description: "A small Regime outpost monitoring the pass. The guards are bored and easily bribed.", factionId: 'equestrian_regime', intelReq: 10, political_influence: 3, economic_value: 2, military_strength: 4, population: 20 },
    { id: 'poi_eq_js_frozen_lake', x: 16.0, y: 55.0, type: 'landmark', subRegion: 'Jackalope Slopes', name: "Glass Lake", description: "A frozen lake so clear you can see the bottom. It's slippery and dangerous.", factionId: 'unaligned', intelReq: 5, political_influence: 0, economic_value: 1, military_strength: 0, population: 0 },
    { id: 'poi_eq_js_yeti_cave', x: 14.0, y: 58.0, type: 'lair', subRegion: 'Jackalope Slopes', name: "Yeti's Lair", description: "Home to a reclusive yeti who just wants to be left alone to sculpt ice.", factionId: 'unaligned', intelReq: 25, political_influence: 1, economic_value: 3, military_strength: 6, population: 1 },
    { id: 'poi_eq_js_smugglers_path', x: 20.0, y: 42.0, type: 'mountain_pass', subRegion: 'Jackalope Slopes', name: "The Hare's Path", description: "A winding, hidden path known only to locals and smugglers.", factionId: 'freelancer_underworld', intelReq: 35, political_influence: 1, economic_value: 5, military_strength: 2, population: 0 },
    { id: 'poi_eq_js_hot_cocoa_hut', x: 27.0, y: 41.0, type: 'inn', subRegion: 'Jackalope Slopes', name: "Cocoa & Comfort", description: "A cozy inn serving the best hot chocolate in the mountains. Neutral ground.", factionId: 'unaligned', intelReq: 5, political_influence: 2, economic_value: 6, military_strength: 1, population: 10 },
    { id: 'poi_eq_js_ancient_observatory', x: 30.0, y: 35.5, type: 'observatory', subRegion: 'Jackalope Slopes', name: "Star-Gazer's Peak", description: "Ruins of an old observatory. The telescope still works if you know how to align the lenses.", factionId: 'unaligned', intelReq: 45, political_influence: 1, economic_value: 3, military_strength: 1, population: 0 },
    { id: 'poi_eq_js_pine_forest', x: 19.0, y: 48.0, type: 'forest', subRegion: 'Jackalope Slopes', name: "Whispering Pines", description: "A dense pine forest where the wind whispers secrets.", factionId: 'unaligned', intelReq: 15, political_influence: 0, economic_value: 2, military_strength: 2, population: 0 },
    { id: 'poi_eq_js_rebel_cache', x: 23.0, y: 52.0, type: 'bandit_camp', subRegion: 'Jackalope Slopes', name: "Buried Supply Cache", description: "Supplies hidden by the rebels for a future offensive. Marked by a blue ribbon on a tree.", factionId: 'spark_of_rebellion', intelReq: 50, political_influence: 2, economic_value: 4, military_strength: 3, population: 0 },
    { id: 'poi_eq_js_diamond_dog_dig', x: 12.0, y: 52.0, type: 'mine', subRegion: 'Jackalope Slopes', name: "Dog's Dig", description: "An illegal mining operation run by Diamond Dogs. They are aggressive and greedy.", factionId: 'unaligned', intelReq: 20, political_influence: 1, economic_value: 5, military_strength: 5, population: 60 },
    { id: 'poi_eq_js_frost_giant_remains', x: 10.0, y: 59.0, type: 'ruins', subRegion: 'Jackalope Slopes', name: "Fallen Giant", description: "The frozen corpse of a frost giant, now a landmark. Scavengers pick at its armor.", factionId: 'unaligned', intelReq: 10, political_influence: 0, economic_value: 3, military_strength: 1, population: 0 },
    { id: 'poi_eq_js_magic_spring', x: 21.0, y: 46.0, type: 'oasis', subRegion: 'Jackalope Slopes', name: "Spring of Vitality", description: "A hot spring that heals minor wounds and restores fatigue.", factionId: 'unaligned', intelReq: 30, political_influence: 1, economic_value: 4, military_strength: 0, population: 0 },
    { id: 'poi_eq_js_wind_tunnel', x: 18.0, y: 40.0, type: 'landmark', subRegion: 'Jackalope Slopes', name: "The Wind Tunnel", description: "A natural rock formation that channels wind at hurricane speeds. Pegasus ponies use it for training.", factionId: 'unaligned', intelReq: 15, political_influence: 0, economic_value: 0, military_strength: 3, population: 0 },
    { id: 'poi_eq_js_bridge_out', x: 24.0, y: 40.0, type: 'bridge', subRegion: 'Jackalope Slopes', name: "Broken Bridge", description: "A bridge destroyed by rebels to slow down Regime patrols.", factionId: 'spark_of_rebellion', intelReq: 5, political_influence: 1, economic_value: -1, military_strength: 0, population: 0 },
    { id: 'poi_eq_js_nomad_camp', x: 13.0, y: 55.0, type: 'village', subRegion: 'Jackalope Slopes', name: "Yak Nomad Camp", description: "A temporary camp of Yaks moving south for trade.", factionId: 'unaligned', intelReq: 10, political_influence: 2, economic_value: 3, military_strength: 6, population: 50 },
    { id: 'poi_eq_js_ice_sculpture', x: 25.5, y: 46.0, type: 'landmark', subRegion: 'Jackalope Slopes', name: "The Ice Jackalope", description: "A massive ice sculpture of a jackalope that never melts.", factionId: 'unaligned', intelReq: 5, political_influence: 1, economic_value: 2, military_strength: 0, population: 0 },
    { id: 'poi_eq_js_signal_fire', x: 31.5, y: 37.0, type: 'watchtower', subRegion: 'Jackalope Slopes', name: "Signal Peak", description: "A peak used to light signal fires to warn of danger.", factionId: 'unaligned', intelReq: 15, political_influence: 2, economic_value: 0, military_strength: 2, population: 5 },
    { id: 'poi_eq_js_hunting_lodge', x: 22.0, y: 38.0, type: 'village', subRegion: 'Jackalope Slopes', name: "Hunter's Lodge", description: "A lodge for ponies hunting in the mountains. A place to swap stories.", factionId: 'unaligned', intelReq: 10, political_influence: 1, economic_value: 3, military_strength: 3, population: 20 },
    { id: 'poi_eq_js_crystal_flower', x: 19.0, y: 50.0, type: 'farm', subRegion: 'Jackalope Slopes', name: "Crystal Flower Patch", description: "Rare flowers that look like ice crystals grow here. Alchemists prize them.", factionId: 'unaligned', intelReq: 35, political_influence: 1, economic_value: 6, military_strength: 0, population: 0 },
    { id: 'poi_eq_js_regime_patrol', x: 29.0, y: 39.0, type: 'barracks', subRegion: 'Jackalope Slopes', name: "Patrol Station", description: "A small barracks for Regime soldiers patrolling the slopes.", factionId: 'equestrian_regime', intelReq: 20, political_influence: 3, economic_value: 1, military_strength: 5, population: 15 },
    { id: 'poi_eq_js_hidden_cave', x: 15.0, y: 53.0, type: 'cave_entrance', subRegion: 'Jackalope Slopes', name: "Bear Cave", description: "Don't go in. There's a bear.", factionId: 'unaligned', intelReq: 5, political_influence: 0, economic_value: 0, military_strength: 7, population: 1 },
    { id: 'poi_eq_js_trading_post', x: 26.5, y: 43.0, type: 'trade_post', subRegion: 'Jackalope Slopes', name: "Slope-Side Traders", description: "A general store for travelers and locals.", factionId: 'unaligned', intelReq: 5, political_influence: 2, economic_value: 5, military_strength: 1, population: 10 },
    { id: 'poi_eq_js_avalanche_zone', x: 17.0, y: 45.0, type: 'landmark', subRegion: 'Jackalope Slopes', name: "Danger Zone", description: "Area prone to natural avalanches. Watch your step.", factionId: 'unaligned', intelReq: 10, political_influence: 0, economic_value: 0, military_strength: 1, population: 0 },
    { id: 'poi_eq_js_summit', x: 11.0, y: 60.0, type: 'landmark', subRegion: 'Jackalope Slopes', name: "Jackalope Summit", description: "The peak of the mountain range.", factionId: 'unaligned', intelReq: 20, political_influence: 0, economic_value: 0, military_strength: 0, population: 0 },
    { id: 'poi_eq_js_ski_lift', x: 28.5, y: 40.5, type: 'workshop', subRegion: 'Jackalope Slopes', name: "Broken Ski Lift", description: "A rusted ski lift. Mechanics might be able to fix it.", factionId: 'ratchet_raiders', intelReq: 25, political_influence: 1, economic_value: 2, military_strength: 1, population: 0 }
];

export const jackalopeSlopesData = {
    pointsOfInterest: jackalopeSlopesPois,

};
