
export const siresHollowPois = [
    { id: 'poi_eq_sh_manor', x: 40.0, y: 32.0, type: 'castle', subRegion: 'Sires Hollow', name: "The Patriarch's Manor", description: "An opulent retirement estate for high-ranking stallions of the nobility. It is a place of quiet luxury and backroom deals.", factionId: 'pony_nobility', intelReq: 20, political_influence: 9, economic_value: 7, military_strength: 4, population: 150 },
    { id: 'poi_eq_sh_gardens', x: 38.0, y: 31.0, type: 'landmark', subRegion: 'Sires Hollow', name: "Gardens of Reflection", description: "Meticulously maintained gardens where retired generals walk and discuss strategy.", factionId: 'pony_nobility', intelReq: 10, political_influence: 4, economic_value: 3, military_strength: 1, population: 20 },
    { id: 'poi_eq_sh_club', x: 42.0, y: 33.0, type: 'inn', subRegion: 'Sires Hollow', name: "The Gentlemen's Club", description: "An exclusive club for stallions. Entry is by invitation only. Gambling and drinking are common.", factionId: 'pony_nobility', intelReq: 30, political_influence: 7, economic_value: 8, military_strength: 2, population: 50 },
    { id: 'poi_eq_sh_archive', x: 41.0, y: 30.0, type: 'library', subRegion: 'Sires Hollow', name: "Archive of Lineage", description: "A library containing the genealogical records of every noble family in Equestria.", factionId: 'pony_nobility', intelReq: 40, political_influence: 8, economic_value: 5, military_strength: 1, population: 10 },
    { id: 'poi_eq_sh_gatehouse', x: 35.0, y: 35.0, type: 'watchtower', subRegion: 'Sires Hollow', name: "Hollow Gatehouse", description: "The only entrance to the valley, guarded by private security.", factionId: 'pony_nobility', intelReq: 15, political_influence: 3, economic_value: 2, military_strength: 6, population: 30 },
    { id: 'poi_eq_sh_winery', x: 45.0, y: 34.0, type: 'farm', subRegion: 'Sires Hollow', name: "Vintage Winery", description: "Produces the finest wines in Equestria, exclusively for the nobility.", factionId: 'pony_nobility', intelReq: 10, political_influence: 2, economic_value: 9, military_strength: 1, population: 100 },
    { id: 'poi_eq_sh_stables', x: 39.0, y: 34.0, type: 'workshop', subRegion: 'Sires Hollow', name: "Royal Stables", description: "Breeding grounds for the finest horses (non-sentient) and pegasi mounts.", factionId: 'equestrian_regime', intelReq: 20, political_influence: 3, economic_value: 6, military_strength: 3, population: 50 },
    { id: 'poi_eq_sh_secret_tunnel', x: 48.0, y: 32.0, type: 'cave_entrance', subRegion: 'Sires Hollow', name: "Servant's Passage", description: "A secret tunnel used by servants to enter and exit the valley without being seen by the nobles. Also used by spies.", factionId: 'spark_of_rebellion', intelReq: 50, political_influence: 4, economic_value: 1, military_strength: 2, population: 0 },
    { id: 'poi_eq_sh_lake', x: 43.0, y: 31.0, type: 'landmark', subRegion: 'Sires Hollow', name: "Serene Lake", description: "A private lake for boating and fishing. Rumored to have a monster in it, but the nobles deny it.", factionId: 'unaligned', intelReq: 5, political_influence: 1, economic_value: 3, military_strength: 0, population: 0 },
    { id: 'poi_eq_sh_guards_barracks', x: 36.0, y: 34.5, type: 'barracks', subRegion: 'Sires Hollow', name: "Private Security Barracks", description: "Housing for the mercenaries hired to protect the retired nobility.", factionId: 'iron_legion', intelReq: 25, political_influence: 2, economic_value: 4, military_strength: 8, population: 200 },
    { id: 'poi_eq_sh_ancient_statue', x: 44.0, y: 30.0, type: 'shrine', subRegion: 'Sires Hollow', name: "Statue of the First Sire", description: "A statue of the founder of the hollow. Cultists sometimes gather here.", factionId: 'unaligned', intelReq: 35, political_influence: 2, economic_value: 1, military_strength: 1, population: 0 },
    { id: 'poi_eq_sh_observatory', x: 47.0, y: 29.0, type: 'observatory', subRegion: 'Sires Hollow', name: "Private Observatory", description: "A small observatory owned by a retired astronomer.", factionId: 'unaligned', intelReq: 20, political_influence: 1, economic_value: 3, military_strength: 0, population: 2 },
    { id: 'poi_eq_sh_vault', x: 40.5, y: 32.5, type: 'dungeon_entrance', subRegion: 'Sires Hollow', name: "The Family Vault", description: "A secure vault where families store their most precious heirlooms and secrets.", factionId: 'pony_nobility', intelReq: 70, political_influence: 5, economic_value: 10, military_strength: 5, population: 0 },
    { id: 'poi_eq_sh_market', x: 37.0, y: 33.0, type: 'market', subRegion: 'Sires Hollow', name: "Luxury Market", description: "A market selling only the finest goods. No commoners allowed.", factionId: 'pony_nobility', intelReq: 10, political_influence: 4, economic_value: 8, military_strength: 2, population: 50 },
    { id: 'poi_eq_sh_hunting_lodge', x: 49.0, y: 31.0, type: 'village', subRegion: 'Sires Hollow', name: "Hunting Lodge", description: "A base for hunting trips into the surrounding mountains.", factionId: 'pony_nobility', intelReq: 15, political_influence: 2, economic_value: 4, military_strength: 3, population: 20 },
    { id: 'poi_eq_sh_cliff_path', x: 51.0, y: 30.5, type: 'mountain_pass', subRegion: 'Sires Hollow', name: "Cliffside Path", description: "A dangerous path along the cliffs, offering a view of the valley below.", factionId: 'unaligned', intelReq: 20, political_influence: 0, economic_value: 0, military_strength: 1, population: 0 },
    { id: 'poi_eq_sh_fountain', x: 40.0, y: 31.5, type: 'landmark', subRegion: 'Sires Hollow', name: "Fountain of Youth (Fake)", description: "A fountain claimed to restore youth. It's just tap water.", factionId: 'unaligned', intelReq: 5, political_influence: 1, economic_value: 5, military_strength: 0, population: 0 },
    { id: 'poi_eq_sh_servant_quarters', x: 36.5, y: 32.0, type: 'village', subRegion: 'Sires Hollow', name: "Servant Quarters", description: "Where the staff live. Cramped conditions, ripe for dissent.", factionId: 'spark_of_rebellion', intelReq: 15, political_influence: 3, economic_value: 2, military_strength: 2, population: 300 },
    { id: 'poi_eq_sh_tea_house', x: 39.5, y: 30.5, type: 'inn', subRegion: 'Sires Hollow', name: "Golden Leaf Tea House", description: "A quiet place for tea and gossip.", factionId: 'pony_nobility', intelReq: 10, political_influence: 5, economic_value: 4, military_strength: 1, population: 30 },
    { id: 'poi_eq_sh_clock_tower', x: 41.5, y: 31.0, type: 'watchtower', subRegion: 'Sires Hollow', name: "The Clock Tower", description: "Keeps perfect time for the valley. Also a good sniper spot.", factionId: 'equestrian_regime', intelReq: 25, political_influence: 2, economic_value: 2, military_strength: 4, population: 5 },
    { id: 'poi_eq_sh_hidden_dock', x: 43.5, y: 30.5, type: 'port', subRegion: 'Sires Hollow', name: "Private Dock", description: "A dock on the lake for private yachts.", factionId: 'pony_nobility', intelReq: 15, political_influence: 2, economic_value: 6, military_strength: 1, population: 5 },
    { id: 'poi_eq_sh_ruined_estate', x: 46.0, y: 33.0, type: 'ruins', subRegion: 'Sires Hollow', name: "Ruined Estate", description: "The burnt-out shell of an estate. Rumored to be the work of a dragon.", factionId: 'unaligned', intelReq: 30, political_influence: 1, economic_value: 2, military_strength: 1, population: 0 },
    { id: 'poi_eq_sh_art_gallery', x: 38.5, y: 31.5, type: 'landmark', subRegion: 'Sires Hollow', name: "Valley Art Gallery", description: "Displays portraits of famous stallions.", factionId: 'pony_nobility', intelReq: 10, political_influence: 3, economic_value: 5, military_strength: 1, population: 10 },
    { id: 'poi_eq_sh_apothecary', x: 37.5, y: 33.5, type: 'workshop', subRegion: 'Sires Hollow', name: "Noble Apothecary", description: "Sells cures for old age and gout.", factionId: 'unaligned', intelReq: 10, political_influence: 1, economic_value: 6, military_strength: 1, population: 5 },
    { id: 'poi_eq_sh_crystal_statue', x: 42.5, y: 32.0, type: 'ley_line', subRegion: 'Sires Hollow', name: "Singing Crystal", description: "A crystal that hums when magic is used nearby. Used as a warning system.", factionId: 'equestrian_regime', intelReq: 40, political_influence: 2, economic_value: 3, military_strength: 5, population: 0 },
    { id: 'poi_eq_sh_falconry', x: 48.5, y: 33.0, type: 'lair', subRegion: 'Sires Hollow', name: "Royal Falconry", description: "Where hunting birds are trained.", factionId: 'pony_nobility', intelReq: 20, political_influence: 2, economic_value: 3, military_strength: 3, population: 10 },
    { id: 'poi_eq_sh_music_hall', x: 40.0, y: 34.0, type: 'landmark', subRegion: 'Sires Hollow', name: "Hollow Music Hall", description: "For private concerts.", factionId: 'pony_nobility', intelReq: 10, political_influence: 3, economic_value: 4, military_strength: 0, population: 20 },
    { id: 'poi_eq_sh_gate_road', x: 30.0, y: 30.0, type: 'trade_post', subRegion: 'Sires Hollow', name: "The Approach", description: "The road leading up to the gate, lined with statues.", factionId: 'unaligned', intelReq: 5, political_influence: 1, economic_value: 2, military_strength: 2, population: 0 },
    { id: 'poi_eq_sh_storage', x: 35.5, y: 33.0, type: 'workshop', subRegion: 'Sires Hollow', name: "Supply Storage", description: "Warehouses for food and luxury goods.", factionId: 'unaligned', intelReq: 15, political_influence: 1, economic_value: 5, military_strength: 2, population: 20 },
    { id: 'poi_eq_sh_crypt', x: 50.0, y: 32.0, type: 'haunted_place', subRegion: 'Sires Hollow', name: "Old Family Crypt", description: "Where the ancestors are buried. Some say they still advise the living.", factionId: 'unaligned', intelReq: 45, political_influence: 3, economic_value: 2, military_strength: 4, population: 0 }
];

export const siresHollowData = {
    pointsOfInterest: siresHollowPois,

};
