
export const wanderingWoodsPois = [
    { id: 'poi_eq_ww_changeling_hive_entry', x: 12.0, y: 38.0, type: 'dungeon_entrance', subRegion: 'Wandering Woods', name: "The Hive Maw", description: "The hidden, organic entrance to the main Changeling Hive. It looks like a gaping mouth in the earth, surrounded by sticky green resin.", factionId: 'changeling_hive', intelReq: 60, political_influence: 8, economic_value: 4, military_strength: 9, population: 5000 },
    { id: 'poi_eq_ww_illusion_glade', x: 10.0, y: 35.0, type: 'forest', subRegion: 'Wandering Woods', name: "Glade of Mirrors", description: "A forest glade where the trees reflect your own image, confusing travelers and making navigation nearly impossible.", factionId: 'unaligned', intelReq: 30, political_influence: 1, economic_value: 2, military_strength: 3, population: 0 },
    { id: 'poi_eq_ww_chrysalis_throne', x: 13.0, y: 42.0, type: 'castle', subRegion: 'Wandering Woods', name: "Queen's Spire", description: "A twisted, chitinous spire rising from the center of the woods, serving as Queen Chrysalis's throne room and command center.", factionId: 'changeling_hive', intelReq: 75, political_influence: 10, economic_value: 6, military_strength: 10, population: 200 },
    { id: 'poi_eq_ww_cocoon_storage', x: 11.0, y: 40.0, type: 'prison', subRegion: 'Wandering Woods', name: "The Cocoon Chamber", description: "A horrifying cavern filled with green pods where captured ponies are kept in stasis to feed the hive.", factionId: 'changeling_hive', intelReq: 50, political_influence: 3, economic_value: 7, military_strength: 5, population: 100 },
    { id: 'poi_eq_ww_mimic_village', x: 15.0, y: 32.0, type: 'village', subRegion: 'Wandering Woods', name: "Hollow Hoof", description: "A village that appears normal but is entirely populated by Changelings practicing their disguises.", factionId: 'changeling_hive', intelReq: 45, political_influence: 5, economic_value: 3, military_strength: 4, population: 300 },
    { id: 'poi_eq_ww_rebel_scout_camp', x: 8.0, y: 30.0, type: 'outpost', subRegion: 'Wandering Woods', name: "Rebel Watchpost", description: "A hidden camp of rebel ponies monitoring Changeling activity. They are constantly on the move to avoid detection.", factionId: 'spark_of_rebellion', intelReq: 40, political_influence: 3, economic_value: 2, military_strength: 4, population: 20 },
    { id: 'poi_eq_ww_ancient_ruin', x: 18.0, y: 36.0, type: 'ruins', subRegion: 'Wandering Woods', name: "Ruins of the Old Kingdom", description: "Crumbling stone structures from a pony civilization that predates the hive. Rumored to hold anti-changeling magic.", factionId: 'unaligned', intelReq: 55, political_influence: 2, economic_value: 5, military_strength: 2, population: 0 },
    { id: 'poi_eq_ww_resin_pits', x: 14.0, y: 45.0, type: 'mine', subRegion: 'Wandering Woods', name: "Resin Pits", description: "Pits where Changelings harvest the sticky green substance used to build their hive structures.", factionId: 'changeling_hive', intelReq: 25, political_influence: 2, economic_value: 6, military_strength: 3, population: 150 },
    { id: 'poi_eq_ww_shifting_path', x: 9.0, y: 33.0, type: 'landmark', subRegion: 'Wandering Woods', name: "The Shifting Path", description: "A trail that changes direction when you aren't looking, leading unwary travelers deeper into the hive's territory.", factionId: 'unaligned', intelReq: 20, political_influence: 0, economic_value: 0, military_strength: 2, population: 0 },
    { id: 'poi_eq_ww_siren_pond', x: 16.0, y: 40.0, type: 'haunted_place', subRegion: 'Wandering Woods', name: "Siren's Pond", description: "A dark pond inhabited by kelpies that lure ponies into the water. Even Changelings avoid it.", factionId: 'unaligned', intelReq: 35, political_influence: 1, economic_value: 2, military_strength: 6, population: 0 },
    { id: 'poi_eq_ww_training_grounds', x: 12.5, y: 43.0, type: 'barracks', subRegion: 'Wandering Woods', name: "Infiltration Training Grounds", description: "An area where young Changelings are taught the art of mimicry and espionage.", factionId: 'changeling_hive', intelReq: 30, political_influence: 4, economic_value: 2, military_strength: 7, population: 400 },
    { id: 'poi_eq_ww_honey_tree', x: 7.0, y: 36.0, type: 'landmark', subRegion: 'Wandering Woods', name: "Giant Honey Tree", description: "A massive tree dripping with magical honey. It attracts giant bears and other dangerous wildlife.", factionId: 'unaligned', intelReq: 15, political_influence: 0, economic_value: 4, military_strength: 4, population: 0 },
    { id: 'poi_eq_ww_lost_peddler', x: 6.0, y: 32.0, type: 'shipwreck', subRegion: 'Wandering Woods', name: "Wrecked Wagon", description: "The remains of a peddler's wagon, looted and overturned. A warning to those who enter the woods.", factionId: 'unaligned', intelReq: 10, political_influence: 0, economic_value: 2, military_strength: 0, population: 0 },
    { id: 'poi_eq_ww_dark_crystal', x: 13.5, y: 39.0, type: 'ley_line', subRegion: 'Wandering Woods', name: "Dark Crystal Node", description: "A corrupted magical crystal that empowers Changeling magic and dampens pony magic.", factionId: 'changeling_hive', intelReq: 65, political_influence: 3, economic_value: 5, military_strength: 5, population: 0 },
    { id: 'poi_eq_ww_guard_post', x: 19.0, y: 34.0, type: 'watchtower', subRegion: 'Wandering Woods', name: "Hive Watchpost", description: "A tall, resin-coated tree used by Changeling sentries to watch the forest perimeter.", factionId: 'changeling_hive', intelReq: 20, political_influence: 2, economic_value: 1, military_strength: 4, population: 10 },
    { id: 'poi_eq_ww_love_extractor', x: 11.5, y: 41.0, type: 'workshop', subRegion: 'Wandering Woods', name: "Love Extraction Chamber", description: "A horrific machine designed to drain love from captured creatures to feed the Queen.", factionId: 'changeling_hive', intelReq: 80, political_influence: 5, economic_value: 8, military_strength: 3, population: 20 },
    { id: 'poi_eq_ww_thorny_thicket', x: 17.0, y: 42.0, type: 'forest', subRegion: 'Wandering Woods', name: "Thorny Thicket", description: "An impenetrable wall of magically reinforced thorns that protects the hive's flank.", factionId: 'unaligned', intelReq: 10, political_influence: 0, economic_value: 1, military_strength: 6, population: 0 },
    { id: 'poi_eq_ww_secret_tunnel', x: 9.5, y: 37.0, type: 'cave_entrance', subRegion: 'Wandering Woods', name: "Smuggler's Tunnel", description: "A narrow tunnel used by rebels and smugglers to bypass the main Changeling patrols.", factionId: 'freelancer_underworld', intelReq: 45, political_influence: 2, economic_value: 5, military_strength: 2, population: 5 },
    { id: 'poi_eq_ww_abandoned_cottage', x: 8.5, y: 31.0, type: 'ruins', subRegion: 'Wandering Woods', name: "Abandoned Witch's Cottage", description: "The home of a witch who was driven out by the Changelings. Potions and ingredients still rot on the shelves.", factionId: 'unaligned', intelReq: 25, political_influence: 1, economic_value: 4, military_strength: 1, population: 0 },
    { id: 'poi_eq_ww_changeling_market', x: 14.5, y: 39.5, type: 'market', subRegion: 'Wandering Woods', name: "The Hive Market", description: "A market where Changelings trade stolen goods and captured emotions.", factionId: 'changeling_hive', intelReq: 35, political_influence: 4, economic_value: 7, military_strength: 3, population: 200 },
    { id: 'poi_eq_ww_fog_bank', x: 10.5, y: 30.0, type: 'landmark', subRegion: 'Wandering Woods', name: "Perpetual Fog Bank", description: "A bank of thick fog that never lifts, hiding the western approach to the woods.", factionId: 'unaligned', intelReq: 15, political_influence: 0, economic_value: 0, military_strength: 2, population: 0 },
    { id: 'poi_eq_ww_timber_wolf_den', x: 16.5, y: 37.0, type: 'lair', subRegion: 'Wandering Woods', name: "Timber Wolf Den", description: "A den of wooden wolves. They are hostile to everything, including Changelings.", factionId: 'unaligned', intelReq: 20, political_influence: 0, economic_value: 3, military_strength: 5, population: 0 },
    { id: 'poi_eq_ww_reformed_enclave', x: 6.5, y: 35.0, type: 'village', subRegion: 'Wandering Woods', name: "Reformed Enclave", description: "A small, hidden community of Changelings who have rejected Chrysalis and seek to share love instead of stealing it.", factionId: 'spark_of_rebellion', intelReq: 60, political_influence: 5, economic_value: 2, military_strength: 3, population: 50 },
    { id: 'poi_eq_ww_poison_swamp', x: 12.0, y: 46.0, type: 'swamp', subRegion: 'Wandering Woods', name: "Poison Swamp", description: "A toxic swamp fed by runoff from the hive's industry. Dangerous to traverse.", factionId: 'unaligned', intelReq: 25, political_influence: 0, economic_value: 1, military_strength: 4, population: 0 },
    { id: 'poi_eq_ww_sentry_tree', x: 19.5, y: 35.0, type: 'watchtower', subRegion: 'Wandering Woods', name: "Outer Sentry Tree", description: "A lone, tall tree used by Changeling scouts to spot approaching armies.", factionId: 'changeling_hive', intelReq: 15, political_influence: 1, economic_value: 0, military_strength: 3, population: 5 },
    { id: 'poi_eq_ww_web_bridge', x: 11.0, y: 34.0, type: 'bridge', subRegion: 'Wandering Woods', name: "Spider Silk Bridge", description: "A bridge made of thick spider silk spanning a ravine. Sticky and precarious.", factionId: 'unaligned', intelReq: 20, political_influence: 0, economic_value: 1, military_strength: 1, population: 0 },
    { id: 'poi_eq_ww_dead_zone', x: 15.5, y: 43.0, type: 'landmark', subRegion: 'Wandering Woods', name: "The Dead Zone", description: "An area where nothing grows, drained of all life energy by the hive's hunger.", factionId: 'unaligned', intelReq: 30, political_influence: 1, economic_value: 0, military_strength: 0, population: 0 },
    { id: 'poi_eq_ww_illusion_barrier', x: 18.5, y: 33.0, type: 'landmark', subRegion: 'Wandering Woods', name: "Illusion Barrier", description: "A magical barrier that makes the forest look like a solid wall of rock to outsiders.", factionId: 'changeling_hive', intelReq: 50, political_influence: 3, economic_value: 0, military_strength: 6, population: 0 },
    { id: 'poi_eq_ww_captured_supply', x: 13.5, y: 41.5, type: 'trade_post', subRegion: 'Wandering Woods', name: "Captured Supply Depot", description: "A stockpile of goods stolen from pony caravans, waiting to be processed.", factionId: 'changeling_hive', intelReq: 35, political_influence: 2, economic_value: 7, military_strength: 4, population: 20 },
    { id: 'poi_eq_ww_chrysalis_statue', x: 13.0, y: 43.5, type: 'shrine', subRegion: 'Wandering Woods', name: "Statue of the Queen", description: "A massive statue of Queen Chrysalis, where Changelings offer tribute.", factionId: 'changeling_hive', intelReq: 10, political_influence: 6, economic_value: 1, military_strength: 2, population: 0 }
];

export const wanderingWoodsData = {
    pointsOfInterest: wanderingWoodsPois,

};
