// map-data/warhammer/the_empire.js
export const theEmpirePois = [
    {
        id: 'poi_wh_altdorf', x: 53.0, y: 16.0, type: 'capital_city', subRegion: 'the_empire',
        name: "Altdorf, The Imperial Capital",
        description: "The heart of The Empire and the seat of the Emperor. A sprawling city of grand cathedrals, magical colleges, and squalid slums, all situated at the confluence of the rivers Reik and Talabec.",
        factionId: 'the_empire', intelReq: 5, political_influence: 10, economic_value: 10, military_strength: 9, population: 100000,
        age_of_antiquity: 8, magical_resonance: 7, crime_rate: 6,
        library_summary: "The Great Library of Altdorf contains the most extensive collection of human history in the Old World, as well as treatises on Imperial law and military strategy. It also has a heavily guarded wing dedicated to the study of Chaos.",
        libraryStockKey: 'warhammer_empire',
    },
    {
        id: 'poi_wh_helmgart', x: 50.0, y: 22.0, type: 'fortress', subRegion: 'the_empire',
        name: "Fortress of Helmgart",
        description: "A massive fortress guarding the Axe Bite Pass against Greenskin incursions from the Grey Mountains. A grim and vital bastion of the Empire's defense.",
        factionId: 'the_empire', intelReq: 15, political_influence: 4, economic_value: 3, military_strength: 9, population: 3000,
        age_of_antiquity: 6, magical_resonance: 2, crime_rate: 3,
    },
    {
        id: 'poi_wh_ubersreik', x: 51.5, y: 20.0, type: 'town', subRegion: 'the_empire',
        name: "Ubersreik",
        description: "A bustling trade town at a key river crossing, known for its independent spirit and frequent troubles with mutants and beastmen from the nearby forests.",
        factionId: 'the_empire', intelReq: 10, political_influence: 5, economic_value: 7, military_strength: 5, population: 8000,
        age_of_antiquity: 5, magical_resonance: 3, crime_rate: 7,
    },
    {
        id: 'poi_wh_nuln', x: 55.0, y: 22.0, type: 'major_city', subRegion: 'the_empire',
        name: "Nuln, Jewel of the Empire",
        description: "The second largest city in the Empire, famed for its Imperial Gunnery School, its skilled engineers, and the massive cannons they produce for the Emperor's armies.",
        factionId: 'the_empire', intelReq: 10, political_influence: 8, economic_value: 9, military_strength: 8, population: 75000,
        age_of_antiquity: 7, magical_resonance: 5, crime_rate: 5,
    },
    {
        id: 'poi_wh_marienburg', x: 49.0, y: 10.0, type: 'port', subRegion: 'the_empire',
        name: "Marienburg, City of Trade",
        description: "The largest and wealthiest port in the Old World. Though technically independent from the Empire, its immense wealth and naval power make it a key player in Imperial politics. A den of intrigue, merchants, and spies.",
        factionId: 'unaligned', intelReq: 20, political_influence: 7, economic_value: 10, military_strength: 6, population: 90000,
        age_of_antiquity: 6, magical_resonance: 4, crime_rate: 9,
    },
    {
        id: 'poi_wh_middenheim', x: 56.5, y: 8.0, type: 'capital_city', subRegion: 'the_empire',
        name: "Middenheim, City of the White Wolf",
        description: "A great city-fortress built upon a sheer-sided pinnacle of rock, dedicated to the warrior-god Ulric. A bastion of martial tradition and the capital of the northern Empire.",
        factionId: 'the_empire', intelReq: 15, political_influence: 9, economic_value: 7, military_strength: 9, population: 60000,
        age_of_antiquity: 8, magical_resonance: 4, crime_rate: 4,
    },
    {
        id: 'poi_wh_averheim', x: 60.0, y: 20.0, type: 'major_city', subRegion: 'the_empire',
        name: "Averheim",
        description: "The capital of the province of Averland, a rich and prosperous city known for its stubborn soldiers and its fine cattle.",
        factionId: 'the_empire', intelReq: 10, political_influence: 6, economic_value: 8, military_strength: 6, population: 40000,
        age_of_antiquity: 6, magical_resonance: 2, crime_rate: 5,
    },
    {
        id: 'poi_wh_drakwald', x: 54.0, y: 12.0, type: 'forest', subRegion: 'the_empire',
        name: "The Drakwald Forest",
        description: "A vast, dark, and dangerous forest in the heart of the Empire. It is infested with Beastmen warherds, goblin tribes, and other foul creatures.",
        factionId: 'unaligned', intelReq: 25, political_influence: 1, economic_value: 2, military_strength: 7, population: 500,
        age_of_antiquity: 10, magical_resonance: 6, crime_rate: 9,
    },
    {
        id: 'poi_wh_black_fire_pass', x: 61.0, y: 15.0, type: 'mountain_pass', subRegion: 'the_empire',
        name: "Black Fire Pass",
        description: "The site of a legendary battle where Sigmar himself defeated a vast greenskin horde. It is a key strategic pass through the mountains, connecting the Empire to the lands beyond.",
        factionId: 'the_empire', intelReq: 20, political_influence: 3, economic_value: 3, military_strength: 8, population: 100,
        age_of_antiquity: 10, magical_resonance: 7, crime_rate: 6,
    },
    {
        id: 'poi_wh_reikland_moot', x: 52.0, y: 18.0, type: 'landmark', subRegion: 'the_empire',
        name: "The Reikland Moot Stone",
        description: "An ancient stone where the chieftains of the Reik tribes first swore fealty to Sigmar. It remains a potent symbol of Imperial unity.",
        factionId: 'the_empire', intelReq: 10, political_influence: 5, economic_value: 1, military_strength: 2, population: 0,
        age_of_antiquity: 10, magical_resonance: 5, crime_rate: 2,
    },
    {
        id: 'poi_wh_brass_keep', x: 58.0, y: 18.0, type: 'castle', subRegion: 'the_empire',
        name: "The Brass Keep",
        description: "The fortress-monastery of the Knights of the Blazing Sun, a religious order of knights dedicated to the goddess Myrmidia.",
        factionId: 'the_empire', intelReq: 30, political_influence: 4, economic_value: 2, military_strength: 7, population: 500,
        age_of_antiquity: 5, magical_resonance: 4, crime_rate: 2,
    },
    {
        id: 'poi_wh_smugglers_run', x: 50.0, y: 14.0, type: 'cave_entrance', subRegion: 'the_empire',
        name: "Smuggler's Run",
        description: "A network of sea caves and hidden tunnels used by smugglers to bypass the heavy taxes of Marienburg. A haven for the Freelancer Underworld.",
        factionId: 'freelancer_underworld', intelReq: 25, political_influence: 2, economic_value: 5, military_strength: 3, population: 100,
        age_of_antiquity: 3, magical_resonance: 1, crime_rate: 10,
    },
    {
        id: 'poi_wh_greywater', x: 59.5, y: 13.0, type: 'fortress', subRegion: 'the_empire',
        name: "Greywater Fastness",
        description: "A fortified town on the edge of the Grey Marshes, constantly vigilant against the undead horrors that rise from the cursed swamps.",
        factionId: 'the_empire', intelReq: 15, political_influence: 3, economic_value: 3, military_strength: 7, population: 2000,
        age_of_antiquity: 4, magical_resonance: 3, crime_rate: 4,
    },
    {
        id: 'poi_wh_temple_sigmar', x: 53.5, y: 15.5, type: 'temple', subRegion: 'the_empire',
        name: "Great Temple of Sigmar",
        description: "The heart of the Sigmarite faith in Altdorf. A massive, fortress-like cathedral where the Grand Theogonist preaches and warrior priests train for war.",
        factionId: 'the_empire', intelReq: 10, political_influence: 8, economic_value: 4, military_strength: 6, population: 1000,
        age_of_antiquity: 8, magical_resonance: 8, crime_rate: 2,
    },
    {
        id: 'poi_wh_carroburg', x: 52.0, y: 11.0, type: 'town', subRegion: 'the_empire',
        name: "Carroburg",
        description: "A fiercely proud city known for its elite Greatswords, who famously fought to the last man to defend an Emperor. Their loyalty is legendary.",
        factionId: 'the_empire', intelReq: 15, political_influence: 5, economic_value: 6, military_strength: 7, population: 12000,
        age_of_antiquity: 7, magical_resonance: 2, crime_rate: 3,
    }
];
