// map-data/kivotos/Kivotos.js
export const kivotosPois = [
    { id: 'poi_kv_gsu_tower', x: 35.8, y: 34.2, type: 'capital_city', name: "General Student Union Tower", subRegion: 'kivotos', description: "The administrative heart of Kivotos. A colossal tower where the GSU President's office resides, though it has been vacant for some time, leading to city-wide instability.", factionId: 'general_student_union', intelReq: 5, political_influence: 10, economic_value: 8, military_strength: 7, population: 5000 },
    { id: 'poi_kv_schale_building', x: 33.5, y: 38.1, type: 'outpost', name: "Schale Federal Investigation Club", subRegion: 'kivotos', description: "The headquarters of the club founded by the Sensei. An extrajudicial organization tasked with resolving the various incidents throughout Kivotos.", factionId: 'unaligned', intelReq: 0, political_influence: 8, economic_value: 5, military_strength: 6, population: 10 },
    { id: 'poi_kv_angel_24', x: 39.2, y: 30.5, type: 'market', name: "Angel 24 Convenience Store", subRegion: 'kivotos', description: "A 24/7 convenience store that seems to be at the center of frequent robberies and gang fights. A surprising hotspot for intel.", factionId: 'unaligned', intelReq: 5, political_influence: 2, economic_value: 4, military_strength: 1, population: 5 },
    { id: 'poi_kv_black_market', x: 44.1, y: 30.2, type: 'lair', name: "The Black Market", subRegion: 'kivotos', description: "A massive, illegal market operating out of a repurposed underground cargo depot. Everything from military-grade weapons to contraband tech can be bought here.", factionId: 'freelancer_underworld', intelReq: 30, political_influence: 4, economic_value: 9, military_strength: 5, population: 2000 },
    { id: 'poi_kv_downtown', x: 42.5, y: 35.8, type: 'major_city', name: "Central District Downtown", subRegion: 'kivotos', description: "The main commercial and residential hub of the central district. A place of skyscrapers, cafes, and constant, low-level gang violence.", factionId: 'unaligned', intelReq: 0, political_influence: 5, economic_value: 8, military_strength: 3, population: 50000 },
    { id: 'poi_kv_central_station', x: 38.8, y: 40.1, type: 'trade_post', name: "Kivotos Central Station", subRegion: 'kivotos', description: "The main transportation hub for the city's monorail system, connecting all the major academy districts.", factionId: 'general_student_union', intelReq: 5, political_influence: 6, economic_value: 7, military_strength: 5, population: 3000 },
    { id: 'poi_kv_sanae_park', x: 31.6, y: 30.1, type: 'landmark', name: "Sanae Park", subRegion: 'kivotos', description: "A large, beautiful park that serves as a neutral ground between the districts. A popular spot for students to relax, and for clandestine meetings.", factionId: 'unaligned', intelReq: 5, political_influence: 3, economic_value: 2, military_strength: 2, population: 500 },
    { id: 'poi_kv_abydos_district', x: 28.5, y: 34.0, type: 'ruins', name: "Abydos High School District (Abandoned)", subRegion: 'kivotos', description: "A vast, sand-swept school district that was abandoned due to a massive debt crisis. The few remaining students fight desperately to protect their school from foreclosure.", factionId: 'unaligned', intelReq: 15, political_influence: 2, economic_value: 1, military_strength: 3, population: 5 },
    { id: 'poi_kv_chronos_media', x: 47.2, y: 32.5, type: 'workshop', name: "Chronos Media Center", subRegion: 'kivotos', description: "The headquarters of Kivotos's largest news network. They report on the city's daily incidents with a mixture of professionalism and sensationalism.", factionId: 'unaligned', intelReq: 10, political_influence: 5, economic_value: 6, military_strength: 3, population: 800 },
    { id: 'poi_kv_redevelopment_zone', x: 26.5, y: 43.1, type: 'ruins', name: "Abandoned Redevelopment Zone", subRegion: 'kivotos', description: "A failed urban development project, now a ghost town of half-finished buildings. A perfect hideout for delinquents and criminal elements.", factionId: 'unaligned', intelReq: 10, political_influence: 1, economic_value: 2, military_strength: 2, population: 50 },
    { id: 'poi_kv_gematria_sanctum', x: 48.0, y: 28.5, type: 'ley_line', name: "Gematria Sanctum (Incomprehensible)", subRegion: 'kivotos', description: "A location that seems to defy normal geometry. It is the known meeting place of the enigmatic group Gematria, who study the mysteries of Kivotos.", factionId: 'cosmic_jesters', intelReq: 90, political_influence: 7, economic_value: 4, military_strength: 8, population: 4 },
    { id: 'poi_kv_financial_district', x: 45.0, y: 40.0, type: 'market', name: "Central Financial District", subRegion: 'kivotos', description: "A district of towering banks and corporate headquarters. The economic heart of Kivotos, and a frequent target for high-stakes heists.", factionId: 'unaligned', intelReq: 10, political_influence: 6, economic_value: 10, military_strength: 5, population: 15000 },
    { id: 'poi_kv_river_walk', x: 40.0, y: 43.0, type: 'landmark', name: "Kivotos River Walk", subRegion: 'kivotos', description: "A scenic promenade along the central river, lined with cafes and shops. It is often the site of territorial disputes between academy patrols.", factionId: 'unaligned', intelReq: 5, political_influence: 2, economic_value: 5, military_strength: 2, population: 1000 },
    { id: 'poi_kv_decagrammaton_nexus', x: 25.0, y: 30.0, type: 'ruins', name: "Decagrammaton Nexus Point", subRegion: 'kivotos', description: "An ancient, inactive ruin that occasionally pulses with strange energy. It is believed to be a communication node for a mysterious AI prophet.", factionId: 'cybernetic_collectives', intelReq: 75, political_influence: 3, economic_value: 3, military_strength: 4, population: 0 },
    { id: 'poi_kv_srt_campus', x: 24.0, y: 39.0, type: 'academy', name: "SRT Special Academy (Closed)", subRegion: 'kivotos', description: "The former campus of an elite academy that was shut down by the GSU. Its students now operate as a PMC, camping out in the local parks.", factionId: 'unaligned', intelReq: 25, political_influence: 2, economic_value: 1, military_strength: 6, population: 4 },
    { id: 'poi_kv_helmet_gang_turf', x: 47.0, y: 37.0, type: 'lair', name: "Helmet Gang Turf", subRegion: 'kivotos', description: "A downtown block notorious as the territory of the Helmet Gang, a large mob of armed delinquents wearing helmets. They are a constant nuisance for Schale.", factionId: 'freelancer_underworld', intelReq: 10, political_influence: 2, economic_value: 2, military_strength: 3, population: 300 },
    { id: 'poi_kv_valkyrie_academy_hq', x: 30.0, y: 43.0, type: 'barracks', name: "Valkyrie Police Academy HQ", subRegion: 'kivotos', description: "The central headquarters for the Valkyrie Police, Kivotos's official (but often ineffective) law enforcement. They struggle to maintain order amidst the chaos.", factionId: 'general_student_union', intelReq: 15, political_influence: 5, economic_value: 4, military_strength: 6, population: 4000 },
    { id: 'poi_kv_old_district', x: 33.0, y: 28.0, type: 'town', name: "The Old District", subRegion: 'kivotos', description: "A historic district with traditional architecture. It's a quiet area, but its winding alleys are perfect for ambushes and secret dealings.", factionId: 'unaligned', intelReq: 10, political_influence: 3, economic_value: 4, military_strength: 2, population: 2000 },
    { id: 'poi_kv_kaiser_corp_office', x: 45.0, y: 33.0, type: 'fortress', name: "Kaiser Corporation District Office", subRegion: 'kivotos', description: "The local office for the nefarious Kaiser Corporation. A heavily fortified building from which they run their predatory loan and PMC operations.", factionId: 'freelancer_underworld', intelReq: 35, political_influence: 5, economic_value: 7, military_strength: 7, population: 600 },
    { id: 'poi_kv_underground_ruins', x: 28.0, y: 27.0, type: 'dungeon_entrance', name: "Forgotten Underground Ruins", subRegion: 'kivotos', description: "The entrance to a vast, unexplored underground ruin beneath the city. Believed to hold ancient technology and dangerous automated defenses.", factionId: 'unaligned', intelReq: 50, political_influence: 2, economic_value: 6, military_strength: 5, population: 0 },
];
export const kivotosData = {
    pointsOfInterest: kivotosPois,
    fogOfWar: []
};
