
export const farasiPois = [
    { id: 'poi_eq_farasi_capital', x: 2.0, y: 45.0, type: 'capital_city', subRegion: 'Farasi', name: "Al-Zahra", description: "The glistening coastal capital of Farasi. Known for its grand bazaars, skilled navigators, and the unique magic woven into its silk sails.", factionId: 'farasi', intelReq: 10, political_influence: 8, economic_value: 9, military_strength: 6, population: 4000 },
    { id: 'poi_eq_farasi_docks', x: 5.0, y: 48.0, type: 'port', subRegion: 'Farasi', name: "Farasi Shipyards", description: "Shipyards that produce the fastest vessels on the Ocean. They trade heavily with Teyvat and Saddle Arabia.", factionId: 'farasi', intelReq: 20, political_influence: 5, economic_value: 10, military_strength: 5, population: 1500 },
    { id: 'poi_eq_farasi_lighthouse', x: 5.5, y: 55.0, type: 'watchtower', subRegion: 'Farasi', name: "The Star-Guide Beacon", description: "An ancient lighthouse powered by a captured star fragment. It guides ships through the treacherous mists bordering the Teyvat sea.", factionId: 'farasi', intelReq: 25, political_influence: 3, economic_value: 4, military_strength: 4, population: 20 },
    { id: 'poi_eq_farasi_spice_market', x: 1.5, y: 42.0, type: 'market', subRegion: 'Farasi', name: "Spice Bazaar", description: "A chaotic, aromatic market selling rare spices from across the ocean. A hub for gossip and espionage.", factionId: 'unaligned', intelReq: 15, political_influence: 4, economic_value: 8, military_strength: 2, population: 600 },
    { id: 'poi_eq_farasi_ruins', x: 0.5, y: 38.0, type: 'ruins', subRegion: 'Farasi', name: "Ruins of Old Farasi", description: "The crumbling remains of the previous capital, destroyed in a magical cataclysm centuries ago. Scavengers pick through the rubble.", factionId: 'unaligned', intelReq: 30, political_influence: 1, economic_value: 3, military_strength: 1, population: 0 },
    { id: 'poi_eq_farasi_oasis', x: 1.0, y: 30.0, type: 'oasis', subRegion: 'Farasi', name: "The Sapphire Oasis", description: "A stunning desert oasis with water as blue as a sapphire. It is a sacred site for the nomadic horse tribes of the region.", factionId: 'unaligned', intelReq: 20, political_influence: 2, economic_value: 5, military_strength: 3, population: 50 },
    { id: 'poi_eq_farasi_smugglers_cove', x: 4.0, y: 60.0, type: 'cave_entrance', subRegion: 'Farasi', name: "Smuggler's Arch", description: "A hidden sea cave used by pirates and smugglers to move goods between Equestria and the outer lands.", factionId: 'freelancer_underworld', intelReq: 40, political_influence: 2, economic_value: 7, military_strength: 4, population: 30 },
    { id: 'poi_eq_farasi_naval_fort', x: 3.0, y: 49.0, type: 'fortress', subRegion: 'Farasi', name: "Fort Wave-Breaker", description: "A coastal fortress defending the harbor. Its cannons are enchanted to fire bolts of lightning.", factionId: 'farasi', intelReq: 35, political_influence: 4, economic_value: 2, military_strength: 8, population: 300 },
    { id: 'poi_eq_farasi_border_post', x: 0.5, y: 25.0, type: 'outpost', subRegion: 'Farasi', name: "Northern Border Post", description: "A lonely outpost marking the border with the badlands. Soldiers here are wary of changeling infiltrators.", factionId: 'farasi', intelReq: 15, political_influence: 2, economic_value: 1, military_strength: 4, population: 20 },
    { id: 'poi_eq_farasi_observatory', x: 2.5, y: 40.0, type: 'observatory', subRegion: 'Farasi', name: "Dune-Watcher's Spire", description: "An observatory used to track celestial movements and predict sandstorms.", factionId: 'unaligned', intelReq: 45, political_influence: 1, economic_value: 2, military_strength: 1, population: 5 }
];

export const farasiData = {
    pointsOfInterest: farasiPois,

};
