export const halfingerGroveData = {
    pointsOfInterest: [
        {
            "id": "halfingerGrove_1",
            "x": 67.59,
            "y": 67.14,
            "type": "landmark",
            "subRegion": "Halfinger Grove",
            "name": "Dragon's Tooth Peak",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 24,
            "political_influence": 9,
            "economic_value": 9,
            "military_strength": 9,
            "population": 7760
        },
        {
            "id": "halfingerGrove_2",
            "x": 63.21,
            "y": 65.58,
            "type": "town",
            "subRegion": "Halfinger Grove",
            "name": "Wyvern's Roost",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 76,
            "political_influence": 0,
            "economic_value": 0,
            "military_strength": 0,
            "population": 1000
        },
        {
            "id": "halfingerGrove_3",
            "x": 69.29,
            "y": 66.58,
            "type": "other",
            "subRegion": "Halfinger Grove",
            "name": "Scaly Overlook",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 66,
            "political_influence": 6,
            "economic_value": 6,
            "military_strength": 6,
            "population": 6000
        },
        {
            "id": "halfingerGrove_4",
            "x": 66.5,
            "y": 69.53,
            "type": "other",
            "subRegion": "Halfinger Grove",
            "name": "Emberstone Quarry",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 10,
            "political_influence": 0,
            "economic_value": 0,
            "military_strength": 0,
            "population": 1000
        },
        {
            "id": "halfingerGrove_5",
            "x": 67.93,
            "y": 53.46,
            "type": "other",
            "subRegion": "Halfinger Grove",
            "name": "Serpent's Pass",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 88,
            "political_influence": 8,
            "economic_value": 8,
            "military_strength": 8,
            "population": 8000
        },
        {
            "id": "halfingerGrove_6",
            "x": 64.05,
            "y": 68.16,
            "type": "other",
            "subRegion": "Halfinger Grove",
            "name": "Drake's Landing",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 12,
            "political_influence": 2,
            "economic_value": 2,
            "military_strength": 2,
            "population": 2000
        },
        {
            "id": "halfingerGrove_7",
            "x": 66.01,
            "y": 69.82,
            "type": "landmark",
            "subRegion": "Halfinger Grove",
            "name": "Ancient Dragon's Lair",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 34,
            "political_influence": 4,
            "economic_value": 4,
            "military_strength": 4,
            "population": 4000
        },
        {
            "id": "halfingerGrove_8",
            "x": 63.13,
            "y": 60.02,
            "type": "town",
            "subRegion": "Halfinger Grove",
            "name": "Wyrm's Breath Caverns",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 56,
            "political_influence": 6,
            "economic_value": 6,
            "military_strength": 6,
            "population": 6000
        },
        {
            "id": "halfingerGrove_9",
            "x": 63.61,
            "y": 67.0,
            "type": "other",
            "subRegion": "Halfinger Grove",
            "name": "The Dragon's Maw",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 78,
            "political_influence": 8,
            "economic_value": 8,
            "military_strength": 8,
            "population": 8000
        },
        {
            "id": "halfingerGrove_10",
            "x": 63.05,
            "y": 67.19,
            "type": "other",
            "subRegion": "Halfinger Grove",
            "name": "Fire-Drake's Eyrie",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 99,
            "political_influence": 9,
            "economic_value": 9,
            "military_strength": 9,
            "population": 9000
        },
        {
            "id": "halfingerGrove_11",
            "x": 65.56,
            "y": 69.1,
            "type": "other",
            "subRegion": "Halfinger Grove",
            "name": "Glaurung's Goldhoard",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 2,
            "political_influence": 2,
            "economic_value": 2,
            "military_strength": 2,
            "population": 2000
        },
        {
            "id": "halfingerGrove_12",
            "x": 65.81,
            "y": 69.3,
            "type": "other",
            "subRegion": "Halfinger Grove",
            "name": "Smaug's Solitude",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 24,
            "political_influence": 4,
            "economic_value": 4,
            "military_strength": 4,
            "population": 4000
        },
        {
            "id": "halfingerGrove_13",
            "x": 65.91,
            "y": 69.95,
            "type": "landmark",
            "subRegion": "Halfinger Grove",
            "name": "Ancalagon's Fall",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 46,
            "political_influence": 6,
            "economic_value": 6,
            "military_strength": 6,
            "population": 6000
        },
        {
            "id": "halfingerGrove_14",
            "x": 65.9,
            "y": 69.73,
            "type": "town",
            "subRegion": "Halfinger Grove",
            "name": "Dragon's Spine Ridge",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 68,
            "political_influence": 8,
            "economic_value": 8,
            "military_strength": 8,
            "population": 8000
        },
        {
            "id": "halfingerGrove_15",
            "x": 63.47,
            "y": 67.88,
            "type": "other",
            "subRegion": "Halfinger Grove",
            "name": "Wyvern's Watch",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 90,
            "political_influence": 9,
            "economic_value": 9,
            "military_strength": 9,
            "population": 9000
        },
        {
            "id": "halfingerGrove_16",
            "x": 65.2,
            "y": 69.2,
            "type": "other",
            "subRegion": "Halfinger Grove",
            "name": "The Broodmother's Nest",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 12,
            "political_influence": 2,
            "economic_value": 2,
            "military_strength": 2,
            "population": 2000
        },
        {
            "id": "halfingerGrove_17",
            "x": 67.92,
            "y": 47.35,
            "type": "other",
            "subRegion": "Halfinger Grove",
            "name": "Scale-Scorched Plains",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 34,
            "political_influence": 4,
            "economic_value": 4,
            "military_strength": 4,
            "population": 4000
        },
        {
            "id": "halfingerGrove_18",
            "x": 67.5,
            "y": 53.18,
            "type": "other",
            "subRegion": "Halfinger Grove",
            "name": "Dragon's Claw Valley",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 56,
            "political_influence": 6,
            "economic_value": 6,
            "military_strength": 6,
            "population": 6000
        },
        {
            "id": "halfingerGrove_19",
            "x": 65.91,
            "y": 69.85,
            "type": "landmark",
            "subRegion": "Halfinger Grove",
            "name": "The Last Dragon's Grave",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 78,
            "political_influence": 8,
            "economic_value": 8,
            "military_strength": 8,
            "population": 8000
        },
        {
            "id": "halfingerGrove_20",
            "x": 64.6,
            "y": 68.7,
            "type": "town",
            "subRegion": "Halfinger Grove",
            "name": "Wyrmrest Temple",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 99,
            "political_influence": 9,
            "economic_value": 9,
            "military_strength": 9,
            "population": 9000
        },
        {
            "id": "halfingerGrove_21",
            "x": 65.2,
            "y": 69.21,
            "type": "other",
            "subRegion": "Halfinger Grove",
            "name": "Dragon's Breath Forge",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 21,
            "political_influence": 1,
            "economic_value": 1,
            "military_strength": 1,
            "population": 1000
        },
        {
            "id": "halfingerGrove_22",
            "x": 65.67,
            "y": 69.42,
            "type": "other",
            "subRegion": "Halfinger Grove",
            "name": "The Serpent's Stone",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 43,
            "political_influence": 3,
            "economic_value": 3,
            "military_strength": 3,
            "population": 3000
        },
        {
            "id": "halfingerGrove_23",
            "x": 68.67,
            "y": 46.87,
            "type": "other",
            "subRegion": "Halfinger Grove",
            "name": "Drake-Fire Delta",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 65,
            "political_influence": 5,
            "economic_value": 5,
            "military_strength": 5,
            "population": 5000
        },
        {
            "id": "halfingerGrove_24",
            "x": 65.83,
            "y": 69.67,
            "type": "other",
            "subRegion": "Halfinger Grove",
            "name": "Wyvern's Strike Peak",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 87,
            "political_influence": 7,
            "economic_value": 7,
            "military_strength": 7,
            "population": 7000
        },
        {
            "id": "halfingerGrove_25",
            "y": 51.67,
            "x": 67.33,
            "type": "landmark",
            "subRegion": "Halfinger Grove",
            "name": "Dragon's Eye Lake",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 9,
            "political_influence": 9,
            "economic_value": 9,
            "military_strength": 9,
            "population": 9000
        },
        {
            "id": "halfingerGrove_26",
            "x": 65.0,
            "y": 69.0,
            "type": "town",
            "subRegion": "Halfinger Grove",
            "name": "The Hatchling Crags",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 31,
            "political_influence": 1,
            "economic_value": 1,
            "military_strength": 1,
            "population": 1000
        },
        {
            "id": "halfingerGrove_27",
            "x": 64.0,
            "y": 68.0,
            "type": "other",
            "subRegion": "Halfinger Grove",
            "name": "Old Dragon's Scar",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 53,
            "political_influence": 3,
            "economic_value": 3,
            "military_strength": 3,
            "population": 3000
        },
        {
            "id": "halfingerGrove_28",
            "x": 63.0,
            "y": 67.0,
            "type": "other",
            "subRegion": "Halfinger Grove",
            "name": "Wyrm-Skull Camp",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 75,
            "political_influence": 5,
            "economic_value": 5,
            "military_strength": 5,
            "population": 5000
        },
        {
            "id": "halfingerGrove_29",
            "x": 66.0,
            "y": 50.0,
            "type": "other",
            "subRegion": "Halfinger Grove",
            "name": "Dragon's Tail River",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 97,
            "political_influence": 7,
            "economic_value": 7,
            "military_strength": 7,
            "population": 7000
        },
        {
            "id": "halfingerGrove_30",
            "x": 65.5,
            "y": 69.5,
            "type": "other",
            "subRegion": "Halfinger Grove",
            "name": "The Obsidian Perch",
            "description": "A notable location within the Halfinger Grove, home of dragons and wyverns.",
            "factionId": "unaligned",
            "intelReq": 19,
            "political_influence": 9,
            "economic_value": 9,
            "military_strength": 9,
            "population": 9000
        }
    ]
};