// map-data/ngamia-pois.js

export const ngAmiaData = {
    pointsOfInterest: [
        {
            id: 'poi_ng_sun_city',
            x: 86.0,
            y: 75.0,
            type: 'capital_city',
            name: "Al-Humpra, City of Gold",
            description: "A glittering city in the middle of the dunes. The domes are plated in gold. It is the center of the spice trade and ruled by the Sultan of Sands.",
            factionId: 'desert_sultanate',
            intelReq: 10,
            political_influence: 10,
            economic_value: 10,
            military_strength: 8,
            population: 5000
        },
        {
            id: 'poi_ng_pyramid',
            x: 88.0,
            y: 82.0,
            type: 'dungeon_entrance',
            name: "Pyramid of the Scorched King",
            description: "A massive structure of sandstone. Traps, mummies, and curses await those who seek the Pharoah's treasure.",
            factionId: 'undead',
            intelReq: 30,
            political_influence: 2,
            economic_value: 8,
            military_strength: 9,
            population: 0
        },
        {
            id: 'poi_ng_camel_market',
            x: 84.0,
            y: 70.0,
            type: 'market',
            name: "Dromedary Depots",
            description: "The largest livestock market in the region. You can buy a racing camel or a war-camel here. Smells terrible.",
            factionId: 'desert_traders',
            intelReq: 5,
            political_influence: 4,
            economic_value: 6,
            military_strength: 3,
            population: 800
        },
        {
            id: 'poi_ng_oasis_glass',
            x: 90.0,
            y: 68.0,
            type: 'oasis',
            name: "Oasis of Glass",
            description: "A supernatural oasis where the water is crystal clear and the sand has been fused into beautiful glass sculptures by lightning.",
            factionId: 'unaligned',
            intelReq: 15,
            political_influence: 2,
            economic_value: 5,
            military_strength: 2,
            population: 100
        },
        {
            id: 'poi_ng_salt_flats',
            x: 92.0,
            y: 78.0,
            type: 'resource',
            name: "The Blinding Flats",
            description: "Miles of flat, white salt. Sun glare is blinding. Salt miners work here under brutal conditions.",
            factionId: 'desert_sultanate',
            intelReq: 10,
            political_influence: 5,
            economic_value: 7,
            military_strength: 4,
            population: 400
        },
        {
            id: 'poi_ng_nomad_cliffs',
            x: 82.0,
            y: 85.0,
            type: 'town',
            name: "Cliff-Dweller's Rise",
            description: "Homes carved directly into the canyon walls to escape the heat. Inhabited by strict traditionalists.",
            factionId: 'desert_traders',
            intelReq: 20,
            political_influence: 3,
            economic_value: 3,
            military_strength: 6,
            population: 600
        },
        {
            id: 'poi_ng_ancient_aqueduct',
            x: 85.0,
            y: 72.0,
            type: 'ruins',
            name: "The Broken Spine",
            description: "Ruins of a massive aqueduct that once brought water to the deep desert. Now a hideout for bandits.",
            factionId: 'bandits',
            intelReq: 15,
            political_influence: 1,
            economic_value: 2,
            military_strength: 5,
            population: 150
        },
        {
            id: 'poi_ng_scropion_den',
            x: 91.0,
            y: 85.0,
            type: 'dungeon_entrance',
            name: "Venom Hollow",
            description: "A subterranean network of tunnels inhabited by Giant Scorpions and the cultists who milk their venom.",
            factionId: 'monsters',
            intelReq: 35,
            political_influence: 0,
            economic_value: 4,
            military_strength: 7,
            population: 50
        },
        {
            id: 'poi_ng_mirage_tower',
            x: 89.0,
            y: 71.0,
            type: 'tower',
            name: "Tower of Mirages",
            description: "A wizard's tower that constantly changes location and appearance. Only visible at high noon.",
            factionId: 'mages_guild',
            intelReq: 50,
            political_influence: 4,
            economic_value: 6,
            military_strength: 8,
            population: 10
        },
        {
            id: 'poi_ng_stargate',
            x: 93.0,
            y: 74.0,
            type: 'landmark',
            name: "The Star Gate",
            description: "A mysterious circular stone ring half-buried in the sand. It hums with energy.",
            factionId: 'unaligned',
            intelReq: 60,
            political_influence: 2,
            economic_value: 10,
            military_strength: 0,
            population: 0
        }
    ],
    fogOfWar: []
};