// map-data/shire-lanka-pois.js

export const riverlandsData = {
    pointsOfInterest: [
        {
            id: 'poi_sl_capital',
            x: 73.0,
            y: 80.0,
            type: 'capital_city',
            name: "Colombo Hobbiton",
            description: "A bustling port city where round doors are built into tropical hillsides. The scent of cinnamon and tea fills the air.",
            factionId: 'halfling_federation',
            intelReq: 10,
            political_influence: 8,
            economic_value: 9,
            military_strength: 4,
            population: 2500
        },
        {
            id: 'poi_sl_tea_plantations',
            x: 71.0,
            y: 76.0,
            type: 'resource',
            name: "Emerald Tea Terraces",
            description: "Endless stepped hills of green tea bushes. The finest tea in the world is grown here by meticulous halfling farmers.",
            factionId: 'halfling_federation',
            intelReq: 5,
            political_influence: 6,
            economic_value: 8,
            military_strength: 2,
            population: 800
        },
        {
            id: 'poi_sl_elephant_sanctuary',
            x: 74.5,
            y: 82.0,
            type: 'landmark',
            name: "Pachyderm Palace",
            description: "A sanctuary for the island's small, intelligent elephants. Halflings ride them for work and ceremony.",
            factionId: 'druid_circle',
            intelReq: 10,
            political_influence: 3,
            economic_value: 4,
            military_strength: 6,
            population: 200
        },
        {
            id: 'poi_sl_temple_tooth',
            x: 72.5,
            y: 78.0,
            type: 'temple',
            name: "Temple of the Golden Spork",
            description: "A sacred temple housing a relic of the Great Feast. It is a place of pilgrimage for food lovers everywhere.",
            factionId: 'halfling_federation',
            intelReq: 15,
            political_influence: 7,
            economic_value: 5,
            military_strength: 3,
            population: 300
        },
        {
            id: 'poi_sl_pirate_cove',
            x: 70.5,
            y: 81.0,
            type: 'dungeon_entrance',
            name: "Smuggler's Inlet",
            description: "A hidden cove used by pirates to smuggle spices. The caves are booby-trapped.",
            factionId: 'freelancer_underworld',
            intelReq: 25,
            political_influence: 2,
            economic_value: 6,
            military_strength: 5,
            population: 150
        },
        {
            id: 'poi_sl_volcano',
            x: 75.0,
            y: 75.0,
            type: 'dungeon_entrance',
            name: "Mount Spicy",
            description: "An active volcano. Fire newts live near the rim. The lava is used to forge specialized cooking tools.",
            factionId: 'monsters',
            intelReq: 30,
            political_influence: 1,
            economic_value: 3,
            military_strength: 8,
            population: 50
        },
        {
            id: 'poi_sl_fishing_village',
            x: 72.0,
            y: 83.0,
            type: 'town',
            name: "Stilt-Walker Village",
            description: "A fishing village where the huts stand on tall stilts above the tide. Famous for its spicy crab curry.",
            factionId: 'halfling_federation',
            intelReq: 5,
            political_influence: 2,
            economic_value: 4,
            military_strength: 2,
            population: 400
        },
        {
            id: 'poi_sl_jungle_ruins',
            x: 74.0,
            y: 79.0,
            type: 'ruins',
            name: "Ruins of Sigiriya",
            description: "A massive rock fortress from a previous civilization. Monkeys rule the ruins now, guarding ancient treasures.",
            factionId: 'unaligned',
            intelReq: 20,
            political_influence: 2,
            economic_value: 4,
            military_strength: 4,
            population: 0
        },
        {
            id: 'poi_sl_lotus_pond',
            x: 71.5,
            y: 77.0,
            type: 'landmark',
            name: "Lotus Meditation Gardens",
            description: "A peaceful garden of giant lotus flowers. Monks train here in the art of the 'Silent Step'.",
            factionId: 'monks_order',
            intelReq: 15,
            political_influence: 4,
            economic_value: 2,
            military_strength: 7,
            population: 100
        },
        {
            id: 'poi_sl_gem_market',
            x: 73.5,
            y: 81.5,
            type: 'market',
            name: "Sapphire Street",
            description: "A street lined with jewelers. The island is famous for its blue sapphires.",
            factionId: 'merchant_guild',
            intelReq: 10,
            political_influence: 5,
            economic_value: 9,
            military_strength: 3,
            population: 200
        }
    ],
    fogOfWar: []
};