// map-data/trotting-terrians-pois.js

export const trottingTerriansData = {
    pointsOfInterest: [
        {
            id: 'poi_tt_centaur_citadel',
            x: 78.0,
            y: 58.0,
            type: 'capital_city',
            name: "Hoofbeat Stronghold",
            description: "A massive wooden fortress surrounded by palisades. It is the central gathering point for the Great Herds and the seat of the Khan.",
            factionId: 'centaur_khanate',
            intelReq: 10,
            political_influence: 9,
            economic_value: 7,
            military_strength: 9,
            population: 4000
        },
        {
            id: 'poi_tt_grand_racetrack',
            x: 82.0,
            y: 48.0,
            type: 'landmark',
            name: "The Endless Track",
            description: "A 10-mile loop of packed dirt. Here, the fastest runners in the world compete for glory. Gambling is technically illegal but rampant.",
            factionId: 'unaligned',
            intelReq: 5,
            political_influence: 4,
            economic_value: 10,
            military_strength: 2,
            population: 1500
        },
        {
            id: 'poi_tt_nomad_camp_north',
            x: 74.0,
            y: 68.0,
            type: 'town',
            name: "Northwind Camp",
            description: "A temporary settlement of yurts and tents. The inhabitants are expert archers and move with the seasons.",
            factionId: 'centaur_khanate',
            intelReq: 15,
            political_influence: 3,
            economic_value: 4,
            military_strength: 7,
            population: 600
        },
        {
            id: 'poi_tt_steel_shod_smithy',
            x: 75.0,
            y: 45.0,
            type: 'workshop',
            name: "Steel-Shod Smithy",
            description: "Renowned for creating magical horseshoes and barding. The clang of metal on anvils rings across the plains day and night.",
            factionId: 'iron_legion',
            intelReq: 20,
            political_influence: 4,
            economic_value: 8,
            military_strength: 5,
            population: 300
        },
        {
            id: 'poi_tt_ancestral_mounds',
            x: 85.0,
            y: 50.0,
            type: 'graveyard',
            name: "The Silent Mounds",
            description: "Burial grounds of the ancient horse-lords. Disturbing the grass here brings down the wrath of spectral cavalry.",
            factionId: 'undead',
            intelReq: 35,
            political_influence: 2,
            economic_value: 1,
            military_strength: 8,
            population: 0
        },
        {
            id: 'poi_tt_watering_hole',
            x: 80.0,
            y: 41.0,
            type: 'oasis',
            name: "The Truce Waters",
            description: "A massive lake where no violence is permitted. Predators and prey drink side by side under the watchful eyes of druids.",
            factionId: 'druid_circle',
            intelReq: 5,
            political_influence: 5,
            economic_value: 3,
            military_strength: 6,
            population: 100
        },
        {
            id: 'poi_tt_cavalry_academy',
            x: 90.0,
            y: 49.0,
            type: 'academy',
            name: "High Saddle Academy",
            description: "Where humanoids from other lands come to learn the art of mounted warfare from the masters.",
            factionId: 'centaur_khanate',
            intelReq: 15,
            political_influence: 6,
            economic_value: 6,
            military_strength: 5,
            population: 500
        },
        {
            id: 'poi_tt_border_outpost',
            x: 73.0,
            y: 55.0,
            type: 'barracks',
            name: "Westguard Post",
            description: "Guards the border against the dragons of Halfinger Grove. Equipped with massive ballistae.",
            factionId: 'centaur_khanate',
            intelReq: 20,
            political_influence: 3,
            economic_value: 2,
            military_strength: 8,
            population: 250
        },
        {
            id: 'poi_tt_whispering_grass',
            x: 76.0,
            y: 72.0,
            type: 'dungeon_entrance',
            name: "Field of Whispers",
            description: "The grass here grows taller than a man and seems to shift on its own. Travelers often disappear, lured by voices.",
            factionId: 'monsters',
            intelReq: 40,
            political_influence: 0,
            economic_value: 0,
            military_strength: 7,
            population: 0
        },
        {
            id: 'poi_tt_wild_stallion_peak',
            x: 91.0,
            y: 40.0,
            type: 'landmark',
            name: "Stallion's Peak",
            description: "A rocky outcrop resembling a rearing horse. A legendary golden steed is said to appear here once every decade.",
            factionId: 'unaligned',
            intelReq: 25,
            political_influence: 2,
            economic_value: 9,
            military_strength: 3,
            population: 0
        }
    ],
    fogOfWar: []
};