// ===== COMPREHENSIVE MAP DATA =====

const MAPS = [
    // ===== D-DAY & NAVAL MAPS =====
    {
        id: "omaha_beach",
        name: "Omaha Beach",
        description: "Classic D-Day assault. Attackers must storm the fortified beach from naval transports.",
        width: 30,
        height: 18,
        terrain: [
            "wwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            "ssssssssssssssssssssssssssssss",
            "ssssssssssssssssssssssssssssss",
            "gggggggggggggggggggggggggggggg",
            "gggggggggggggggggggggggggggggg",
            "nnnnggggnnnnggggnnnnggggnnnngg",
            "ccccggggccccggggccccggggccccgg",
            "ccccrrrrccccrrrrccccrrrrccccgg",
            "ggggrrrrggggrrrrggggrrrrgggggg",
            "ggggrrrrggggrrrrggggrrrrgggggg",
            "ffffrrrrffffrrrrffffrrrrffffff",
            "ffffrrrrffffrrrrffffrrrrffffff",
            "gggggggggggggggggggggggggggggg",
            "gggggggggggggggggggggggggggggg",
            "gggggggggggggggggggggggggggggg"
        ],
        sideAZone: { x1: 0, x2: 29, y1: 0, y2: 5 },
        sideBZone: { x1: 0, x2: 29, y1: 12, y2: 17 }
    },
    {
        id: "normandy_cliffs",
        name: "Normandy Cliffs",
        description: "Scale the deadly cliffs under heavy fire. Defenders have the high ground.",
        width: 28,
        height: 20,
        terrain: [
            "wwwwwwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwwwwwww",
            "ssssssssssssssssssssssssssss",
            "ssssssssssssssssssssssssssss",
            "nnnnnnnnnnnnnnnnnnnnnnnnnnnn",
            "nnnnnnnnnnnnnnnnnnnnnnnnnnnn",
            "nnnnnnnnnnnnnnnnnnnnnnnnnnnn",
            "gggggggggggggggggggggggggggg",
            "ggggccccggggccccggggccccgggg",
            "ggggccccggggccccggggccccgggg",
            "rrrrrrrrrrrrrrrrrrrrrrrrrrrr",
            "gggggggggggggggggggggggggggg",
            "gggggggggggggggggggggggggggg",
            "ffffggggffffggggffffggggffff",
            "ffffggggffffggggffffggggffff",
            "gggggggggggggggggggggggggggg",
            "gggggggggggggggggggggggggggg",
            "gggggggggggggggggggggggggggg",
            "gggggggggggggggggggggggggggg"
        ],
        sideAZone: { x1: 0, x2: 27, y1: 0, y2: 5 },
        sideBZone: { x1: 0, x2: 27, y1: 14, y2: 19 }
    },
    {
        id: "pacific_island",
        name: "Pacific Island Assault",
        description: "Storm the volcanic island fortress. Watch out for the lava flows!",
        width: 26,
        height: 18,
        terrain: [
            "wwwwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwwwww",
            "wwssssssssssssssssssssswww",
            "ssssssggggggggggggssssssss",
            "ssggggggggggggggggggggggss",
            "ggggggggnnnnnnnngggggggggg",
            "ggggggnnllllllllnngggggggg",
            "ggggnnnnllllllllnnnngggggg",
            "ggggnnnnllllllllnnnngggggg",
            "ggggggnnllllllllnngggggggg",
            "ggggggggnnnnnnnngggggggggg",
            "gggggggggggggggggggggggggg",
            "ffggggggggggggggggggggggff",
            "ffffggggggggggggggggggffff",
            "ffffffggggggggggggggffffff",
            "gggggggggggggggggggggggggg",
            "gggggggggggggggggggggggggg"
        ],
        sideAZone: { x1: 0, x2: 25, y1: 0, y2: 5 },
        sideBZone: { x1: 0, x2: 25, y1: 12, y2: 17 }
    },
    {
        id: "naval_strait",
        name: "Naval Strait Battle",
        description: "Pure naval combat through a dangerous strait. Control the chokepoint!",
        width: 24,
        height: 20,
        terrain: [
            "nnnnnnwwwwwwwwwwwwnnnnnn",
            "nnnnwwwwwwwwwwwwwwwwnnnn",
            "nnnwwwwwwwwwwwwwwwwwwnnn",
            "nnwwwwwwwwwwwwwwwwwwwwnn",
            "nwwwwwwwwwwwwwwwwwwwwwwn",
            "wwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwww",
            "nwwwwwwwwwwwwwwwwwwwwwwn",
            "nnwwwwwwwwwwwwwwwwwwwwnn",
            "nnnwwwwwwwwwwwwwwwwwwnnn",
            "nnnnwwwwwwwwwwwwwwwwnnnn",
            "nnnnnnwwwwwwwwwwwwnnnnnn"
        ],
        sideAZone: { x1: 0, x2: 23, y1: 0, y2: 6 },
        sideBZone: { x1: 0, x2: 23, y1: 13, y2: 19 }
    },
    {
        id: "harbor_assault",
        name: "Harbor Assault",
        description: "Capture the enemy harbor. Mix of naval and land combat.",
        width: 28,
        height: 18,
        terrain: [
            "cccccccccccccccccccccccccccc",
            "crrrrrrrrrrrrrrrrrrrrrrrrrrc",
            "crggggggggggggggggggggggggrc",
            "crggggggggggggggggggggggggrc",
            "crggggggggggggggggggggggggrc",
            "cbbbbbbbbbbbbbbbbbbbbbbbbbc",
            "wwwwwwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwwwwwww",
            "cbbbbbbbbbbbbbbbbbbbbbbbbbc",
            "crggggggggggggggggggggggggrc",
            "crggggggggggggggggggggggggrc",
            "crggggggggggggggggggggggggrc",
            "crrrrrrrrrrrrrrrrrrrrrrrrrrc",
            "cccccccccccccccccccccccccccc"
        ],
        sideAZone: { x1: 0, x2: 27, y1: 0, y2: 5 },
        sideBZone: { x1: 0, x2: 27, y1: 12, y2: 17 }
    },
    {
        id: "river_crossing",
        name: "River Crossing",
        description: "Cross the deadly river under fire. Bridges are key chokepoints.",
        width: 26,
        height: 16,
        terrain: [
            "gggggggggggggggggggggggggg",
            "gggggggggggggggggggggggggg",
            "ffffggggffffggggffffggggff",
            "ffffggggffffggggffffggggff",
            "gggggggggggggggggggggggggg",
            "gggggggggggggggggggggggggg",
            "wwwwwwwwbbbbwwwwbbbbwwwwww",
            "wwwwwwwwbbbbwwwwbbbbwwwwww",
            "wwwwwwwwbbbbwwwwbbbbwwwwww",
            "wwwwwwwwbbbbwwwwbbbbwwwwww",
            "gggggggggggggggggggggggggg",
            "gggggggggggggggggggggggggg",
            "ffffggggffffggggffffggggff",
            "ffffggggffffggggffffggggff",
            "gggggggggggggggggggggggggg",
            "gggggggggggggggggggggggggg"
        ],
        sideAZone: { x1: 0, x2: 25, y1: 0, y2: 5 },
        sideBZone: { x1: 0, x2: 25, y1: 10, y2: 15 }
    },
    {
        id: "archipelago",
        name: "Archipelago Islands",
        description: "Island hopping warfare. Control the seas to win.",
        width: 30,
        height: 20,
        terrain: [
            "wwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwggggwwwwwwwwwwwwggggwwwwww",
            "wwwggggggwwwwwwwwwwggggggwwwww",
            "wwwggggggwwwwwwwwwwggggggwwwww",
            "wwwwggggwwwwwwwwwwwwggggwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwwwwwwwggggwwwwwwwwwwwwww",
            "wwwwwwwwwwwggggggwwwwwwwwwwwww",
            "wwwwwwwwwwwggggggwwwwwwwwwwwww",
            "wwwwwwwwwwwwggggwwwwwwwwwwwwww",
            "wwwwwwwwwwwwggggwwwwwwwwwwwwww",
            "wwwwwwwwwwwggggggwwwwwwwwwwwww",
            "wwwwwwwwwwwggggggwwwwwwwwwwwww",
            "wwwwwwwwwwwwggggwwwwwwwwwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwggggwwwwwwwwwwwwggggwwwwww",
            "wwwggggggwwwwwwwwwwggggggwwwww",
            "wwwggggggwwwwwwwwwwggggggwwwww",
            "wwwwggggwwwwwwwwwwwwggggwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwwwwwwwww"
        ],
        sideAZone: { x1: 0, x2: 10, y1: 0, y2: 19 },
        sideBZone: { x1: 19, x2: 29, y1: 0, y2: 19 }
    },

    // ===== CLASSIC FANTASY MAPS =====
    {
        id: "raventree_manor",
        name: "Raventree Manor",
        description: "Haunted mansion with supernatural entities. Void terrain damages non-ethereal units.",
        width: 20,
        height: 14,
        terrain: [
            "cccccccccccccccccccc",
            "cmmmvvvvmmmmmvvvvmmc",
            "cmmmvvvvmmmmmvvvvmmc",
            "ccccccrrrrrrrrcccccc",
            "mvvvvvrggggggrvvvvvm",
            "mvvvvvrggggggrvvvvvm",
            "mrrrrrrggggggrrrrrrm",
            "mrrrrrrggggggrrrrrrm",
            "mvvvvvrggggggrvvvvvm",
            "mvvvvvrggggggrvvvvvm",
            "ccccccrrrrrrrrcccccc",
            "cmmmvvvvmmmmmvvvvmmc",
            "cmmmvvvvmmmmmvvvvmmc",
            "cccccccccccccccccccc"
        ],
        sideAZone: { x1: 0, x2: 5, y1: 0, y2: 13 },
        sideBZone: { x1: 14, x2: 19, y1: 0, y2: 13 }
    },
    {
        id: "bramblehaven",
        name: "Bramblehaven Fortress",
        description: "Bloody siege location. Castles provide strong defense bonuses.",
        width: 24,
        height: 16,
        terrain: [
            "ffffffffffffffffffffffff",
            "fggggggggggggggggggggggf",
            "fggggggccccccccggggggggf",
            "fggggggcrrrrrrrcgggggggf",
            "fgggggcrggggggrcggggggf",
            "fgggggcrggggggrcggggggf",
            "frrrrrrrrggggrrrrrrrrrf",
            "frrrrrrrrggggrrrrrrrrrf",
            "frrrrrrrrggggrrrrrrrrrf",
            "frrrrrrrrggggrrrrrrrrrf",
            "fgggggcrggggggrcggggggf",
            "fgggggcrggggggrcggggggf",
            "fggggggcrrrrrrrcgggggggf",
            "fggggggccccccccggggggggf",
            "fggggggggggggggggggggggf",
            "ffffffffffffffffffffffff"
        ],
        sideAZone: { x1: 0, x2: 6, y1: 0, y2: 15 },
        sideBZone: { x1: 17, x2: 23, y1: 0, y2: 15 }
    },
    {
        id: "dk_island",
        name: "DK Island",
        description: "Kong-Kremling battleground with beaches, forests and water.",
        width: 22,
        height: 14,
        terrain: [
            "wwwwwwwwwwwwwwwwwwwwww",
            "wssssgggggggggggssssw",
            "wssssggffffffggssssw",
            "wggggffffffffffggggggw",
            "wggggffffffffffggggggw",
            "wgggggggrrrrggggggggw",
            "wbbbbbbbrrrrbbbbbbbbw",
            "wbbbbbbbrrrrbbbbbbbbw",
            "wgggggggrrrrggggggggw",
            "wggggffffffffffggggggw",
            "wggggffffffffffggggggw",
            "wssssggffffffggssssw",
            "wssssgggggggggggssssw",
            "wwwwwwwwwwwwwwwwwwwwww"
        ],
        sideAZone: { x1: 0, x2: 5, y1: 0, y2: 13 },
        sideBZone: { x1: 16, x2: 21, y1: 0, y2: 13 }
    },
    {
        id: "aegis_command",
        name: "Aegis Command",
        description: "Iron Legion fortress. Roads speed up movement.",
        width: 24,
        height: 16,
        terrain: [
            "cccccccccccccccccccccccc",
            "crrrrrrrrrrrrrrrrrrrrrrc",
            "crggggggggggggggggggggrc",
            "crggggggggggggggggggggrc",
            "crggccccggggggccccggggrc",
            "crggccccggggggccccggggrc",
            "crggggggggggggggggggggrc",
            "crrrrrrrrrrrrrrrrrrrrrc",
            "crrrrrrrrrrrrrrrrrrrrrc",
            "crggggggggggggggggggggrc",
            "crggccccggggggccccggggrc",
            "crggccccggggggccccggggrc",
            "crggggggggggggggggggggrc",
            "crggggggggggggggggggggrc",
            "crrrrrrrrrrrrrrrrrrrrrrc",
            "cccccccccccccccccccccccc"
        ],
        sideAZone: { x1: 0, x2: 6, y1: 0, y2: 15 },
        sideBZone: { x1: 17, x2: 23, y1: 0, y2: 15 }
    },
    {
        id: "dragon_mountain",
        name: "Dragon Mountain",
        description: "Where the truth was revealed. Lava damages non-flying units.",
        width: 22,
        height: 16,
        terrain: [
            "nnnnnnnnnnnnnnnnnnnnnn",
            "ngggggggllllgggggggggn",
            "ngggggggllllgggggggggn",
            "nggggggggllggggggggggn",
            "ngggggnnnllnnnggggggn",
            "ngggggnnnllnnnggggggn",
            "ngggggggggggggggggggn",
            "nrrrrrrrrrrrrrrrrrrrrn",
            "nrrrrrrrrrrrrrrrrrrrrn",
            "ngggggggggggggggggggn",
            "ngggggnnnllnnnggggggn",
            "ngggggnnnllnnnggggggn",
            "nggggggggllggggggggggn",
            "ngggggggllllgggggggggn",
            "ngggggggllllgggggggggn",
            "nnnnnnnnnnnnnnnnnnnnnn"
        ],
        sideAZone: { x1: 0, x2: 5, y1: 0, y2: 15 },
        sideBZone: { x1: 16, x2: 21, y1: 0, y2: 15 }
    },
    {
        id: "mushroom_plains",
        name: "Mushroom Plains",
        description: "Classic open battlefield. Great for large army clashes.",
        width: 24,
        height: 14,
        terrain: [
            "gggggggggggggggggggggggg",
            "gggggggggggggggggggggggg",
            "gggggggggggggggggggggggg",
            "gggggggfffffffffffffgggg",
            "gggggggfffffffffffffgggg",
            "gggggggggggggggggggggggg",
            "rrrrrrrrrrrrrrrrrrrrrrrr",
            "rrrrrrrrrrrrrrrrrrrrrrrr",
            "gggggggggggggggggggggggg",
            "gggggggfffffffffffffgggg",
            "gggggggfffffffffffffgggg",
            "gggggggggggggggggggggggg",
            "gggggggggggggggggggggggg",
            "gggggggggggggggggggggggg"
        ],
        sideAZone: { x1: 0, x2: 6, y1: 0, y2: 13 },
        sideBZone: { x1: 17, x2: 23, y1: 0, y2: 13 }
    },
    {
        id: "swamp_crossing",
        name: "Swamp Crossing",
        description: "Treacherous swamplands. Swimming units excel here.",
        width: 22,
        height: 14,
        terrain: [
            "pppppppppppppppppppppp",
            "pgggggpppppppppggggggp",
            "pggggggggppppggggggggp",
            "pgggggggbbbbgggggggggp",
            "ppppppppbbbbppppppppppp",
            "pwwwwwwwbbbbwwwwwwwwwp",
            "pwwwwwwwbbbbwwwwwwwwwp",
            "pwwwwwwwbbbbwwwwwwwwwp",
            "pwwwwwwwbbbbwwwwwwwwwp",
            "ppppppppbbbbppppppppppp",
            "pgggggggbbbbgggggggggp",
            "pggggggggppppggggggggp",
            "pgggggpppppppppggggggp",
            "pppppppppppppppppppppp"
        ],
        sideAZone: { x1: 0, x2: 5, y1: 0, y2: 13 },
        sideBZone: { x1: 16, x2: 21, y1: 0, y2: 13 }
    },
    {
        id: "castle_siege",
        name: "Castle Siege",
        description: "Attack or defend the central fortress!",
        width: 26,
        height: 16,
        terrain: [
            "gggggggggggggggggggggggggg",
            "ggggggggggccccccgggggggggg",
            "ggggggggccccccccccgggggggg",
            "ggggggggccggggggccgggggggg",
            "ggggggggccggggggccgggggggg",
            "ggggggggccggggggccgggggggg",
            "gggggggrrrrrrrrrrrrgggggg",
            "rrrrrrrrrrrrrrrrrrrrrrrrrr",
            "rrrrrrrrrrrrrrrrrrrrrrrrrr",
            "gggggggrrrrrrrrrrrrgggggg",
            "ggggggggccggggggccgggggggg",
            "ggggggggccggggggccgggggggg",
            "ggggggggccggggggccgggggggg",
            "ggggggggccccccccccgggggggg",
            "ggggggggggccccccgggggggggg",
            "gggggggggggggggggggggggggg"
        ],
        sideAZone: { x1: 0, x2: 6, y1: 0, y2: 15 },
        sideBZone: { x1: 19, x2: 25, y1: 0, y2: 15 }
    },
    {
        id: "lava_fields",
        name: "Lava Fields",
        description: "Volcanic battleground. Flying units have huge advantage.",
        width: 22,
        height: 14,
        terrain: [
            "nnnnnnnnnnnnnnnnnnnnnn",
            "nggggllllllllllggggggn",
            "nggggllllllllllggggggn",
            "nggggggllllllggggggggn",
            "nbbbbbbbbbbbbbbbbbbbbn",
            "nllllllgggggglllllllln",
            "nllllllgggggglllllllln",
            "nllllllgggggglllllllln",
            "nllllllgggggglllllllln",
            "nbbbbbbbbbbbbbbbbbbbbn",
            "nggggggllllllggggggggn",
            "nggggllllllllllggggggn",
            "nggggllllllllllggggggn",
            "nnnnnnnnnnnnnnnnnnnnnn"
        ],
        sideAZone: { x1: 0, x2: 5, y1: 0, y2: 13 },
        sideBZone: { x1: 16, x2: 21, y1: 0, y2: 13 }
    },
    {
        id: "forest_ambush",
        name: "Forest Ambush",
        description: "Dense forest provides cover. Scouts and ranged units shine.",
        width: 24,
        height: 14,
        terrain: [
            "ffffffffffffffffffffffff",
            "ffggggfffffffffffggggfff",
            "ffggggggffffffggggggggff",
            "fffgggggggggggggggggffff",
            "ffffggggggrrggggggfffff",
            "fffffgggggrrggggggfffff",
            "ffffffrrrrrrrrrrfffffff",
            "ffffffrrrrrrrrrrfffffff",
            "fffffgggggrrggggggfffff",
            "ffffggggggrrggggggfffff",
            "fffgggggggggggggggggffff",
            "ffggggggffffffggggggggff",
            "ffggggfffffffffffggggfff",
            "ffffffffffffffffffffffff"
        ],
        sideAZone: { x1: 0, x2: 6, y1: 0, y2: 13 },
        sideBZone: { x1: 17, x2: 23, y1: 0, y2: 13 }
    },

    // ===== NEW UNIQUE MAPS =====
    {
        id: "frozen_wastes",
        name: "Frozen Wastes",
        description: "Icy tundra battlefield. Rivers are frozen solid.",
        width: 26,
        height: 16,
        terrain: [
            "gggggggggggggggggggggggggg",
            "ggggnnnnggggggggnnnngggggg",
            "ggnnnnnnnnggggnnnnnnnngggg",
            "ggnnnnnnnnggggnnnnnnnngggg",
            "ggggnnnnggggggggnnnngggggg",
            "gggggggggggggggggggggggggg",
            "gggggggggggggggggggggggggg",
            "bbbbbbbbbbbbbbbbbbbbbbbbbb",
            "bbbbbbbbbbbbbbbbbbbbbbbbbb",
            "gggggggggggggggggggggggggg",
            "gggggggggggggggggggggggggg",
            "ggggnnnnggggggggnnnngggggg",
            "ggnnnnnnnnggggnnnnnnnngggg",
            "ggnnnnnnnnggggnnnnnnnngggg",
            "ggggnnnnggggggggnnnngggggg",
            "gggggggggggggggggggggggggg"
        ],
        sideAZone: { x1: 0, x2: 7, y1: 0, y2: 15 },
        sideBZone: { x1: 18, x2: 25, y1: 0, y2: 15 }
    },
    {
        id: "desert_oasis",
        name: "Desert Oasis",
        description: "Fight over the precious water source in the scorching desert.",
        width: 24,
        height: 16,
        terrain: [
            "ssssssssssssssssssssssss",
            "ssssssssssssssssssssssss",
            "ssssssggggggggggggssssss",
            "ssssggggggggggggggggssss",
            "ssssggggggggggggggggssss",
            "ssssggggggwwwwggggggssss",
            "ssssggggwwwwwwwwggggssss",
            "ssssggggwwwwwwwwggggssss",
            "ssssggggwwwwwwwwggggssss",
            "ssssggggggwwwwggggggssss",
            "ssssggggggggggggggggssss",
            "ssssggggggggggggggggssss",
            "ssssssggggggggggggssssss",
            "ssssssssssssssssssssssss",
            "ssssssssssssssssssssssss",
            "ssssssssssssssssssssssss"
        ],
        sideAZone: { x1: 0, x2: 7, y1: 0, y2: 15 },
        sideBZone: { x1: 16, x2: 23, y1: 0, y2: 15 }
    },
    {
        id: "twin_fortresses",
        name: "Twin Fortresses",
        description: "Two castles face each other across no-man's land.",
        width: 28,
        height: 14,
        terrain: [
            "ccccccggggggggggggggcccccc",
            "ccccccggggggggggggggcccccc",
            "ccrrccggggggggggggggccrrcc",
            "ccrrccggggggggggggggccrrcc",
            "ccrrccggggggggggggggccrrcc",
            "ccrrccggggggggggggggccrrcc",
            "rrrrrrrrrrrrrrrrrrrrrrrrrr",
            "rrrrrrrrrrrrrrrrrrrrrrrrrr",
            "ccrrccggggggggggggggccrrcc",
            "ccrrccggggggggggggggccrrcc",
            "ccrrccggggggggggggggccrrcc",
            "ccrrccggggggggggggggccrrcc",
            "ccccccggggggggggggggcccccc",
            "ccccccggggggggggggggcccccc"
        ],
        sideAZone: { x1: 0, x2: 5, y1: 0, y2: 13 },
        sideBZone: { x1: 22, x2: 27, y1: 0, y2: 13 }
    },
    {
        id: "canyon_pass",
        name: "Canyon Pass",
        description: "Narrow canyon with deadly cliffs. Control the pass!",
        width: 22,
        height: 18,
        terrain: [
            "nnnnnnnnnnnnnnnnnnnnnn",
            "nnnnnnnnnnnnnnnnnnnnnn",
            "nnnnggggggggggggnnnnnn",
            "nnggggggggggggggggnnnn",
            "nnggggggggggggggggnnnn",
            "nnggggggggggggggggnnnn",
            "nnnnggggrrrrggggnnnnnn",
            "nnnnnnggrrrrggnnnnnnnn",
            "nnnnnnggrrrrggnnnnnnnn",
            "nnnnnnggrrrrggnnnnnnnn",
            "nnnnnnggrrrrggnnnnnnnn",
            "nnnnggggrrrrggggnnnnnn",
            "nnggggggggggggggggnnnn",
            "nnggggggggggggggggnnnn",
            "nnggggggggggggggggnnnn",
            "nnnnggggggggggggnnnnnn",
            "nnnnnnnnnnnnnnnnnnnnnn",
            "nnnnnnnnnnnnnnnnnnnnnn"
        ],
        sideAZone: { x1: 2, x2: 19, y1: 0, y2: 5 },
        sideBZone: { x1: 2, x2: 19, y1: 12, y2: 17 }
    },
    {
        id: "haunted_graveyard",
        name: "Haunted Graveyard",
        description: "Ethereal units thrive in this cursed burial ground.",
        width: 24,
        height: 16,
        terrain: [
            "vvvvvvvvvvvvvvvvvvvvvvvv",
            "vmmmggggmmmmmmmggggmmmv",
            "vggggggggggggggggggggggv",
            "vggggmmmmggggggmmmmggggv",
            "vggggmmmmggggggmmmmggggv",
            "vggggggggggggggggggggggv",
            "vrrrrrrrrrrrrrrrrrrrrrv",
            "vrrrrrrrrrrrrrrrrrrrrrv",
            "vrrrrrrrrrrrrrrrrrrrrrv",
            "vggggggggggggggggggggggv",
            "vggggmmmmggggggmmmmggggv",
            "vggggmmmmggggggmmmmggggv",
            "vggggggggggggggggggggggv",
            "vmmmggggmmmmmmmggggmmmv",
            "vvvvvvvvvvvvvvvvvvvvvvvv",
            "vvvvvvvvvvvvvvvvvvvvvvvv"
        ],
        sideAZone: { x1: 0, x2: 7, y1: 0, y2: 15 },
        sideBZone: { x1: 16, x2: 23, y1: 0, y2: 15 }
    },
    {
        id: "volcanic_island",
        name: "Volcanic Island",
        description: "Active volcano surrounded by ocean. Lava flows change the battlefield.",
        width: 24,
        height: 18,
        terrain: [
            "wwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwssssssssssswwwwwww",
            "wwwwwsssgggggggsssswwwww",
            "wwwwssggggggggggggssswww",
            "wwwssgggggggggggggggssww",
            "wwssggggggnnnngggggggssww",
            "wwssggggnnnllnnngggggssww",
            "wwssggggnnnllnnngggggssww",
            "wwssggggnnnllnnngggggssww",
            "wwssggggnnnllnnngggggssww",
            "wwssggggggnnnngggggggssww",
            "wwwssgggggggggggggggssww",
            "wwwwssggggggggggggssswww",
            "wwwwwsssgggggggsssswwwww",
            "wwwwwwssssssssssswwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwww"
        ],
        sideAZone: { x1: 0, x2: 10, y1: 0, y2: 17 },
        sideBZone: { x1: 13, x2: 23, y1: 0, y2: 17 }
    },
    {
        id: "siege_of_toad_town",
        name: "Siege of Toad Town",
        description: "Assault on the Mushroom Kingdom capital. Street fighting ahead.",
        width: 26,
        height: 18,
        terrain: [
            "cccccccccccccccccccccccccc",
            "crrrrrrrrrrrrrrrrrrrrrrrrc",
            "crcccccrcccccccrcccccrrrrc",
            "crcccccrcccccccrcccccrrrrc",
            "crrrrrrrrrrrrrrrrrrrrrrrc",
            "crcccccrcccccccrcccccrrrrc",
            "crcccccrcccccccrcccccrrrrc",
            "crrrrrrrrrrrrrrrrrrrrrrrrc",
            "crrrrrrrrrrrrrrrrrrrrrrrrc",
            "crrrrrrrrrrrrrrrrrrrrrrrrc",
            "crrrrrrrrrrrrrrrrrrrrrrrrc",
            "crcccccrcccccccrcccccrrrrc",
            "crcccccrcccccccrcccccrrrrc",
            "crrrrrrrrrrrrrrrrrrrrrrrc",
            "crcccccrcccccccrcccccrrrrc",
            "crcccccrcccccccrcccccrrrrc",
            "crrrrrrrrrrrrrrrrrrrrrrrrc",
            "cccccccccccccccccccccccccc"
        ],
        sideAZone: { x1: 0, x2: 8, y1: 0, y2: 17 },
        sideBZone: { x1: 17, x2: 25, y1: 0, y2: 17 }
    },
    {
        id: "mushroom_forest",
        name: "Giant Mushroom Forest",
        description: "Towering mushrooms provide cover. Classic Mushroom Kingdom terrain.",
        width: 24,
        height: 16,
        terrain: [
            "gggggggggggggggggggggggg",
            "ggffggffggffggffggffgggg",
            "ggffggffggffggffggffgggg",
            "gggggggggggggggggggggggg",
            "ffggffggffggffggffggffgg",
            "ffggffggffggffggffggffgg",
            "gggggggggggggggggggggggg",
            "rrrrrrrrrrrrrrrrrrrrrrrr",
            "rrrrrrrrrrrrrrrrrrrrrrrr",
            "gggggggggggggggggggggggg",
            "ffggffggffggffggffggffgg",
            "ffggffggffggffggffggffgg",
            "gggggggggggggggggggggggg",
            "ggffggffggffggffggffgggg",
            "ggffggffggffggffggffgggg",
            "gggggggggggggggggggggggg"
        ],
        sideAZone: { x1: 0, x2: 7, y1: 0, y2: 15 },
        sideBZone: { x1: 16, x2: 23, y1: 0, y2: 15 }
    },
    {
        id: "peachs_castle_grounds",
        name: "Peach's Castle Grounds",
        description: "The historic royal castle. Now a contested warzone.",
        width: 26,
        height: 18,
        terrain: [
            "gggggggggggggggggggggggggg",
            "ggggggggccccccccgggggggggg",
            "ggggggccccccccccccgggggggg",
            "ggggccccccccccccccccgggggg",
            "ggggccccccccccccccccgggggg",
            "ggggccrrrrrrrrrrrrccgggggg",
            "ggggccrrggggggggrrccgggggg",
            "ggggrrrrggggggggrrrrggggg",
            "rrrrrrrrrrrrrrrrrrrrrrrrrr",
            "rrrrrrrrrrrrrrrrrrrrrrrrrr",
            "ggggrrrrggggggggrrrrggggg",
            "ggggggrrggggggggrrgggggggg",
            "gggggggggggggggggggggggggg",
            "ggffggggggggggggggggffgggg",
            "ffffggggggggggggggggffffgg",
            "ffffggggggggggggggggffffgg",
            "ggffggggggggggggggggffgggg",
            "gggggggggggggggggggggggggg"
        ],
        sideAZone: { x1: 0, x2: 8, y1: 0, y2: 17 },
        sideBZone: { x1: 17, x2: 25, y1: 0, y2: 17 }
    },
    {
        id: "fawfuls_factory",
        name: "Fawful's Factory",
        description: "Industrial nightmare. Mechanical units have advantage.",
        width: 28,
        height: 16,
        terrain: [
            "cccccccccccccccccccccccccccc",
            "crrrrrrrrrrrrrrrrrrrrrrrrrrc",
            "crccccccccccccccccccccccccrc",
            "crccllccccccccccccccllccccrc",
            "crrrrrrrrrrrrrrrrrrrrrrrrrc",
            "crccccccccccccccccccccccccrc",
            "crccllccccccccccccccllccccrc",
            "crrrrrrrrrrrrrrrrrrrrrrrrrc",
            "crrrrrrrrrrrrrrrrrrrrrrrrrc",
            "crccllccccccccccccccllccccrc",
            "crccccccccccccccccccccccccrc",
            "crrrrrrrrrrrrrrrrrrrrrrrrrc",
            "crccllccccccccccccccllccccrc",
            "crccccccccccccccccccccccccrc",
            "crrrrrrrrrrrrrrrrrrrrrrrrrrc",
            "cccccccccccccccccccccccccccc"
        ],
        sideAZone: { x1: 0, x2: 8, y1: 0, y2: 15 },
        sideBZone: { x1: 19, x2: 27, y1: 0, y2: 15 }
    },
    {
        id: "koopa_keep",
        name: "Koopa Keep",
        description: "Bowser's ancient fortress in Dark Land. Lava moats everywhere.",
        width: 26,
        height: 18,
        terrain: [
            "llllllllllllllllllllllllll",
            "lggggggggggggggggggggggggl",
            "lgccccccccccccccccccccccgl",
            "lgcrrrrrrrrrrrrrrrrrrrrcgl",
            "lgcrggggggggggggggggggrcgl",
            "lgcrggccccccccccccggggrcgl",
            "lgcrggccccccccccccggggrcgl",
            "lgcrggccrrrrrrrrccggggrcgl",
            "lgcrggccrrrrrrrrccggggrcgl",
            "lgcrggccrrrrrrrrccggggrcgl",
            "lgcrggccrrrrrrrrccggggrcgl",
            "lgcrggccccccccccccggggrcgl",
            "lgcrggccccccccccccggggrcgl",
            "lgcrggggggggggggggggggrcgl",
            "lgcrrrrrrrrrrrrrrrrrrrrcgl",
            "lgccccccccccccccccccccccgl",
            "lggggggggggggggggggggggggl",
            "llllllllllllllllllllllllll"
        ],
        sideAZone: { x1: 1, x2: 8, y1: 1, y2: 16 },
        sideBZone: { x1: 17, x2: 24, y1: 1, y2: 16 }
    },
    {
        id: "airship_fleet",
        name: "Airship Fleet Battle",
        description: "Flying units dominate. Ground units must use the bridges.",
        width: 28,
        height: 14,
        terrain: [
            "vvvvvvvvvvvvvvvvvvvvvvvvvvvv",
            "vccccccvvvvvvvvvvvvccccccvv",
            "vcrrrrcvvvvvvvvvvvvcrrrrcvv",
            "vcrrrrcbbbbbbbbbbbbcrrrrcvv",
            "vcrrrrcvvvvvvvvvvvvcrrrrcvv",
            "vccccccvvvvvvvvvvvvccccccvv",
            "vvvvvvvvvvccccccvvvvvvvvvvv",
            "vvvvvvvvvvcrrrrcvvvvvvvvvvv",
            "vccccccvvvcrrrrcvvvccccccvv",
            "vcrrrrcbbbbcrrrrcbbbbcrrrrcvv",
            "vcrrrrcvvvcrrrrcvvvcrrrrcvv",
            "vcrrrrcvvvccccccvvvcrrrrcvv",
            "vccccccvvvvvvvvvvvvccccccvv",
            "vvvvvvvvvvvvvvvvvvvvvvvvvvvv"
        ],
        sideAZone: { x1: 0, x2: 7, y1: 0, y2: 13 },
        sideBZone: { x1: 20, x2: 27, y1: 0, y2: 13 }
    },
    {
        id: "kremling_swamp",
        name: "Kremling Swamp",
        description: "Home territory for the Kremlings. Swamp and water everywhere.",
        width: 24,
        height: 16,
        terrain: [
            "pppppppppppppppppppppppp",
            "pwwwwppppppppppppwwwwwpp",
            "pwwwwwwppppppppwwwwwwwpp",
            "ppwwwwwwwppppwwwwwwwwppp",
            "pppwwwwwwwwwwwwwwwwwpppp",
            "ppppppwwwwwwwwwwpppppppp",
            "pggggppwwwwwwwwppggggppp",
            "pggggggpwwwwwwpggggggppp",
            "pggggggpwwwwwwpggggggppp",
            "pggggppwwwwwwwwppggggppp",
            "ppppppwwwwwwwwwwpppppppp",
            "pppwwwwwwwwwwwwwwwwwpppp",
            "ppwwwwwwwppppwwwwwwwwppp",
            "pwwwwwwppppppppwwwwwwwpp",
            "pwwwwppppppppppppwwwwwpp",
            "pppppppppppppppppppppppp"
        ],
        sideAZone: { x1: 0, x2: 7, y1: 0, y2: 15 },
        sideBZone: { x1: 16, x2: 23, y1: 0, y2: 15 }
    },
    {
        id: "rogueport_docks",
        name: "Rogueport Docks",
        description: "Seedy port town. Naval and ground combat mix.",
        width: 26,
        height: 16,
        terrain: [
            "cccccccccccccccccccccccccc",
            "crrrrrrrrrrrrrrrrrrrrrrrrc",
            "crcccccrcccccccrcccccccrrc",
            "crcccccrcccccccrcccccccrrc",
            "crrrrrrrrrrrrrrrrrrrrrrrc",
            "bbbbbbbbbbbbbbbbbbbbbbbbbbb",
            "wwwwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwwwww",
            "wwwwwwwwwwwwwwwwwwwwwwwwww",
            "bbbbbbbbbbbbbbbbbbbbbbbbbbb",
            "crrrrrrrrrrrrrrrrrrrrrrrc",
            "crcccccrcccccccrcccccccrrc",
            "crcccccrcccccccrcccccccrrc",
            "crrrrrrrrrrrrrrrrrrrrrrrrc",
            "cccccccccccccccccccccccccc"
        ],
        sideAZone: { x1: 0, x2: 25, y1: 0, y2: 5 },
        sideBZone: { x1: 0, x2: 25, y1: 10, y2: 15 }
    },
    {
        id: "dark_land_border",
        name: "Dark Land Border",
        description: "The frontier between kingdoms. Fortified positions on both sides.",
        width: 28,
        height: 16,
        terrain: [
            "gggggggggggggggggggggggggggg",
            "gccccgggggggggggggggggccccgg",
            "gccccgggggggggggggggggccccgg",
            "grrrrggggggggggggggggggrrrrg",
            "gggggggggggggggggggggggggggg",
            "ggggffffggggggggggffffgggggg",
            "ggggffffggggggggggffffgggggg",
            "rrrrrrrrrrrrrrrrrrrrrrrrrrrr",
            "rrrrrrrrrrrrrrrrrrrrrrrrrrrr",
            "ggggffffggggggggggffffgggggg",
            "ggggffffggggggggggffffgggggg",
            "gggggggggggggggggggggggggggg",
            "grrrrggggggggggggggggggrrrrg",
            "gccccgggggggggggggggggccccgg",
            "gccccgggggggggggggggggccccgg",
            "gggggggggggggggggggggggggggg"
        ],
        sideAZone: { x1: 0, x2: 8, y1: 0, y2: 15 },
        sideBZone: { x1: 19, x2: 27, y1: 0, y2: 15 }
    },
    {
        id: "bob_omb_battlefield",
        name: "Bob-omb Battlefield",
        description: "Crater-scarred wasteland from the legendary battle. Dangerous terrain.",
        width: 26,
        height: 16,
        terrain: [
            "gggggggggggggggggggggggggg",
            "ggnngggnnggggggnngggnnggg",
            "gnnnngnnnnggggnnnngnnnnggg",
            "ggnngggnnggggggnngggnnggg",
            "gggggggggggggggggggggggggg",
            "gggllggggllggllggggllggggg",
            "gggllggggllggllggggllggggg",
            "rrrrrrrrrrrrrrrrrrrrrrrrrr",
            "rrrrrrrrrrrrrrrrrrrrrrrrrr",
            "gggllggggllggllggggllggggg",
            "gggllggggllggllggggllggggg",
            "gggggggggggggggggggggggggg",
            "ggnngggnnggggggnngggnnggg",
            "gnnnngnnnnggggnnnngnnnnggg",
            "ggnngggnnggggggnngggnnggg",
            "gggggggggggggggggggggggggg"
        ],
        sideAZone: { x1: 0, x2: 8, y1: 0, y2: 15 },
        sideBZone: { x1: 17, x2: 25, y1: 0, y2: 15 }
    },
    {
        id: "underground_caverns",
        name: "Underground Caverns",
        description: "Deep cave system with underground rivers and lava pockets.",
        width: 24,
        height: 18,
        terrain: [
            "nnnnnnnnnnnnnnnnnnnnnnnn",
            "nggggggggggggggggggggggn",
            "ngggwwwwgggggggwwwwgggn",
            "nggwwwwwwgggggwwwwwwggn",
            "nggwwwwwwgggggwwwwwwggn",
            "ngggwwwwgggggggwwwwgggn",
            "nggggggggggggggggggggggn",
            "nggggggggrrrrggggggggggn",
            "nggggggggrrrrggggggggggn",
            "nggggggggrrrrggggggggggn",
            "nggggggggrrrrggggggggggn",
            "nggggggggggggggggggggggn",
            "ngggllllgggggggllllgggn",
            "nggllllllgggggllllllggn",
            "nggllllllgggggllllllggn",
            "ngggllllgggggggllllgggn",
            "nggggggggggggggggggggggn",
            "nnnnnnnnnnnnnnnnnnnnnnnn"
        ],
        sideAZone: { x1: 1, x2: 10, y1: 1, y2: 16 },
        sideBZone: { x1: 13, x2: 22, y1: 1, y2: 16 }
    },
    {
        id: "cloud_kingdom",
        name: "Cloud Kingdom",
        description: "Battle among the clouds. Flying units essential, ground troops must use platforms.",
        width: 26,
        height: 14,
        terrain: [
            "vvvvvvvvvvvvvvvvvvvvvvvvvv",
            "vvccccvvvvvvvvvvvvccccvvvv",
            "vvcrrcvvvvvvvvvvvvcrrcvvvv",
            "vvcrrcbbbbbbbbbbbbcrrcvvvv",
            "vvccccvvvvvvvvvvvvccccvvvv",
            "vvvvvvvvvccccccvvvvvvvvvvv",
            "vvvvvvvvvcrrrrcvvvvvvvvvvv",
            "vvvvvvvvvcrrrrcvvvvvvvvvvv",
            "vvvvvvvvvccccccvvvvvvvvvvv",
            "vvccccvvvvvvvvvvvvccccvvvv",
            "vvcrrcbbbbbbbbbbbbcrrcvvvv",
            "vvcrrcvvvvvvvvvvvvcrrcvvvv",
            "vvccccvvvvvvvvvvvvccccvvvv",
            "vvvvvvvvvvvvvvvvvvvvvvvvvv"
        ],
        sideAZone: { x1: 0, x2: 7, y1: 0, y2: 13 },
        sideBZone: { x1: 18, x2: 25, y1: 0, y2: 13 }
    },
    {
        id: "midnight_jungle",
        name: "Midnight Jungle",
        description: "Dense DK Island jungle at night. Reduced visibility, ambush territory.",
        width: 24,
        height: 16,
        terrain: [
            "ffffffffffffffffffffffffffff",
            "ffggggffggggggggffggggffff",
            "fgggggggggggggggggggggggff",
            "fgggggggggggggggggggggggff",
            "ffggggffggggggggffggggffff",
            "fffffffffffffffffffffffff",
            "ffggggggggggggggggggggggff",
            "fggggggrrrrrrrrggggggggff",
            "fggggggrrrrrrrrggggggggff",
            "ffggggggggggggggggggggggff",
            "fffffffffffffffffffffffff",
            "ffggggffggggggggffggggffff",
            "fgggggggggggggggggggggggff",
            "fgggggggggggggggggggggggff",
            "ffggggffggggggggffggggffff",
            "ffffffffffffffffffffffffffff"
        ],
        sideAZone: { x1: 0, x2: 7, y1: 0, y2: 15 },
        sideBZone: { x1: 16, x2: 23, y1: 0, y2: 15 }
    },
    {
        id: "crystal_caves",
        name: "Crystal Caves",
        description: "Glittering underground realm. Reflective surfaces confuse combatants.",
        width: 24,
        height: 16,
        terrain: [
            "nnnnnnnnnnnnnnnnnnnnnnnn",
            "nmmmgggggggggggggggmmmn",
            "nmgggggggggggggggggggmn",
            "ngggggmmmggggmmmgggggggn",
            "ngggggmmmggggmmmgggggggn",
            "nggggggggggggggggggggggn",
            "nggggggggrrrrggggggggggn",
            "nrrrrrrrrrrrrrrrrrrrrrrn",
            "nrrrrrrrrrrrrrrrrrrrrrrn",
            "nggggggggrrrrggggggggggn",
            "nggggggggggggggggggggggn",
            "ngggggmmmggggmmmgggggggn",
            "ngggggmmmggggmmmgggggggn",
            "nmgggggggggggggggggggmn",
            "nmmmgggggggggggggggmmmn",
            "nnnnnnnnnnnnnnnnnnnnnnnn"
        ],
        sideAZone: { x1: 1, x2: 8, y1: 1, y2: 14 },
        sideBZone: { x1: 15, x2: 22, y1: 1, y2: 14 }
    },
    {
        id: "floating_fortress",
        name: "Floating Fortress",
        description: "Massive airborne structure. Flying units have clear advantage.",
        width: 28,
        height: 16,
        terrain: [
            "vvvvvvvvvvvvvvvvvvvvvvvvvvvv",
            "vvvvccccccccccccccccccvvvvvv",
            "vvvvcrrrrrrrrrrrrrrrrcvvvvvv",
            "vvvvcrggggggggggggggrcvvvvvv",
            "vvvvcrggccccccccccggrcvvvvvv",
            "vvvvcrggccrrrrrrccggrcvvvvvv",
            "vvvvcrggccrggggrcggrcvvvvvv",
            "bbbbcrggccrggggrcggrcbbbbbb",
            "bbbbcrggccrggggrcggrcbbbbbb",
            "vvvvcrggccrggggrcggrcvvvvvv",
            "vvvvcrggccrrrrrrccggrcvvvvvv",
            "vvvvcrggccccccccccggrcvvvvvv",
            "vvvvcrggggggggggggggrcvvvvvv",
            "vvvvcrrrrrrrrrrrrrrrrcvvvvvv",
            "vvvvccccccccccccccccccvvvvvv",
            "vvvvvvvvvvvvvvvvvvvvvvvvvvvv"
        ],
        sideAZone: { x1: 0, x2: 10, y1: 0, y2: 15 },
        sideBZone: { x1: 17, x2: 27, y1: 0, y2: 15 }
    }
];

// Extended terrain types for naval warfare
const TERRAIN_TYPES = {
    'g': { class: 'terrain-grass', name: 'Grass', defenseBonus: 0, color: '#4a7c23' },
    'w': { class: 'terrain-water', name: 'Water', defenseBonus: 0, damage: 5, color: '#2266aa' },
    'n': { class: 'terrain-mountain', name: 'Mountain', defenseBonus: 20, color: '#666666' },
    'f': { class: 'terrain-forest', name: 'Forest', defenseBonus: 10, color: '#2d5016' },
    's': { class: 'terrain-sand', name: 'Sand', defenseBonus: 0, color: '#d4a84b' },
    'l': { class: 'terrain-lava', name: 'Lava', defenseBonus: 0, damage: 15, color: '#cc2200' },
    'c': { class: 'terrain-castle', name: 'Castle', defenseBonus: 25, color: '#555555' },
    'm': { class: 'terrain-manor', name: 'Manor', defenseBonus: 15, color: '#3a2a4a' },
    'v': { class: 'terrain-void', name: 'Void', defenseBonus: 0, damage: 8, color: '#111111' },
    'r': { class: 'terrain-road', name: 'Road', defenseBonus: -5, color: '#8b7355' },
    'b': { class: 'terrain-bridge', name: 'Bridge', defenseBonus: 0, color: '#6b5344' },
    'p': { class: 'terrain-swamp', name: 'Swamp', defenseBonus: 5, damage: 3, color: '#3d4a2a' }
};

// Movement types for all unit categories
const MOVEMENT_TYPES = {
    foot: { name: 'Foot', grass: 1, water: 999, mountain: 2, forest: 1.5, sand: 1.5, lava: 2, castle: 1, manor: 1, void: 1.5, road: 0.7, bridge: 1, swamp: 2 },
    mounted: { name: 'Mounted', grass: 0.7, water: 999, mountain: 3, forest: 2, sand: 1, lava: 999, castle: 1, manor: 1.5, void: 1, road: 0.5, bridge: 1, swamp: 3 },
    flying: { name: 'Flying', grass: 0.8, water: 0.8, mountain: 0.8, forest: 0.8, sand: 0.8, lava: 1, castle: 0.8, manor: 0.8, void: 0.8, road: 0.8, bridge: 0.8, swamp: 0.8 },
    swimming: { name: 'Swimming', grass: 2, water: 0.5, mountain: 999, forest: 2, sand: 1.5, lava: 999, castle: 2, manor: 2, void: 1, road: 2, bridge: 1, swamp: 1 },
    mechanical: { name: 'Mechanical', grass: 1, water: 999, mountain: 2.5, forest: 2, sand: 1.5, lava: 1.5, castle: 0.8, manor: 1, void: 1, road: 0.5, bridge: 1, swamp: 999 },
    ethereal: { name: 'Ethereal', grass: 1, water: 1, mountain: 1, forest: 1, sand: 1, lava: 1, castle: 1, manor: 0.7, void: 0.5, road: 1, bridge: 1, swamp: 1 },
    heavy: { name: 'Heavy', grass: 1.2, water: 999, mountain: 2.5, forest: 2, sand: 2, lava: 1.5, castle: 1, manor: 1.2, void: 1, road: 0.8, bridge: 1.5, swamp: 999 },
    naval: { name: 'Naval', grass: 999, water: 0.5, mountain: 999, forest: 999, sand: 999, lava: 999, castle: 999, manor: 999, void: 999, road: 999, bridge: 1, swamp: 999 },
    amphibious: { name: 'Amphibious', grass: 1, water: 1, mountain: 2, forest: 1.5, sand: 1, lava: 999, castle: 1, manor: 1, void: 1, road: 0.8, bridge: 1, swamp: 1 }
};

// Export for use
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { MAPS, TERRAIN_TYPES, MOVEMENT_TYPES };
}
