// map-data/kivotos/Austelarassia.js
export const austelarassiaPois = [
    { id: 'poi_au_gehenna_central', x: 35.5, y: 73.0, type: 'major_city', name: "Gehenna Central District", subRegion: 'austelarassia', description: "The chaotic heart of the Gehenna Academy. A district of unruly students, constant street brawls, and a surprising number of food stalls.", factionId: 'gehenna_academy', intelReq: 10, political_influence: 7, economic_value: 6, military_strength: 7, population: 30000 },
    { id: 'poi_au_pandemonium_society_hq', x: 34.0, y: 70.0, type: 'castle', name: "Pandemonium Society HQ", subRegion: 'austelarassia', description: "The headquarters of Gehenna's ruling body. A grim, gothic building where the Prefect Team is in a constant, losing battle against the rest of the student body.", factionId: 'gehenna_academy', intelReq: 25, political_influence: 9, economic_value: 4, military_strength: 8, population: 200 },
    { id: 'poi_au_hot_springs_department', x: 32.5, y: 75.0, type: 'lair', name: "Hot Springs Development Department", subRegion: 'austelarassia', description: "The base for a club dedicated to finding and 'developing' hot springs, usually by blowing things up. They possess an alarming amount of explosives.", factionId: 'gehenna_academy', intelReq: 15, political_influence: 3, economic_value: 2, military_strength: 5, population: 4 },
    { id: 'poi_au_prefect_team_hq', x: 34.5, y: 68.0, type: 'barracks', name: "Prefect Team Headquarters", subRegion: 'austelarassia', description: "The heavily fortified headquarters of Gehenna's disciplinary committee. A small bastion of order in a sea of chaos.", factionId: 'gehenna_academy', intelReq: 20, political_influence: 6, economic_value: 3, military_strength: 9, population: 500 },
    { id: 'poi_au_gourmet_research_club', x: 37.5, y: 67.0, type: 'workshop', name: "Gourmet Research Society Kitchen", subRegion: 'austelarassia', description: "The base of operations for a club dedicated to the pursuit of exotic and often dangerous cuisine. Known for 'acquiring' rare ingredients via explosions.", factionId: 'gehenna_academy', intelReq: 15, political_influence: 3, economic_value: 3, military_strength: 4, population: 4 },
    { id: 'au_problem_solver_68_office', x: 39.0, y: 69.0, type: 'outpost', name: "Problem Solver 68 Office", subRegion: 'austelarassia', description: "A small, unassuming office that serves as the front for a group of mercenaries-for-hire who take on any odd job for cash.", factionId: 'freelancer_underworld', intelReq: 20, political_influence: 4, economic_value: 5, military_strength: 5, population: 4 },
    { id: 'au_emergency_medical_outpost', x: 43.0, y: 74.0, type: 'monastery', name: "Emergency Medical Department Outpost", subRegion: 'austelarassia', description: "A perpetually busy field hospital that patches up students injured in the district's constant fighting.", factionId: 'gehenna_academy', intelReq: 10, political_influence: 4, economic_value: 3, military_strength: 3, population: 150 },
    { id: 'au_barbed_wire_checkpoint', x: 44.5, y: 77.0, type: 'watchtower', name: "Barbed Wire Checkpoint", subRegion: 'austelarassia', description: "A makeshift but heavily armed checkpoint on the border with the central district, manned by the Prefect Team.", factionId: 'gehenna_academy', intelReq: 15, political_influence: 3, economic_value: 1, military_strength: 7, population: 50 },
    { id: 'au_food_truck_graveyard', x: 40.5, y: 77.5, type: 'ruins', name: "Food Truck Graveyard", subRegion: 'austelarassia', description: "The final resting place for food trucks that failed to pay protection money to the Gourmet Research Society. A grim warning to all.", factionId: 'unaligned', intelReq: 10, political_influence: 1, economic_value: 2, military_strength: 1, population: 0 },
    { id: 'au_firing_range', x: 31.0, y: 68.0, type: 'barracks', name: "Public Firing Range", subRegion: 'austelarassia', description: "A public firing range where Gehenna students can 'let off steam'. The definition of 'safety protocols' is extremely loose here.", factionId: 'unaligned', intelReq: 5, political_influence: 2, economic_value: 2, military_strength: 3, population: 100 },
];
export const austelarassiaData = {
    pointsOfInterest: austelarassiaPois,
    fogOfWar: []
};
