// directory-system.js - Player Relations Focused Directory System

import { state, loadState } from './state.js';
import { LORE_DATA } from './lore.js';
import { FACTION_ASSESSMENTS } from './assessments.js';
import { getReputation, getGenericFactionAssessment } from './reputation.js';
import { getIntelForFaction, getIntelBreakdown } from './systems/common.js';
import { playSound } from './common.js';
import { getAllFactions, getFaction, getFactionStats, toSystemId } from './systems/faction-registry.js';
import { getRealTimeMapStats } from './global-map-analysis.js';
import { WAHBOOK_POSTS } from './assembly-data.js';
import { calculateRumorMetrics } from './research-data.js'; 

// ============================================
// STATE
// ============================================

let currentView = 'grid';
let selectedPlayer = null;
let currentFilters = {
    region: 'all',
    standing: 'all',
    sort: 'reputation',
    search: ''
};

// ============================================
// INITIALIZATION
// ============================================

function init() {
    console.log('[Directory] Initializing...');
    
    if (!state.finalReputations || Object.keys(state.finalReputations).length === 0) {
        loadState();
    }
    
    selectedPlayer = state.loggedInUser !== 'generic' ? state.loggedInUser : state.party[0];
    
    render();
    initEventListeners();
    handleHashRoute();
    
    const allFactions = getUnifiedFactionList();
    console.log('[Directory] Initialized with', allFactions.length, 'factions (predefined + POI-extracted)');
}

// ============================================
// UNIFIED FACTION DATA - PREDEFINED + POI EXTRACTION
// ============================================

/**
 * Gets a unified list of factions by:
 * 1. Using predefined templates from LORE_DATA.factions when available
 * 2. Falling back to POI-extracted data from the faction registry
 */
function getUnifiedFactionList() {
    const predefinedFactions = LORE_DATA.factions || {};
    const registryFactions = getAllFactions(); // From faction-registry.js
    const mapStats = getRealTimeMapStats(); // POI-derived stats
    
    const unifiedFactions = new Map();
    
    // Step 1: Add all predefined factions first (they take priority)
    Object.entries(predefinedFactions).forEach(([key, faction]) => {
        const registryId = toSystemId(key);
        const registryData = registryFactions[registryId] || {};
        const stats = mapStats.global[registryId] || {};
        
        unifiedFactions.set(key, {
            key,
            registryId,
            source: 'predefined',
            // Predefined template data
            name: faction.name || registryData.name || key,
            description: faction.description || registryData.description || '',
            region: faction.region || 'Unknown',
            logo: faction.logo || 'logos/default.png',
            notable_people: faction.notable_people || [],
            relations: faction.relations || {},
            // Registry/POI data for display
            color: registryData.color || faction.color || '#888888',
            icon: registryData.icon || faction.icon || '🏴',
            shortName: registryData.shortName || faction.shortName || faction.name || key,
            leaderName: registryData.leaderName || faction.leaderName || 'Unknown',
            leaderTitle: registryData.leaderTitle || faction.leaderTitle || 'Leader',
            isAutoGenerated: false,
            // Stats from POI analysis
            military: stats.military || 0,
            economic: stats.economic || 0,
            political: stats.political || 0,
            population: stats.population || 0,
            poiCount: stats.poiCount || 0,
            activeRegions: stats.activeRegions || 0,
            controlledRegions: stats.controlledRegions || 0
        });
    });
    
    // Step 2: Add registry factions that don't have predefined templates
    Object.entries(registryFactions).forEach(([registryId, registryData]) => {
        if (registryId === 'unaligned') return;
        
        // Check if we already have this faction from predefined
        const existingKey = Array.from(unifiedFactions.keys()).find(k => 
            toSystemId(k) === registryId || k === registryId
        );
        
        if (!existingKey) {
            const stats = mapStats.global[registryId] || {};
            
            // Only add if the faction has some presence (POIs, military, etc.)
            const hasPresence = (stats.military || 0) > 0 || 
                               (stats.economic || 0) > 0 || 
                               (stats.poiCount || 0) > 0;
            
            if (hasPresence || registryData.isAutoGenerated === false) {
                unifiedFactions.set(registryId, {
                    key: registryId,
                    registryId,
                    source: registryData.isAutoGenerated ? 'poi-extracted' : 'registry',
                    // Use registry data as template
                    name: registryData.name || registryId,
                    description: registryData.description || `A faction discovered through exploration.`,
                    region: registryData.region || extractRegionFromPOIs(registryId, mapStats) || 'Unknown',
                    logo: registryData.logo || 'logos/default.png',
                    notable_people: registryData.notable_people || [],
                    relations: registryData.relations || {},
                    // Visual data
                    color: registryData.color || '#888888',
                    icon: registryData.icon || '🏴',
                    shortName: registryData.shortName || registryData.name || registryId,
                    leaderName: registryData.leaderName || 'Unknown',
                    leaderTitle: registryData.leaderTitle || 'Leader',
                    isAutoGenerated: registryData.isAutoGenerated || false,
                    // Stats
                    military: stats.military || 0,
                    economic: stats.economic || 0,
                    political: stats.political || 0,
                    population: stats.population || 0,
                    poiCount: stats.poiCount || 0,
                    activeRegions: stats.activeRegions || 0,
                    controlledRegions: stats.controlledRegions || 0
                });
            }
        }
    });
    
    return Array.from(unifiedFactions.values());
}

/**
 * Extract the primary region for a faction based on where most of their POIs are located
 */
function extractRegionFromPOIs(factionId, mapStats) {
    if (!mapStats.regions) return null;
    
    let maxPois = 0;
    let primaryRegion = null;
    
    mapStats.regions.forEach(region => {
        const factionPois = (region.pois || []).filter(poi => 
            toSystemId(poi.factionId || poi.controller) === factionId
        ).length;
        
        if (factionPois > maxPois) {
            maxPois = factionPois;
            primaryRegion = region.name;
        }
    });
    
    return primaryRegion;
}

/**
 * Get a single faction's unified data by key
 */
function getUnifiedFaction(factionKey) {
    const allFactions = getUnifiedFactionList();
    return allFactions.find(f => 
        f.key === factionKey || 
        f.registryId === factionKey || 
        toSystemId(f.key) === toSystemId(factionKey)
    );
}

// ============================================
// DATA FUNCTIONS
// ============================================

function getPartyAverageReputation(factionKey) {
    let total = 0;
    state.party.forEach(playerKey => {
        total += getReputation(playerKey, factionKey);
    });
    return Math.round(total / state.party.length);
}

function getPlayerReputation(playerKey, factionKey) {
    if (state.finalReputations && state.finalReputations[playerKey]) {
        return state.finalReputations[playerKey].reputation[factionKey] || 0;
    }
    return getReputation(playerKey, factionKey);
}

function getPlayerNotoriety(playerKey, factionKey) {
    if (state.finalReputations && state.finalReputations[playerKey]) {
        return state.finalReputations[playerKey].notoriety[factionKey] || 0;
    }
    return 0;
}

function getFactionAssessment(factionKey, playerKey) {
    if (FACTION_ASSESSMENTS[factionKey] && FACTION_ASSESSMENTS[factionKey][playerKey]) {
        return FACTION_ASSESSMENTS[factionKey][playerKey];
    }
    return null;
}

function getReputationClass(rep) {
    if (rep >= 50) return 'friendly';
    if (rep >= 20) return 'warm';
    if (rep > -20) return 'neutral';
    if (rep > -50) return 'cold';
    return 'hostile';
}

function getReputationLabel(rep) {
    if (rep >= 75) return 'Allied';
    if (rep >= 50) return 'Friendly';
    if (rep >= 20) return 'Warm';
    if (rep > -20) return 'Neutral';
    if (rep > -50) return 'Cold';
    if (rep > -75) return 'Hostile';
    return 'Enemy';
}

function getFilteredFactions() {
    const isDebug = state.debugMode;
    const allFactions = getUnifiedFactionList();
    
    let factions = allFactions
        .filter(faction => {
            // Filter out factions with no intel unless debug
            const intel = getIntelForFaction(faction.key);
            if (!isDebug && intel <= 0) {
                // Still show if they have POI presence
                if (faction.poiCount === 0 && faction.military === 0 && faction.economic === 0) {
                    return false;
                }
            }
            return true;
        })
        .map(faction => {
            const partyRep = getPartyAverageReputation(faction.key);
            const intel = getIntelForFaction(faction.key);
            
            // Get individual player reps
            const playerReps = {};
            state.party.forEach(playerKey => {
                playerReps[playerKey] = getPlayerReputation(playerKey, faction.key);
            });
            
            return {
                key: faction.key,
                faction: faction, // The unified faction object
                partyRep,
                intel,
                playerReps,
                region: faction.region || 'Unknown',
                source: faction.source,
                isAutoGenerated: faction.isAutoGenerated
            };
        });
    
    // Apply filters
    if (currentFilters.region !== 'all') {
        factions = factions.filter(f => f.region === currentFilters.region);
    }
    
    if (currentFilters.standing !== 'all') {
        factions = factions.filter(f => {
            const rep = selectedPlayer ? f.playerReps[selectedPlayer] : f.partyRep;
            switch (currentFilters.standing) {
                case 'friendly': return rep >= 50;
                case 'neutral': return rep > -50 && rep < 50;
                case 'hostile': return rep <= -50;
                default: return true;
            }
        });
    }
    
    if (currentFilters.search) {
        const search = currentFilters.search.toLowerCase();
        factions = factions.filter(f => 
            f.faction.name?.toLowerCase().includes(search) ||
            f.faction.description?.toLowerCase().includes(search) ||
            f.key.toLowerCase().includes(search)
        );
    }
    
    // Sort
    switch (currentFilters.sort) {
        case 'name':
            factions.sort((a, b) => (a.faction.name || a.key).localeCompare(b.faction.name || b.key));
            break;
        case 'intel':
            factions.sort((a, b) => b.intel - a.intel);
            break;
        case 'notoriety':
            const getNotoriety = (f) => selectedPlayer 
                ? getPlayerNotoriety(selectedPlayer, f.key)
                : state.party.reduce((sum, p) => sum + getPlayerNotoriety(p, f.key), 0) / state.party.length;
            factions.sort((a, b) => getNotoriety(b) - getNotoriety(a));
            break;
        case 'power':
            // Sort by combined military + economic + political
            factions.sort((a, b) => {
                const powerA = (a.faction.military || 0) + (a.faction.economic || 0) + (a.faction.political || 0);
                const powerB = (b.faction.military || 0) + (b.faction.economic || 0) + (b.faction.political || 0);
                return powerB - powerA;
            });
            break;
        case 'reputation':
        default:
            factions.sort((a, b) => {
                const repA = selectedPlayer ? a.playerReps[selectedPlayer] : a.partyRep;
                const repB = selectedPlayer ? b.playerReps[selectedPlayer] : b.partyRep;
                return repB - repA;
            });
    }
    
    return factions;
}

function getUniqueRegions() {
    const allFactions = getUnifiedFactionList();
    const regions = new Set();
    allFactions.forEach(f => {
        if (f.region && f.region !== 'Unknown') regions.add(f.region);
    });
    return [...regions].sort();
}

function getStandingSummary() {
    const factions = getFilteredFactions();
    
    let friendly = 0, neutral = 0, hostile = 0;
    
    factions.forEach(f => {
        const rep = selectedPlayer ? f.playerReps[selectedPlayer] : f.partyRep;
        
        if (rep >= 50) friendly++;
        else if (rep <= -50) hostile++;
        else neutral++;
    });
    
    return { friendly, neutral, hostile, total: factions.length };
}

function getRecentRumors(count = 5) {
    if (!LORE_DATA.rumors) return [];
    
    return [...LORE_DATA.rumors]
        .sort((a, b) => {
            const dateA = new Date(a.date.year, a.date.monthIndex, a.date.day);
            const dateB = new Date(b.date.year, b.date.monthIndex, b.date.day);
            return dateB - dateA;
        })
        .slice(0, count);
}

// ============================================
// CALCULATIONS FOR MODAL
// ============================================

function getReputationFactors(factionKey) {
    const targetPlayer = (selectedPlayer && selectedPlayer !== 'generic') 
        ? selectedPlayer 
        : state.party[0];

    const factors = [];
    const breakdown = state.calculationBreakdown?.[targetPlayer]?.[factionKey];

    if (breakdown) {
        if (breakdown.base !== 0) {
            factors.push({
                source: 'History',
                text: 'Base Reputation',
                impact: breakdown.base >= 0 ? 'positive' : 'negative',
                value: breakdown.base
            });
        }

        if (breakdown.rumors && breakdown.rumors.length > 0) {
            breakdown.rumors.forEach(r => {
                factors.push({
                    source: 'Rumor',
                    text: r.title,
                    impact: r.value >= 0 ? 'positive' : 'negative',
                    value: r.value
                });
            });
        }

        if (breakdown.propagation && breakdown.propagation.length > 0) {
            breakdown.propagation.forEach(p => {
                const sourceFaction = getUnifiedFaction(p.source);
                const sourceName = sourceFaction?.name || p.source;
                factors.push({
                    source: 'Relations',
                    text: `Influence from ${sourceName}`,
                    impact: p.value >= 0 ? 'positive' : 'negative',
                    value: Math.round(p.value)
                });
            });
        }
    } else {
        const rep = getReputation(targetPlayer, factionKey);
        factors.push({
            source: 'Unknown',
            text: 'General diplomatic relations',
            impact: rep >= 0 ? 'positive' : 'negative',
            value: rep
        });
    }

    return factors;
}

// ============================================
// RENDER FUNCTIONS
// ============================================

function renderPartyStatsBar() {
    const container = document.getElementById('party-stats-bar');
    if (!container) return;
    
    const summary = getStandingSummary();
    const factions = getFilteredFactions();
    
    const totalIntel = factions.reduce((sum, f) => sum + f.intel, 0);
    const avgIntel = factions.length > 0 ? Math.round(totalIntel / factions.length) : 0;
    
    // Count auto-generated vs predefined
    const autoCount = factions.filter(f => f.isAutoGenerated).length;
    const predefinedCount = factions.length - autoCount;
    
    container.innerHTML = `
        <div class="pstat-item">
            <span class="pstat-icon">🏴</span>
            <span class="pstat-value">${summary.total}</span>
            <span class="pstat-label">Known Factions</span>
        </div>
        <div class="pstat-item friendly">
            <span class="pstat-icon">💚</span>
            <span class="pstat-value">${summary.friendly}</span>
            <span class="pstat-label">Friendly</span>
        </div>
        <div class="pstat-item neutral">
            <span class="pstat-icon">💛</span>
            <span class="pstat-value">${summary.neutral}</span>
            <span class="pstat-label">Neutral</span>
        </div>
        <div class="pstat-item hostile">
            <span class="pstat-icon">❤️</span>
            <span class="pstat-value">${summary.hostile}</span>
            <span class="pstat-label">Hostile</span>
        </div>
        <div class="pstat-item">
            <span class="pstat-icon">🔍</span>
            <span class="pstat-value">${avgIntel}%</span>
            <span class="pstat-label">Avg Intel</span>
        </div>
        <div class="pstat-item">
            <span class="pstat-icon">📍</span>
            <span class="pstat-value">${autoCount}</span>
            <span class="pstat-label">Discovered</span>
        </div>
    `;
}

function renderPartyMemberList() {
    const container = document.getElementById('party-member-list');
    if (!container) return;
    
    container.innerHTML = state.party.map(playerKey => {
        const player = LORE_DATA.characters[playerKey];
        const isSelected = selectedPlayer === playerKey;
        
        return `
            <div class="party-member-item ${isSelected ? 'selected' : ''}" data-player="${playerKey}">
                <img src="${player?.portrait || 'portraits/unknown.png'}" alt="${player?.name}" class="party-member-portrait">
                <div class="party-member-info">
                    <span class="party-member-name">${player?.name || playerKey}</span>
                    <span class="party-member-status">${isSelected ? 'Selected' : 'Click to view'}</span>
                </div>
            </div>
        `;
    }).join('');
}

function renderStandingSummary() {
    const container = document.getElementById('standing-summary-content');
    if (!container) return;
    
    const summary = getStandingSummary();
    const total = summary.total || 1;
    
    const friendlyPct = (summary.friendly / total) * 100;
    const neutralPct = (summary.neutral / total) * 100;
    const hostilePct = (summary.hostile / total) * 100;

    container.innerHTML = `
        <div class="standing-bar">
            <div class="standing-segment friendly" style="width: ${friendlyPct}%;" title="${summary.friendly} Friendly"></div>
            <div class="standing-segment neutral" style="width: ${neutralPct}%;" title="${summary.neutral} Neutral"></div>
            <div class="standing-segment hostile" style="width: ${hostilePct}%;" title="${summary.hostile} Hostile"></div>
        </div>
        <div class="standing-legend">
            <span class="legend-item"><span class="legend-dot friendly"></span> ${summary.friendly} Friendly (${Math.round(friendlyPct)}%)</span>
            <span class="legend-item"><span class="legend-dot neutral"></span> ${summary.neutral} Neutral (${Math.round(neutralPct)}%)</span>
            <span class="legend-item"><span class="legend-dot hostile"></span> ${summary.hostile} Hostile (${Math.round(hostilePct)}%)</span>
        </div>
    `;
}

function renderRecentEvents() {
    const container = document.getElementById('recent-events-list');
    if (!container) return;
    
    const rumors = getRecentRumors(5);
    
    if (rumors.length === 0) {
        container.innerHTML = '<p class="no-events">No recent events</p>';
        return;
    }
    
    container.innerHTML = rumors.map(rumor => `
        <div class="recent-event-item">
            <span class="event-date">${rumor.date.day}/${rumor.date.monthIndex + 1}</span>
            <span class="event-title">${rumor.title}</span>
        </div>
    `).join('');
}

function renderRegionFilter() {
    const select = document.getElementById('region-filter');
    if (!select) return;
    
    const regions = getUniqueRegions();
    select.innerHTML = `
        <option value="all">All Regions (${regions.length})</option>
        ${regions.map(r => `<option value="${r}" ${currentFilters.region === r ? 'selected' : ''}>${r}</option>`).join('')}
    `;
}

function renderGridView() {
    const container = document.getElementById('view-container');
    if (!container) return;
    
    const factions = getFilteredFactions();
    const isDebug = state.debugMode;
    
    if (factions.length === 0) {
        container.innerHTML = '<div class="no-factions"><p>No factions match your filters.</p></div>';
        return;
    }
    
    // Separate predefined and auto-generated for display grouping
    const predefined = factions.filter(f => !f.isAutoGenerated);
    const discovered = factions.filter(f => f.isAutoGenerated);
    
    container.innerHTML = `
        <div class="faction-grid">
            ${predefined.map(faction => renderFactionCard(faction, isDebug)).join('')}
        </div>
        ${discovered.length > 0 ? `
            <div class="discovered-section">
                <h4 class="discovered-header">
                    <span class="discovered-icon">🔍</span>
                    Discovered Factions (${discovered.length})
                    <span class="discovered-subtitle">Extracted from exploration data</span>
                </h4>
                <div class="faction-grid discovered-grid">
                    ${discovered.map(faction => renderFactionCard(faction, isDebug)).join('')}
                </div>
            </div>
        ` : ''}
    `;
}
function renderWhyModal(factionKey) {
    const faction = getUnifiedFaction(factionKey);
    if (!faction) return;
    
    const factors = getReputationFactors(factionKey);
    const targetPlayer = (selectedPlayer && selectedPlayer !== 'generic') ? selectedPlayer : state.party[0];
    const totalRep = getReputation(targetPlayer, factionKey);
    const playerData = LORE_DATA.characters[targetPlayer];
    
    // Get intel breakdown
    const intelBreakdown = getIntelBreakdown(factionKey);
    
    let modal = document.getElementById('why-modal');
    if (!modal) {
        modal = document.createElement('div');
        modal.id = 'why-modal';
        modal.className = 'faction-modal-overlay';
        document.body.appendChild(modal);
    }

    const html = `
        <div class="faction-modal why-modal">
            <button class="modal-close" id="why-close-btn">✕</button>
            
            <!-- Header -->
            <div class="why-modal-header">
                <img src="${faction.logo || 'logos/default.png'}" class="why-modal-logo" alt="${faction.name}">
                <div class="why-modal-title">
                    <h3>${faction.icon || ''} ${faction.name}</h3>
                    <span class="why-modal-region">${faction.region || 'Unknown Region'}</span>
                </div>
            </div>
            
            <!-- Tab Navigation -->
            <div class="why-tabs">
                <button class="why-tab-btn active" data-tab="reputation">
                    <span class="why-tab-icon">💬</span>
                    Reputation
                </button>
                <button class="why-tab-btn" data-tab="intel">
                    <span class="why-tab-icon">🔍</span>
                    Intel
                </button>
            </div>
            
            <!-- Reputation Tab -->
            <div class="why-tab-content active" id="why-tab-reputation">
                <div class="why-section-header">
                    <div class="why-section-title">
                        <h4>Reputation Breakdown</h4>
                        <span class="why-section-subtitle">How ${playerData?.name || targetPlayer} is viewed</span>
                    </div>
                    <div class="why-total-badge ${getReputationClass(totalRep)}">
                        ${totalRep >= 0 ? '+' : ''}${totalRep}
                    </div>
                </div>
                
                <div class="why-list">
                    ${factors.map(f => `
                        <div class="why-item ${f.impact}">
                            <div class="why-icon">${f.impact === 'negative' ? '📉' : '📈'}</div>
                            <div class="why-content">
                                <span class="why-text">${f.text}</span>
                                <span class="why-source">${f.source}</span>
                            </div>
                            <span class="why-value ${f.value >= 0 ? 'positive' : 'negative'}">
                                ${f.value >= 0 ? '+' : ''}${f.value}
                            </span>
                        </div>
                    `).join('')}
                </div>
                
                <div class="why-footer">
                    <div class="why-footer-label">Standing</div>
                    <div class="why-footer-value">
                        <span class="why-standing-label ${getReputationClass(totalRep)}">${getReputationLabel(totalRep)}</span>
                        <span class="why-standing-player">for ${playerData?.name || targetPlayer}</span>
                    </div>
                </div>
            </div>
            
            <!-- Intel Tab -->
            <div class="why-tab-content" id="why-tab-intel">
                <div class="why-section-header">
                    <div class="why-section-title">
                        <h4>Intel Breakdown</h4>
                        <span class="why-section-subtitle">What you know about this faction</span>
                    </div>
                    <div class="why-total-badge intel">
                        ${intelBreakdown.total}%
                    </div>
                </div>
                
                <div class="intel-visual-bar">
                    <div class="intel-bar-track">
                        <div class="intel-bar-fill" style="width: ${intelBreakdown.total}%;"></div>
                        <div class="intel-bar-markers">
                            <span class="intel-marker" style="left: 25%;" title="Basic Info">25%</span>
                            <span class="intel-marker" style="left: 50%;" title="Detailed Info">50%</span>
                            <span class="intel-marker" style="left: 75%;" title="Deep Intel">75%</span>
                        </div>
                    </div>
                    <div class="intel-bar-labels">
                        <span>Unknown</span>
                        <span>Full Intel</span>
                    </div>
                </div>
                
                <div class="why-list">
                    <!-- Base Intel -->
                    <div class="why-item ${intelBreakdown.base > 0 ? 'positive' : 'neutral'}">
                        <div class="why-icon">📚</div>
                        <div class="why-content">
                            <span class="why-text">Base Knowledge</span>
                            <span class="why-source">From encounters, POIs, and known information</span>
                        </div>
                        <span class="why-value ${intelBreakdown.base > 0 ? 'positive' : 'neutral'}">
                            ${intelBreakdown.base > 0 ? '+' : ''}${intelBreakdown.base}%
                        </span>
                    </div>
                    
                    <!-- History Modifier -->
                    <div class="why-item ${intelBreakdown.history > 0 ? 'positive' : intelBreakdown.history < 0 ? 'negative' : 'neutral'}">
                        <div class="why-icon">${intelBreakdown.history >= 0 ? '📈' : '📉'}</div>
                        <div class="why-content">
                            <span class="why-text">Relationship History</span>
                            <span class="why-source">${getHistoryDescription(intelBreakdown.history, factionKey)}</span>
                        </div>
                        <span class="why-value ${intelBreakdown.history >= 0 ? 'positive' : 'negative'}">
                            ${intelBreakdown.history >= 0 ? '+' : ''}${intelBreakdown.history}%
                        </span>
                    </div>
                    
                    <!-- Decay -->
                    ${intelBreakdown.decay !== 0 ? `
                        <div class="why-item negative">
                            <div class="why-icon">⏳</div>
                            <div class="why-content">
                                <span class="why-text">Information Decay</span>
                                <span class="why-source">${getDecayDescription(factionKey)}</span>
                            </div>
                            <span class="why-value negative">
                                ${intelBreakdown.decay}%
                            </span>
                        </div>
                    ` : ''}
                    
                    <!-- Active Chatter -->
                    <div class="why-item ${intelBreakdown.active > 0 ? 'positive' : 'neutral'}">
                        <div class="why-icon">${intelBreakdown.active > 0 ? '💬' : '🔇'}</div>
                        <div class="why-content">
                            <span class="why-text">Active Chatter</span>
                            <span class="why-source">${getActiveChatterDescription(intelBreakdown.active, factionKey)}</span>
                        </div>
                        <span class="why-value ${intelBreakdown.active > 0 ? 'positive' : 'neutral'}">
                            ${intelBreakdown.active > 0 ? '+' : ''}${intelBreakdown.active}%
                        </span>
                    </div>
                </div>
                
                <!-- Intel Unlocks -->
                <div class="intel-unlocks">
                    <h5 class="intel-unlocks-title">Intel Unlocks</h5>
                    <div class="intel-unlock-list">
                        ${renderIntelUnlocks(intelBreakdown.total)}
                    </div>
                </div>
                
                <div class="why-footer">
                    <div class="why-footer-label">Intel Status</div>
                    <div class="why-footer-value">
                        <span class="why-intel-status ${getIntelStatusClass(intelBreakdown.total)}">${getIntelStatusLabel(intelBreakdown.total)}</span>
                        <span class="why-intel-trend">${getIntelTrend(intelBreakdown)}</span>
                    </div>
                </div>
            </div>
        </div>
    `;

    modal.innerHTML = html;
    modal.classList.add('visible');

    // Tab switching
    const tabBtns = modal.querySelectorAll('.why-tab-btn');
    const tabContents = modal.querySelectorAll('.why-tab-content');
    
    tabBtns.forEach(btn => {
        btn.addEventListener('click', () => {
            playSound('click.mp3', 0.3);
            tabBtns.forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            
            const tabId = btn.dataset.tab;
            tabContents.forEach(content => {
                content.classList.toggle('active', content.id === `why-tab-${tabId}`);
            });
        });
    });

    // Close handlers
    document.getElementById('why-close-btn').onclick = () => {
        playSound('click.mp3', 0.3);
        modal.classList.remove('visible');
    };
    
    modal.onclick = (e) => { 
        if (e.target === modal) {
            modal.classList.remove('visible');
        }
    };
}
function renderIntelUnlocks(intelLevel) {
    const unlocks = [
        { threshold: 10, label: 'Basic Info', icon: '📋', desc: 'Name and region' },
        { threshold: 25, label: 'Notable People', icon: '👤', desc: 'Key figures revealed' },
        { threshold: 40, label: 'Assessments', icon: '💭', desc: 'Personal opinions visible' },
        { threshold: 50, label: 'Relations', icon: '🤝', desc: 'Allies and enemies known' },
        { threshold: 60, label: 'Deep Intel', icon: '🔮', desc: 'Detailed descriptions' },
        { threshold: 75, label: 'Secrets', icon: '🗝️', desc: 'Hidden information' },
        { threshold: 90, label: 'Full Dossier', icon: '📖', desc: 'Complete knowledge' }
    ];
    
    return unlocks.map(unlock => {
        const isUnlocked = intelLevel >= unlock.threshold;
        const isNext = !isUnlocked && intelLevel >= unlock.threshold - 15;
        
        return `
            <div class="intel-unlock-item ${isUnlocked ? 'unlocked' : ''} ${isNext ? 'next' : ''}">
                <div class="intel-unlock-icon">${isUnlocked ? unlock.icon : '🔒'}</div>
                <div class="intel-unlock-info">
                    <span class="intel-unlock-label">${unlock.label}</span>
                    <span class="intel-unlock-threshold">${unlock.threshold}%</span>
                </div>
                ${isNext ? `<span class="intel-unlock-needed">Need ${unlock.threshold - intelLevel}% more</span>` : ''}
            </div>
        `;
    }).join('');
}
function getIntelStatusClass(intel) {
    if (intel >= 75) return 'excellent';
    if (intel >= 50) return 'good';
    if (intel >= 25) return 'moderate';
    return 'poor';
}

/**
 * Get intel status label
 */
function getIntelStatusLabel(intel) {
    if (intel >= 90) return 'Full Dossier';
    if (intel >= 75) return 'Well Informed';
    if (intel >= 50) return 'Moderate Intel';
    if (intel >= 25) return 'Basic Knowledge';
    if (intel >= 10) return 'Minimal Intel';
    return 'Unknown';
}

/**
 * Get intel trend indicator
 */
function getIntelTrend(breakdown) {
    const trend = breakdown.active + breakdown.decay;
    
    if (trend > 5) return '📈 Increasing';
    if (trend < -5) return '📉 Decreasing';
    return '➡️ Stable';
}
function getHistoryDescription(historyValue, factionKey) {
    const historyData = state.factionHistory?.[factionKey];
    
    if (!historyData || historyValue === 0) {
        return 'No established relationship history yet';
    }
    
    const days = historyData.consecutiveDays || 0;
    const direction = historyData.isPositive ? 'positive' : 'negative';
    
    if (days === 1) {
        return `1 day of ${direction} standing`;
    }
    
    return `${days} consecutive days of ${direction} standing`;
}
function getDecayDescription(factionKey) {
    const lastActive = state.factionChatterLastActive?.[factionKey];
    
    if (!lastActive) {
        return 'No recent information flow';
    }
    
    const daysSince = getDaysBetween(lastActive, CURRENT_GAME_DATE);
    
    if (daysSince === 1) {
        return 'Information going stale (1 day since last update)';
    }
    
    return `Information going stale (${daysSince} days since last update)`;
}
function getActiveChatterDescription(activeValue, factionKey) {
    if (activeValue === 0) {
        return 'No current rumors or news about this faction';
    }
    
    // Count active rumors involving this faction
    let activeRumorCount = 0;
    if (LORE_DATA && LORE_DATA.rumors) {
        LORE_DATA.rumors.forEach(rumor => {
            const isAffected = rumor.effects && rumor.effects[factionKey] !== undefined;
            const isTarget = rumor.targets && rumor.targets.includes(factionKey);
            
            if (isAffected || isTarget) {
                const relatedPosts = WAHBOOK_POSTS.filter(p => p.rumorId === rumor.id);
                const metrics = calculateRumorMetrics(rumor, relatedPosts);
                
                if (metrics.status !== 'Dead' && metrics.status !== 'Old News') {
                    activeRumorCount++;
                }
            }
        });
    }
    
    if (activeRumorCount === 1) {
        return '1 active rumor providing fresh intel';
    }
    
    return `${activeRumorCount} active rumors providing fresh intel`;
}

function renderFactionCard(factionData, isDebug) {
    const { key, faction, partyRep, intel, playerReps, source, isAutoGenerated } = factionData;
    
    const displayRep = selectedPlayer ? playerReps[selectedPlayer] : partyRep;
    const repClass = getReputationClass(displayRep);
    const repLabel = getReputationLabel(displayRep);
    
    const notoriety = selectedPlayer 
        ? getPlayerNotoriety(selectedPlayer, key)
        : Math.round(state.party.reduce((sum, p) => sum + getPlayerNotoriety(p, key), 0) / state.party.length);
    
    const assessmentPlayer = selectedPlayer || 'archie';
    const assessment = getFactionAssessment(key, assessmentPlayer);
    const assessmentSnippet = assessment 
        ? assessment.substring(0, 120) + (assessment.length > 120 ? '...' : '')
        : getGenericFactionAssessment(displayRep);
    
    const playerIndicators = state.party.map(p => {
        const rep = playerReps[p];
        const cls = getReputationClass(rep);
        const char = LORE_DATA.characters[p];
        return `<span class="player-rep-dot ${cls}" title="${char?.name || p}: ${rep}"></span>`;
    }).join('');

    const widthPct = Math.min(Math.abs(displayRep), 100) / 2;
    const barStyle = displayRep < 0 
        ? `width: ${widthPct}%; right: 50%; border-radius: 4px 0 0 4px;` 
        : `width: ${widthPct}%; left: 50%; border-radius: 0 4px 4px 0;`;
    
    // Source badge for auto-generated factions
    const sourceBadge = isAutoGenerated 
        ? '<span class="source-badge from-poi"></span>' 
        : '';
    
    // POI stats display for factions with presence
    const hasPOIStats = faction.military > 0 || faction.economic > 0 || faction.poiCount > 0;
    const poiStatsHTML = hasPOIStats ? `
        <div class="fc-poi-stats">
            <span class="fc-poi-stat" title="Military Strength">⚔️ ${faction.military || 0}</span>
            <span class="fc-poi-stat" title="Economic Value">💰 ${faction.economic || 0}</span>
            <span class="fc-poi-stat" title="Controlled POIs">📍 ${faction.poiCount || 0}</span>
        </div>
    ` : '';
    
    return `
        <div class="faction-card ${repClass} ${isAutoGenerated ? 'auto-generated' : ''}" 
             data-faction="${key}"
             style="border-top-color: ${faction.color || 'var(--accent-color)'};">
            <div class="fc-header">
                <img src="${faction.logo || 'logos/default.png'}" alt="${faction.name}" class="fc-logo">
                <div class="fc-title-block">
                    <h4 class="fc-name">
                        ${faction.icon || ''} ${faction.name || key}
                        ${sourceBadge}
                    </h4>
                    <span class="fc-region">${faction.region || 'Unknown Region'}</span>
                </div>
                
                <div class="fc-rep-wrapper">
                    <div class="fc-rep-badge ${repClass}">
                        ${displayRep >= 0 ? '+' : ''}${displayRep}
                    </div>
                    <button class="fc-why-btn" data-why="${key}" title="View Reputation Breakdown">?</button>
                </div>
            </div>
            
            <div class="fc-rep-bar-container">
                <div class="fc-rep-bar">
                    <div class="fc-rep-fill ${repClass}" style="${barStyle}"></div>
                    <div class="fc-rep-center"></div>
                </div>
                <div class="fc-rep-labels">
                    <span>Hostile</span>
                    <span class="fc-rep-label">${repLabel}</span>
                    <span>Friendly</span>
                </div>
            </div>
            
            <p class="fc-assessment">"${assessmentSnippet}"</p>
            
            ${poiStatsHTML}
            
            <div class="fc-stats">
                <div class="fc-stat">
                    <span class="fc-stat-label">Intel</span>
                    <div class="fc-stat-bar">
                        <div class="fc-stat-fill intel" style="width: ${intel}%;"></div>
                    </div>
                    <span class="fc-stat-value">${intel}%</span>
                </div>
                <div class="fc-stat">
                    <span class="fc-stat-label">Notoriety</span>
                    <div class="fc-stat-bar">
                        <div class="fc-stat-fill notoriety" style="width: ${notoriety}%;"></div>
                    </div>
                    <span class="fc-stat-value">${notoriety}%</span>
                </div>
            </div>
            
            <div class="fc-footer">
                <div class="fc-party-reps">
                    ${playerIndicators}
                </div>
                <button class="fc-details-btn" data-faction="${key}">View Details →</button>
            </div>
        </div>
    `;
}

function renderPlayerView() {
    const container = document.getElementById('view-container');
    if (!container) return;
    
    const player = LORE_DATA.characters[selectedPlayer];
    const factions = getFilteredFactions();
    
    const friendly = factions.filter(f => f.playerReps[selectedPlayer] >= 50);
    const warm = factions.filter(f => f.playerReps[selectedPlayer] >= 20 && f.playerReps[selectedPlayer] < 50);
    const neutral = factions.filter(f => f.playerReps[selectedPlayer] > -20 && f.playerReps[selectedPlayer] < 20);
    const cold = factions.filter(f => f.playerReps[selectedPlayer] <= -20 && f.playerReps[selectedPlayer] > -50);
    const hostile = factions.filter(f => f.playerReps[selectedPlayer] <= -50);
    
    container.innerHTML = `
        <div class="player-view">
            <div class="pv-header">
                <img src="${player?.portrait || 'portraits/unknown.png'}" alt="${player?.name}" class="pv-portrait">
                <div class="pv-info">
                    <h3 class="pv-name">${player?.name || selectedPlayer}</h3>
                    <p class="pv-title">${player?.title || 'Party Member'}</p>
                </div>
                <div class="pv-summary">
                    <div class="pv-stat"><span class="pv-stat-value">${friendly.length}</span><span class="pv-stat-label">Allies</span></div>
                    <div class="pv-stat"><span class="pv-stat-value">${hostile.length}</span><span class="pv-stat-label">Enemies</span></div>
                    <div class="pv-stat"><span class="pv-stat-value">${neutral.length + warm.length + cold.length}</span><span class="pv-stat-label">Neutral</span></div>
                </div>
            </div>
            
            ${renderPlayerStandingSection('💚 Friendly Factions', friendly, selectedPlayer, 'friendly')}
            ${renderPlayerStandingSection('💛 Warm Relations', warm, selectedPlayer, 'warm')}
            ${renderPlayerStandingSection('⚪ Neutral', neutral, selectedPlayer, 'neutral')}
            ${renderPlayerStandingSection('🧊 Cold Relations', cold, selectedPlayer, 'cold')}
            ${renderPlayerStandingSection('❤️ Hostile Factions', hostile, selectedPlayer, 'hostile')}
        </div>
    `;
}

function renderPlayerStandingSection(title, factions, playerKey, className) {
    if (factions.length === 0) return '';
    
    return `
        <div class="pv-section ${className}">
            <h4 class="pv-section-title">${title} (${factions.length})</h4>
            <div class="pv-faction-list">
                ${factions.map(f => {
                    const rep = f.playerReps[playerKey];
                    const assessment = getFactionAssessment(f.key, playerKey);
                    
                    return `
                        <div class="pv-faction-item ${f.isAutoGenerated ? 'auto-generated' : ''}" data-faction="${f.key}">
                            <img src="${f.faction.logo || 'logos/default.png'}" alt="${f.faction.name}" class="pv-faction-logo">
                            <div class="pv-faction-info">
                                <span class="pv-faction-name">
                                    ${f.faction.icon || ''} ${f.faction.name}
                                    ${f.isAutoGenerated ? '<span class="source-badge-small">POI</span>' : ''}
                                </span>
                                <span class="pv-faction-region">${f.region}</span>
                            </div>
                            <div class="pv-faction-rep ${getReputationClass(rep)}">
                                ${rep >= 0 ? '+' : ''}${rep}
                            </div>
                            ${assessment ? `<p class="pv-faction-assessment">"${assessment.substring(0, 80)}..."</p>` : ''}
                        </div>
                    `;
                }).join('')}
            </div>
        </div>
    `;
}

function renderStandingsMatrix() {
    const container = document.getElementById('view-container');
    if (!container) return;
    
    const factions = getFilteredFactions().slice(0, 25);
    
    container.innerHTML = `
        <div class="standings-matrix">
            <h3 class="matrix-title">📈 Party Standing Matrix</h3>
            <p class="matrix-desc">How each party member stands with each faction</p>
            
            <div class="matrix-container">
                <table class="matrix-table">
                    <thead>
                        <tr>
                            <th class="matrix-corner">Faction</th>
                            ${state.party.map(p => {
                                const char = LORE_DATA.characters[p];
                                return `<th class="matrix-player-header">
                                    <img src="${char?.portrait || 'portraits/unknown.png'}" alt="${char?.name}" class="matrix-portrait">
                                    <span>${char?.name?.split(' ')[0] || p}</span>
                                </th>`;
                            }).join('')}
                            <th class="matrix-player-header">
                                <span>👥 Party</span>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        ${factions.map(f => `
                            <tr class="matrix-row ${f.isAutoGenerated ? 'auto-row' : ''}" data-faction="${f.key}">
                                <td class="matrix-faction-cell">
                                    <img src="${f.faction.logo || 'logos/default.png'}" alt="${f.faction.name}" class="matrix-faction-logo">
                                    <span>${f.faction.icon || ''} ${f.faction.name}</span>
                                    ${f.isAutoGenerated ? '<span class="source-badge-tiny">POI</span>' : ''}
                                </td>
                                ${state.party.map(p => {
                                    const rep = f.playerReps[p];
                                    const cls = getReputationClass(rep);
                                    return `<td class="matrix-rep-cell ${cls}">${rep >= 0 ? '+' : ''}${rep}</td>`;
                                }).join('')}
                                <td class="matrix-rep-cell ${getReputationClass(f.partyRep)}">${f.partyRep >= 0 ? '+' : ''}${f.partyRep}</td>
                            </tr>
                        `).join('')}
                    </tbody>
                </table>
            </div>
            
            <div class="matrix-legend">
                <span class="legend-item"><span class="legend-dot friendly"></span> 50+ Friendly</span>
                <span class="legend-item"><span class="legend-dot warm"></span> 20-49 Warm</span>
                <span class="legend-item"><span class="legend-dot neutral"></span> -19 to 19 Neutral</span>
                <span class="legend-item"><span class="legend-dot cold"></span> -20 to -49 Cold</span>
                <span class="legend-item"><span class="legend-dot hostile"></span> -50- Hostile</span>
            </div>
        </div>
    `;
}

function renderIntelReport() {
    const container = document.getElementById('view-container');
    if (!container) return;
    
    const factions = getFilteredFactions().sort((a, b) => b.intel - a.intel);
    
    container.innerHTML = `
        <div class="intel-report">
            <h3 class="intel-title">🔍 Intelligence Report</h3>
            <p class="intel-desc">Current intelligence levels on known factions</p>
            
            <div class="intel-list">
                ${factions.map(f => {
                    const breakdown = getIntelBreakdown(f.key);
                    
                    return `
                        <div class="intel-item ${f.isAutoGenerated ? 'auto-generated' : ''}" data-faction="${f.key}">
                            <div class="intel-item-header">
                                <img src="${f.faction.logo || 'logos/default.png'}" alt="${f.faction.name}" class="intel-logo">
                                <div class="intel-item-info">
                                    <span class="intel-item-name">
                                        ${f.faction.icon || ''} ${f.faction.name}
                                        ${f.isAutoGenerated ? '<span class="source-badge-small">Discovered</span>' : ''}
                                    </span>
                                    <span class="intel-item-region">${f.region}</span>
                                </div>
                                <div class="intel-level">
                                    <span class="intel-value">${f.intel}%</span>
                                </div>
                            </div>
                            <div class="intel-bar">
                                <div class="intel-bar-fill" style="width: ${f.intel}%;"></div>
                            </div>
                            <div class="intel-breakdown">
                                <span>Base: ${breakdown.base}</span>
                                <span>History: +${breakdown.history}</span>
                                <span class="intel-active">Active: +${breakdown.active}</span>
                            </div>
                        </div>
                    `;
                }).join('')}
            </div>
        </div>
    `;
}

function renderFactionDetailModal(factionKey) {
    const faction = getUnifiedFaction(factionKey);
    if (!faction) return;
    
    const intel = getIntelForFaction(factionKey);
    const isDebug = state.debugMode;
    
    const content = document.getElementById('faction-modal-content');
    if (!content) return;
    
    // Build player assessments section
    const assessmentsHTML = state.party.map(playerKey => {
        const player = LORE_DATA.characters[playerKey];
        const rep = getPlayerReputation(playerKey, factionKey);
        const notoriety = getPlayerNotoriety(playerKey, factionKey);
        const assessment = getFactionAssessment(factionKey, playerKey);
        const repClass = getReputationClass(rep);
        
        return `
            <div class="modal-player-assessment">
                <div class="mpa-header">
                    <img src="${player?.portrait || 'portraits/unknown.png'}" alt="${player?.name}" class="mpa-portrait">
                    <div class="mpa-info">
                        <span class="mpa-name">${player?.name || playerKey}</span>
                        <div class="mpa-stats">
                            <span class="mpa-rep ${repClass}">Rep: ${rep >= 0 ? '+' : ''}${rep}</span>
                            <span class="mpa-notoriety">Notoriety: ${notoriety}</span>
                        </div>
                    </div>
                </div>
                ${assessment && (intel >= 40 || isDebug) ? `
                    <div class="mpa-assessment">
                        <p>"${assessment}"</p>
                    </div>
                ` : `
                    <div class="mpa-assessment locked">
                        <p>🔒 Requires ${40 - intel}% more intel to view assessment</p>
                    </div>
                `}
            </div>
        `;
    }).join('');
    
    // Notable people section
    let notablePeopleHTML = '';
    if ((intel >= 25 || isDebug) && faction.notable_people && faction.notable_people.length > 0) {
        notablePeopleHTML = `
            <div class="modal-section">
                <h4>Notable People</h4>
                <div class="modal-people-grid">
                    ${faction.notable_people.map(person => `
                        <div class="modal-person">
                            <strong>${person.name}</strong>
                            <span class="person-role">${person.role}</span>
                            ${intel >= 60 || isDebug ? `<p class="person-desc">${person.description}</p>` : ''}
                        </div>
                    `).join('')}
                </div>
            </div>
        `;
    }
    
    // Relations section
    let relationsHTML = '';
    if ((intel >= 50 || isDebug) && faction.relations) {
        const allies = faction.relations.allies || [];
        const enemies = faction.relations.enemies || [];
        
        if (allies.length > 0 || enemies.length > 0) {
            relationsHTML = `
                <div class="modal-section">
                    <h4>Known Relations</h4>
                    <div class="modal-relations">
                        ${allies.length > 0 ? `
                            <div class="modal-relation-group">
                                <span class="relation-label">🤝 Allies:</span>
                                ${allies.map(a => {
                                    const allyFaction = getUnifiedFaction(a);
                                    return allyFaction ? `<span class="relation-tag ally">${allyFaction.name}</span>` : '';
                                }).join('')}
                            </div>
                        ` : ''}
                        ${enemies.length > 0 ? `
                            <div class="modal-relation-group">
                                <span class="relation-label">⚔️ Enemies:</span>
                                ${enemies.map(e => {
                                    const enemyFaction = getUnifiedFaction(e);
                                    return enemyFaction ? `<span class="relation-tag enemy">${enemyFaction.name}</span>` : '';
                                }).join('')}
                            </div>
                        ` : ''}
                    </div>
                </div>
            `;
        }
    }
    
    // POI presence section for factions with territorial data
    let poiPresenceHTML = '';
    if (faction.poiCount > 0 || faction.military > 0 || faction.economic > 0) {
        poiPresenceHTML = `
            <div class="modal-section">
                <h4>Territorial Presence</h4>
                <div class="modal-poi-stats">
                    <div class="poi-stat-card">
                        <span class="poi-stat-value">⚔️ ${faction.military}</span>
                        <span class="poi-stat-label">Military Strength</span>
                    </div>
                    <div class="poi-stat-card">
                        <span class="poi-stat-value">💰 ${faction.economic}</span>
                        <span class="poi-stat-label">Economic Value</span>
                    </div>
                    <div class="poi-stat-card">
                        <span class="poi-stat-value">🏛️ ${faction.political}</span>
                        <span class="poi-stat-label">Political Influence</span>
                    </div>
                    <div class="poi-stat-card">
                        <span class="poi-stat-value">📍 ${faction.poiCount}</span>
                        <span class="poi-stat-label">Controlled POIs</span>
                    </div>
                    <div class="poi-stat-card">
                        <span class="poi-stat-value">🌍 ${faction.activeRegions}</span>
                        <span class="poi-stat-label">Active Regions</span>
                    </div>
                </div>
            </div>
        `;
    }
    
    // Source badge
    const sourceBadge = faction.isAutoGenerated 
        ? '<span class="source-badge from-poi"></span>'
        : '<span class="source-badge from-lore"></span>';
    
    content.innerHTML = `
        <div class="modal-header" style="border-color: ${faction.color || 'var(--accent-color)'};">
            <img src="${faction.logo || 'logos/default.png'}" alt="${faction.name}" class="modal-logo">
            <div class="modal-title-block">
                <h2>${faction.icon || ''} ${faction.name} ${sourceBadge}</h2>
                <span class="modal-region">${faction.region || 'Unknown Region'}</span>
            </div>
        </div>
        
        <div class="modal-intel-bar">
            <span class="modal-intel-label">Intel Level: ${intel}%</span>
            <div class="modal-intel-track">
                <div class="modal-intel-fill" style="width: ${intel}%;"></div>
            </div>
        </div>
        
        <div class="modal-section">
            <h4>Description</h4>
            <p class="modal-description">${faction.description || 'No description available.'}</p>
        </div>
        
        ${poiPresenceHTML}
        
        <div class="modal-section">
            <h4>Party Standings & Assessments</h4>
            <div class="modal-assessments">
                ${assessmentsHTML}
            </div>
        </div>
        
        ${notablePeopleHTML}
        ${relationsHTML}
    `;
    
    const modal = document.getElementById('faction-detail-modal');
    if (modal) {
        modal.classList.add('visible');
    }
}

// ============================================
// MAIN RENDER
// ============================================

function render() {
    renderPartyStatsBar();
    renderPartyMemberList();
    renderStandingSummary();
    renderRecentEvents();
    renderRegionFilter();
    
    switch (currentView) {
        case 'player':
            renderPlayerView();
            break;
        case 'standings':
            renderStandingsMatrix();
            break;
        case 'intel':
            renderIntelReport();
            break;
        default:
            renderGridView();
    }
}

// ============================================
// HASH ROUTING
// ============================================

function handleHashRoute() {
    const hash = window.location.hash;
    if (hash.startsWith('#faction/')) {
        const factionKey = hash.replace('#faction/', '');
        const faction = getUnifiedFaction(factionKey);
        if (faction) {
            renderFactionDetailModal(factionKey);
        }
    }
}

// ============================================
// EVENT LISTENERS
// ============================================

function initEventListeners() {
    const mainContent = document.getElementById('main-content');
    if (!mainContent) return;
    
    window.addEventListener('hashchange', handleHashRoute);
    
    document.addEventListener('click', (e) => {
        const whyBtn = e.target.closest('.fc-why-btn');
        if (whyBtn) {
            e.stopPropagation();
            const factionKey = whyBtn.dataset.why;
            playSound('click.mp3', 0.5);
            renderWhyModal(factionKey);
        }
    });

    mainContent.addEventListener('click', (e) => {
        const viewBtn = e.target.closest('.view-mode-btn');
        if (viewBtn) {
            playSound('click.mp3', 0.5);
            document.querySelectorAll('.view-mode-btn').forEach(b => b.classList.remove('active'));
            viewBtn.classList.add('active');
            currentView = viewBtn.dataset.view;
            render();
            return;
        }
        
        const partyMember = e.target.closest('.party-member-item');
        if (partyMember) {
            playSound('click.mp3', 0.5);
            selectedPlayer = partyMember.dataset.player;
            render();
            return;
        }
        
        const factionCard = e.target.closest('.faction-card, .pv-faction-item, .matrix-row, .intel-item');
        if (factionCard && !e.target.closest('button')) {
            playSound('click.mp3', 0.5);
            const factionKey = factionCard.dataset.faction;
            window.location.hash = `faction/${factionKey}`;
            renderFactionDetailModal(factionKey);
            return;
        }
        
        const detailsBtn = e.target.closest('.fc-details-btn');
        if (detailsBtn) {
            playSound('click.mp3', 0.5);
            const factionKey = detailsBtn.dataset.faction;
            window.location.hash = `faction/${factionKey}`;
            renderFactionDetailModal(factionKey);
            return;
        }
    });
    
    const modalClose = document.getElementById('modal-close-btn');
    if (modalClose) {
        modalClose.addEventListener('click', () => {
            playSound('click.mp3', 0.5);
            document.getElementById('faction-detail-modal')?.classList.remove('visible');
            window.location.hash = '';
        });
    }
    
    const modal = document.getElementById('faction-detail-modal');
    if (modal) {
        modal.addEventListener('click', (e) => {
            if (e.target === modal) {
                modal.classList.remove('visible');
                window.location.hash = '';
            }
        });
    }
    
    document.getElementById('region-filter')?.addEventListener('change', (e) => {
        currentFilters.region = e.target.value;
        render();
    });
    
    document.getElementById('standing-filter')?.addEventListener('change', (e) => {
        currentFilters.standing = e.target.value;
        render();
    });
    
    document.getElementById('sort-filter')?.addEventListener('change', (e) => {
        currentFilters.sort = e.target.value;
        render();
    });
    
    document.getElementById('search-filter')?.addEventListener('input', (e) => {
        currentFilters.search = e.target.value;
        render();
    });
    
    document.addEventListener('keydown', (e) => {
        if (e.key === 'Escape') {
            document.getElementById('faction-detail-modal')?.classList.remove('visible');
            document.getElementById('why-modal')?.classList.remove('visible');
            window.location.hash = '';
        }
    });
}

// ============================================
// INITIALIZATION
// ============================================

if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
} else {
    init();
}

export { render, getFilteredFactions, getUnifiedFactionList, getUnifiedFaction };