// map-data/pokemon/fiore.js
export const fiorePois = [
    { id: 'poi_fi_ringtown', x: 28.00, y: 18.00, type: 'town', name: "Ringtown", description: "A peaceful town in southern Fiore, known for its scenic beauty. It serves as a major base for the Ranger Union, with a Ranger Base responsible for the surrounding area.", factionId: 'ranger_union', intelReq: 5 },
    { id: 'poi_fi_fall_city', x: 22.00, y: 22.00, type: 'major_city', name: "Fall City", description: "The largest city in Fiore, a bustling port with a famous fountain. It houses the main Ranger Union headquarters and is a center for technology and trade.", factionId: 'ranger_union', intelReq: 10 },
    { id: 'poi_fi_summerland', x: 10.00, y: 18.00, type: 'village', name: "Summerland", description: "A tropical town on the coast, known for its dense jungle and the ancient Jungle Relic. A local Ranger Base monitors the area.", factionId: 'ranger_union', intelReq: 10 },
    { id: 'poi_fi_winternea', x: 15.00, y: 15.00, type: 'village', name: "Winternea", description: "A cold, snowy town at the foot of the Shiver Mountains. It is isolated but resilient, with a Ranger Base that specializes in cold-weather operations.", factionId: 'ranger_union', intelReq: 10 },
    { id: 'poi_fi_go_rock_base', x: 2.00, y: 17.00, type: 'fortress', name: "Go-Rock Squad Base", description: "The secret, high-tech headquarters of the villainous Go-Rock Squad, hidden deep within the mountains. From here, they plan their operations to capture legendary Pokémon.", factionId: 'go_rock_squad', intelReq: 40 },
    { id: 'poi_fi_fiore_temple', x: 20.00, y: 15.00, type: 'temple', name: "Fiore Temple", description: "An ancient, puzzle-filled temple that is sacred to the people of Fiore. It is said to be a place of immense power and a key location in the region's legends.", factionId: 'unaligned', intelReq: 35 },
    { id: 'poi_fi_lyra_forest', x: 29.00, y: 21.00, type: 'forest', name: "Lyra Forest", description: "A dense forest known for its complex layout and powerful wild Pokémon. A frequent patrol route for Pokémon Rangers.", factionId: 'unaligned', intelReq: 15 },
    { id: 'poi_fi_waterworks', x: 24.00, y: 20.00, type: 'workshop', name: "Fall City Waterworks", description: "The underground system that supplies water to Fall City. The Go-Rock Squad has been known to use these tunnels for their clandestine movements.", factionId: 'unaligned', intelReq: 25 },
];