// map-data/kivotos/NorthernAureanPole.js
export const northernAureanPolePois = [
    { id: 'poi_np_red_winter_academy', x: 40.0, y: 8.0, type: 'academy', name: "Red Winter Federal Academy", subRegion: 'northern_aurean_pole', description: "The main, imposing campus of the isolationist Red Winter academy. A place of strict rules, constant political purges, and revolutionary fervor.", factionId: 'red_winter_federal_academy', intelReq: 20, political_influence: 9, economic_value: 6, military_strength: 8, population: 10000 },
    { id: 'poi_np_spec_bureau_hq', x: 35.0, y: 8.5, type: 'fortress', name: "Spec Bureau Headquarters", subRegion: 'northern_aurean_pole', description: "The heavily fortified headquarters of Red Winter's powerful and feared student council. From here, they issue edicts and plan purges.", factionId: 'red_winter_federal_academy', intelReq: 35, political_influence: 10, economic_value: 4, military_strength: 9, population: 500 },
    { id: 'poi_np_no227_club_shack', x: 45.0, y: 7.0, type: 'outpost', name: "Spec Ops No. 227 Club Shack", subRegion: 'northern_aurean_pole', description: "A small, unassuming shack that serves as the base for a club of outcast students who specialize in unorthodox 'waste disposal' and survival skills.", factionId: 'red_winter_federal_academy', intelReq: 25, political_influence: 3, economic_value: 2, military_strength: 5, population: 3 },
    { id: 'poi_np_gulag', x: 10.0, y: 8.0, type: 'prison', name: "The Engineering Dept. Gulag", subRegion: 'northern_aurean_pole', description: "A brutal labor and re-education camp for students who have fallen out of favor with the Spec Bureau. Escape is said to be impossible.", factionId: 'red_winter_federal_academy', intelReq: 40, political_influence: 4, economic_value: 3, military_strength: 7, population: 1000 },
    { id: 'poi_np_munitions_factory', x: 20.0, y: 8.0, type: 'workshop', name: "Abandoned Munitions Factory", subRegion: 'northern_aurean_pole', description: "A massive, derelict factory from a past era. It is filled with dangerous, unstable old munitions and is a source of scrap for Red Winter's engineering clubs.", factionId: 'unaligned', intelReq: 15, political_influence: 1, economic_value: 5, military_strength: 3, population: 0 },
    { id: 'poi_np_frozen_harbor', x: 55.0, y: 9.0, type: 'port', name: "Frozen Harbor", subRegion: 'northern_aurean_pole', description: "Red Winter's only sea access, a harbor that is frozen for most of the year. It is patrolled by heavily armed icebreaker ships.", factionId: 'red_winter_federal_academy', intelReq: 20, political_influence: 5, economic_value: 6, military_strength: 7, population: 800 },
    { id: 'poi_np_comms_outpost', x: 65.0, y: 7.5, type: 'watchtower', name: "Secret Communications Outpost", subRegion: 'northern_aurean_pole', description: "A remote, disguised listening post used by the Spec Bureau to intercept communications from other academies.", factionId: 'red_winter_federal_academy', intelReq: 50, political_influence: 4, economic_value: 2, military_strength: 6, population: 20 },
    { id: 'poi_np_research_station', x: 2.0, y: 8.5, type: 'workshop', name: "Polar Research Station", subRegion: 'northern_aurean_pole', description: "A scientific research station studying the unique properties of the polar region's flora and fauna. Ostensibly neutral, but often forced to cooperate with Red Winter.", factionId: 'unaligned', intelReq: 15, political_influence: 2, economic_value: 4, military_strength: 2, population: 30 },
    { id: 'poi_np_permafrost_caverns', x: 30.0, y: 7.5, type: 'cave_entrance', name: "Permafrost Caverns", subRegion: 'northern_aurean_pole', description: "A network of deep, frozen caves that wind beneath the tundra. They are rumored to contain ancient secrets and cryogenically frozen creatures.", factionId: 'unaligned', intelReq: 25, political_influence: 1, economic_value: 3, military_strength: 3, population: 0 },
    { id: 'poi_np_cherenka_tavern', x: 42.0, y: 7.5, type: 'inn', name: "The 'Cherenka' Tavern", subRegion: 'northern_aurean_pole', description: "The only tavern in the district. A place where students can get a warm meal and engage in hushed, paranoid conversations away from the Spec Bureau's listening devices.", factionId: 'unaligned', intelReq: 10, political_influence: 3, economic_value: 4, military_strength: 2, population: 100 },
];
export const northernAureanPoleData = {
    pointsOfInterest: northernAureanPolePois,
    fogOfWar: []
};
