// map-data/kivotos/Silbaarstadt.js
export const silbaarstadtPois = [
    { id: 'poi_sb_millennium_tower', x: 21.0, y: 25.0, type: 'capital_city', name: "Millennium Tower", subRegion: 'silbaarstadt', description: "The central tower and administrative hub of the Millennium Science School. A marvel of futuristic architecture and high technology.", factionId: 'millennium_science_school', intelReq: 10, political_influence: 9, economic_value: 9, military_strength: 8, population: 6000 },
    { id: 'poi_sb_seminar_council_room', x: 23.0, y: 23.0, type: 'academy', name: "Seminar Council Room", subRegion: 'silbaarstadt', description: "The high-tech meeting room for Millennium's student council, Seminar. It is equipped with advanced holographic displays and security systems.", factionId: 'millennium_science_school', intelReq: 25, political_influence: 10, economic_value: 5, military_strength: 7, population: 50 },
    { id: 'poi_sb_engineering_dept', x: 15.0, y: 15.0, type: 'workshop', name: "Engineering Department", subRegion: 'silbaarstadt', description: "A massive complex of workshops and labs where students design and build everything from personal gadgets to giant robots.", factionId: 'millennium_science_school', intelReq: 15, political_influence: 6, economic_value: 8, military_strength: 7, population: 3000 },
    { id: 'poi_sb_cnc_hq', x: 14.0, y: 20.0, type: 'barracks', name: "C&C Headquarters", subRegion: 'silbaarstadt', description: "The headquarters for the 'Cleaning & Clearing' club, Millennium's elite special-ops team. They are equipped with the school's most advanced combat gear.", factionId: 'millennium_science_school', intelReq: 30, political_influence: 5, economic_value: 4, military_strength: 9, population: 5 },
    { id: 'poi_sb_veritas_hideout', x: 28.0, y: 30.0, type: 'lair', name: "Veritas Hideout", subRegion: 'silbaarstadt', description: "The hidden, data-crammed club room for the hacker group Veritas. They are a constant thorn in the side of Millennium's student council, Seminar.", factionId: 'millennium_science_school', intelReq: 40, political_influence: 4, economic_value: 3, military_strength: 5, population: 4 },
    { id: 'poi_sb_game_dev_dept', x: 18.0, y: 35.0, type: 'academy', name: "Game Development Department", subRegion: 'silbaarstadt', description: "The department where students create video games. They are rumored to be working on a secret project that could change Kivotos forever.", factionId: 'millennium_science_school', intelReq: 10, political_influence: 4, economic_value: 6, military_strength: 2, population: 500 },
    { id: 'poi_sb_ruined_lab', x: 27.0, y: 15.0, type: 'ruins', name: "Abandoned Laboratory Ruins", subRegion: 'silbaarstadt', description: "The ruins of a lab destroyed in a catastrophic experiment. It is now a dangerous area, leaking strange energy and guarded by rogue security bots.", factionId: 'unaligned', intelReq: 20, political_influence: 1, economic_value: 3, military_strength: 4, population: 0 },
    { id: 'poi_sb_data_archives', x: 13.0, y: 25.0, type: 'library', name: "Millennium Data Archives", subRegion: 'silbaarstadt', description: "A massive data center containing all of the school's research and student records. It is protected by state-of-the-art digital and physical security.", factionId: 'millennium_science_school', intelReq: 30, political_influence: 7, economic_value: 6, military_strength: 8, population: 100 },
    { id: 'poi_sb_super_arena', x: 25.0, y: 40.0, type: 'landmark', name: "The Super Arena", subRegion: 'silbaarstadt', description: "A holographic arena where students test their combat robots and experimental weapons in spectacular public battles.", factionId: 'unaligned', intelReq: 10, political_influence: 3, economic_value: 5, military_strength: 3, population: 1000 },
    { id: 'poi_sb_monorail_station', x: 20.0, y: 40.0, type: 'trade_post', name: "Millennium Monorail Station", subRegion: 'silbaarstadt', description: "A sleek, automated monorail station that connects Millennium to the rest of Kivotos.", factionId: 'millennium_science_school', intelReq: 5, political_influence: 4, economic_value: 5, military_strength: 4, population: 500 },
];
export const silbaarstadtData = {
    pointsOfInterest: silbaarstadtPois,
    fogOfWar: []
};
