

export const SPECIES_DATA = {
    // === D&D / FANTASY BASE (Expanded) ===
    dnd_human: { name: 'Human (Variant)', color: '#d4a373', icon: '🧑', description: 'Versatile and ambitious humans found across all realms.' },
    dnd_elf_high: { name: 'Elf (High)', color: '#ffd700', icon: '🧝‍♂️', description: 'Graceful masters of arcane magic and high culture.' },
    dnd_elf_wood: { name: 'Elf (Wood)', color: '#558b2f', icon: '🏹', description: 'Swift and stealthy guardians of the deep forests.' },
    dnd_elf_drow: { name: 'Elf (Drow)', color: '#424242', icon: '🕷️', description: 'Subterranean elves adapted to the dark dangers of the Underdark.' },
    dnd_dwarf_hill: { name: 'Dwarf (Hill)', color: '#8d6e63', icon: '🍺', description: 'Tough and intuitive dwarves with a love for craftsmanship.' },
    dnd_dwarf_mountain: { name: 'Dwarf (Mountain)', color: '#5d4037', icon: '🛡️', description: 'Strong and rugged dwarves from high peaks and deep mines.' },
    dnd_halfling_lightfoot: { name: 'Halfling (Lightfoot)', color: '#ffcc80', icon: '🦶', description: 'Stealthy and lucky folk who blend into crowds easily.' },
    dnd_halfling_stout: { name: 'Halfling (Stout)', color: '#ef6c00', icon: '🌾', description: 'Hardier halflings with a resistance to poison.' },
    dnd_gnome_forest: { name: 'Gnome (Forest)', color: '#aed581', icon: '🌳', description: 'Illusionists and tricksters who speak with small beasts.' },
    dnd_gnome_rock: { name: 'Gnome (Rock)', color: '#9e9d24', icon: '⚙️', description: 'Inventive tinkers with a love for technology.' },
    dnd_dragonborn_chromatic: { name: 'Dragonborn (Chromatic)', color: '#b71c1c', icon: '🔥', description: 'Proud warriors claiming ancestry from chromatic dragons.' },
    dnd_dragonborn_metallic: { name: 'Dragonborn (Metallic)', color: '#fbc02d', icon: '⚡', description: 'Noble dragonkin claiming ancestry from metallic dragons.' },
    dnd_tiefling: { name: 'Tiefling', color: '#7b1fa2', icon: '😈', description: 'Individuals with an infernal heritage and innate magic.' },
    dnd_orc: { name: 'Orc', color: '#33691e', icon: '👹', description: 'Strong, tribal warriors who value physical might.' },
    dnd_half_orc: { name: 'Half-Orc', color: '#689f38', icon: '🪓', description: 'Beings combining orcish strength with human adaptability.' },
    dnd_kobold: { name: 'Kobold', color: '#bf360c', icon: '🦎', description: 'Small, trap-making reptilians often serving dragons.' },
    dnd_goblin: { name: 'Goblin', color: '#4caf50', icon: '👺', description: 'Scrappy and numerous, thriving in the margins of society.' },
    dnd_hobgoblin: { name: 'Hobgoblin', color: '#d84315', icon: '💂', description: 'Disciplined and martial goblinoids with a strict code.' },
    dnd_bugbear: { name: 'Bugbear', color: '#795548', icon: '🐻', description: 'Large, hairy goblinoids who excel at ambush.' },
    dnd_aasimar: { name: 'Aasimar', color: '#e0f7fa', icon: '👼', description: 'Mortals touched by celestial power.' },
    dnd_genasi_fire: { name: 'Genasi (Fire)', color: '#ff5722', icon: '🔥', description: 'Elementals with burning passion and fiery skin.' },
    dnd_genasi_water: { name: 'Genasi (Water)', color: '#03a9f4', icon: '💧', description: 'Fluid beings with the essence of the sea.' },
    dnd_genasi_earth: { name: 'Genasi (Earth)', color: '#795548', icon: '🪨', description: 'Stoic beings with skin like stone or dust.' },
    dnd_genasi_air: { name: 'Genasi (Air)', color: '#b3e5fc', icon: '💨', description: 'Flighty beings who seem to drift on the wind.' },
    dnd_goliath: { name: 'Goliath', color: '#90a4ae', icon: '🏔️', description: 'Mountain-dwelling giants with stone-like skin.' },
    dnd_tabaxi: { name: 'Tabaxi', color: '#ffb74d', icon: '🐱', description: 'Cat-like humanoids driven by curiosity.' },
    dnd_kenku: { name: 'Kenku', color: '#212121', icon: '🐦', description: 'Flightless bird-folk who speak only in mimicry.' },
    dnd_tortle: { name: 'Tortle', color: '#558b2f', icon: '🐢', description: 'Nomadic tortoise-folk who carry their homes on their backs.' },
    dnd_triton: { name: 'Triton', color: '#00acc1', icon: '🔱', description: 'Guardians of the deep ocean trenches.' },
    dnd_firbolg: { name: 'Firbolg', color: '#a1887f', icon: '🌲', description: 'Gentle giants of the forest who prefer peace.' },
    
    // === SPECIAL REQUESTS (Reduced) ===
    centaur_human_head: { name: 'Centaur (Classic)', color: '#8d6e63', icon: '🐎', description: 'The classic centaur: human torso and head on a horse body. Noble and proud.' },
    centaur_horse_head: { name: 'Centaur (Equine)', color: '#5d4037', icon: '🐴', description: 'A terrifying anomaly: A horse torso and body, with a horse head where the human torso should be.' },
    
    // === MARIO WORLD ===
    toad_citizen: { name: 'Toad', color: '#ff6b6b', icon: '🍄', description: 'The peaceful, fungal-capped citizens of the Mushroom Kingdom.' },
    koopa: { name: 'Koopa', color: '#ffd93d', icon: '🐢', description: 'Turtle-like creatures that form the backbone of Bowser\'s army.' },
    goomba: { name: 'Goomba', color: '#8d6e63', icon: '😠', description: 'Small, mushroom-like creatures with a grumpy disposition.' },
    yoshi: { name: 'Yoshi', color: '#76ff03', icon: '🦖', description: 'Friendly, dinosaur-like omnivores from Yoshi\'s Island.' },
    pianta: { name: 'Pianta', color: '#f48c06', icon: '🌴', description: 'Strong, tree-loving islanders from the Sunshine Isles.' },
    noki: { name: 'Noki', color: '#4fc3f7', icon: '🐚', description: 'Shell-dwelling islanders often found near coral reefs.' },
    shy_guy: { name: 'Shy Guy', color: '#ef5350', icon: '🎭', description: 'Masked, mysterious minions who serve various masters.' },
    bob_omb: { name: 'Bob-omb', color: '#212121', icon: '💣', description: 'Living explosives with a short fuse and shorter temper.' },
    monty_mole: { name: 'Monty Mole', color: '#795548', icon: '👓', description: 'Subterranean pests that ambush travelers.' },

    // === THE MIDLANDS ===
    regal_midlander: { name: 'Regal Midlander', color: '#ffadad', icon: '🧑', description: 'The dominant human culture of the Midlands, known for discipline and ambition.' },
    moonfang_werewolf: { name: 'Werewolf', color: '#ffd6a5', icon: '🐺', description: 'Lycanthropes bound to the lunar cycle and pack hierarchy.' },
    elder_vampire: { name: 'Vampire', color: '#e4c1f9', icon: '🧛', description: 'Ancient, powerful undead aristocrats who feed on the living.' },
    midlands_orc: { name: 'Orc (Midlands)', color: '#2d6a4f', icon: '👹', description: 'Brutish warriors of the Wilderlands who live for battle.' },
    rakasha_hunter: { name: 'Rakasha', color: '#f0c69d', icon: '🐅', description: 'Proud, cat-like beastfolk who value honor and nature.' },
    midlands_goblin: { name: 'Goblin (Scrapper)', color: '#aed581', icon: '👺', description: 'Scrappy scavengers and mechanics of the Ratchet Raiders.' },
    skeleton_warrior: { name: 'Skeleton', color: '#cfd8dc', icon: '💀', description: 'Animated remains serving necromancers or ancient curses.' },
    ghost_spirit: { name: 'Spirit', color: '#b3e5fc', icon: '👻', description: 'Restless souls bound to the mortal plane.' },

    // === WARHAMMER (THE FATED PLACE) ===
    warhammer_human: { name: 'Empire Human', color: '#c81d25', icon: '⚔️', description: 'Hardy humans of the Old World, beset by chaos on all sides.' },
    skaven: { name: 'Skaven', color: '#70e000', icon: '🐀', description: 'Insidious rat-men who dwell in the Under-Empire.' },
    warhammer_dwarf: { name: 'Dwarf (Old World)', color: '#0077b6', icon: '🛡️', description: 'Grudge-bearing mountain dwellers and master smiths.' },
    warhammer_orc: { name: 'Greenskin', color: '#38b000', icon: '🤮', description: 'Savage orcs living for the WAAAGH!' },
    warhammer_elf: { name: 'High Elf', color: '#caf0f8', icon: '✨', description: 'Arrogant masters of magic from Ulthuan.' },
    beastman: { name: 'Beastman', color: '#5d4037', icon: '🐐', description: 'Twisted children of Chaos who haunt the deep woods.' },
    chaos_warrior: { name: 'Chaos Warrior', color: '#263238', icon: '🛡️', description: 'Heavily armored humans sworn to the Dark Gods.' },
    lizardman: { name: 'Lizardman', color: '#00bcd4', icon: '🦎', description: 'Cold-blooded guardians of the Great Plan.' },

    // === MIDDLE-EARTH ===
    gondorian: { name: 'Man of Gondor', color: '#e0e0e0', icon: '🏰', description: 'Noble descendants of Numenor guarding the White City.' },
    rohirrim: { name: 'Rohirrim', color: '#81c784', icon: '🐎', description: 'Horse-lords of the grassy plains.' },
    middle_earth_elf: { name: 'Elf (Middle-earth)', color: '#ffd700', icon: '🧝', description: 'Immortal beings of starlight, song, and sorrow.' },
    middle_earth_dwarf: { name: 'Dwarf (Durin\'s Folk)', color: '#a9a9a9', icon: '⛏️', description: 'Miners and smiths of Erebor and the Iron Hills.' },
    uruk_hai: { name: 'Uruk-hai', color: '#3e2723', icon: '🤚', description: 'A superior breed of Orc created for war.' },
    mordor_orc: { name: 'Orc (Mordor)', color: '#5c4d3c', icon: '👺', description: 'Corrupted servants of the Dark Lord.' },
    hobbit: { name: 'Hobbit', color: '#8ab17d', icon: '🦶', description: 'Small, comfort-loving folk of the Shire.' },
    ent: { name: 'Ent', color: '#33691e', icon: '🌳', description: 'Ancient tree-shepherds of Fangorn Forest.' },
    cave_troll: { name: 'Troll', color: '#616161', icon: '🧌', description: 'Huge, dim-witted creatures of stone and darkness.' },

    // === KIVOTOS ===
    kivotos_human: { name: 'Student (Human)', color: '#4a86e8', icon: '👩‍🎓', description: 'Ordinary students wielding extraordinary firepower.' },
    kivotos_angel: { name: 'Student (Angel)', color: '#fff9c4', icon: '😇', description: 'Halo-bearing students, often from Trinity.' },
    kivotos_demon: { name: 'Student (Demon)', color: '#ef9a9a', icon: '😈', description: 'Horned and tailed students, often from Gehenna.' },
    kivotos_beastkin: { name: 'Student (Beastkin)', color: '#ffcc80', icon: '🦊', description: 'Students with animal traits like ears or tails.' },
    kivotos_robot: { name: 'Automata', color: '#999999', icon: '🤖', description: 'Robotic citizens and combat units of Kivotos.' },

    // === POKEMON REGIONS ===
    pokemon_human: { name: 'Human (Trainer)', color: '#ff0000', icon: '🧢', description: 'Humans who live, work, and battle alongside Pokémon.' },
    grass_pokemon: { name: 'Pokémon (Grass)', color: '#78c850', icon: '🌿', description: 'Pokémon with an affinity for nature and plants.' },
    fire_pokemon: { name: 'Pokémon (Fire)', color: '#f08030', icon: '🔥', description: 'Pokémon that command the power of flame.' },
    water_pokemon: { name: 'Pokémon (Water)', color: '#6890f0', icon: '💧', description: 'Pokémon adapted to aquatic environments.' },
    electric_pokemon: { name: 'Pokémon (Electric)', color: '#f8d030', icon: '⚡', description: 'Pokémon that generate and store electricity.' },
    normal_pokemon: { name: 'Pokémon (Normal)', color: '#a8a878', icon: '⚪', description: 'Versatile Pokémon adaptable to many environments.' },
    ghost_pokemon: { name: 'Pokémon (Ghost)', color: '#705898', icon: '👻', description: 'Spectral Pokémon with mischievous or spooky natures.' },
    dark_pokemon: { name: 'Pokémon (Dark)', color: '#705848', icon: '🌑', description: 'Pokémon known for their cunning and night-time activity.' },
    psychic_pokemon: { name: 'Pokémon (Psychic)', color: '#f85888', icon: '🔮', description: 'Pokémon with powerful mental abilities.' },
    fighting_pokemon: { name: 'Pokémon (Fighting)', color: '#c03028', icon: '🥊', description: 'Pokémon dedicated to martial arts and physical prowess.' },
    steel_pokemon: { name: 'Pokémon (Steel)', color: '#b8b8d0', icon: '🔩', description: 'Pokémon with bodies of hardened metal.' },
    fairy_pokemon: { name: 'Pokémon (Fairy)', color: '#ee99ac', icon: '🧚', description: 'Cute but powerful Pokémon with magical affinity.' },
    dragon_pokemon: { name: 'Pokémon (Dragon)', color: '#7038f8', icon: '🐉', description: 'Draconic Pokémon of immense power.' },
    bug_pokemon: { name: 'Pokémon (Bug)', color: '#a8b820', icon: '🪲', description: 'Insectoid Pokémon found in forests and fields.' },
    ice_pokemon: { name: 'Pokémon (Ice)', color: '#98d8d8', icon: '❄️', description: 'Pokémon adapted to freezing environments.' },
    ground_pokemon: { name: 'Pokémon (Ground)', color: '#e0c068', icon: '🏜️', description: 'Pokémon with a deep connection to the earth.' },
    rock_pokemon: { name: 'Pokémon (Rock)', color: '#b8a038', icon: '🪨', description: 'Sturdy Pokémon made of rock and stone.' },
    flying_pokemon: { name: 'Pokémon (Flying)', color: '#a890f0', icon: '🕊️', description: 'Pokémon capable of flight, ruling the skies.' },
    poison_pokemon: { name: 'Pokémon (Poison)', color: '#a040a0', icon: '☠️', description: 'Pokémon that use toxins for defense and offense.' },
    legendary_pokemon: { name: 'Pokémon (Legendary)', color: '#ffd700', icon: '✨', description: 'Rare and powerful Pokémon of myth and legend.' },

    // === THE INTERNET ===
    netizen: { name: 'Netizen', color: '#00ffff', icon: '🌐', description: 'Digital avatars representing users in the data-stream.' },
    spam_bot: { name: 'Spam Bot', color: '#ffc107', icon: '📧', description: 'Annoying, self-replicating constructs selling nonsense.' },
    living_meme: { name: 'Living Meme', color: '#00e676', icon: '🐸', description: 'Information entities that evolve through viral spread.' },
    virus_entity: { name: 'Virus', color: '#d500f9', icon: '🦠', description: 'Malicious code given form, seeking to corrupt data.' },
    moderator_construct: { name: 'Moderator', color: '#304ffe', icon: '🛡️', description: 'Enforcers of the Terms of Service.' },

    // === ANIMATOPIA ===
    fox_folk: { name: 'Fox', color: '#e65100', icon: '🦊', description: 'Cunning and adaptable canids.' },
    rabbit_folk: { name: 'Rabbit', color: '#bdbdbd', icon: '🐰', description: 'Fast, prolific, and generally peaceful lagomorphs.' },
    lion_folk: { name: 'Lion', color: '#fbc02d', icon: '🦁', description: 'Proud felines often found in leadership roles.' },
    sheep_folk: { name: 'Sheep', color: '#f5f5f5', icon: '🐑', description: 'Community-minded herbivores with soft wool.' },
    sloth_folk: { name: 'Sloth', color: '#8d6e63', icon: '🦥', description: 'Slow-moving but thoughtful arboreal mammals.' },
    bear_folk: { name: 'Bear', color: '#3e2723', icon: '🐻', description: 'Strong and solitary omnivores.' },

    // === EQUESTRIA (Expanded) ===
    earth_pony: { name: 'Earth Pony', color: '#8d6e63', icon: '🐴', description: 'Strong, dependable ponies with a deep connection to the land.' },
    pegasus: { name: 'Pegasus', color: '#4fc3f7', icon: '🪽', description: 'Winged ponies who manage the weather and serve as the aerial military.' },
    unicorn: { name: 'Unicorn', color: '#e1bee7', icon: '🦄', description: 'Magic-wielding ponies who form the scholarly and noble classes.' },
    crystal_pony: { name: 'Crystal Pony', color: '#e0f7fa', icon: '💎', description: 'Ancient ponies from the Crystal Empire, radiating hope and light.' },
    bat_pony: { name: 'Thestral (Bat Pony)', color: '#424242', icon: '🦇', description: 'Nocturnal ponies with leathery wings, often serving in the Royal Guard.' },
    changeling_reformed: { name: 'Changeling (Reformed)', color: '#81c784', icon: '🦟', description: 'Metamorphosing insectoid creatures who now share love rather than stealing it.' },
    kirin: { name: 'Kirin', color: '#ffcc80', icon: '🔥', description: 'Reclusive, draconic ponies who can burst into flames when angered.' },
    griffon: { name: 'Griffon', color: '#ffca28', icon: '🦅', description: 'Proud, eagle-lion hybrids from Griffonstone.' },
    yak: { name: 'Yak', color: '#5d4037', icon: '🐂', description: 'Large, powerful bovine creatures from the frozen north of Yakyakistan.' },
    hippogriff: { name: 'Hippogriff/Seapony', color: '#ec407a', icon: '🌊', description: 'Transforming creatures who dwell on Mt. Aris and in Seaquestria.' },

    // === TEYVAT (Expanded Lore) ===
    teyvat_human: { name: 'Human (Teyvat)', color: '#ffca3a', icon: '⚖️', description: 'The primary populace of the seven nations.' },
    hilichurl: { name: 'Hilichurl', color: '#5d4037', icon: '🎭', description: 'Tribal monsters found across the wilderness, remnants of a lost civilization.' },
    adeptus: { name: 'Adeptus', color: '#00bfa5', icon: '🐉', description: 'Illuminated beasts and demigods of Liyue, bound by contract to protect the harbor.' },
    youkai_inazuma: { name: 'Youkai', color: '#ab47bc', icon: '👺', description: 'Supernatural beings of Inazuma, including Kitsune, Oni, and Tengu.' },
    fontainian: { name: 'Fontainian', color: '#42a5f5', icon: '💧', description: 'Humans of Fontaine, born from the oceanid\'s power and water.' },
    melusine: { name: 'Melusine', color: '#f48fb1', icon: '🐌', description: 'Small, aquatic beings from Fontaine with keen sight and a unique perspective.' },
    aranara: { name: 'Aranara', color: '#76ff03', icon: '🌱', description: 'Small, plant-like forest spirits of Sumeru, usually invisible to adults.' },
    abyss_order: { name: 'Abyss Creature', color: '#6200ea', icon: '🧙‍♂️', description: 'Corrupted beings of the Void seeking to overthrow the divine throne.' },
    elemental_lifeform: { name: 'Elemental', color: '#29b6f6', icon: '✨', description: 'Pure elemental lifeforms like Slimes, Hypostases, and Specters.' },

    // === FAERUN (Expanded D&D) ===
    faerun_human: { name: 'Human (Realms)', color: '#cdb4db', icon: '🧑‍🤝‍🧑', description: 'The adaptable and numerous humans of Toril.' },
    faerun_elf: { name: 'Elf (Realms)', color: '#bde0fe', icon: '🧝‍♀️', description: 'Long-lived beings of magic and grace.' },
    faerun_dwarf: { name: 'Dwarf (Realms)', color: '#607d8b', icon: '⛏️', description: 'Stout warriors and master craftsmen.' },
    faerun_halfling: { name: 'Halfling (Realms)', color: '#ffcc80', icon: '🍞', description: 'Small, lucky folk who value home and hearth.' },
    faerun_gnome: { name: 'Gnome (Realms)', color: '#ba68c8', icon: '⚙️', description: 'Inventive and inquisitive small folk.' },
    faerun_tiefling: { name: 'Tiefling (Realms)', color: '#ff5252', icon: '😈', description: 'Heirs to an infernal bloodline.' },
    faerun_dragonborn: { name: 'Dragonborn (Realms)', color: '#d4af37', icon: '🐲', description: 'Honor-bound warriors of draconic descent.' },
    faerun_drow: { name: 'Drow (Realms)', color: '#212121', icon: '🕷️', description: 'Dark elves of the Underdark.' },
    faerun_tabaxi: { name: 'Tabaxi', color: '#ffb74d', icon: '🐆', description: 'Cat-like wanderers driven by curiosity.' },
    faerun_genasi: { name: 'Genasi', color: '#00bcd4', icon: '🔥', description: 'Those who carry the blood of the elemental planes.' },
    faerun_aasimar: { name: 'Aasimar', color: '#e0f7fa', icon: '👼', description: 'Humans with a touch of celestial power.' },
    faerun_tortle: { name: 'Tortle', color: '#558b2f', icon: '🐢', description: 'Nomadic tortoise-folk.' },
    faerun_firbolg: { name: 'Firbolg', color: '#a1887f', icon: '🌲', description: 'Reclusive forest guardians.' },
    faerun_goliath: { name: 'Goliath', color: '#90a4ae', icon: '🏔️', description: 'Strong folk from the highest mountain peaks.' },

    // === CONNECTOPIA ===
    block_folk: { name: 'Block Folk', color: '#795548', icon: '🟦', description: 'Pixelated humanoids who build and craft.' },
    creeper_kind: { name: 'Exploder', color: '#43a047', icon: '🟩', description: 'Silent, green creatures that explode near others.' },
    ender_kind: { name: 'Void Walker', color: '#311b92', icon: '👁️', description: 'Tall, dark figures that teleport and steal blocks.' },

    // === EARTH LAND ===
    earth_land_mage: { name: 'Mage', color: '#f4a261', icon: '🔥', description: 'Humans capable of wielding magic.' },
    exceed: { name: 'Exceed', color: '#90caf9', icon: '😺', description: 'Winged cats from another dimension.' },
    celestial_spirit: { name: 'Celestial Spirit', color: '#ffd700', icon: '🔑', description: 'Beings from the Spirit World summoned by keys.' },
    vulcan: { name: 'Vulcan', color: '#f44336', icon: '🦍', description: 'Monstrous ape-like creatures that inhabit mountains.' },

    // === L'ECLAIRE ISLE (The Originals) ===
    dough_glazed: { name: 'Dough Folk (Glazed)', color: '#f4d35e', icon: '🍩', description: 'The ruling class of sweet, shiny original inhabitants.' },
    dough_cake: { name: 'Dough Folk (Cake)', color: '#8d6e63', icon: '🍰', description: 'Dense, hardy folk often found in construction.' },
    dough_jelly: { name: 'Dough Folk (Jelly)', color: '#e91e63', icon: '🍓', description: 'Volatile and energetic, filled with sweet potential.' },
    dough_cruller: { name: 'Dough Folk (Cruller)', color: '#d7ccc8', icon: '🥨', description: 'Twisted, complex thinkers and philosophers.' },
    dough_croissant: { name: 'Pastry-Kin (Croissant)', color: '#ffecb3', icon: '🥐', description: 'Flaky, layered aristocrats.' },
    frosting_slime: { name: 'Frosting Slime', color: '#f06292', icon: '🧁', description: 'Semi-sentient blobs of animated sugar.' },
    candy_construct: { name: 'Candy Golem', color: '#e91e63', icon: '🍭', description: 'Hard-candy constructs serving as guards.' },

    // === THE DOUGHNUT HOLE & THE EDGE ===
    void_entity: { name: 'Void Entity', color: '#000000', icon: '🌑', description: 'Beings composed of emptiness and cosmic dust.' },
    cosmic_entity: { name: 'Cosmic Entity', color: '#9d4edd', icon: '🌌', description: 'Beings of pure energy and starlight.' },
    fractal_being: { name: 'Fractal Being', color: '#6200ea', icon: '💠', description: 'Lifeforms based on repeating mathematical patterns.' },
    time_echo: { name: 'Time Echo', color: '#bdbdbd', icon: '⏳', description: 'Residual images of beings from other timelines.' },
    logic_crystal: { name: 'Logic Crystal', color: '#00e5ff', icon: '💎', description: 'Sentient mineral structures seeking order.' },
    null_texture: { name: 'Null Texture', color: '#ff00ff', icon: '🔲', description: 'Entities missing their visual data, appearing as magenta checkers.' },
    wireframe_husk: { name: 'Wireframe', color: '#00ff00', icon: '🕸️', description: 'Creatures reduced to their structural geometry.' },
    glitch_ghost: { name: 'Glitch Ghost', color: '#ffffff', icon: '🌫️', description: 'Fragmented data haunting the edge of reality.' },

    // === CATCH-ALL ===
    other: { name: 'Other / Unknown', color: '#6c757d', icon: '❓', description: 'Unclassified, unique, or minor species.' }
};

export const REGIONAL_DEMOGRAPHICS = {
    'Mushroom Kingdom Regions': { toad_citizen: 0.55, goomba: 0.15, koopa: 0.10, yoshi: 0.05, bob_omb: 0.05, shy_guy: 0.05, dnd_human: 0.05 },
    'Islands & Outer Realms': { pianta: 0.30, noki: 0.20, yoshi: 0.30, koopa: 0.10, monty_mole: 0.05, dnd_triton: 0.05 },
    'The Midlands': { regal_midlander: 0.45, dnd_human: 0.15, moonfang_werewolf: 0.10, elder_vampire: 0.05, midlands_orc: 0.05, rakasha_hunter: 0.05, midlands_goblin: 0.05, skeleton_warrior: 0.05, ghost_spirit: 0.03, centaur_human_head: 0.02 },
    'The Fated Place': { warhammer_human: 0.30, skaven: 0.15, warhammer_orc: 0.15, warhammer_dwarf: 0.10, warhammer_elf: 0.05, beastman: 0.05, chaos_warrior: 0.05, lizardman: 0.05, dnd_goblin: 0.05, dnd_halfling_stout: 0.05 },
    'Middle-earth': { gondorian: 0.25, rohirrim: 0.15, middle_earth_elf: 0.10, middle_earth_dwarf: 0.10, hobbit: 0.05, mordor_orc: 0.20, uruk_hai: 0.10, ent: 0.02, cave_troll: 0.03 },
    'Kivotos': { kivotos_human: 0.40, kivotos_angel: 0.20, kivotos_demon: 0.20, kivotos_beastkin: 0.10, kivotos_robot: 0.10 },
    'Pokémon Regions': { 
        pokemon_human: 0.20, 
        normal_pokemon: 0.12, 
        water_pokemon: 0.12, 
        grass_pokemon: 0.10, 
        flying_pokemon: 0.08,
        bug_pokemon: 0.08,
        fire_pokemon: 0.05,
        electric_pokemon: 0.05,
        rock_pokemon: 0.04,
        ground_pokemon: 0.04,
        poison_pokemon: 0.04,
        fighting_pokemon: 0.02,
        psychic_pokemon: 0.02,
        dark_pokemon: 0.01,
        steel_pokemon: 0.01,
        fairy_pokemon: 0.01,
        ice_pokemon: 0.01
    },
    'The Internet': { netizen: 0.40, spam_bot: 0.25, living_meme: 0.15, virus_entity: 0.10, moderator_construct: 0.10 },
    'The Doughnut Hole': { void_entity: 0.30, cosmic_entity: 0.20, fractal_being: 0.15, time_echo: 0.15, logic_crystal: 0.10, dnd_goliath: 0.10 },
    'Animatopia': { rabbit_folk: 0.30, sheep_folk: 0.20, fox_folk: 0.15, lion_folk: 0.10, sloth_folk: 0.10, bear_folk: 0.10, dnd_tabaxi: 0.05 },
    'The Edge Regions': { null_texture: 0.40, wireframe_husk: 0.25, glitch_ghost: 0.20, void_entity: 0.10, dnd_genasi_water: 0.05 },
    'Connectopia': { block_folk: 0.70, creeper_kind: 0.15, ender_kind: 0.10, dnd_dwarf_mountain: 0.05 },
    'Earth Land': { earth_land_mage: 0.60, exceed: 0.20, celestial_spirit: 0.10, vulcan: 0.05, dnd_genasi_fire: 0.05 },
    'Faerûn': { faerun_human: 0.25, faerun_elf: 0.15, faerun_dwarf: 0.10, faerun_halfling: 0.10, faerun_gnome: 0.05, faerun_tiefling: 0.05, faerun_dragonborn: 0.05, faerun_drow: 0.05, faerun_tabaxi: 0.05, faerun_genasi: 0.05, faerun_aasimar: 0.05, faerun_goliath: 0.05 },
    'L\'Eclaire Isle': { dough_glazed: 0.30, dough_cake: 0.20, dough_jelly: 0.15, dough_cruller: 0.10, dough_croissant: 0.10, frosting_slime: 0.10, candy_construct: 0.05 },
    'Teyvat': { teyvat_human: 0.60, hilichurl: 0.15, fontainian: 0.10, melusine: 0.05, youkai_inazuma: 0.05, adeptus: 0.02, abyss_mage: 0.03 },
    'Equestria': { earth_pony: 0.30, pegasus: 0.25, unicorn: 0.20, crystal_pony: 0.10, bat_pony: 0.05, changeling_reformed: 0.05, kirin: 0.02, griffon: 0.02, yak: 0.01 },
};
