#!/usr/bin/env python3
"""dedupe-images.py — one file per image: exact duplicates collapsed, references repointed.

The archive grew copies of the same bytes under different names
(`portraits/toriel.jpg` / `toriel_v2.jpg` / `lady_toriel.jpg`, `bones.png` /
`bones_scene.png`, the same still in `assets/` and `Reputation-Matrix2/assets/`).
Byte-identical files are found by SHA-256 under the image roots, every text
source that names one of them is read (JSON data, HTML, JS, CSS, Markdown,
the actor mirror — never the generated files), the copy most records use
becomes the keeper, the other references are rewritten to it, and the spare
files are deleted. Then the generated files are rebuilt by their own tools
(`tools/build-chatroom.py`, `tools/sheets-suite.py`).

What is never deleted
  * `assets/images/toads/roster/` — the liberated toads' art is left alone;
  * a `.png` whose stem is an id the site looks up dynamically
    (`portraits/${id}.png` in index.html, the profile / family-tree / map
    pages): the stem appears as a quoted token in the data or the app code.
    Two such files with the same bytes both stay (reported);
  * a file whose only duplicates are the protected kind.

    python3 tools/dedupe-images.py              # report: groups, keepers, what would change
    python3 tools/dedupe-images.py --write      # repoint + delete, then rebuild the generated files yourself
    python3 tools/dedupe-images.py --check      # exit 1 when a deletable duplicate exists (tools/check-all.py)

Only exact duplicates (same bytes) are touched: a re-render, a crop or a
re-encode is a different file and stays. The report lists every group so a
human can still decide to keep a "duplicate" under its own name — move it
out of the roots or give it different bytes, and the tool leaves it.
"""
from __future__ import annotations

import argparse
import hashlib
import os
import re
import subprocess
import sys
import urllib.parse

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RM = os.path.join(ROOT, "Reputation-Matrix2")
IMAGE_ROOTS = ("Reputation-Matrix2/portraits", "Reputation-Matrix2/assets", "Reputation-Matrix2/images", "assets")
PROTECTED_DIRS = ("Reputation-Matrix2/assets/images/toads/roster",)
IMAGE_EXTS = {".png", ".webp", ".jpg", ".jpeg", ".gif", ".svg", ".avif"}
TEXT_EXTS = {".json", ".html", ".js", ".mjs", ".css", ".md", ".txt", ".py", ".yml", ".yaml", ".csv", ".hbs", ".ts", ".tsx", ".svg", ".bat"}
# generated by other tools from the sources this script rewrites — rebuilt, never edited
GENERATED = ("chatroom.html", "workflow/roleplay.html", "Reputation-Matrix2/data/sheets.json", "Reputation-Matrix2/actors/cast/")
SKIP_DIRS = ("node_modules/", ".git/", "Reputation-Matrix2/Foundry/mass_import.zip")
# where a dynamic `portraits/${id}.png` lookup may come from: ids quoted in the data and the app
ID_SOURCES = ("Reputation-Matrix2/data", "Reputation-Matrix2/app", "index.html", "Reputation-Matrix2/index.html")
VERSION_SUFFIX = re.compile(r"(_v\d+|_scene|_old|_alt|_copy|\s*\(\d+\))$", re.I)


def rel(path):
    return os.path.relpath(path, os.path.realpath(ROOT)).replace(os.sep, "/")


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def tracked_files():
    try:
        # Tracked + untracked-but-not-ignored, minus what is deleted in the
        # working tree: a mirror the organizer just re-filed (files moved,
        # nothing committed yet) must still check cleanly.
        out = subprocess.run(["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard"],
                             cwd=ROOT, capture_output=True, check=True).stdout
        return [p for p in out.decode("utf-8", "surrogateescape").split("\0")
                if p and os.path.exists(os.path.join(ROOT, p))]
    except (OSError, subprocess.CalledProcessError):
        files = []
        for dirpath, dirnames, names in os.walk(ROOT):
            dirnames[:] = [d for d in dirnames if d not in ("node_modules", ".git")]
            files += [rel(os.path.join(dirpath, n)) for n in names]
        return files


def image_groups(files):
    """{sha: [rel paths]} for the images under IMAGE_ROOTS, duplicates only."""
    by_hash = {}
    for p in files:
        if not p.startswith(tuple(r + "/" for r in IMAGE_ROOTS)) or os.path.splitext(p)[1].lower() not in IMAGE_EXTS:
            continue
        full = os.path.join(ROOT, p)
        if not os.path.isfile(full):
            continue
        by_hash.setdefault((sha256(full), os.path.getsize(full)), []).append(p)
    return {k: sorted(v) for k, v in by_hash.items() if len(v) > 1}


def text_sources(files):
    for p in files:
        if os.path.splitext(p)[1].lower() not in TEXT_EXTS or p.startswith(SKIP_DIRS) or p.startswith(GENERATED) or p in GENERATED:
            continue
        if p == rel(os.path.abspath(__file__)):
            continue
        yield p


def read_text(p):
    with open(os.path.join(ROOT, p), "rb") as fh:
        raw = fh.read()
    try:
        return raw.decode("utf-8")
    except UnicodeDecodeError:
        return None


def id_tokens():
    """Every quoted [a-z0-9_]+ token in the data and app sources — the ids a dynamic portrait lookup could use."""
    toks = set()
    pat = re.compile(r"""["']([a-z0-9][a-z0-9_]{1,80})["']""")
    for base in ID_SOURCES:
        full = os.path.join(ROOT, base)
        paths = [full] if os.path.isfile(full) else [os.path.join(d, n) for d, _, ns in os.walk(full) for n in ns if os.path.splitext(n)[1] in (".json", ".js", ".html", ".mjs")]
        for path in paths:
            try:
                with open(path, encoding="utf-8", errors="ignore") as fh:
                    toks.update(pat.findall(fh.read()))
            except OSError:
                continue
    return toks


def protected(p, ids):
    if p.startswith(tuple(d + "/" for d in PROTECTED_DIRS)):
        return "liberated toads' roster art — never modified"
    stem, ext = os.path.splitext(os.path.basename(p))
    if ext.lower() == ".png" and stem in ids:
        return f"`{stem}` is an id the site may look up as portraits/{stem}.png"
    return None


def resolve(ref, from_file):
    """A path as written in a source -> the repo file it names (rel) and how it resolved, or (None, None)."""
    clean = urllib.parse.unquote(ref.split("?")[0].split("#")[0])
    # relative to the file first; then the tree the file lives in (a data
    # record or an app page under Reputation-Matrix2/ means the archive's
    # assets/, resolved by assetPath); then the other tree
    inside_rm = from_file.startswith("Reputation-Matrix2/")
    tries = [("file", os.path.normpath(os.path.join(ROOT, os.path.dirname(from_file), clean)))]
    tries += [("rm", os.path.normpath(os.path.join(RM, clean.lstrip("/")))), ("root", os.path.normpath(os.path.join(ROOT, clean.lstrip("/"))))][:: 1 if inside_rm else -1]
    for mode, cand in tries:
        if os.path.isfile(cand):
            # the root-level `portraits` is a link to Reputation-Matrix2/portraits: name the real file
            return rel(os.path.realpath(cand)), mode
    return None, None


def find_references(groups, sources):
    """{member: [(file, start, end, ref_text, mode)]} for every literal mention of a duplicate's file name."""
    by_name = {}
    for members in groups.values():
        for m in members:
            by_name.setdefault(os.path.basename(m), set()).add(m)
    if not by_name:
        return {}
    names = sorted(by_name, key=len, reverse=True)
    alt = "|".join(re.escape(n) for n in names) + "|" + "|".join(re.escape(urllib.parse.quote(n)) for n in names if urllib.parse.quote(n) != n)
    pat = re.compile(r"(?<![A-Za-z0-9_.%-])((?:[A-Za-z0-9_.%()\-]+/)*)(" + alt + r")(?![A-Za-z0-9_])")
    refs = {}
    for src in sources:
        text = read_text(src)
        if text is None:
            continue
        for m in pat.finditer(text):
            ref = m.group(1) + m.group(2)
            target, mode = resolve(ref, src)
            if target is None or target not in by_name.get(urllib.parse.unquote(m.group(2)), set()) and target not in by_name.get(m.group(2), set()):
                continue
            refs.setdefault(target, []).append((src, m.start(), m.end(), ref, mode))
    return refs


def choose_keeper(members, refs, ids):
    """(keeper, deletable, kept_protected)."""
    prot = {m: protected(m, ids) for m in members}
    def score(m):
        # most referenced; then the plain name over `_v2` / `_scene`; then the
        # archive's own tree over the root copy; then the shorter, then a-z
        stem = os.path.splitext(os.path.basename(m))[0]
        return (len(refs.get(m, [])), -bool(VERSION_SUFFIX.search(stem)), m.startswith("Reputation-Matrix2/"), -len(stem), [-ord(c) for c in m])
    protected_members = [m for m in members if prot[m]]
    free = [m for m in members if not prot[m]]
    pool = protected_members or free
    keeper = max(pool, key=score)
    deletable = [m for m in free if m != keeper]
    kept = [(m, prot[m]) for m in protected_members if m != keeper]
    return keeper, deletable, kept


def rewrite_ref(ref, old, keeper):
    """The text that names `keeper` the way `ref` named `old`: the directory
    part of the reference is kept as written (`portraits/x.png` stays
    RM-relative, `../portraits/x.png` stays relative to its page) and only the
    step from the old file to the keeper is applied — a bare swap of the file
    name when both sit in one directory."""
    clean = urllib.parse.unquote(ref)
    encoded = clean != ref
    step = os.path.relpath(os.path.join(ROOT, keeper), os.path.join(ROOT, os.path.dirname(old))).replace(os.sep, "/")
    head = clean.rsplit("/", 1)[0] + "/" if "/" in clean else ""
    new = os.path.normpath(head + step).replace(os.sep, "/") if head else step
    if clean.startswith("./") and not new.startswith("."):
        new = "./" + new
    if clean.startswith("/") and not new.startswith("/"):
        new = "/" + new
    return urllib.parse.quote(new, safe="/") if encoded else new


def plan(files=None):
    files = files or tracked_files()
    groups = image_groups(files)
    ids = id_tokens()
    refs = find_references(groups, list(text_sources(files)))
    rows = []
    for key, members in sorted(groups.items(), key=lambda kv: kv[1][0]):
        keeper, deletable, kept = choose_keeper(members, refs, ids)
        edits = []
        for m in deletable:
            for src, start, end, ref, mode in refs.get(m, []):
                edits.append((src, start, end, ref, rewrite_ref(ref, m, keeper)))
        rows.append({"members": members, "keeper": keeper, "deletable": deletable, "kept": kept, "bytes": key[1],
                     "refs": {m: len(refs.get(m, [])) for m in members}, "edits": edits})
    return rows


def apply(rows):
    """Rewrite the sources (right-to-left per file so offsets hold), delete the spare files."""
    per_file = {}
    for r in rows:
        for src, start, end, old, new in r["edits"]:
            per_file.setdefault(src, []).append((start, end, old, new))
    for src, edits in per_file.items():
        text = read_text(src)
        for start, end, old, new in sorted(edits, key=lambda e: -e[0]):
            assert text[start:end] == old, (src, start, old, text[start:end])
            text = text[:start] + new + text[end:]
        with open(os.path.join(ROOT, src), "wb") as fh:
            fh.write(text.encode("utf-8"))
    removed = []
    for r in rows:
        for m in r["deletable"]:
            full = os.path.join(ROOT, m)
            if os.path.exists(full):
                os.remove(full)
                removed.append(m)
    return per_file, removed


def report(rows, verbose=True):
    deletable = [m for r in rows for m in r["deletable"]]
    freed = sum(r["bytes"] * len(r["deletable"]) for r in rows)
    edits = sum(len(r["edits"]) for r in rows)
    if verbose:
        for r in rows:
            short = lambda p: p.replace("Reputation-Matrix2/", "RM/")
            print(f"  keep {short(r['keeper'])} ({r['refs'][r['keeper']]} ref)")
            for m in r["deletable"]:
                print(f"    - delete {short(m)} ({r['refs'][m]} ref -> repointed)")
            for m, why in r["kept"]:
                print(f"    = keep   {short(m)} ({r['refs'][m]} ref): {why}")
    print(f"dedupe-images: {len(rows)} duplicate group(s); {len(deletable)} file(s) to delete ({freed / 1e6:.1f} MB), "
          f"{edits} reference(s) to repoint, {sum(len(r['kept']) for r in rows)} protected copy(ies) kept")
    return deletable, edits


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0], formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", action="store_true", help="repoint the references and delete the spare files")
    ap.add_argument("--check", action="store_true", help="exit 1 when a deletable duplicate exists")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args(argv)
    rows = plan()
    if args.check:
        deletable, _ = report(rows, verbose=not args.quiet)
        if deletable:
            print("FAIL dedupe-images: duplicate images with references to repoint — run tools/dedupe-images.py --write, then tools/build-chatroom.py and tools/sheets-suite.py")
            return 1
        print("OK dedupe-images: no deletable duplicate images")
        return 0
    deletable, edits = report(rows, verbose=not args.quiet)
    if not args.write:
        if deletable:
            print("(report only — --write applies it; then run tools/build-chatroom.py and tools/sheets-suite.py to rebuild the generated files)")
        return 0
    per_file, removed = apply(rows)
    print(f"dedupe-images: rewrote {len(per_file)} file(s), deleted {len(removed)} image(s) — now rebuild: python3 tools/build-chatroom.py && python3 tools/sheets-suite.py --no-publish")
    return 0


if __name__ == "__main__":
    sys.exit(main())
