#!/usr/bin/env python3
"""Cautious overnight expansion for stubs + books + timeline.

Stubs: expands `needsReview` / `autoGenerated` / short-description characters
       by pulling archive cards (lore_search) + related events, then asks LM
       Studio for a 600-1000 word Waluigi-voiced expansion. Keeps original ID,
       preserves summary, marks as expanded but leaves `needsReview` true for
       human pass.

Books: generates one new book at a time from the same lore context. Checks
       for duplicate title/id, validates against existing categories.

Timeline: proposes one historical event with full calendar audit
          (722-1040 BF, valid month/day, no duplicate title). Requires
          --allow-timeline because it is the riskiest.

All three can run together overnight, but the tool is intentionally cautious:
 - one LLM call per item, then saves immediately (crash-safe)
 - --limit, --sleep, --timeout, --dry-run
 - timeline entries are *never* auto-merged into events.json; they go to
   historicalTimeline.json with a `proposed: true` flag for the author to promote.

Usage:
  python tools/expand-waluipedia.py --stubs --dry-run --limit 3
  python tools/expand-waluipedia.py --stubs --overnight --limit 10
  python tools/expand-waluipedia.py --books --limit 1
  python tools/expand-waluipedia.py --timeline --allow-timeline --limit 1
  python tools/expand-waluipedia.py --all --overnight   # stubs+books+codex in sequence

Codex is still owned by gen-mages-guild-code.py; this tool can optionally
drive it via --codex (just shells out to that script).
"""
from __future__ import annotations
import argparse, json, re, sys, time, urllib.request, urllib.error, hashlib, subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(Path(__file__).resolve().parent))
from lore_search import cards_for_slot, format_cards, search as lore_lookup

CHAR_PATH = ROOT / "Reputation-Matrix2" / "data" / "characters.json"
BOOKS_JS  = ROOT / "Reputation-Matrix2" / "data" / "books-data.js"
TL_PATH   = ROOT / "Reputation-Matrix2" / "data" / "historicalTimeline.json"
CAL_PATH  = ROOT / "Reputation-Matrix2" / "data" / "calendarMeta.json"
CUR_PATH  = ROOT / "Reputation-Matrix2" / "data" / "currentDate.json"
MONTHS_P  = ROOT / "Reputation-Matrix2" / "data" / "calendarMonths.json"

VOICE_STUB = """You are Waluigi's archivist expanding a STUB character file. Be cautious.

Constraints:
- Keep the character's id, name, and existing summary. Do not rename.
- Expand `description` to 600-900 words, 2-4 paragraphs + 1-2 Waluigi asides. Preserve Waluigi's voice (opinionated, physical detail) but do not invent new factions, items, or timeline dates beyond what's in the archive cards. If unsure, say 'Waluigi has not yet interviewed...' rather than inventing.
- Do not contradict the provided cards. Cite no new canon dates.
- Output format:
PAGE {character name}
Then the expanded description (continuous prose, markdown allowed for ## headers). No JSON.

If you need a fact: NEED: short query
"""

VOICE_BOOK = """You are Master Scribe Inkwell cataloging ONE new book for the Grand Scriptorium.

Constraints:
- Title must be new (not in the existing 51). Pick a category from: Imperial Archive, Field Journals, WAH & Chaos, Cosmic & Star Relics, Realms & Wilds.
- 3-5 pages, each 150-250 words, Waluigi-adjacent but in Inkwell's catalog voice.
- One `effect` line (tactical insight).
- Output format:
PAGE Book Title Goes Here
Category: <one of the list>
Then page 1 text (150-250 words)
--- PAGE 2 ---
page 2 text
--- etc for 3-5 pages

If you need a fact: NEED: short query
"""

VOICE_TL = """You are the chronicle annalist proposing ONE historical timeline entry.

Constraints:
- Must fit Regal Empire Standard Calendar (722-1040 BF, 12 months, Deepwinter=35 days). Larger year = closer to now.
- Pick a year not already densely covered (audit below). Provide year, monthIndex, day, title, description (120-180 words).
- Do not duplicate existing titles. Must be plausible within filed lore (use cards). No modern slang.
- Output format (exactly):
PAGE Title of Event
Year: 9xx BF
Month: <name> <day>
Description: 120-180 words

If you need a fact: NEED: short query
"""

def load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))

def chat(base: str, model: str, messages: list, timeout: int) -> str:
    url = base.rstrip("/") + "/chat/completions"
    payload = json.dumps({"model": model, "temperature": 0.7, "max_tokens": 4096, "messages": messages}).encode()
    req = urllib.request.Request(url, data=payload, headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        data = json.loads(r.read().decode())
    return data["choices"][0]["message"]["content"]

def parse_need(q):
    qs=[]
    for line in (q or "").splitlines():
        import re as _re
        m=_re.match(r"^\s*(NEED|SEARCH)\s*:\s*(.+)$", line, _re.I)
        if m: qs.append(m.group(2).strip()[:80])
    return qs[:2]

def chat_with_need(base, model, msgs, timeout):
    raw=chat(base, model, msgs, timeout)
    needs=parse_need(raw)
    if not needs: return raw
    extra="\n".join(format_cards(lore_lookup(q, k=4)) for q in needs)
    follow=msgs+[ {"role":"assistant","content":raw}, {"role":"user","content":"Cards (do not dump files):\n"+extra+"\nNow write PAGE only."}]
    return chat(base, model, follow, timeout)

def list_models(base: str):
    try:
        with urllib.request.urlopen(base.rstrip("/")+"/models", timeout=10) as r:
            return [m.get("id") for m in json.loads(r.read().decode()).get("data") or [] if m.get("id")]
    except: return []

# --- Stubs ---

def find_stubs(limit=0):
    chars=load_json(CHAR_PATH)
    if not isinstance(chars, list): return []
    stubs=[]
    for c in chars:
        desc=c.get("description","") or ""
        if c.get("needsReview") or c.get("autoGenerated") or len(desc)<800 or "Needs Waluipedia review" in desc:
            stubs.append(c)
    # shortest first (most stubby)
    stubs.sort(key=lambda c: len(c.get("description","")))
    return stubs[:limit] if limit else stubs

def pack_stub_context(char: dict) -> str:
    title=char.get("name","") or char.get("id","")
    summary=char.get("summary","") or ""
    desc=char.get("description","")[:800]
    cards=cards_for_slot(title, summary+" "+desc)
    # related events sample?
    return f"STUB: {char.get('id')} — {title}\nSummary: {summary}\nCurrent stub excerpt: {desc[:600]}\n\nCARDS:\n{cards}\n\nCalendar: {load_json(CUR_PATH)}"

def parse_stub_page(raw: str):
    import re as _re
    m=_re.search(r'PAGE\s+(.+?)\n(.+)', raw, flags=_re.S)
    if not m: return None
    body=m.group(2).strip()
    # must be substantial
    if len(body.split()) < 200: return None
    return body

def expand_stubs(base, model, timeout, limit, dry_run, sleep):
    stubs=find_stubs(limit if limit else 0)
    if not stubs:
        print("no stubs found")
        return 0
    print(f"stubs: {len(stubs)} queued (of 26 total) — most stubby first")
    if dry_run:
        for char in stubs:
            print(f"DRY stub {char.get('id')} '{char.get('name')}' — {len((char.get('description') or '').split())} words → would expand to 600-900 words")
            print(f"  cards: {cards_for_slot(char.get('name',''), char.get('summary','') or '')[:120]}...")
        return len(stubs)
    expanded=0
    for char in stubs:
        q=pack_stub_context(char)
        prompt=q+f"\n\nExpand this stub cautiously. Keep id={char.get('id')}. Need 600-900 words."
        try:
            raw=chat_with_need(base, model, [{"role":"system","content":VOICE_STUB},{"role":"user","content":prompt}], timeout)
        except Exception as e:
            print(f"stub {char.get('id')} wait: {e}")
            time.sleep(5)
            continue
        body=parse_stub_page(raw)
        if not body:
            print(f"skip stub {char.get('id')}: unusable")
            continue
        if dry_run:
            print(f"DRY {char.get('id')} would grow {len(char.get('description','').split())} -> {len(body.split())} words")
            print(body[:400].replace("\n"," ")+"...")
            continue
        # write back
        chars=load_json(CHAR_PATH)
        for c in chars:
            if c.get("id")==char.get("id"):
                c["description"]=body
                c["expandedAt"]="overnight"
                # keep needsReview true so human still checks, but remove autoGenerated
                c.pop("autoGenerated", None)
                break
        tmp=CHAR_PATH.with_suffix(".json.tmp")
        tmp.write_text(json.dumps(chars, indent=2, ensure_ascii=False)+"\n", encoding="utf-8")
        tmp.replace(CHAR_PATH)
        print(f"expand stub {char.get('id')} {char.get('name')} ({expanded+1}/{len(stubs)}) {len(body.split())} words")
        expanded+=1
        time.sleep(sleep)
    return expanded

# --- Books ---

def load_books_js():
    txt=BOOKS_JS.read_text(encoding="utf-8")
    # window.BOOKS_DATA = { "books": [ ... ]}
    m=re.search(r'"books"\s*:\s*\[', txt)
    if not m: return [], txt
    # crude but we can eval via json extraction: find matching bracket? easier to just load via exec in python
    # Use regex to extract JSON object: from first { to last }
    start=txt.find("{", txt.find("window.BOOKS_DATA"))
    end=txt.rfind("}")
    # The file ends with "};" — json needs to be that object
    obj=json.loads(txt[start:end+1])
    return obj.get("books",[]), txt

def add_book(base, model, timeout, dry_run, sleep):
    books, raw_js = load_books_js()
    titles={b.get("title","").lower() for b in books}
    ids={b.get("id","") for b in books}
    if dry_run:
        print(f"DRY book would add 1 to {len(books)} existing (e.g. '{list(titles)[:1]}')")
        print(f"  sparse check: categories Imperial Archive/Field Journals/WAH & Chaos/Cosmic & Star Relics/Realms & Wilds")
        return 1
    # pack context: categories + a few titles
    cat_cards=cards_for_slot("Grand Scriptorium books", "Inkwell catalog Imperial Archive Field Journals WAH Chaos Cosmic Star Relics Realms Wilds")
    prompt=f"Existing titles ({len(books)}): {', '.join(list(titles)[:12])}\nCards:\n{cat_cards}\nWrite ONE new book not in that list."
    try:
        raw=chat_with_need(base, model, [{"role":"system","content":VOICE_BOOK},{"role":"user","content":prompt}], timeout)
    except Exception as e:
        print(f"book wait: {e}")
        return 0
    # parse PAGE Title + Category + pages
    import re as _re
    m=_re.search(r'PAGE\s+(.+?)\nCategory:\s*(.+?)\n(.+)', raw, flags=_re.S)
    if not m:
        print("skip book: unparseable")
        print(raw[:600])
        return 0
    title=m.group(1).strip()[:80]
    category=m.group(2).strip()
    body=m.group(3).strip()
    pages=[p.strip() for p in _re.split(r'---\s*PAGE\s*\d+\s*---', body) if p.strip()]
    if len(pages)<2:  # maybe single page split by ---
        pages=[body]
    # validate
    if title.lower() in titles:
        print(f"skip book duplicate title {title}")
        return 0
    bid=re.sub(r'[^a-z0-9]+','_', title.lower()).strip('_')[:30]
    if bid in ids:
        bid=bid+"_"+str(len(books)+1)
    if category not in ["Imperial Archive","Field Journals","WAH & Chaos","Cosmic & Star Relics","Realms & Wilds"]:
        category="Imperial Archive"
    if dry_run:
        print(f"DRY book {bid} '{title}' [{category}] {len(pages)} pages")
        print(pages[0][:400])
        return 1
    # append
    new_book={
        "id": bid,
        "title": title,
        "subtitle": "Codex Record",
        "author": "Master Scribe Inkwell",
        "category": category,
        "rarity": "uncommon",
        "description": pages[0][:300],
        "pages": pages,
        "cover_image": None,
        "cover_color": "#2d0f42",
        "cover_accent": "#ffd700",
        "icon": "📜",
        "effect": "Grants insight filed by Inkwell. Waluigi will still complain."
    }
    books.append(new_book)
    # write back to JS file: replace books array
    # Simplest: rebuild file as window.BOOKS_DATA = { "books": [...] };
    out={"books": books}
    new_js=f"window.BOOKS_DATA = {json.dumps(out, indent=2, ensure_ascii=False)};\n"
    BOOKS_JS.write_text(new_js, encoding="utf-8")
    print(f"book added {bid} '{title}' [{category}] {len(pages)} pages (now {len(books)} total)")
    time.sleep(sleep)
    return 1

# --- Timeline ---

def audit_timeline(year, month_name, day):
    # validate against calendar
    try:
        months=json.loads(MONTHS_P.read_text())
        names=[m.get("name") for m in months]
    except: names=[]
    if month_name not in names:
        return False, f"bad month {month_name}, must be one of {names}"
    # Deepwinter 35 days else 30
    max_day=35 if month_name=="Deepwinter" else 30
    if not (1 <= day <= max_day):
        return False, f"day {day} out of range for {month_name} (1-{max_day})"
    if not (722 <= year <= 1040):
        return False, f"year {year} outside 722-1040 BF chronicle range"
    # duplicate check
    tl=load_json(TL_PATH)
    # tl is list or dict?
    entries=tl if isinstance(tl, list) else (tl.get("timeline") or tl.get("events") or [])
    for e in entries:
        if isinstance(e, dict) and e.get("title","").lower()==year: pass
    return True, "ok"

def add_timeline(base, model, timeout, dry_run, sleep):
    tl=load_json(TL_PATH)
    if dry_run:
        entries=tl if isinstance(tl, list) else (tl.get("timeline") or [])
        from collections import Counter
        years=[e.get('date',{}).get('year') or e.get('year') for e in entries if isinstance(e, dict)]
        cnt=Counter(y for y in years if y)
        sparse=min(range(722,1041), key=lambda y: cnt.get(y,0))
        print(f"DRY timeline would add 1 to {len(entries)} entries — sparse year {sparse} BF ({cnt.get(sparse,0)} existing)")
        print(f"  audit: 722-1040 BF, Deepwinter=35d, else 30d, no duplicate title")
        return 1
    entries=tl if isinstance(tl, list) else (tl.get("timeline") or [])
    # pick a sparse year
    from collections import Counter
    years=[]
    for e in entries:
        if isinstance(e, dict) and e.get("date") and isinstance(e["date"], dict) and "year" in e["date"]:
            years.append(e["date"]["year"])
        elif isinstance(e, dict) and "year" in e:
            years.append(e["year"])
    cnt=Counter(years)
    sparse=min(range(722, 1041), key=lambda y: cnt.get(y,0))
    prompt=f"Sparse year is {sparse} BF (only {cnt.get(sparse,0)} entries). Existing titles nearby: {[e.get('title','')[:40] for e in entries if isinstance(e, dict) and abs((e.get('date',{}).get('year') or e.get('year') or 9999)-sparse)<5][:5]}\nCards:\n{cards_for_slot('historical timeline', f'year {sparse} BF historical')}\nPropose ONE event for {sparse} BF."
    try:
        raw=chat_with_need(base, model, [{"role":"system","content":VOICE_TL},{"role":"user","content":prompt}], timeout)
    except Exception as e:
        print(f"timeline wait: {e}")
        return 0
    import re as _re
    m=_re.search(r'PAGE\s+(.+?)\nYear:\s*(\d+).*?Month:\s*(.+?)\s+(\d+).*?Description:\s*(.+)', raw, flags=_re.S|_re.I)
    if not m:
        print("skip timeline: unparseable")
        print(raw[:600])
        return 0
    title=m.group(1).strip()[:80]
    year=int(m.group(2))
    month_name=m.group(3).strip().split()[0].capitalize()
    day=int(m.group(4))
    desc=m.group(5).strip()
    if len(desc.split())<80 or len(desc.split())>250:
        print(f"skip timeline: desc length {len(desc.split())}")
        return 0
    ok,msg=audit_timeline(year, month_name, day)
    if not ok:
        print(f"skip timeline audit fail: {msg}")
        return 0
    # duplicate title check
    if any(isinstance(e, dict) and e.get("title","").lower()==title.lower() for e in entries):
        print(f"skip timeline duplicate title {title}")
        return 0
    if dry_run:
        print(f"DRY timeline {year} BF {month_name} {day} — {title}")
        print(desc[:400])
        return 1
    # append as proposed
    new_entry={
        "type": "event",
        "title": title,
        "date": {"year": year, "month": month_name, "day": day},
        "description": desc,
        "proposed": True,
        "source": "expand-waluipedia overnight"
    }
    # handle both formats
    if isinstance(tl, list):
        tl.append(new_entry)
        out=tl
    else:
        (tl.setdefault("timeline", [])).append(new_entry)
        out=tl
    tmp=TL_PATH.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(out, indent=2, ensure_ascii=False)+"\n", encoding="utf-8")
    tmp.replace(TL_PATH)
    print(f"timeline added {year} BF {month_name} {day} — {title} (now {len(entries)+1})")
    time.sleep(sleep)
    return 1

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--stubs", action="store_true", help="expand stub characters")
    ap.add_argument("--books", action="store_true", help="add one book")
    ap.add_argument("--timeline", action="store_true", help="add one timeline event (needs --allow-timeline)")
    ap.add_argument("--allow-timeline", action="store_true")
    ap.add_argument("--codex", action="store_true", help="shell out to gen-mages-guild-code.py for one codex batch")
    ap.add_argument("--all", action="store_true", help="stubs + books (+ timeline if --allow-timeline)")
    ap.add_argument("--overnight", action="store_true", help="loop until --target total items (vs one-shot)")
    ap.add_argument("--target", type=int, default=20, help="how many items for overnight")
    ap.add_argument("--limit", type=int, default=0, help="max items for one-shot (0 = all stubs)")
    ap.add_argument("--base-url", default="http://127.0.0.1:1234/v1")
    ap.add_argument("--model", default="")
    ap.add_argument("--sleep", type=float, default=0.4)
    ap.add_argument("--timeout", type=int, default=180)
    ap.add_argument("--dry-run", action="store_true")
    args=ap.parse_args()

    if args.all:
        args.stubs=True
        args.books=True
        if args.allow_timeline: args.timeline=True

    if not any([args.stubs, args.books, args.timeline, args.codex]):
        print("pick --stubs / --books / --timeline / --codex / --all")
        return 2

    if args.timeline and not args.allow_timeline:
        print("timeline is risky — add --allow-timeline to confirm you will review it. No writes until then.")
        return 2

    models=list_models(args.base_url)
    model=args.model or (models[0] if models else "")
    if not model and not args.dry_run:
        print(f"LM Studio not reachable at {args.base_url}", file=sys.stderr)
        return 2
    if not model and args.dry_run:
        model="(dry-run)"
    print(f"model: {model} dry_run={args.dry_run}", file=sys.stderr)

    total=0
    goal=args.target if args.overnight else 1

    def do_one():
        nonlocal total
        if args.codex:
            # shell out to codex for one batch (count 1)
            cmd=[sys.executable, str(ROOT/"tools"/"gen-mages-guild-code.py"), "--base-url", args.base_url, "--model", model, "--count", "1", "--timeout", str(args.timeout)]
            print("codex:", " ".join(cmd), file=sys.stderr)
            if not args.dry_run:
                subprocess.run(cmd, check=False)
                total+=1
            else:
                print("DRY codex would run")
        if args.stubs:
            n=expand_stubs(args.base_url, model, args.timeout, args.limit or 1, args.dry_run, args.sleep)
            total+=n
        if args.books:
            n=add_book(args.base_url, model, args.timeout, args.dry_run, args.sleep)
            total+=n
        if args.timeline:
            n=add_timeline(args.base_url, model, args.timeout, args.dry_run, args.sleep)
            total+=n
        return total

    if args.overnight:
        while total < goal:
            before=total
            do_one()
            if total==before:
                print("no progress, sleeping 5s", file=sys.stderr)
                time.sleep(5)
                if total>=goal: break
            time.sleep(args.sleep)
        print(f"done {total}/{goal}")
    else:
        do_one()
        print(f"done {total}")
    return 0

if __name__=="__main__":
    raise SystemExit(main())
