#!/usr/bin/env python3
"""Cautious overnight expansion for stubs + books + PAST foreign events.

Stubs: expands `needsReview` / `autoGenerated` / short-description characters
       by pulling archive cards + related events, then asks LM
       Studio for a 600-900 word Waluigi-voiced expansion. Keeps original ID,
       preserves summary, marks as expanded but leaves `needsReview` true for
       human pass.

Books: generates one new book at a time from the same lore context. Checks
       for duplicate title/id, validates against existing categories.

Past Events (foreign): proposes ONE past event OR battle for a nation OTHER
       THAN Mushroom Kingdom / Midlands. Writes to events.json or battles.json
       (500-1000 words, README / STORY_FORMAT_GUIDE compliant). Full calendar
       audit (722-1040 BF), nation check, word-count check, duplicate-title
       check. Uses lore_search for nation context. HistoricalTimeline.json is
       NOT touched — it would fill with junk (per author request).

All three can run together overnight, but intentionally cautious:
 - one LLM call per item, then saves immediately (crash-safe)
 - --limit, --sleep, --timeout, --dry-run
 - past events are written directly to events.json/battles.json with a
   `proposed: true`-style flag in description for promoter to verify.

Usage:
  python tools/expand-waluipedia.py --stubs --dry-run --limit 3
  python tools/expand-waluipedia.py --stubs --overnight --limit 10
  python tools/expand-waluipedia.py --books --limit 1
  python tools/expand-waluipedia.py --past-events --dry-run --limit 1
  python tools/expand-waluipedia.py --past-events --overnight --target 5
  python tools/expand-waluipedia.py --all --overnight   # stubs+books+past-events+codex

Codex is still owned by gen-mages-guild-code.py; this tool can optionally
drive it via --codex (shells out). Timeline flag is deprecated — use --past-events.
"""
from __future__ import annotations
import argparse, json, re, sys, time, urllib.request, urllib.error, hashlib, subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(Path(__file__).resolve().parent))
from lore_search import cards_for_slot, format_cards, search as lore_lookup

CHAR_PATH = ROOT / "Reputation-Matrix2" / "data" / "characters.json"
BOOKS_JS  = ROOT / "Reputation-Matrix2" / "data" / "books-data.js"
BOOKS_JSON = ROOT / "Reputation-Matrix2" / "data" / "books.json"
EVENTS_P  = ROOT / "Reputation-Matrix2" / "data" / "events.json"
BATTLES_P = ROOT / "Reputation-Matrix2" / "data" / "battles.json"
NATIONS_P = ROOT / "Reputation-Matrix2" / "data" / "nations.json"
CUR_PATH  = ROOT / "Reputation-Matrix2" / "data" / "currentDate.json"
MONTHS_P  = ROOT / "Reputation-Matrix2" / "data" / "calendarMonths.json"

VOICE_STUB = """You are Waluigi's archivist expanding a STUB character file. Be cautious.

Constraints:
- Keep the character's id, name, and existing summary. Do not rename.
- Expand `description` to 600-900 words, 2-4 paragraphs + 1-2 Waluigi asides. Preserve Waluigi's voice (opinionated, physical detail) but do not invent new factions, items, or timeline dates beyond what's in the archive cards. If unsure, say 'Waluigi has not yet interviewed...' rather than inventing.
- Do not contradict the provided cards. Cite no new canon dates.
- Output format:
PAGE {character name}
Then the expanded description (continuous prose, markdown allowed for ## headers). No JSON.

If you need a fact: NEED: short query
"""

VOICE_BOOK = """You are Master Scribe Inkwell cataloging ONE new book for the Grand Scriptorium.

Constraints:
- Title must be new (not in the existing 51). Pick a category from: Imperial Archive, Field Journals, WAH & Chaos, Cosmic & Star Relics, Realms & Wilds.
- 3-5 pages, each 150-250 words, Waluigi-adjacent but in Inkwell's catalog voice.
- One `effect` line (tactical insight).
- Output format:
PAGE Book Title Goes Here
Category: <one of the list>
Then page 1 text (150-250 words)
--- PAGE 2 ---
page 2 text
--- etc for 3-5 pages

If you need a fact: NEED: short query
"""

VOICE_PAST = """You are Waluigi's chronicler filing ONE PAST historical event for a FOREIGN nation (NOT Mushroom Kingdom, NOT Midlands). Follow README + STORY_FORMAT_GUIDE:

- Story with a commentator, not a report with scenes attached. Physical detail: quoted speech, named objects, sounds. Commentary is second layer.
- 500-1000 words. Filed by Waluigi (opinionated, petty, frequently right). In-world encyclopedia voice.
- Must be PAST: 722-1039 BF, before present 1040 BF. Use Regal Empire Standard Calendar (12 months, Deepwinter=35 days). Pick a date not already dense.
- Location must be inside the chosen nation's territory. No Mushroom/Midlands locations.
- If the event is a battle/skirmish/siege, say Type: battle — it will go to battles.json. Otherwise Type: event → events.json.
- Do not duplicate existing titles.
- Output format (exactly):
PAGE Title of the Past Event
Nation: <nation id e.g. equestria, regal_empire, faerun, kivotos, teyvat>
Type: event OR battle
Year: 8xx or 9xx BF
Month: <name> <day>
Location: <specific place inside that nation>
Description: 500-1000 words (continuous prose, markdown allowed)

If you need a fact: NEED: short query
"""

EMOJI_RE = re.compile(r"[\U0001F300-\U0001FAFF\U00002600-\U000027BF]")
WORD_RE = re.compile(r"[A-Za-z][A-Za-z'’-]*")


def text_quality_error(text: str) -> str:
    """Reject obvious model spam before any generated text reaches live data."""
    words = WORD_RE.findall(text or "")
    emoji_count = len(EMOJI_RE.findall(text or ""))
    if emoji_count > 2:
        return f"emoji spam ({emoji_count}; maximum 2)"
    if len(words) < 1:
        return "empty text"
    # A repeated long n-gram is a stronger signal than ordinary word reuse.
    tokens = [w.lower() for w in words]
    for size in (5, 6, 7):
        grams = [tuple(tokens[i:i + size]) for i in range(len(tokens) - size + 1)]
        if len(grams) != len(set(grams)):
            return f"repeated {size}-word phrase"
    lines = [re.sub(r"\s+", " ", line.strip().lower()) for line in (text or "").splitlines() if line.strip()]
    if lines and any(lines.count(line) >= 3 for line in set(lines) if len(line) > 24):
        return "repeated line spam"
    return ""


def require_clean_text(text: str, label: str) -> bool:
    reason = text_quality_error(text)
    if reason:
        print(f"skip {label}: {reason}")
        return False
    return True


def load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))

def chat(base: str, model: str, messages: list, timeout: int) -> str:
    url = base.rstrip("/") + "/chat/completions"
    payload = json.dumps({"model": model, "temperature": 0.7, "max_tokens": 4096, "messages": messages}).encode()
    req = urllib.request.Request(url, data=payload, headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        data = json.loads(r.read().decode())
    return data["choices"][0]["message"]["content"]

def parse_need(q):
    qs=[]
    for line in (q or "").splitlines():
        m=re.match(r"^\s*(NEED|SEARCH)\s*:\s*(.+)$", line, re.I)
        if m: qs.append(m.group(2).strip()[:80])
    return qs[:2]

def chat_with_need(base, model, msgs, timeout):
    raw=chat(base, model, msgs, timeout)
    needs=parse_need(raw)
    if not needs: return raw
    extra="\n".join(format_cards(lore_lookup(q, k=4)) for q in needs)
    follow=msgs+[ {"role":"assistant","content":raw}, {"role":"user","content":"Cards (do not dump files):\n"+extra+"\nNow write PAGE only."}]
    return chat(base, model, follow, timeout)

def list_models(base: str):
    try:
        with urllib.request.urlopen(base.rstrip("/")+ "/models", timeout=10) as r:
            return [m.get("id") for m in json.loads(r.read().decode()).get("data") or [] if m.get("id")]
    except: return []

# --- Stubs ---

def find_stubs(limit=0):
    chars=load_json(CHAR_PATH)
    if not isinstance(chars, list): return []
    stubs=[]
    for c in chars:
        desc=c.get("description","") or ""
        if c.get("needsReview") or c.get("autoGenerated") or len(desc)<800 or "Needs Waluipedia review" in desc:
            stubs.append(c)
    stubs.sort(key=lambda c: len(c.get("description","")))
    return stubs[:limit] if limit else stubs

def pack_stub_context(char: dict) -> str:
    title=char.get("name","") or char.get("id","")
    summary=char.get("summary","") or ""
    desc=char.get("description","")[:800]
    cards=cards_for_slot(title, summary+" "+desc)
    return f"STUB: {char.get('id')} — {title}\nSummary: {summary}\nCurrent stub excerpt: {desc[:600]}\n\nCARDS:\n{cards}\n\nCalendar: {load_json(CUR_PATH)}"

def parse_stub_page(raw: str):
    m=re.search(r'PAGE\s+(.+?)\n(.+)', raw, flags=re.S)
    if not m: return None
    body=m.group(2).strip()
    if len(body.split()) < 200: return None
    return body

def expand_stubs(base, model, timeout, limit, dry_run, sleep):
    stubs=find_stubs(limit if limit else 0)
    if not stubs:
        print("no stubs found")
        return 0
    print(f"stubs: {len(stubs)} queued (of 26 total) — most stubby first")
    if dry_run:
        for char in stubs:
            print(f"DRY stub {char.get('id')} '{char.get('name')}' — {len((char.get('description') or '').split())} words → would expand to 600-900 words")
            print(f"  cards: {cards_for_slot(char.get('name',''), char.get('summary','') or '')[:120]}...")
        return len(stubs)
    expanded=0
    for char in stubs:
        q=pack_stub_context(char)
        prompt=q+f"\n\nExpand this stub cautiously. Keep id={char.get('id')}. Need 600-900 words."
        try:
            raw=chat_with_need(base, model, [{"role":"system","content":VOICE_STUB},{"role":"user","content":prompt}], timeout)
        except Exception as e:
            print(f"stub {char.get('id')} wait: {e}")
            time.sleep(5)
            continue
        body=parse_stub_page(raw)
        if not body or not require_clean_text(body, f"stub {char.get('id')}"):
            print(f"skip stub {char.get('id')}: unusable")
            continue
        chars=load_json(CHAR_PATH)
        for c in chars:
            if c.get("id")==char.get("id"):
                c["description"]=body
                c["expandedAt"]="overnight"
                c.pop("autoGenerated", None)
                break
        tmp=CHAR_PATH.with_suffix(".json.tmp")
        tmp.write_text(json.dumps(chars, indent=2, ensure_ascii=False)+"\n", encoding="utf-8")
        tmp.replace(CHAR_PATH)
        print(f"expand stub {char.get('id')} {char.get('name')} ({expanded+1}/{len(stubs)}) {len(body.split())} words")
        expanded+=1
        time.sleep(sleep)
    return expanded

# --- Books ---

def load_books_js():
    txt=BOOKS_JS.read_text(encoding="utf-8")
    m=re.search(r'"books"\s*:\s*\[', txt)
    if not m: return [], txt
    start=txt.find("{", txt.find("window.BOOKS_DATA"))
    end=txt.rfind("}")
    obj=json.loads(txt[start:end+1])
    return obj.get("books",[]), txt

def add_book(base, model, timeout, dry_run, sleep):
    books, raw_js = load_books_js()
    titles={b.get("title","").lower() for b in books}
    ids={b.get("id","") for b in books}
    if dry_run:
        print(f"DRY book would add 1 to {len(books)} existing (e.g. '{list(titles)[:1]}')")
        print(f"  sparse check: categories Imperial Archive/Field Journals/WAH & Chaos/Cosmic & Star Relics/Realms & Wilds")
        return 1
    cat_cards=cards_for_slot("Grand Scriptorium books", "Inkwell catalog Imperial Archive Field Journals WAH Chaos Cosmic Star Relics Realms Wilds")
    prompt=f"Existing titles ({len(books)}): {', '.join(list(titles)[:12])}\nCards:\n{cat_cards}\nWrite ONE new book not in that list."
    try:
        raw=chat_with_need(base, model, [{"role":"system","content":VOICE_BOOK},{"role":"user","content":prompt}], timeout)
    except Exception as e:
        print(f"book wait: {e}")
        return 0
    m=re.search(r'PAGE\s+(.+?)\nCategory:\s*(.+?)\n(.+)', raw, flags=re.S)
    if not m:
        print("skip book: unparseable")
        print(raw[:600])
        return 0
    title=m.group(1).strip()[:80]
    category=m.group(2).strip()
    body=m.group(3).strip()
    pages=[p.strip() for p in re.split(r'---\s*PAGE\s*\d+\s*---', body) if p.strip()]
    if len(pages)<2:
        pages=[body]
    if title.lower() in titles:
        print(f"skip book duplicate title {title}")
        return 0
    if not require_clean_text(body, "book"):
        return 0
    bid=re.sub(r'[^a-z0-9]+','_', title.lower()).strip('_')[:30]
    if bid in ids:
        bid=bid+"_"+str(len(books)+1)
    if category not in ["Imperial Archive","Field Journals","WAH & Chaos","Cosmic & Star Relics","Realms & Wilds"]:
        category="Imperial Archive"
    new_book={
        "id": bid,
        "title": title,
        "subtitle": "Codex Record",
        "author": "Master Scribe Inkwell",
        "category": category,
        "rarity": "uncommon",
        "description": pages[0][:300],
        "pages": pages,
        "cover_image": None,
        "cover_color": "#2d0f42",
        "cover_accent": "#ffd700",
        "icon": "📜",
        "effect": "Grants insight filed by Inkwell. Waluigi will still complain."
    }
    books.append(new_book)
    out={"books": books}
    new_js=f"window.BOOKS_DATA = {json.dumps(out, indent=2, ensure_ascii=False)};\n"
    BOOKS_JS.write_text(new_js, encoding="utf-8")
    # Also write to books.json (proper location) so both stay in sync — fixes pull-from-proper-location bug
    try:
        bj_path = BOOKS_JSON
        bj_data = json.loads(bj_path.read_text(encoding="utf-8")) if bj_path.exists() else {"books": []}
        bj_books = bj_data.get("books", []) if isinstance(bj_data, dict) else bj_data
        if isinstance(bj_books, list) and not any(b.get("id")==bid for b in bj_books):
            bj_books.append(new_book)
            bj_out = {"books": bj_books} if isinstance(bj_data, dict) and "books" in bj_data else bj_books
            # Preserve original structure (books.json is {"books": [...]})
            if isinstance(bj_data, dict) and "books" in bj_data:
                bj_data["books"] = bj_books
                bj_path.write_text(json.dumps(bj_data, indent=2, ensure_ascii=False)+"\n", encoding="utf-8")
            else:
                bj_path.write_text(json.dumps(bj_out, indent=2, ensure_ascii=False)+"\n", encoding="utf-8")
    except Exception as e:
        print(f"warn: could not sync books.json: {e}", file=__import__('sys').stderr)
    print(f"book added {bid} '{title}' [{category}] {len(pages)} pages (now {len(books)} total) — synced to both books.json and books-data.js")
    time.sleep(sleep)
    return 1

# --- Past Events (foreign nations → events.json / battles.json) ---

EXCLUDE_NATIONS = {"mushroom_kingdom","midlands","holy_midlands","monster_underground"}
def is_foreign(nid: str) -> bool:
    nid=nid.lower()
    if nid in EXCLUDE_NATIONS: return False
    if "mushroom" in nid or "midland" in nid: return False
    return True

def audit_past_event(nation_id, year, month_name, day, title, word_count, events, battles):
    # nation check
    nats=load_json(NATIONS_P)
    nids={n.get("id") for n in nats} if isinstance(nats, list) else set()
    if nation_id not in nids:
        return False, f"unknown nation {nation_id}"
    if not is_foreign(nation_id):
        return False, f"nation {nation_id} is excluded (Mushroom/Midlands only past foreign)"
    # calendar
    try:
        months=json.loads(MONTHS_P.read_text())
        names=[m.get("name") for m in months]
    except: names=[]
    if month_name not in names:
        return False, f"bad month {month_name}, must be one of {names}"
    max_day=35 if month_name=="Deepwinter" else 30
    if not (1 <= day <= max_day):
        return False, f"day {day} out of range for {month_name} (1-{max_day})"
    if not (722 <= year <= 1039):
        return False, f"year {year} must be 722-1039 BF (past, before 1040)"
    if not (500 <= word_count <= 1200):
        return False, f"word count {word_count} outside 500-1000 target"
    # duplicate title
    all_titles={e.get("title","").lower() for e in events} | {b.get("name","").lower() for b in battles} | {b.get("title","").lower() for b in battles}
    if title.lower() in all_titles:
        return False, f"duplicate title {title}"
    return True, "ok"

def foreign_coverage():
    """Score how much detail exists for each foreign nation, not just location mentions."""
    nats=load_json(NATIONS_P)
    events=load_json(EVENTS_P)
    battles=load_json(BATTLES_P)
    scores={str(n.get("id")): len(WORD_RE.findall(json.dumps(n, ensure_ascii=False))) for n in nats if is_foreign(n.get("id"))}
    for record in [*events, *battles]:
        blob=json.dumps(record, ensure_ascii=False).lower()
        for n in nats:
            nid=str(n.get("id"))
            if not is_foreign(nid): continue
            name=str(n.get("name") or nid).lower()
            if nid.lower() in blob or name in blob:
                scores[nid] = scores.get(nid, 0) + min(1200, len(WORD_RE.findall(blob)))
    return scores


def find_sparse_foreign_nation():
    nats=load_json(NATIONS_P)
    scores=foreign_coverage()
    foreign=[str(n.get("id")) for n in nats if is_foreign(n.get("id"))]
    if not foreign: return "equestria"
    # Lowest coverage first; stable id tie-break makes the pass eventually
    # flesh every under-documented nation instead of repeatedly picking one.
    return min(foreign, key=lambda nid: (scores.get(nid, 0), nid))

def add_past_event(base, model, timeout, dry_run, sleep):
    nats=load_json(NATIONS_P)
    events=load_json(EVENTS_P)
    battles=load_json(BATTLES_P)
    if dry_run:
        sparse=find_sparse_foreign_nation()
        # find counts for message
        from collections import Counter
        counts=Counter()
        for e in events:
            loc=(e.get("location") or "").lower()
            if sparse.replace("_"," ") in loc or sparse in loc:
                counts[sparse]+=1
        print(f"DRY past-event would add 1 past event for foreign nation '{sparse}' → events.json (or battles.json if battle)")
        print(f"  audit: 722-1039 BF, valid month/day, 500-1000 words, not Mushroom/Midlands, duplicate check across {len(events)} events + {len(battles)} battles")
        print(f"  example foreign pool: {[n.get('id') for n in nats if is_foreign(n.get('id'))][:8]}")
        return 1
    sparse=find_sparse_foreign_nation()
    # get nation record for context
    nation_rec=next((n for n in nats if n.get("id")==sparse), {"name": sparse, "id": sparse})
    nation_name=nation_rec.get("name") or sparse
    # build prompt with sparse nation's context
    cards=cards_for_slot(f"{nation_name} past history foreign", f"{nation_name} {nation_rec.get('region','')} {nation_rec.get('type','')}")
    # existing titles for dedup hint
    existing_titles=[e.get("title","")[:50] for e in events if isinstance(e, dict)][:8]
    prompt=f"Foreign nation: {sparse} ({nation_name}) — region {nation_rec.get('region','')}. Sparse (fewest past events). Existing titles to avoid: {existing_titles}\nCards:\n{cards}\nWrite ONE PAST event (722-1039 BF) for this nation. Location must be inside {nation_name}. 500-1000 words."
    try:
        raw=chat_with_need(base, model, [{"role":"system","content":VOICE_PAST},{"role":"user","content":prompt}], timeout)
    except Exception as e:
        print(f"past-event wait: {e}")
        return 0
    m=re.search(r'PAGE\s+(.+?)\nNation:\s*(\S+).*?Type:\s*(event|battle).*?Year:\s*(\d+).*?Month:\s*(.+?)\s+(\d+).*?Location:\s*(.+?)\nDescription:\s*(.+)', raw, flags=re.S|re.I)
    if not m:
        print("skip past-event: unparseable")
        print(raw[:800])
        return 0
    title=m.group(1).strip()[:80]
    nation_id=m.group(2).strip().lower()
    typ=m.group(3).strip().lower()
    year=int(m.group(4))
    month_name=m.group(5).strip().split()[0].capitalize()
    # handle month like Harvestide vs Harvestide — ensure proper case
    # normalize month name from calendar list
    try:
        months=json.loads(MONTHS_P.read_text())
        names={mm.get("name").lower(): mm.get("name") for mm in months}
        month_name=names.get(month_name.lower(), month_name)
    except: pass
    day=int(m.group(6))
    location=m.group(7).strip()[:80]
    desc=m.group(8).strip()
    wc=len(desc.split())
    if nation_id != sparse:
        print(f"skip past-event audit fail: model changed assigned nation from {sparse} to {nation_id}")
        return 0
    if not require_clean_text(desc, "past-event"):
        return 0
    ok,msg=audit_past_event(nation_id, year, month_name, day, title, wc, events, battles)
    if not ok:
        print(f"skip past-event audit fail: {msg}")
        print(f"  got: nation={nation_id} year={year} {month_name} {day} wc={wc} title={title}")
        return 0
    # also ensure location not mushroom/midlands
    if "mushroom" in location.lower() or "midland" in location.lower():
        print(f"skip past-event: location {location} is Mushroom/Midlands (must be foreign)")
        return 0
    # write to appropriate file
    new_id=re.sub(r'[^a-z0-9]+','_', title.lower()).strip('_')[:40]
    # avoid collision
    all_ids={e.get("id") for e in events} | {b.get("id") for b in battles}
    if new_id in all_ids:
        new_id=new_id+"_"+str(year)
    date_str=f"{month_name} {day}, {year} BF"
    if typ=="battle":
        new_entry={
            "id": new_id,
            "name": title,
            "title": title,
            "date": date_str,
            "location": location,
            "type": "Historical Battle (Past)",
            "result": "Filed as past foreign record — see description",
            "belligerents": [nation_name],
            "casualties": "Filed for later audit",
            "summary": desc[:180],
            "description": desc,
            "aftermath": "Waluigi notes this predates the 1040 BF crisis by decades — filed for cross-nation context.",
            "relatedArticles": [nation_id],
            "reputationChanges": [],
            "proposed": True
        }
        battles.append(new_entry)
        out=battles
        path=BATTLES_P
        kind="battle"
    else:
        new_entry={
            "id": new_id,
            "name": title,
            "title": title,
            "type": "Historical Event (Past, Foreign)",
            "date": date_str,
            "era": f"{year} BF — Past Foreign Record",
            "location": location,
            "status": "Historical — Proposed",
            "summary": desc[:180],
            "description": desc,
            "notableFeatures": [f"Foreign nation: {nation_name}", f"Past date {date_str}"],
            "relatedArticles": [nation_id],
            "reputationChanges": [],
            "proposed": True
        }
        events.append(new_entry)
        out=events
        path=EVENTS_P
        kind="event"
    tmp=path.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(out, indent=2, ensure_ascii=False)+"\n", encoding="utf-8")
    tmp.replace(path)
    total=len(events) if typ!="battle" else len(battles)
    print(f"past {kind} added {new_id} '{title}' {date_str} @ {location} [{wc}w] for {nation_id} → {path.name} (now {total})")
    time.sleep(sleep)
    return 1

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--stubs", action="store_true", help="expand stub characters")
    ap.add_argument("--books", action="store_true", help="add one book")
    ap.add_argument("--past-events", action="store_true", help="add one PAST foreign event/battle (722-1039 BF, not Mushroom/Midlands)")
    ap.add_argument("--forms", action="store_true", help="generate one missing guild form (MG-xxx) with strict JSON validation)")
    ap.add_argument("--timeline", action="store_true", help="deprecated alias for --past-events")
    ap.add_argument("--allow-timeline", action="store_true", help="deprecated, no longer needed")
    ap.add_argument("--codex", action="store_true", help="shell out to gen-mages-guild-code.py for one codex batch")
    ap.add_argument("--guild-ratio", type=int, default=100, help="when --all --overnight, how many Codex pages per one other task (default 100). Limits spam while still growing laws.")
    ap.add_argument("--all", action="store_true", help="stubs + books + past-events + codex + forms")
    ap.add_argument("--overnight", action="store_true", help="loop until --target total items (vs one-shot)")
    ap.add_argument("--target", type=int, default=20, help="how many items for overnight")
    ap.add_argument("--limit", type=int, default=0, help="max items for one-shot (0 = all stubs)")
    ap.add_argument("--base-url", default="http://127.0.0.1:1234/v1")
    ap.add_argument("--model", default="")
    ap.add_argument("--sleep", type=float, default=0.4)
    ap.add_argument("--timeout", type=int, default=180)
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--max-attempts", type=int, default=0, help="overnight safety ceiling; 0 = target plus 10 retries per item")
    args=ap.parse_args()

    # timeline alias
    if args.timeline:
        print("note: --timeline is now --past-events (events.json/battles.json, not historicalTimeline.json)", file=sys.stderr)
        args.past_events=True

    if args.all:
        args.stubs=True
        args.books=True
        args.past_events=True
        args.forms=True

    if not any([args.stubs, args.books, args.past_events, args.codex, args.forms]):
        print("pick --stubs / --books / --past-events / --codex / --all")
        return 2

    models=list_models(args.base_url)
    model=args.model or (models[0] if models else "")
    if not model and not args.dry_run:
        print(f"LM Studio not reachable at {args.base_url}", file=sys.stderr)
        return 2
    if not model and args.dry_run:
        model="(dry-run)"
    print(f"model: {model} dry_run={args.dry_run}", file=sys.stderr)

    total=0
    goal=args.target if args.overnight else 1

    def do_one():
        nonlocal total
        if args.codex:
            cmd=[sys.executable, str(ROOT/"tools"/"gen-mages-guild-code.py"), "--base-url", args.base_url, "--model", model, "--count", "1", "--timeout", str(args.timeout)]
            print("codex:", " ".join(cmd), file=sys.stderr)
            if not args.dry_run:
                subprocess.run(cmd, check=False)
                total+=1
            else:
                print("DRY codex would run")
                total+=1
            if not args.overnight and not args.all:
                return total
        if args.stubs:
            n=expand_stubs(args.base_url, model, args.timeout, args.limit or 1, args.dry_run, args.sleep)
            total+=n if args.overnight else min(n,1)
            if not args.overnight and not args.all:
                return total
        if args.books:
            n=add_book(args.base_url, model, args.timeout, args.dry_run, args.sleep)
            total+=n
            if not args.overnight and not args.all:
                return total
        if args.past_events:
            n=add_past_event(args.base_url, model, args.timeout, args.dry_run, args.sleep)
            total+=n
        if args.forms:
            # generate one form via gen-mages-forms.py (validated JSON, retries)
            cmd=[sys.executable, str(ROOT/"tools"/"gen-mages-forms.py"), "--base-url", args.base_url, "--model", model, "--generate", "--all"]
            if args.dry_run:
                cmd.append("--dry-run")
            print("forms:", " ".join(cmd), file=sys.stderr)
            if not args.dry_run:
                subprocess.run(cmd, check=False)
                # count forms added
                try:
                    jf=json.loads((ROOT/"Reputation-Matrix2"/"data"/"laws"/"mages-forms.json").read_text())
                    total+=1
                except: pass
            else:
                print("DRY forms would generate 1 missing form")
                total+=1
        return total

    # Throttle: when --all --overnight, do guild-ratio Codex pages per one other task
    is_throttled = args.all and args.overnight and args.guild_ratio>1 and any([args.stubs, args.books, args.past_events])
    if args.overnight and is_throttled:
        # throttled all-night: 100 Codex then 1 other round-robin
        other_turn = 0
        while total < goal:
            # Codex burst
            if args.codex or args.all:
                batch = min(args.guild_ratio, goal - total)
                if batch>0:
                    cmd=[sys.executable, str(ROOT/"tools"/"gen-mages-guild-code.py"), "--base-url", args.base_url, "--model", model, "--count", str(batch), "--timeout", str(args.timeout)]
                    if not args.dry_run:
                        print(f"codex burst: {batch} pages (ratio 1:{args.guild_ratio})", file=sys.stderr)
                        subprocess.run(cmd, check=False)
                        total+=batch
                    else:
                        print(f"DRY codex burst {batch} pages (ratio 1:{args.guild_ratio})")
                        total+=batch
                    if total>=goal: break
                    time.sleep(args.sleep)
            # One other task per 100 — round-robin stubs/books/past-events
            # pick which other to do this turn
            others=[]
            if args.stubs: others.append("stubs")
            if args.books: others.append("books")
            if args.past_events: others.append("past")
            if args.forms: others.append("forms")
            if others:
                pick=others[other_turn % len(others)]
                other_turn+=1
                if pick=="stubs":
                    n=expand_stubs(args.base_url, model, args.timeout, 1, args.dry_run, args.sleep)
                elif pick=="books":
                    n=add_book(args.base_url, model, args.timeout, args.dry_run, args.sleep)
                elif pick=="past":
                    n=add_past_event(args.base_url, model, args.timeout, args.dry_run, args.sleep)
                else: # forms
                    cmd=[sys.executable, str(ROOT/"tools"/"gen-mages-forms.py"), "--base-url", args.base_url, "--model", model, "--generate", "--all"]
                    if args.dry_run: cmd.append("--dry-run")
                    print("forms:", " ".join(cmd), file=sys.stderr)
                    if not args.dry_run:
                        subprocess.run(cmd, check=False)
                        n=1
                    else:
                        print("DRY forms would generate 1 missing form")
                        n=1
                total+=n
            if total>=goal: break
            time.sleep(args.sleep)
        print(f"done {total}/{goal} (throttled {args.guild_ratio}:1)")
    elif args.overnight:
        attempts=0
        ceiling=args.max_attempts or max(goal * 11, goal + 10)
        while total < goal and attempts < ceiling:
            attempts += 1
            before=total
            do_one()
            if total==before:
                print(f"no progress ({attempts}/{ceiling}), sleeping 5s", file=sys.stderr)
                time.sleep(5)
            time.sleep(args.sleep)
        if total < goal:
            print(f"past expansion stopped safely after {attempts} attempts: {total}/{goal} accepted", file=sys.stderr)
            return 1
        print(f"done {total}/{goal}")
    else:
        do_one()
        print(f"done {total}")
    return 0

if __name__=="__main__":
    raise SystemExit(main())
