#!/usr/bin/env python3
"""make-token-plates.py — full-body transparent plates for the table, in batches.

A token on the map wants the whole figure on a transparent field. The portraits
stay what they are (the article's picture); the plate is a second file,
`portraits/player/fullbody/<id>.png`, wired as `fullBody` on the article, and
the sheet builder puts it on the prototype token (`token_of()`).

The batch is a pipeline, not a grid (a 9x9 cuts to ~200 px a figure, below
what a token survives):

  plan    which sheet characters are READY / CUT (a flat field to key) /
          GENERATE (needs a render), in table-use order, and a manifest of
          prompts built from the article (look from the appearance captions,
          the lead as the reference image, a key colour the character does not
          wear).
  cut     key a render (or an opaque plate on a flat field) into a trimmed,
          square, transparent PNG — magenta / green chroma or the border colour.
  apply   write `fullBody` + `fullBodyCaption` for every plate on disk that the
          article does not point at yet (characters.json round-trips as is).
  check   every `fullBody` is a real transparent plate (alpha border, >= MIN_PX);
          `--check` exits 1 otherwise.
  pixel   a pixel-art sprite (the Bone-Line cast): keep the figure, drop the burnt-in name under it,
          scale by whole pixels to >= 640 px — pixel art is regenerated by nobody.
  sheet   a contact sheet of plates for the eyeball pass.

  python3 tools/make-token-plates.py plan [--manifest /tmp/plates/manifest.json] [--tier 1]
  python3 tools/make-token-plates.py cut  --id waluigi --src /tmp/plates/raw/waluigi.png [--key magenta|green|auto]
  python3 tools/make-token-plates.py cut  --flat                 # key every opaque plate whose field is flat
  python3 tools/make-token-plates.py cut  --raw-dir ~/renders    # every <id>.png rendered elsewhere from the manifest
  python3 tools/make-token-plates.py apply [--date 2026-10-05]
  python3 tools/make-token-plates.py check
  python3 tools/make-token-plates.py sheet --out /tmp/plates/sheet.jpg [--ids a b c]

Needs Pillow + numpy (+ scipy for a fast flood fill; falls back without).
"""
import argparse
import datetime as dt
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RM = os.path.join(ROOT, "Reputation-Matrix2")
CHARACTERS = os.path.join(RM, "data", "characters.json")
SHEETS = os.path.join(RM, "data", "sheets.json")
EVENTS = os.path.join(RM, "data", "events.json")
PLATES = "portraits/player/fullbody"
MIN_PX = 400          # a token that survives zoom (the 500 px cut-out shelf and the 550 px roster cuts count)
OUT_PX = 1024         # plates are downscaled to this on the long side, never upscaled
BORDER_CLEAR = 0.95   # share of border pixels that must be transparent
MARGIN = 0.04         # empty space around the trimmed figure

KEYS = {"magenta": (255, 0, 255), "green": (0, 255, 0)}
IMAGE_EXT = (".png", ".jpg", ".jpeg", ".webp")
# leads that are not a picture of the character (an icon, a letter, an event scene): never a reference, never cut
NO_REFERENCE = {"kyrn", "gee_lady", "pet_rock", "prunsel", "scorncrow", "alistair_marshkeeper", "cosmic_jester", "director_mario",
                "evil_mario", "lord_darian_marsh", "marilyn_the_chambermaid", "gabriel_freddy", "creek_medic_scene"}
# a flat border around a scene: the lead is a fine reference but nothing to key — render instead
FORCE_GENERATE = {"john_lee", "paulo"}
# wardrobe in the magenta family — key these on green instead
GREEN_KEY_IDS = {"waluigi", "wario", "princess_peach", "captain_toadette", "birdo", "vivian_corvinarus", "ryan", "purple_t", "toadette",
                 "lady_aurelian", "earl_grey", "kamek"}
GREEN_KEY_WORDS = re.compile(r"\b(purple|pink|magenta|violet|plum|lilac|fuchsia|mauve|lavender)\b", re.I)
MAGENTA_KEY_WORDS = re.compile(r"\b(green|emerald|olive|frog|moss|lime)\b", re.I)


# ---------------------------------------------------------------- data ----
def load():
    arts = json.load(open(CHARACTERS, encoding="utf-8"))
    sheets = json.load(open(SHEETS, encoding="utf-8"))
    rows = sheets.get("sheets", sheets) if isinstance(sheets, dict) else sheets
    return arts, {r["id"]: r for r in rows}


def usage_counts():
    """How often each article id is named in the events file — the proxy for 'placed on the map'."""
    try:
        text = open(EVENTS, encoding="utf-8").read()
    except OSError:
        return {}
    return {m: text.count('"%s"' % m) for m in set(re.findall(r'"([a-z0-9_]+)"', text))}


def look_of(a):
    """One line of established look from the appearance captions, else nothing (the reference carries it)."""
    for key in ("fullBodyCaption", "imageCaption"):
        cap = (a.get(key) or "").strip()
        if cap.startswith("Full-body token plate"):   # the pipeline's own caption says nothing about the look
            continue
        if cap:
            cap = re.sub(r"^(Lead plate|Full-body plate|Full-body token plate)\s*[—-]+\s*(established look:)?\s*", "", cap, flags=re.I)
            cap = re.split(r"\.\s+(?:Full figure|Replaces|Painted|The token|Her own|Found|Cut from)", cap)[0]
            return cap.strip().rstrip(".")
    return ""


def key_for(a):
    blob = " ".join(str(a.get(k) or "") for k in ("name", "imageCaption", "fullBodyCaption", "race"))
    if a["id"] in GREEN_KEY_IDS or (GREEN_KEY_WORDS.search(blob) and not MAGENTA_KEY_WORDS.search(blob)):
        return "green"
    return "magenta"


def prompt_for(a):
    name = a.get("name", a["id"])
    race = (a.get("race") or "").strip()
    title = (a.get("title") or "").strip()
    look = look_of(a)
    key = key_for(a)
    who = name + (f", {title}" if title and title.lower() not in name.lower() else "")
    who += f" ({race})" if race and race.lower() not in who.lower() else ""
    parts = [f"Full-body character token art of {who}."]
    if look:
        parts.append(f"Established look: {look}.")
    parts.append("The same character and the same art style as the reference image, with the same face, colours and wardrobe.")
    parts.append("The whole figure from the top of the head to the soles of the feet, standing in a relaxed neutral pose facing the viewer "
                 "and turned slightly, arms and hands visible, weapon or tool held if the character carries one.")
    parts.append("Centred with empty space on every side, nothing cropped.")
    colour = "bright magenta (#FF00FF)" if key == "magenta" else "bright green (#00FF00)"
    parts.append(f"Plain solid flat {colour} background, no floor, no cast shadow on the ground, no scenery, no text, no border, no watermark.")
    return " ".join(parts), key


# --------------------------------------------------------------- image ----
def _np():
    import numpy as np
    return np


def plate_facts(path):
    """(width, height, border_clear, flat_key_or_None) for an image file."""
    from PIL import Image
    np = _np()
    im = Image.open(path)
    w, h = im.size
    has_alpha = im.mode in ("RGBA", "LA") or (im.mode == "P" and "transparency" in im.info)
    rgba = np.asarray(im.convert("RGBA"))
    ring = np.concatenate([rgba[0, :], rgba[-1, :], rgba[:, 0], rgba[:, -1]])
    clear = float((ring[:, 3] < 16).mean()) if has_alpha else 0.0
    flat = None
    if clear < BORDER_CLEAR:
        rgb = ring[:, :3].astype(float)
        med = np.median(rgb, axis=0)
        if np.sqrt(((rgb - med) ** 2).sum(axis=1)).mean() < 12 and (np.sqrt(((rgb - med) ** 2).sum(axis=1)) < 40).mean() > 0.97:
            flat = tuple(int(x) for x in med)
    return w, h, clear, flat


def _label_from_border(hard):
    """Boolean mask of hard-key pixels connected to the border."""
    np = _np()
    try:
        from scipy import ndimage
        lab, n = ndimage.label(hard)
        ids = set(np.unique(lab[0, :])) | set(np.unique(lab[-1, :])) | set(np.unique(lab[:, 0])) | set(np.unique(lab[:, -1]))
        ids.discard(0)
        return np.isin(lab, list(ids)) if ids else np.zeros_like(hard)
    except ImportError:
        reach = np.zeros_like(hard)
        reach[0, :] = hard[0, :]; reach[-1, :] = hard[-1, :]; reach[:, 0] = hard[:, 0]; reach[:, -1] = hard[:, -1]
        while True:
            grown = reach.copy()
            grown[1:, :] |= reach[:-1, :]; grown[:-1, :] |= reach[1:, :]
            grown[:, 1:] |= reach[:, :-1]; grown[:, :-1] |= reach[:, 1:]
            grown &= hard
            if (grown == reach).all():
                return reach
            reach = grown


def cut(src, dst, key="auto", hard_tol=None, soft_tol=None):
    """Key `src` into a trimmed, square, transparent PNG at `dst`. Returns a facts dict."""
    from PIL import Image
    np = _np()
    im = Image.open(src).convert("RGBA")
    arr = np.asarray(im).astype(np.int16)
    rgb = arr[:, :, :3]
    if key == "auto":
        ring = np.concatenate([rgb[0, :], rgb[-1, :], rgb[:, 0], rgb[:, -1]]).astype(float)
        kc = tuple(int(x) for x in np.median(ring, axis=0))
        chroma = None
        for name, val in KEYS.items():
            if np.sqrt(((np.array(kc) - np.array(val)) ** 2).sum()) < 90:
                chroma = name
        key = chroma or kc
    if isinstance(key, str):
        kc = KEYS[key]
        hard_tol = hard_tol or 95
        soft_tol = soft_tol or 150
    else:
        kc = key
        hard_tol = hard_tol or 30
        soft_tol = soft_tol or 70
    dist = np.sqrt(((rgb - np.array(kc, dtype=np.int16)) ** 2).sum(axis=2).astype(float))
    hard = dist <= hard_tol
    # a chroma key is background wherever it is (the hole between an arm and a body is not connected to the
    # border); a flat field is keyed only where it touches the border, so a cream cap survives a cream field
    bg = hard if isinstance(key, str) else _label_from_border(hard)
    # the soft band: pixels touching the background whose colour is part key, part figure
    band = np.zeros_like(bg)
    for dy, dx in ((1, 0), (-1, 0), (0, 1), (0, -1), (1, 1), (-1, -1), (1, -1), (-1, 1)):
        shifted = np.roll(np.roll(bg, dy, axis=0), dx, axis=1)
        band |= shifted
    band &= ~bg
    band &= dist <= soft_tol
    alpha = arr[:, :, 3].astype(float)
    alpha[bg] = 0
    ramp = np.clip((dist - hard_tol) / max(1.0, soft_tol - hard_tol), 0.0, 1.0)
    alpha[band] = np.minimum(alpha[band], 255.0 * (0.25 + 0.75 * ramp[band]))
    out = arr.copy()
    if isinstance(key, str):  # despill the band: pull the key channels down to the others
        r, g, b = out[:, :, 0], out[:, :, 1], out[:, :, 2]
        if key == "magenta":
            cap = g + 40
            r[band] = np.minimum(r[band], cap[band]); b[band] = np.minimum(b[band], cap[band])
        else:
            cap = np.maximum(r, b) + 40
            g[band] = np.minimum(g[band], cap[band])
    out[:, :, 3] = alpha.astype(np.int16)
    res = Image.fromarray(out.clip(0, 255).astype(np.uint8), "RGBA")
    a = res.split()[3]
    bbox = a.point(lambda v: 255 if v > 8 else 0).getbbox()
    if not bbox:
        raise SystemExit(f"cut: nothing left after keying {src}")
    res = res.crop(bbox)
    w, h = res.size
    side = int(max(w, h) * (1 + 2 * MARGIN))
    canvas = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    canvas.paste(res, ((side - w) // 2, (side - h) // 2))
    if side > OUT_PX:
        canvas = canvas.resize((OUT_PX, OUT_PX), Image.LANCZOS)
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    canvas.save(dst, optimize=True)
    fw, fh, clear, _ = plate_facts(dst)
    return {"src": src, "dst": dst, "key": key if isinstance(key, str) else "flat %s" % (kc,), "figure": (w, h), "size": (fw, fh),
            "border_clear": round(clear, 3), "keyed": round(float(bg.mean()), 3)}


# ---------------------------------------------------------------- plan ----
def statuses(arts, by_sheet):
    """One dict per sheet character: id, tier, status (READY / CUT / GENERATE), details."""
    use = usage_counts()
    out = []
    for a in arts:
        s = by_sheet.get(a["id"])
        if not s:
            continue
        fb = (a.get("fullBody") or "").replace("\\", "/")
        lead = (a.get("image") or "").replace("\\", "/")
        cand = fb or lead
        path = os.path.join(RM, cand) if cand and not cand.startswith("http") else None
        facts = plate_facts(path) if path and os.path.isfile(path) else (0, 0, 0.0, None)
        w, h, clear, flat = facts
        if clear >= BORDER_CLEAR and max(w, h) >= MIN_PX:
            status = "READY" if fb else "READY-LEAD"
        elif clear >= BORDER_CLEAR:
            status = "SMALL"           # transparent, but under MIN_PX — regenerate when it matters
        elif flat is not None and max(w, h) >= MIN_PX and a["id"] not in NO_REFERENCE and a["id"] not in FORCE_GENERATE:
            status = "CUT"
        else:
            status = "GENERATE"
        tier = 1 if s.get("party") else 2 if use.get(a["id"], 0) >= 3 else 3
        out.append(dict(id=a["id"], name=a.get("name", a["id"]), tier=tier, uses=use.get(a["id"], 0), status=status,
                        source=s.get("source"), candidate=cand, size=(w, h), border_clear=round(clear, 2), flat=flat,
                        generated=bool(a.get("generatedBy"))))
    out.sort(key=lambda r: (r["tier"], -r["uses"], r["id"]))
    return out


def cmd_plan(a):
    arts, by_sheet = load()
    rows = statuses(arts, by_sheet)
    by_id = {x["id"]: x for x in arts}
    counts = {}
    for r in rows:
        counts[r["status"]] = counts.get(r["status"], 0) + 1
    print("token plates: " + ", ".join(f"{k} {v}" for k, v in sorted(counts.items())) + f" — {len(rows)} sheet characters")
    todo = [r for r in rows if r["status"] in ("GENERATE", "SMALL", "CUT") and (not a.tier or r["tier"] <= a.tier)]
    if a.ids:
        todo = [r for r in rows if r["id"] in set(a.ids)]
    print(f"{'id':<36} {'tier':>4} {'uses':>4} {'status':<10} {'size':<10} candidate")
    for r in todo:
        print(f"{r['id']:<36} {r['tier']:>4} {r['uses']:>4} {r['status']:<10} {'%dx%d' % r['size']:<10} {r['candidate']}")
    manifest = []
    for r in todo:
        if r["status"] in ("GENERATE", "SMALL") or a.ids:     # named ids are rendered whatever their status
            prompt, key = prompt_for(by_id[r["id"]])
            art = by_id[r["id"]]
            fb = (art.get("fullBody") or "").replace("\\", "/")
            ref = "" if r["id"] in NO_REFERENCE else (fb if fb and os.path.isfile(os.path.join(RM, fb)) else (art.get("image") or ""))
            if not ref:
                summary = re.sub(r"\s+", " ", by_id[r["id"]].get("summary") or "")[:400]
                prompt = prompt.replace("The same character and the same art style as the reference image, with the same face, colours and wardrobe. ",
                                        f"Who they are: {summary} Painterly fantasy illustration, the archive's house style. ")
            manifest.append(dict(id=r["id"], name=r["name"], tier=r["tier"], key=key, prompt=prompt,
                                 reference=os.path.join("Reputation-Matrix2", ref).replace("\\", "/") if ref else None,
                                 out=f"{PLATES}/{r['id']}.png"))
        else:
            manifest.append(dict(id=r["id"], name=r["name"], tier=r["tier"], cut_from=r["candidate"], flat=r["flat"], out=f"{PLATES}/{r['id']}.png"))
    if a.manifest:
        os.makedirs(os.path.dirname(os.path.abspath(a.manifest)), exist_ok=True)
        json.dump(manifest, open(a.manifest, "w", encoding="utf-8"), indent=1, ensure_ascii=False)
        print(f"manifest: {len(manifest)} entries -> {a.manifest}")
    return 0


# ----------------------------------------------------------------- cut ----
def cmd_cut(a):
    arts, by_sheet = load()
    by_id = {x["id"]: x for x in arts}
    jobs = []
    if a.flat:
        for r in statuses(arts, by_sheet):
            if r["status"] == "CUT" and (not a.ids or r["id"] in set(a.ids)):
                jobs.append((r["id"], os.path.join(RM, r["candidate"]), "auto"))
    elif a.raw_dir:
        import glob
        for f in sorted(glob.glob(os.path.join(os.path.expanduser(a.raw_dir), "*.*"))):
            cid = os.path.splitext(os.path.basename(f))[0]
            if cid in by_id and f.lower().endswith(IMAGE_EXT) and (not a.ids or cid in set(a.ids)):
                jobs.append((cid, f, a.key))
    else:
        if not a.id or not a.src:
            raise SystemExit("cut: --id and --src (or --flat, or --raw-dir)")
        jobs.append((a.id, a.src, a.key))
    for cid, src, key in jobs:
        if cid not in by_id:
            raise SystemExit(f"cut: no article {cid}")
        dst = os.path.join(RM, PLATES, cid + ".png")
        if os.path.abspath(src) == os.path.abspath(dst):
            tmp = dst + ".orig.png"
            os.replace(dst, tmp)
            src = tmp
        facts = cut(src, dst, key)
        if src.endswith(".orig.png"):
            os.remove(src)
        flag = "" if facts["border_clear"] >= BORDER_CLEAR and max(facts["size"]) >= MIN_PX else "  <-- CHECK"
        print(f"cut {cid:<34} {facts['key']:<16} figure {facts['figure'][0]}x{facts['figure'][1]} -> {facts['size'][0]}px  keyed {facts['keyed']:.0%}  border clear {facts['border_clear']:.0%}{flag}")
    return 0


# --------------------------------------------------------------- pixel ----
PIXEL_MAX_PX = 260
PIXEL_TARGET = 640


def is_pixel_art(path):
    from PIL import Image
    im = Image.open(path)
    if max(im.size) > PIXEL_MAX_PX:
        return False
    colours = im.convert("RGBA").getcolors(4096)
    return colours is not None and len(colours) <= 1024


def pixel_plate(src, dst):
    """Crop a pixel sprite to its tallest block of content (the figure; the label under it goes), scale by whole pixels."""
    from PIL import Image
    np = _np()
    im = Image.open(src).convert("RGBA")
    arr = np.asarray(im).copy()
    a = arr[:, :, 3] > 0
    try:  # stray marks (an apostrophe, a lost pixel) are not the figure
        from scipy import ndimage
        lab, n = ndimage.label(a)
        sizes = ndimage.sum(a, lab, range(1, n + 1))
        main = int(np.argmax(sizes)) + 1
        cols_main = np.where((lab == main).any(axis=0))[0]
        c0, c1 = cols_main[0] - 4, cols_main[-1] + 4
        for i, sz in enumerate(sizes, 1):
            cols_i = np.where((lab == i).any(axis=0))[0]
            if sz < 6 or cols_i[-1] < c0 or cols_i[0] > c1:   # a lost pixel, or a glyph beside the figure
                arr[lab == i] = 0
        a = arr[:, :, 3] > 0
        im = Image.fromarray(arr, "RGBA")
    except ImportError:
        pass
    widths = a.sum(axis=1)
    rows = np.where(widths > 3)[0]          # a row with <= 3 lit pixels is a gap (or the thread of a stray glyph)
    if not len(rows):
        raise SystemExit(f"pixel: {src} is empty")
    blocks, start, prev = [], rows[0], rows[0]
    for r in rows[1:]:
        if r - prev > 2:
            blocks.append((start, prev)); start = r
        prev = r
    blocks.append((start, prev))
    top, bottom = max(blocks, key=lambda b: b[1] - b[0])
    sub = a[top:bottom + 1]
    cols = np.where(sub.max(axis=0) > 0)[0]
    fig = im.crop((int(cols[0]), int(top), int(cols[-1]) + 1, int(bottom) + 1))
    k = max(1, -(-PIXEL_TARGET // max(fig.size)))
    fig = fig.resize((fig.width * k, fig.height * k), Image.NEAREST)
    side = int(max(fig.size) * (1 + 2 * MARGIN))
    canvas = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    canvas.paste(fig, ((side - fig.width) // 2, (side - fig.height) // 2))
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    canvas.save(dst, optimize=True)
    return k, fig.size, len(blocks) - 1


def cmd_pixel(a):
    arts, by_sheet = load()
    by_id = {x["id"]: x for x in arts}
    ids = a.ids or [r["id"] for r in statuses(arts, by_sheet) if r["status"] == "SMALL" and r["candidate"]
                    and is_pixel_art(os.path.join(RM, r["candidate"])) and r["id"] not in NO_REFERENCE]
    for cid in ids:
        src = os.path.join(RM, (by_id[cid].get("image") or "").replace("\\", "/"))
        k, size, dropped = pixel_plate(src, os.path.join(RM, PLATES, cid + ".png"))
        print(f"pixel {cid:<32} x{k} -> {size[0]}x{size[1]}  ({dropped} label block(s) dropped)")
    return 0


# --------------------------------------------------------------- apply ----
def cmd_apply(a):
    arts = json.load(open(CHARACTERS, encoding="utf-8"))
    date = a.date or dt.date.today().isoformat()
    changed = []
    for art in arts:
        rel = f"{PLATES}/{art['id']}.png"
        path = os.path.join(RM, rel)
        if not os.path.isfile(path):
            continue
        if (art.get("fullBody") or "").replace("\\", "/") == rel:
            continue
        w, h, clear, _ = plate_facts(path)
        if clear < BORDER_CLEAR:
            print(f"apply: {art['id']} plate is not transparent — not wired")
            continue
        caption = (f"Full-body token plate — {art.get('name', art['id'])} head to foot on a transparent field, the look of the lead; "
                   f"cut from a keyed render on {date} for the table's token.")
        items = list(art.items())
        anchor = "imageCaption" if "imageCaption" in art else "image"
        new = {}
        for k, v in items:
            if k in ("fullBody", "fullBodyCaption"):
                continue
            new[k] = v
            if k == anchor:
                new["fullBody"] = rel
                new["fullBodyCaption"] = art.get("fullBodyCaption") or caption
        if "fullBody" not in new:  # no image key at all
            new["fullBody"] = rel
            new["fullBodyCaption"] = caption
        art.clear()
        art.update(new)
        changed.append(art["id"])
    if changed:
        tmp = CHARACTERS + ".tmp"
        with open(tmp, "w", encoding="utf-8") as fh:
            fh.write(json.dumps(arts, indent=2, ensure_ascii=False) + "\n")
        os.replace(tmp, CHARACTERS)
    print(f"apply: {len(changed)} article(s) now point at a plate" + (": " + ", ".join(changed) if changed else ""))
    return 0


# --------------------------------------------------------------- check ----
def cmd_check(a):
    arts, by_sheet = load()
    bad = []
    n = 0
    for art in arts:
        fb = (art.get("fullBody") or "").replace("\\", "/")
        if not fb:
            continue
        n += 1
        path = os.path.join(RM, fb)
        if not os.path.isfile(path):
            bad.append((art["id"], "missing file " + fb)); continue
        w, h, clear, _ = plate_facts(path)
        if clear < BORDER_CLEAR:
            bad.append((art["id"], f"not transparent ({clear:.0%} of the border clear) {fb}"))
        elif max(w, h) < MIN_PX and not art.get("generatedBy"):
            bad.append((art["id"], f"{w}x{h} is under {MIN_PX} px {fb}"))
    rows = statuses(arts, by_sheet)
    left = [r for r in rows if r["status"] not in ("READY", "READY-LEAD")]
    print(f"token plates: {n} fullBody plate(s), {len(bad)} problem(s); {len(rows) - len(left)}/{len(rows)} sheet characters token-ready "
          f"({sum(1 for r in left if r['tier'] == 1)} party, {sum(1 for r in left if r['tier'] == 2)} placed, {sum(1 for r in left if r['tier'] == 3)} other still to do)")
    for cid, why in bad:
        print(f"  {cid:<36} {why}")
    return 1 if (bad and a.check) else 0


# --------------------------------------------------------------- sheet ----
def cmd_sheet(a):
    from PIL import Image, ImageDraw, ImageFont
    arts, by_sheet = load()
    ids = a.ids or [x["id"] for x in arts if (x.get("fullBody") or "").replace("\\", "/").startswith(PLATES)]
    by_id = {x["id"]: x for x in arts}
    cell, cols = a.cell, a.cols
    rows = (len(ids) + cols - 1) // cols
    sheet = Image.new("RGB", (cols * cell, rows * (cell + 14)), "#5a7d5a")
    d = ImageDraw.Draw(sheet)
    font = ImageFont.load_default(size=11)
    for i, cid in enumerate(ids):
        art = by_id.get(cid, {})
        rel = (art.get("fullBody") or art.get("image") or "").replace("\\", "/")
        if os.path.isfile(os.path.join(RM, PLATES, cid + ".png")):   # the plate on disk, wired or not yet
            rel = f"{PLATES}/{cid}.png"
        x, y = (i % cols) * cell, (i // cols) * (cell + 14)
        try:
            im = Image.open(os.path.join(RM, rel)).convert("RGBA")
            im.thumbnail((cell - 4, cell - 4))
            sheet.paste(im, (x + 2, y + 2), im)
        except Exception as exc:  # noqa: BLE001
            d.text((x + 4, y + 4), f"n/a {exc}"[:30], fill="red", font=font)
        d.text((x + 2, y + cell), cid[:30], fill="white", font=font)
    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    sheet.save(a.out, quality=85)
    print(f"sheet: {len(ids)} plates -> {a.out} {sheet.size}")
    return 0


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("plan"); p.add_argument("--manifest"); p.add_argument("--tier", type=int); p.add_argument("--ids", nargs="*")
    p = sub.add_parser("cut"); p.add_argument("--id"); p.add_argument("--src"); p.add_argument("--key", default="auto"); p.add_argument("--flat", action="store_true"); p.add_argument("--raw-dir"); p.add_argument("--ids", nargs="*")
    p = sub.add_parser("apply"); p.add_argument("--date")
    p = sub.add_parser("check"); p.add_argument("--check", action="store_true")
    p = sub.add_parser("pixel"); p.add_argument("--ids", nargs="*")
    p = sub.add_parser("sheet"); p.add_argument("--out", required=True); p.add_argument("--ids", nargs="*"); p.add_argument("--cell", type=int, default=160); p.add_argument("--cols", type=int, default=10)
    a = ap.parse_args(argv)
    return {"plan": cmd_plan, "cut": cmd_cut, "apply": cmd_apply, "check": cmd_check, "sheet": cmd_sheet, "pixel": cmd_pixel}[a.cmd](a)


if __name__ == "__main__":
    sys.exit(main())
