#!/usr/bin/env python3
"""make-token-plates.py — full-body transparent plates for the table, in batches.

A token on the map wants the whole figure on a transparent field. The portraits
stay what they are (the article's picture); the plate is a second file,
`portraits/player/fullbody/<id>.png`, wired as `fullBody` on the article, and
the sheet builder puts it on the prototype token (`token_of()`).

The batch is a pipeline; a grid is one way to feed it. One figure per render
is the quality path (the lead as reference keeps the likeness, ~1024 px a
figure); an RxC sheet trades that for count (a 3x3 at 1024 px is ~340 px a
figure and the generator must keep ten likenesses straight at once) — right
for background NPCs and the roster toads, wrong for the party. The tool here
renders one subject per image, so `plan --grid` exists for a generator that
does not: it writes one prompt per sheet, and `cut --grid-sheet` slices and
keys what comes back.

  plan    which sheet characters are READY / CUT (a flat field to key) /
          GENERATE (needs a render), in table-use order, and a manifest of
          prompts built from the article (look from the appearance captions,
          the lead as the reference image, a key colour the character does not
          wear).
  cut     key a render (or an opaque plate on a flat field) into a trimmed,
          square, transparent PNG — magenta / green chroma or the border colour.
  apply   write `fullBody` + `fullBodyCaption` for every plate on disk that the
          article does not point at yet (characters.json round-trips as is).
  check   every `fullBody` is a real transparent plate (alpha border, >= MIN_PX);
          `--check` exits 1 otherwise.
  pixel   a pixel-art sprite (the Bone-Line cast): keep the figure, drop the burnt-in name under it,
          scale by whole pixels to >= 640 px — pixel art is regenerated by nobody.
  render  the hands-off loop: for every sheet character still without a plate, in table-use order,
          pad the reference onto a key-colour canvas, send prompt + reference to the local ComfyUI
          (a Comfy Desktop instance or classic install on :8188, the legacy app on :8000; Qwen-Image-2.1 when the server has
          it — native alpha — else Qwen-Image-Edit; your own exported API-format workflow with --workflow),
          wait, cut, QC (keyed field, clear border, nothing cropped), retry with a new seed, apply,
          next. Resumable: a plate on disk is skipped. Ctrl-C between characters is safe. The prompt, the
          canvas and the QC follow the character's body plan (`bodyPlan` on the article, else the race line):
          only a biped is asked for legs and feet — a Toad stays short, a Boo floats, a flower keeps its stem.
          --full is the hands-off run: every tier, the best attempt kept when none passes QC (flagged
          "needs eyes" in the caption + log), the reference-less drawn from the record on a 2.1 server,
          a contact sheet at the end; review in git, `drop` the bad ones, re-render them with --ids --redo.
  drop    take plates back out (file + fullBody wiring) — the undo for a plate that failed the eye.
  heal    re-check every chroma-keyed plate on disk pixel by pixel against its key colour and give back
          the figure pixels an earlier keyer (int16 overflow, before 2026-10-05) punched out — specks
          in dark purples / blues / reds. Idempotent; `check` reports plates that still need it.
  sheet   a contact sheet of plates for the eyeball pass.

  python3 tools/make-token-plates.py plan [--manifest /tmp/plates/manifest.json] [--tier 1]
  python3 tools/make-token-plates.py plan --grid 3 3 --manifest grids.json   # one prompt per 3x3 sheet, for a generator that draws grids
  python3 tools/make-token-plates.py cut  --grid-sheet grid-01.png --rows 3 --cols 3 --ids a b c d e f g h i   # slice + key a rendered sheet
  python3 tools/make-token-plates.py cut  --id waluigi --src /tmp/plates/raw/waluigi.png [--key magenta|green|auto]
  python3 tools/make-token-plates.py cut  --flat                 # key every opaque plate whose field is flat
  python3 tools/make-token-plates.py cut  --raw-dir ~/renders    # every <id>.png rendered elsewhere from the manifest
  python3 tools/make-token-plates.py render                      # drive the local ComfyUI (Qwen-Image-2.1 in Comfy Desktop) through everything left
  python3 tools/make-token-plates.py render --workflow my_qwen_edit_api.json --tier 2 --limit 20
  python3 tools/make-token-plates.py render --full               # everything, hands-off (start.bat plates); then: git status, drop the bad ones
  python3 tools/make-token-plates.py drop --ids kyrn pet_rock     # undo two plates the eye rejected
  python3 tools/token-plate-studio.py                            # the same loop with eyes on it: preview, crop, key, remove background, accept
  python3 tools/make-token-plates.py apply [--date 2026-10-05]
  python3 tools/make-token-plates.py check
  python3 tools/make-token-plates.py sheet --out /tmp/plates/sheet.jpg [--ids a b c]

Needs Pillow + numpy (+ scipy for a fast flood fill; falls back without).
"""
import argparse
import datetime as dt
import json
import os
import re
import sys

if hasattr(sys.stdout, "reconfigure"):          # Windows consoles default to cp1252; the names here are not
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
ROOT = os.environ.get("TOKEN_PLATES_ROOT") or os.path.dirname(os.path.dirname(os.path.abspath(__file__)))   # tests point this at a scratch tree
RM = os.path.join(ROOT, "Reputation-Matrix2")
CHARACTERS = os.path.join(RM, "data", "characters.json")
SHEETS = os.path.join(RM, "data", "sheets.json")
EVENTS = os.path.join(RM, "data", "events.json")
PLATES = "portraits/player/fullbody"
MIN_PX = 400          # a token that survives zoom (the 500 px cut-out shelf and the 550 px roster cuts count)
OUT_PX = 1024         # plates are downscaled to this on the long side, never upscaled
BORDER_CLEAR = 0.95   # share of border pixels that must be transparent
MARGIN = 0.04         # empty space around the trimmed figure

KEYS = {"magenta": (255, 0, 255), "green": (0, 255, 0)}
IMAGE_EXT = (".png", ".jpg", ".jpeg", ".webp")
# leads that are not a picture of the character (an icon, a letter, an event scene): never a reference, never cut
NO_REFERENCE = {"kyrn", "gee_lady", "pet_rock", "prunsel", "scorncrow", "alistair_marshkeeper", "cosmic_jester", "director_mario",
                "evil_mario", "lord_darian_marsh", "marilyn_the_chambermaid", "gabriel_freddy", "creek_medic_scene"}
# a flat border around a scene: the lead is a fine reference but nothing to key — render instead
FORCE_GENERATE = {"john_lee", "paulo"}
# wardrobe in the magenta family — key these on green instead
GREEN_KEY_IDS = {"waluigi", "wario", "princess_peach", "captain_toadette", "birdo", "vivian_corvinarus", "ryan", "purple_t", "toadette",
                 "lady_aurelian", "earl_grey", "kamek"}
GREEN_KEY_WORDS = re.compile(r"\b(purple|pink|magenta|violet|plum|lilac|fuchsia|mauve|lavender)\b", re.I)
MAGENTA_KEY_WORDS = re.compile(r"\b(green|emerald|olive|frog|moss|lime)\b", re.I)


# ---------------------------------------------------------------- data ----
def load():
    arts = json.load(open(CHARACTERS, encoding="utf-8"))
    sheets = json.load(open(SHEETS, encoding="utf-8"))
    rows = sheets.get("sheets", sheets) if isinstance(sheets, dict) else sheets
    return arts, {r["id"]: r for r in rows}


def usage_counts():
    """How often each article id is named in the events file — the proxy for 'placed on the map'."""
    try:
        text = open(EVENTS, encoding="utf-8").read()
    except OSError:
        return {}
    return {m: text.count('"%s"' % m) for m in set(re.findall(r'"([a-z0-9_]+)"', text))}


def look_of(a):
    """One line of established look from the appearance captions, else nothing (the reference carries it)."""
    for key in ("fullBodyCaption", "imageCaption"):
        cap = (a.get(key) or "").strip()
        if cap.startswith("Full-body token plate"):   # the pipeline's own caption says nothing about the look
            continue
        if cap:
            cap = re.sub(r"^(Lead plate|Full-body plate|Full-body token plate)\s*[—-]+\s*(established look:)?\s*", "", cap, flags=re.I)
            cap = re.split(r"\.\s+(?:Full figure|Replaces|Painted|The token|Her own|Found|Cut from)", cap)[0]
            return cap.strip().rstrip(".")
    return ""


# ----------------------------------------------------------- body plan ----
# How the character is built. Every prompt used to demand "a standing figure from the top of the head to the soles
# of the feet" of everyone, on a tall portrait canvas, with QC throwing out anything under 45 % of the frame tall and
# the retry loop keeping the tallest — so Fawful, Boos and a flower came back as tall humans with legs. The plan is
# the article's `bodyPlan` (one of the names below, or a free sentence — docs/IMAGE_GUIDELINES.md §4), else read from
# the race line; `unknown` tells the model to judge the body from the reference and never to invent human legs.
BODY_PLANS = {
    "biped": "a standing humanoid of ordinary proportions — head, torso, two arms, two legs and feet",
    "short": ("a short, big-headed figure — the head about as big as all the rest, a small stocky body, short arms and short "
              "legs; not tall, not slender, not human proportions"),
    "goomba": "a Goomba — one round mushroom-shaped body that is also the head, no arms, two small feet directly under it, no legs",
    "floating": "a floating ghost — a round body with little arms, no legs and no feet, nothing below the body; it hovers",
    "ghost": "a ghost — the figure as the reference shows it, fading away into mist below; no legs and no feet unless the reference shows them",
    "object": "a solid round or block-shaped body with no limbs beyond what the reference shows — no human arms, no human legs",
    "plant": "a plant — a flower or leafy head on a stem growing from leaves, roots or soil; no legs, no feet, no arms unless the reference shows them",
    "quadruped": "a four-legged animal body, the torso rising from it if the reference shows one",
    "serpent": "a serpent's tail in place of legs — no legs, no feet",
    "unknown": ("the body this creature would really have, judged from the reference — a person gets a normal standing body with legs "
                "and feet; a floating, round, plant-like or animal creature gets its own kind of body and no human legs"),
}
RACE_PLANS = [                                   # first match on the race line wins
    (r"\bgoomba", "goomba"),
    (r"\bboo\b", "floating"),
    (r"\b(ghost|spirit(?!-)|spectre|specter|wraith|phantom|poltergeist)\b", "ghost"),     # "Spirit-Walker" is a title, not a ghost
    (r"\b(chain ?chomp|bob-?omb|thwomp|whomp|bullet bill|slime|blob|golem)\b", "object"),
    (r"\b(piranha|plant|flower|spore monster|fungus|fungal|shroom)\b", "plant"),
    (r"\bcentaur\b", "quadruped"),
    (r"\b(naga|lamia|yuan-ti|serpentfolk|snake-?bodied)\b", "serpent"),
    (r"\b(toad|toadette|beanish|koopa|magikoopa|shy guy|penguin|kirby)\b", "short"),
    (r"\b(human|dwarf|dwarven|elf|elven|orc|goblin|hobgoblin|vampire|satyr|kremling|rakasha|rakshasa|fey|fairy|skeleton|bone|medusa|"
     r"tiefling|dragonborn|gnome|halfling|kivotan)\b", "biped"),
]
TALL_PLANS = {"biped"}                           # the only build that wants a portrait canvas and a tall figure
PLAN_MIN_HEIGHT = {"biped": 0.45, "unknown": 0.38}   # QC: a figure shorter than this share of the frame is "a bust?" — others 0.28
PLAN_BUST = {"biped": (0.60, 0.42, 0.05), "unknown": (0.60, 0.46, 0.05), "short": (0.62, 0.52, 0.06), "plant": (0.60, 0.50, 0.06),
             "quadruped": (0.60, 0.42, 0.05), "serpent": (0.60, 0.42, 0.05)}   # (max width, max height, top) of a bust on the canvas
PLAN_BUST_DEFAULT = (0.68, 0.62, 0.10)           # goomba / floating / ghost / object / custom: the "bust" is nearly the whole creature


def body_plan_of(a):
    """(plan name, build sentence) for an article: its `bodyPlan` (a name from BODY_PLANS, or a free sentence —
    that becomes plan "custom"), else the first RACE_PLANS match on the race line, else "unknown"."""
    field = (a.get("bodyPlan") or "").strip()
    if field:
        if field in BODY_PLANS:
            return field, BODY_PLANS[field]
        return "custom", field.rstrip(".")
    race = (a.get("race") or "").lower()
    race = re.sub(r"\b(?:confirmed\s+)?(?:not|never|no longer)\s+(?:a|an|the)?\s*[\w-]+", " ", race)   # "confirmed not a Toad" says what she is not
    for pat, plan in RACE_PLANS:
        if re.search(pat, race):
            return plan, BODY_PLANS[plan]
    return "unknown", BODY_PLANS["unknown"]


def plan_canvas(plan, engine):
    """The reference canvas (= the 2.1 output size): portrait for a biped, square for everything else, so a short or
    legless character is not handed half a page of empty field under its head."""
    if plan in TALL_PLANS:
        return REF_SIZES.get(engine, (1024, 1024))
    return (1024, 1024)


def plan_min_height(plan):
    return PLAN_MIN_HEIGHT.get(plan, 0.28)


def best_attempt(attempts):
    """The least-bad of several (why, path, seed, facts): fewest QC flags, then the biggest figure by area — not the
    tallest, which rewarded the stretched ones."""
    return min(attempts, key=lambda t: (len(t[0]), -(t[3]["figure"][0] * t[3]["figure"][1])))


def key_for(a):
    blob = " ".join(str(a.get(k) or "") for k in ("name", "imageCaption", "fullBodyCaption", "race"))
    if a["id"] in GREEN_KEY_IDS or (GREEN_KEY_WORDS.search(blob) and not MAGENTA_KEY_WORDS.search(blob)):
        return "green"
    return "magenta"


def prompt_for(a):
    name = a.get("name", a["id"])
    race = (a.get("race") or "").strip()
    title = (a.get("title") or "").strip()
    look = look_of(a)
    key = key_for(a)
    who = name + (f", {title}" if title and title.lower() not in name.lower() else "")
    who += f" ({race})" if race and race.lower() not in who.lower() else ""
    parts = [f"Full-body character token art of {who}."]
    if look:
        parts.append(f"Established look: {look}.")
    parts.append("The same character and the same art style as the reference image, with the same face, colours and wardrobe.")
    plan, build = body_plan_of(a)
    parts.append(f"The whole figure, nothing cropped, built exactly the way this character is built: {build}. "
                 "Relaxed neutral pose facing the viewer and turned slightly, weapon or tool held if the character carries one"
                 + ("; do not add legs, feet or human proportions the character does not have." if plan != "biped" else "."))
    parts.append("Centred with empty space on every side.")
    colour = "bright magenta (#FF00FF)" if key == "magenta" else "bright green (#00FF00)"
    parts.append(f"Plain solid flat {colour} background, no floor, no cast shadow on the ground, no scenery, no text, no border, no watermark.")
    return " ".join(parts), key


# --------------------------------------------------------------- image ----
def _np():
    import numpy as np
    return np


def plate_facts(path):
    """(width, height, border_clear, flat_key_or_None) for an image file."""
    from PIL import Image
    np = _np()
    im = Image.open(path)
    w, h = im.size
    has_alpha = im.mode in ("RGBA", "LA") or (im.mode == "P" and "transparency" in im.info)
    rgba = np.asarray(im.convert("RGBA"))
    ring = np.concatenate([rgba[0, :], rgba[-1, :], rgba[:, 0], rgba[:, -1]])
    clear = float((ring[:, 3] < 16).mean()) if has_alpha else 0.0
    flat = None
    if clear < BORDER_CLEAR:
        rgb = ring[:, :3].astype(float)
        med = np.median(rgb, axis=0)
        if np.sqrt(((rgb - med) ** 2).sum(axis=1)).mean() < 12 and (np.sqrt(((rgb - med) ** 2).sum(axis=1)) < 40).mean() > 0.97:
            flat = tuple(int(x) for x in med)
    return w, h, clear, flat


def _label_from_border(hard):
    """Boolean mask of hard-key pixels connected to the border."""
    np = _np()
    try:
        from scipy import ndimage
        lab, n = ndimage.label(hard)
        ids = set(np.unique(lab[0, :])) | set(np.unique(lab[-1, :])) | set(np.unique(lab[:, 0])) | set(np.unique(lab[:, -1]))
        ids.discard(0)
        return np.isin(lab, list(ids)) if ids else np.zeros_like(hard)
    except ImportError:
        reach = np.zeros_like(hard)
        reach[0, :] = hard[0, :]; reach[-1, :] = hard[-1, :]; reach[:, 0] = hard[:, 0]; reach[:, -1] = hard[:, -1]
        while True:
            grown = reach.copy()
            grown[1:, :] |= reach[:-1, :]; grown[:-1, :] |= reach[1:, :]
            grown[:, 1:] |= reach[:, :-1]; grown[:, :-1] |= reach[:, 1:]
            grown &= hard
            if (grown == reach).all():
                return reach
            reach = grown


def square_plate(fig, key_rgb):
    """Centre a keyed figure on a square transparent canvas with MARGIN around it. A figure that already fits
    OUT_PX is never resampled (the margin gives first); a bigger one is downscaled, and because resampling
    premultiplies alpha, the key colour is written back under the clear pixels so later passes (specks, heal)
    can still tell background from figure."""
    from PIL import Image
    np = _np()
    w, h = fig.size
    side = int(max(w, h) * (1 + 2 * MARGIN))
    if side > OUT_PX >= max(w, h):
        side = OUT_PX
    canvas = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    canvas.paste(fig, ((side - w) // 2, (side - h) // 2))
    if side > OUT_PX:
        canvas = canvas.resize((OUT_PX, OUT_PX), Image.LANCZOS)
        arr = np.asarray(canvas).copy()
        arr[arr[:, :, 3] < 16, :3] = key_rgb
        canvas = Image.fromarray(arr, "RGBA")
    return canvas


def key_mask(rgb, key, dist, tol):
    """Pixels that are background for a chroma key: within `tol` of the key colour, or the key's own hue in
    shadow — generators like to shade the field near the figure to a dark magenta / dark green, and that has
    to go too. Only chroma keys get the hue rule; a flat field is matched by distance alone."""
    np = _np()
    hard = dist <= tol
    if key in KEYS:
        r, g, b = rgb[:, :, 0], rgb[:, :, 1], rgb[:, :, 2]
        top = rgb.max(axis=2)
        if key == "magenta":
            hard |= (top >= 30) & (top - g >= 20) & (g <= top * 0.35) & (np.abs(r - b) <= top * 0.3 + 8)
        else:
            hard |= (g >= 30) & (g - np.maximum(r, b) >= 20) & (g >= np.maximum(r, b) * 1.8)
    return hard


def cut(src, dst, key="auto", hard_tol=None, soft_tol=None):
    """Key `src` into a trimmed, square, transparent PNG at `dst`. Returns a facts dict."""
    from PIL import Image
    np = _np()
    im = Image.open(src).convert("RGBA")
    has_alpha = Image.open(src).mode in ("RGBA", "LA", "PA") or (Image.open(src).mode == "P" and "transparency" in Image.open(src).info)
    if key == "alpha" or (key == "auto" and has_alpha and plate_facts(src)[2] >= BORDER_CLEAR):
        # the generator drew the alpha itself (Qwen-Image-2.1 does): trim, square, done — nothing to key
        a = im.split()[3]
        bbox = a.point(lambda v: 255 if v > 8 else 0).getbbox()
        if not bbox:
            raise SystemExit(f"cut: {src} is entirely transparent")
        res = im.crop(bbox)
        w, h = res.size
        canvas = square_plate(res, (0, 0, 0))
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        canvas.save(dst, optimize=True)
        fw, fh, clear, _ = plate_facts(dst)
        keyed = float((np.asarray(im)[:, :, 3] < 16).mean())
        return {"src": src, "dst": dst, "key": "alpha", "figure": (w, h), "size": (fw, fh), "border_clear": round(clear, 3), "keyed": round(keyed, 3)}
    arr = np.asarray(im).astype(np.int32)   # int32: a squared channel difference does not fit int16
    rgb = arr[:, :, :3]
    if key == "auto":
        ring = np.concatenate([rgb[0, :], rgb[-1, :], rgb[:, 0], rgb[:, -1]]).astype(float)
        kc = tuple(int(x) for x in np.median(ring, axis=0))
        chroma = None
        for name, val in KEYS.items():
            if np.sqrt(((np.array(kc) - np.array(val)) ** 2).sum()) < 90:
                chroma = name
        key = chroma or kc
    if isinstance(key, str):
        kc = KEYS[key]
        hard_tol = hard_tol or 95
        soft_tol = soft_tol or 150
    else:
        kc = key
        hard_tol = hard_tol or 30
        soft_tol = soft_tol or 70
    dist = np.sqrt(((rgb - np.array(kc, dtype=np.int32)) ** 2).sum(axis=2).astype(float))
    hard = key_mask(rgb, key, dist, hard_tol)
    # a chroma key is background wherever it is (the hole between an arm and a body is not connected to the
    # border); a flat field is keyed only where it touches the border, so a cream cap survives a cream field
    bg = hard if isinstance(key, str) else _label_from_border(hard)
    # the soft band: pixels touching the background whose colour is part key, part figure
    band = np.zeros_like(bg)
    for dy, dx in ((1, 0), (-1, 0), (0, 1), (0, -1), (1, 1), (-1, -1), (1, -1), (-1, 1)):
        shifted = np.roll(np.roll(bg, dy, axis=0), dx, axis=1)
        band |= shifted
    band &= ~bg
    band &= dist <= soft_tol
    alpha = arr[:, :, 3].astype(float)
    alpha[bg] = 0
    ramp = np.clip((dist - hard_tol) / max(1.0, soft_tol - hard_tol), 0.0, 1.0)
    chroma = isinstance(key, str)
    if chroma:
        alpha[band] = np.minimum(alpha[band], 255.0 * (0.25 + 0.75 * ramp[band]))
    else:
        # A flat field's band holds a field/figure MIX at partial alpha; left as-is the
        # plate keeps a cream halo that reads as a white outline on a dark map. Take the
        # field out of the colour (un-matte) and let coverage fall to zero at the field.
        alpha[band] = 255.0 * ramp[band]
    out = arr.copy()
    if not chroma:
        live = band & (alpha >= 1)
        af = np.clip(alpha, 1.0, 255.0) / 255.0
        for ch in range(3):
            c = out[:, :, ch].astype(float)
            fixed = np.clip((c - (1.0 - af) * kc[ch]) / af, 0, 255)
            out[:, :, ch] = np.where(live, fixed, c).astype(np.int32)
        dead = band & (alpha < 1)
        for ch in range(3):
            out[:, :, ch][dead] = kc[ch]
    if chroma:  # despill the edge (the band and 3 px in): pull the key channels down to the others
        ring = band.copy()
        for _ in range(3):
            grown = ring | bg
            for dy, dx in ((1, 0), (-1, 0), (0, 1), (0, -1), (1, 1), (-1, -1), (1, -1), (-1, 1)):
                grown |= np.roll(np.roll(ring | bg, dy, axis=0), dx, axis=1)
            ring = grown & ~bg
        r, g, b = out[:, :, 0], out[:, :, 1], out[:, :, 2]
        if key == "magenta":
            cap = g + 40
            r[ring] = np.minimum(r[ring], cap[ring]); b[ring] = np.minimum(b[ring], cap[ring])
        else:
            cap = np.maximum(r, b) + 40
            g[ring] = np.minimum(g[ring], cap[ring])
    out[:, :, 3] = alpha.astype(np.int32)
    res = Image.fromarray(out.clip(0, 255).astype(np.uint8), "RGBA")
    a = res.split()[3]
    bbox = a.point(lambda v: 255 if v > 8 else 0).getbbox()
    if not bbox:
        raise SystemExit(f"cut: nothing left after keying {src}")
    res = res.crop(bbox)
    w, h = res.size
    canvas = square_plate(res, kc)
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    canvas.save(dst, optimize=True)
    fw, fh, clear, _ = plate_facts(dst)
    return {"src": src, "dst": dst, "key": key if isinstance(key, str) else "flat %s" % (kc,), "figure": (w, h), "size": (fw, fh),
            "border_clear": round(clear, 3), "keyed": round(float(bg.mean()), 3)}


def defringe(path, key=None, hard_tol=30, soft_tol=70):
    """Repair, in place, a plate that was cut from a flat field before the cut un-matted
    its blend band: the band still carries the field's colour at partial alpha, which on a
    dark background is a cream halo around the figure. Only the ring next to transparency
    is touched (interior translucency — a ghost, a glow — is art and stays). Returns facts."""
    from PIL import Image
    np = _np()
    im = Image.open(path).convert("RGBA")
    arr = np.asarray(im).astype(np.int32)
    rgb, alpha = arr[:, :, :3], arr[:, :, 3].astype(float)
    clear = alpha <= 12
    if key is None:
        seen = rgb[clear & (rgb.sum(axis=2) > 0)]
        key = tuple(int(x) for x in np.median(seen, axis=0)) if len(seen) else (247, 244, 234)
    near = clear
    for _ in range(2):
        grown = near.copy()
        for dy, dx in ((1, 0), (-1, 0), (0, 1), (0, -1), (1, 1), (-1, -1), (1, -1), (-1, 1)):
            grown |= np.roll(np.roll(near, dy, axis=0), dx, axis=1)
        near = grown
    dist = np.sqrt(((rgb - np.array(key, dtype=np.int32)) ** 2).sum(axis=2).astype(float))
    band = (alpha > 12) & near & (dist <= soft_tol)
    if not band.any():
        return {"path": path, "key": key, "fixed": 0}
    ramp = np.clip((dist - hard_tol) / max(1.0, soft_tol - hard_tol), 0.0, 1.0)
    out_alpha = np.where(band, 255.0 * ramp, alpha)
    live = band & (out_alpha >= 1)
    af = np.clip(out_alpha, 1.0, 255.0) / 255.0
    out = arr.copy()
    for ch in range(3):
        c = out[:, :, ch].astype(float)
        fixed = np.clip((c - (1.0 - af) * key[ch]) / af, 0, 255)
        out[:, :, ch] = np.where(live, fixed, c).astype(np.int32)
    dead = band & (out_alpha < 1)
    for ch in range(3):
        out[:, :, ch][dead] = key[ch]
    out[:, :, 3] = out_alpha.astype(np.int32)
    Image.fromarray(out.clip(0, 255).astype(np.uint8), "RGBA").save(path, optimize=True)
    return {"path": path, "key": key, "fixed": int(band.sum())}


def fringe_count(path, tol=30):
    """Semi-transparent pixels hugging transparency that still carry the FIELD's colour —
    the cream halo a flat-field cut leaves when it does not un-matte its blend band. A
    figure's own translucency (a ghost, a glow) is another colour and does not count;
    zero on a clean plate. Used by --check style gates."""
    np = _np()
    from PIL import Image
    a = np.asarray(Image.open(path).convert("RGBA")).astype(np.int32)
    al, rgb = a[:, :, 3], a[:, :, :3]
    clear = al <= 12
    seen = rgb[clear & (rgb.sum(axis=2) > 0)]
    key = np.median(seen, axis=0) if len(seen) else np.array([247, 244, 234])
    dist = np.sqrt(((rgb - key.astype(np.int32)) ** 2).sum(axis=2).astype(float))
    semi = (al > 12) & (al < 250) & (dist <= tol)
    near = clear.copy()
    for _ in range(2):
        grown = near.copy()
        for dy, dx in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            grown |= np.roll(near, dy, axis=0) | np.roll(near, dx, axis=1)
        near = grown
    return int((semi & near).sum())


# ---------------------------------------------------------------- plan ----
def statuses(arts, by_sheet):
    """One dict per sheet character: id, tier, status (READY / CUT / GENERATE), details."""
    use = usage_counts()
    out = []
    for a in arts:
        s = by_sheet.get(a["id"])
        if not s:
            continue
        fb = (a.get("fullBody") or "").replace("\\", "/")
        lead = (a.get("image") or "").replace("\\", "/")
        cand = fb or lead
        path = os.path.join(RM, cand) if cand and not cand.startswith("http") else None
        facts = plate_facts(path) if path and os.path.isfile(path) else (0, 0, 0.0, None)
        w, h, clear, flat = facts
        if clear >= BORDER_CLEAR and max(w, h) >= MIN_PX:
            status = "READY" if fb else "READY-LEAD"
        elif clear >= BORDER_CLEAR:
            status = "SMALL"           # transparent, but under MIN_PX — regenerate when it matters
        elif flat is not None and max(w, h) >= MIN_PX and a["id"] not in NO_REFERENCE and a["id"] not in FORCE_GENERATE:
            status = "CUT"
        else:
            status = "GENERATE"
        tier = 1 if s.get("party") else 2 if use.get(a["id"], 0) >= 3 else 3
        out.append(dict(id=a["id"], name=a.get("name", a["id"]), tier=tier, uses=use.get(a["id"], 0), status=status,
                        source=s.get("source"), candidate=cand, size=(w, h), border_clear=round(clear, 2), flat=flat,
                        generated=bool(a.get("generatedBy"))))
    out.sort(key=lambda r: (r["tier"], -r["uses"], r["id"]))
    return out


def cmd_plan(a):
    arts, by_sheet = load()
    rows = statuses(arts, by_sheet)
    by_id = {x["id"]: x for x in arts}
    counts = {}
    for r in rows:
        counts[r["status"]] = counts.get(r["status"], 0) + 1
    print("token plates: " + ", ".join(f"{k} {v}" for k, v in sorted(counts.items())) + f" — {len(rows)} sheet characters")
    todo = [r for r in rows if r["status"] in ("GENERATE", "SMALL", "CUT") and (not a.tier or r["tier"] <= a.tier)]
    if a.ids:
        todo = [r for r in rows if r["id"] in set(a.ids)]
    print(f"{'id':<36} {'tier':>4} {'uses':>4} {'status':<10} {'size':<10} candidate")
    for r in todo:
        print(f"{r['id']:<36} {r['tier']:>4} {r['uses']:>4} {r['status']:<10} {'%dx%d' % r['size']:<10} {r['candidate']}")
    if a.grid:
        return plan_grid(a, todo, by_id)
    manifest = []
    for r in todo:
        if r["status"] in ("GENERATE", "SMALL") or a.ids:     # named ids are rendered whatever their status
            prompt, key = prompt_for(by_id[r["id"]])
            art = by_id[r["id"]]
            fb = (art.get("fullBody") or "").replace("\\", "/")
            ref = "" if r["id"] in NO_REFERENCE else (fb if fb and os.path.isfile(os.path.join(RM, fb)) else (art.get("image") or ""))
            if not ref:
                summary = re.sub(r"\s+", " ", by_id[r["id"]].get("summary") or "")[:400]
                prompt = prompt.replace("The same character and the same art style as the reference image, with the same face, colours and wardrobe. ",
                                        f"Who they are: {summary} Painterly fantasy illustration, the archive's house style. ")
            manifest.append(dict(id=r["id"], name=r["name"], tier=r["tier"], key=key, prompt=prompt,
                                 reference=os.path.join("Reputation-Matrix2", ref).replace("\\", "/") if ref else None,
                                 out=f"{PLATES}/{r['id']}.png"))
        else:
            manifest.append(dict(id=r["id"], name=r["name"], tier=r["tier"], cut_from=r["candidate"], flat=r["flat"], out=f"{PLATES}/{r['id']}.png"))
    if a.manifest:
        os.makedirs(os.path.dirname(os.path.abspath(a.manifest)), exist_ok=True)
        json.dump(manifest, open(a.manifest, "w", encoding="utf-8"), indent=1, ensure_ascii=False)
        print(f"manifest: {len(manifest)} entries -> {a.manifest}")
    return 0


def plan_grid(a, todo, by_id):
    """One prompt per RxC sheet: the same key colour across a sheet, cells in reading order, references listed."""
    rows, cols = a.grid
    per = rows * cols
    todo = [r for r in todo if r["status"] in ("GENERATE", "SMALL") or a.ids]
    buckets = {"magenta": [], "green": []}
    for r in todo:
        buckets[key_for(by_id[r["id"]])].append(r)
    sheets = []
    for key, lst in buckets.items():
        for i in range(0, len(lst), per):
            chunk = lst[i:i + per]
            colour = "bright magenta (#FF00FF)" if key == "magenta" else "bright green (#00FF00)"
            cells = []
            refs = []
            for n, r in enumerate(chunk, 1):
                art = by_id[r["id"]]
                look = look_of(art)
                who = art.get("name", r["id"]) + (f", {art['title']}" if art.get("title") else "") + (f" ({art['race']})" if art.get("race") else "")
                plan, build = body_plan_of(art)
                cells.append(f"Cell {n}: {who}" + (f" — {look}" if look else "") + (f"; built as {build}" if plan != "biped" else "") + ".")
                ref = "" if r["id"] in NO_REFERENCE else ((art.get("fullBody") or "") if (art.get("fullBody") or "").startswith("portraits/player/fullbody/") else (art.get("image") or ""))
                refs.append(os.path.join("Reputation-Matrix2", ref).replace("\\", "/") if ref and not ref.startswith("http") else None)
            prompt = (f"A character token sheet: {len(chunk)} separate full-body figures arranged in a {rows} by {cols} grid of equal cells, "
                      f"read left to right then top to bottom, one figure per cell, each figure whole and uncropped and built the way that character is built "
                      f"(a person standing head to foot; a short big-headed Toad short; a ghost, plant or round creature without human legs), "
                      f"relaxed neutral pose facing the viewer, centred in its cell with empty space around it, no figure touching another or the cell edge. "
                      f"Plain solid flat {colour} background everywhere including the gutters between cells; no floor, no cast shadows, no scenery, no text, no labels, no borders, no watermark. "
                      f"Each figure matches the numbered reference image for that cell — same face, colours and wardrobe — and all share one painterly fantasy illustration style. "
                      + " ".join(cells))
            sheets.append(dict(sheet=f"grid-{len(sheets) + 1:02d}", rows=rows, cols=cols, key=key, ids=[r["id"] for r in chunk],
                               references=refs, prompt=prompt, out=[f"{PLATES}/{r['id']}.png" for r in chunk]))
    print(f"grid plan: {len(todo)} figures on {len(sheets)} sheet(s) of {rows}x{cols}" + (f" -> {a.manifest}" if a.manifest else ""))
    for sh in sheets:
        print(f"  {sh['sheet']}  {sh['key']:<7} {', '.join(sh['ids'])}")
    if a.manifest:
        os.makedirs(os.path.dirname(os.path.abspath(a.manifest)), exist_ok=True)
        json.dump(sheets, open(a.manifest, "w", encoding="utf-8"), indent=1, ensure_ascii=False)
    return 0


def _bands(occupied, min_gap):
    """[(start, end)] runs of occupied indices, merged across gaps shorter than min_gap."""
    np = _np()
    idx = np.where(occupied)[0]
    if not len(idx):
        return []
    bands, start, prev = [], idx[0], idx[0]
    for i in idx[1:]:
        if i - prev > min_gap:
            bands.append((int(start), int(prev))); start = i
        prev = i
    bands.append((int(start), int(prev)))
    return bands


def cut_grid(sheet_path, rows, cols, ids, key="auto"):
    """Key a rendered RxC sheet, find the cells by their empty gutters (equal cells if the gutters are not clean), one plate per id."""
    from PIL import Image
    np = _np()
    tmp = sheet_path + ".keyed.png"
    facts = cut(sheet_path, tmp, key)          # the whole sheet keyed, trimmed and squared — fine for finding figures
    im = Image.open(tmp).convert("RGBA")
    os.remove(tmp)
    a = np.asarray(im)[:, :, 3] > 8
    h, w = a.shape
    row_bands = _bands(a.any(axis=1), max(4, h // 60))
    boxes = []
    if len(row_bands) == rows:
        for (y0, y1) in row_bands:
            col_bands = _bands(a[y0:y1 + 1].any(axis=0), max(4, w // 60))
            if len(col_bands) != cols:
                boxes = []; break
            boxes += [(x0, y0, x1 + 1, y1 + 1) for (x0, x1) in col_bands]
    if not boxes:   # figures touch or the gutters are dirty: equal cells
        cw, ch = w / cols, h / rows
        boxes = [(int(c * cw), int(r * ch), int((c + 1) * cw), int((r + 1) * ch)) for r in range(rows) for c in range(cols)]
        print(f"  grid: gutters not clean on {os.path.basename(sheet_path)} — equal cells")
    out = []
    for cid, box in zip(ids, boxes):
        cell = im.crop(box)
        bbox = cell.split()[3].point(lambda v: 255 if v > 8 else 0).getbbox()
        if not bbox:
            print(f"  grid: {cid} cell is empty"); continue
        cell = cell.crop(bbox)
        cw, ch = cell.size
        canvas = square_plate(cell, KEYS[facts["key"]] if facts["key"] in KEYS else tuple(int(x) for x in re.findall(r"\d+", facts["key"])))
        dst = os.path.join(RM, PLATES, cid + ".png")
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        canvas.save(dst, optimize=True)
        out.append((cid, canvas.size[0], (cw, ch)))
        print(f"  grid: {cid:<32} figure {cw}x{ch} -> {canvas.size[0]}px" + ("  <-- small" if max(cw, ch) < MIN_PX else ""))
    return out


# ----------------------------------------------------------------- cut ----
def cmd_cut(a):
    arts, by_sheet = load()
    by_id = {x["id"]: x for x in arts}
    jobs = []
    if a.grid_sheet:
        if not (a.rows and a.cols and a.ids):
            raise SystemExit("cut: --grid-sheet needs --rows, --cols and --ids in reading order")
        cut_grid(a.grid_sheet, a.rows, a.cols, a.ids, a.key)
        return 0
    if a.flat:
        for r in statuses(arts, by_sheet):
            if r["status"] == "CUT" and (not a.ids or r["id"] in set(a.ids)):
                jobs.append((r["id"], os.path.join(RM, r["candidate"]), "auto"))
    elif a.raw_dir:
        import glob
        for f in sorted(glob.glob(os.path.join(os.path.expanduser(a.raw_dir), "*.*"))):
            cid = os.path.splitext(os.path.basename(f))[0]
            if cid in by_id and f.lower().endswith(IMAGE_EXT) and (not a.ids or cid in set(a.ids)):
                jobs.append((cid, f, a.key))
    else:
        if not a.id or not a.src:
            raise SystemExit("cut: --id and --src (or --flat, or --raw-dir)")
        jobs.append((a.id, a.src, a.key))
    for cid, src, key in jobs:
        if cid not in by_id:
            raise SystemExit(f"cut: no article {cid}")
        dst = os.path.join(RM, PLATES, cid + ".png")
        if os.path.abspath(src) == os.path.abspath(dst):
            tmp = dst + ".orig.png"
            os.replace(dst, tmp)
            src = tmp
        facts = cut(src, dst, key)
        if src.endswith(".orig.png"):
            os.remove(src)
        flag = "" if facts["border_clear"] >= BORDER_CLEAR and max(facts["size"]) >= MIN_PX else "  <-- CHECK"
        print(f"cut {cid:<34} {facts['key']:<16} figure {facts['figure'][0]}x{facts['figure'][1]} -> {facts['size'][0]}px  keyed {facts['keyed']:.0%}  border clear {facts['border_clear']:.0%}{flag}")
    return 0


# --------------------------------------------------------------- pixel ----
PIXEL_MAX_PX = 260
PIXEL_TARGET = 640


def is_pixel_art(path):
    from PIL import Image
    im = Image.open(path)
    if max(im.size) > PIXEL_MAX_PX:
        return False
    colours = im.convert("RGBA").getcolors(4096)
    return colours is not None and len(colours) <= 1024


def pixel_plate(src, dst):
    """Crop a pixel sprite to its tallest block of content (the figure; the label under it goes), scale by whole pixels."""
    from PIL import Image
    np = _np()
    im = Image.open(src).convert("RGBA")
    arr = np.asarray(im).copy()
    a = arr[:, :, 3] > 0
    try:  # stray marks (an apostrophe, a lost pixel) are not the figure
        from scipy import ndimage
        lab, n = ndimage.label(a)
        sizes = ndimage.sum(a, lab, range(1, n + 1))
        main = int(np.argmax(sizes)) + 1
        cols_main = np.where((lab == main).any(axis=0))[0]
        c0, c1 = cols_main[0] - 4, cols_main[-1] + 4
        for i, sz in enumerate(sizes, 1):
            cols_i = np.where((lab == i).any(axis=0))[0]
            if sz < 6 or cols_i[-1] < c0 or cols_i[0] > c1:   # a lost pixel, or a glyph beside the figure
                arr[lab == i] = 0
        a = arr[:, :, 3] > 0
        im = Image.fromarray(arr, "RGBA")
    except ImportError:
        pass
    widths = a.sum(axis=1)
    rows = np.where(widths > 3)[0]          # a row with <= 3 lit pixels is a gap (or the thread of a stray glyph)
    if not len(rows):
        raise SystemExit(f"pixel: {src} is empty")
    blocks, start, prev = [], rows[0], rows[0]
    for r in rows[1:]:
        if r - prev > 2:
            blocks.append((start, prev)); start = r
        prev = r
    blocks.append((start, prev))
    top, bottom = max(blocks, key=lambda b: b[1] - b[0])
    sub = a[top:bottom + 1]
    cols = np.where(sub.max(axis=0) > 0)[0]
    fig = im.crop((int(cols[0]), int(top), int(cols[-1]) + 1, int(bottom) + 1))
    k = max(1, -(-PIXEL_TARGET // max(fig.size)))
    fig = fig.resize((fig.width * k, fig.height * k), Image.NEAREST)
    side = int(max(fig.size) * (1 + 2 * MARGIN))
    canvas = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    canvas.paste(fig, ((side - fig.width) // 2, (side - fig.height) // 2))
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    canvas.save(dst, optimize=True)
    return k, fig.size, len(blocks) - 1


def cmd_pixel(a):
    arts, by_sheet = load()
    by_id = {x["id"]: x for x in arts}
    ids = a.ids or [r["id"] for r in statuses(arts, by_sheet) if r["status"] == "SMALL" and r["candidate"]
                    and is_pixel_art(os.path.join(RM, r["candidate"])) and r["id"] not in NO_REFERENCE]
    for cid in ids:
        src = os.path.join(RM, (by_id[cid].get("image") or "").replace("\\", "/"))
        k, size, dropped = pixel_plate(src, os.path.join(RM, PLATES, cid + ".png"))
        print(f"pixel {cid:<32} x{k} -> {size[0]}x{size[1]}  ({dropped} label block(s) dropped)")
    return 0


# --------------------------------------------------------------- apply ----
def cmd_apply(a):
    arts = json.load(open(CHARACTERS, encoding="utf-8"))
    date = a.date or dt.date.today().isoformat()
    changed = []
    for art in arts:
        rel = f"{PLATES}/{art['id']}.png"
        path = os.path.join(RM, rel)
        if not os.path.isfile(path):
            continue
        note = (getattr(a, "notes", None) or {}).get(art["id"])
        wired = (art.get("fullBody") or "").replace("\\", "/") == rel
        if wired and not note:
            continue
        w, h, clear, _ = plate_facts(path)
        if clear < BORDER_CLEAR:
            print(f"apply: {art['id']} plate is not transparent — not wired")
            continue
        plan = body_plan_of(art)[0]
        caption = (f"Full-body token plate — {art.get('name', art['id'])} whole on a transparent field, the look of the lead"
                   + (f", built as {plan}" if plan != "biped" else "")
                   + f"; {note or 'cut from a keyed render'} on {date} for the table's token.")
        existing = art.get("fullBodyCaption") or ""
        # a hand-written caption stays; the pipeline's own caption gives way to a note (needs eyes / drawn from the record)
        keep = existing if existing and not (note and existing.startswith("Full-body token plate")) else caption
        if wired:
            if art.get("fullBodyCaption") != keep:
                art["fullBodyCaption"] = keep
                changed.append(art["id"])
            continue
        items = list(art.items())
        anchor = "imageCaption" if "imageCaption" in art else "image"
        new = {}
        for k, v in items:
            if k in ("fullBody", "fullBodyCaption"):
                continue
            new[k] = v
            if k == anchor:
                new["fullBody"] = rel
                new["fullBodyCaption"] = keep
        if "fullBody" not in new:  # no image key at all
            new["fullBody"] = rel
            new["fullBodyCaption"] = keep
        art.clear()
        art.update(new)
        changed.append(art["id"])
    if changed:
        tmp = CHARACTERS + ".tmp"
        with open(tmp, "w", encoding="utf-8") as fh:
            fh.write(json.dumps(arts, indent=2, ensure_ascii=False) + "\n")
        os.replace(tmp, CHARACTERS)
    print(f"apply: {len(changed)} article(s) now point at a plate" + (": " + ", ".join(changed) if changed else ""))
    return 0


def cmd_drop(a):
    """Take a plate back out: delete the file (a copy goes to --raw-dir as <id>.dropped.png) and unwire fullBody /
    fullBodyCaption from the article — the undo for a render that passed the robot and failed the eye. Re-render
    with `render --ids <id> --redo` or make it by hand."""
    import shutil
    arts = json.load(open(CHARACTERS, encoding="utf-8"))
    raw_dir = os.path.abspath(os.path.expanduser(a.raw_dir))
    os.makedirs(raw_dir, exist_ok=True)
    dropped = []
    for cid in a.ids:
        path = os.path.join(RM, PLATES, cid + ".png")
        if os.path.isfile(path):
            shutil.copyfile(path, os.path.join(raw_dir, cid + ".dropped.png"))
            os.remove(path)
        for art in arts:
            if art["id"] == cid and (art.get("fullBody") or "").replace("\\", "/") == f"{PLATES}/{cid}.png":
                art.pop("fullBody", None)
                art.pop("fullBodyCaption", None)
        dropped.append(cid)
    tmp = CHARACTERS + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(json.dumps(arts, indent=2, ensure_ascii=False) + "\n")
    os.replace(tmp, CHARACTERS)
    print(f"drop: {len(dropped)} plate(s) removed and unwired (copies in {raw_dir}): " + ", ".join(dropped))
    return 0


# --------------------------------------------------------------- check ----
def cmd_check(a):
    arts, by_sheet = load()
    bad = []
    n = 0
    sprites = pixel_plate_ids(arts)
    for art in arts:
        fb = (art.get("fullBody") or "").replace("\\", "/")
        if not fb:
            continue
        n += 1
        path = os.path.join(RM, fb)
        if not os.path.isfile(path):
            bad.append((art["id"], "missing file " + fb)); continue
        w, h, clear, _ = plate_facts(path)
        if clear < BORDER_CLEAR:
            bad.append((art["id"], f"not transparent ({clear:.0%} of the border clear) {fb}"))
        elif max(w, h) < MIN_PX and not art.get("generatedBy"):
            bad.append((art["id"], f"{w}x{h} is under {MIN_PX} px {fb}"))
        elif fb.startswith(PLATES) and art["id"] not in sprites and specks(path) > 0:
            bad.append((art["id"], f"{specks(path)} figure pixel(s) keyed out — run heal {fb}"))
        elif fb.startswith(PLATES) and art["id"] not in sprites and background_audit(path):
            bad.append((art["id"], "; ".join(background_audit(path)) + " " + fb))
    rows = statuses(arts, by_sheet)
    left = [r for r in rows if r["status"] not in ("READY", "READY-LEAD")]
    print(f"token plates: {n} fullBody plate(s), {len(bad)} problem(s); {len(rows) - len(left)}/{len(rows)} sheet characters token-ready "
          f"({sum(1 for r in left if r['tier'] == 1)} party, {sum(1 for r in left if r['tier'] == 2)} placed, {sum(1 for r in left if r['tier'] == 3)} other still to do)")
    for cid, why in bad:
        print(f"  {cid:<36} {why}")
    legs = legs_suspects(arts)
    if legs:
        by_id = {x["id"]: x for x in arts}
        print(f"  {len(legs)} pipeline plate(s) of a non-biped build were rendered under the old head-to-feet prompt — look at them "
              f"(sheet --ids ...), then drop the wrong ones and render them again with --redo --ids ... or in the studio:")
        print("    " + " ".join(f"{cid}({body_plan_of(by_id[cid])[0]})" for cid in legs))
    return 1 if (bad and a.check) else 0


FIELD_FILL = 0.92    # opaque share of the figure's own box above this is a leftover rectangle of field, not a figure (real figures: <= 0.7)
KEY_HALO = 0.20      # share of the figure's edge band still near a key colour above this is a halo the keyer left
SEMI_FIELD = 0.20    # share of the figure that is translucent above this is a half-keyed field


def background_audit(path):
    """Reasons a transparent plate still carries its background (none when it is clean): a near-rectangular opaque
    mass (the field came along), a key-coloured fringe (the keyer stopped short), a large translucent area (the
    field was keyed to half alpha instead of away). Pixel sprites are not judged (block shapes, flat colours)."""
    from PIL import Image
    np = _np()
    im = np.asarray(Image.open(path).convert("RGBA")).astype(int)
    a, rgb = im[:, :, 3], im[:, :, :3]
    on = a > 16
    if not on.any():
        return ["nothing opaque on the plate"]
    ys, xs = np.where(on)
    why = []
    fill = (a > 200).sum() / ((ys.max() - ys.min() + 1) * (xs.max() - xs.min() + 1))
    if fill > FIELD_FILL:
        why.append("figure fills %d%% of its own box — a leftover field?" % round(fill * 100))
    semi = ((a > 16) & (a <= 200)).sum() / on.sum()
    if semi > SEMI_FIELD:
        why.append("%d%% of the figure is translucent — a half-keyed field?" % round(semi * 100))
    off = ~on
    edge = on & (np.roll(off, 1, 0) | np.roll(off, -1, 0) | np.roll(off, 1, 1) | np.roll(off, -1, 1))
    band = edge.copy()
    for _ in range(2):
        grown = band.copy()
        for dy, dx in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            grown |= np.roll(np.roll(band, dy, 0), dx, 1)
        band = grown & on
    if band.any():
        near = np.zeros(band.sum(), dtype=bool)
        for val in KEYS.values():
            near |= np.sqrt(((rgb[band] - np.array(val)) ** 2).sum(axis=1)) < 120
        if near.mean() > KEY_HALO:
            why.append("%d%% of the figure's edge is key-coloured — a halo the keyer left" % round(near.mean() * 100))
    return why


LEGGY = 1.7          # a figure this many times taller than wide, on a build that is short, round or legless, probably got legs


def figure_aspect(path):
    """height / width of the opaque figure on a plate (0 when there is none)."""
    from PIL import Image
    np = _np()
    alpha = np.asarray(Image.open(path).convert("RGBA"))[:, :, 3] > 16
    rows, cols = np.where(alpha.any(axis=1))[0], np.where(alpha.any(axis=0))[0]
    if not len(rows) or not len(cols):
        return 0.0
    return (rows[-1] - rows[0] + 1) / (cols[-1] - cols[0] + 1)


def legs_suspects(arts):
    """Pipeline-rendered plates (the pipeline's own caption, from before the build went into the prompt) of a build
    that is not a biped, whose figure came out tall and narrow — the ones the old head-to-feet prompt gave legs."""
    out = []
    for art in arts:
        cap = art.get("fullBodyCaption") or ""
        fb = (art.get("fullBody") or "").replace("\\", "/")
        if not cap.startswith("Full-body token plate") or not fb.startswith(PLATES) or "built as" in cap:
            continue
        path = os.path.join(RM, fb)
        if body_plan_of(art)[0] not in ("biped", "unknown") and os.path.isfile(path) and figure_aspect(path) > LEGGY:
            out.append(art["id"])
    return out


# ---------------------------------------------------------------- heal ----
def plate_key(rgba):
    """Which chroma key a transparent plate was cut on, from the colour stored under its clear pixels — or
    None when there is nothing to go by (a downscaled plate stores black there; a flat cut, a sprite)."""
    np = _np()
    clear = (rgba[:, :, 3] < 16) & (rgba[:, :, :3].sum(axis=2) > 0)      # pad is exact (0,0,0,0)
    if clear.sum() < 50:
        return None
    med = np.median(rgba[:, :, :3][clear], axis=0)
    for name, val in KEYS.items():
        if np.sqrt(((med - np.array(val)) ** 2).sum()) < 90:
            return name
    return None


SPECK_PX = 64          # an enclosed clear patch this small inside a figure is a keyer artefact, not a gap


def _dilate(mask, n=1):
    np = _np()
    out = mask.copy()
    for _ in range(n):
        grown = out.copy()
        for dy, dx in ((1, 0), (-1, 0), (0, 1), (0, -1), (1, 1), (-1, -1), (1, -1), (-1, 1)):
            grown |= np.roll(np.roll(out, dy, axis=0), dx, axis=1)
        out = grown
    return out


def _speck_mask(alpha):
    """Enclosed (not border-connected) patches of alpha < 250 up to SPECK_PX pixels."""
    np = _np()
    dim = alpha < 250
    try:
        from scipy import ndimage
    except ImportError:
        return np.zeros_like(dim)
    lab, n = ndimage.label(dim)
    if not n:
        return np.zeros_like(dim)
    border = set(np.unique(np.concatenate([lab[0], lab[-1], lab[:, 0], lab[:, -1]]).tolist()))
    sizes = ndimage.sum(dim, lab, index=np.arange(1, n + 1))
    small = [i + 1 for i, sz in enumerate(sizes) if sz <= SPECK_PX and (i + 1) not in border]
    return np.isin(lab, small) if small else np.zeros_like(dim)


def specks(path):
    """Pixels the keyer wrongly cleared: clear pixels inside the figure whose stored colour is nowhere near
    the key (exact, for plates that still store it) plus tiny enclosed clear patches (any plate)."""
    from PIL import Image
    np = _np()
    rgba = np.asarray(Image.open(path).convert("RGBA")).astype(np.int32)
    tiny = _speck_mask(rgba[:, :, 3])
    key = plate_key(rgba)
    if not key:
        return int(tiny.sum())
    rgb, alpha = rgba[:, :, :3], rgba[:, :, 3]
    dist = np.sqrt(((rgb - np.array(KEYS[key])) ** 2).sum(axis=2).astype(float))
    bg = (alpha < 16) & (key_mask(rgb, key, dist, 95) | (rgb.sum(axis=2) == 0))  # keyed, or the transparent pad
    edge = _dilate(bg, 1)                                   # the band next to real background is despilled, not damage
    tiny &= ~bg & ~edge                                     # a tiny gap that really showed the key is a gap
    return int(tiny.sum() + ((alpha < 255) & (dist > 150) & (rgb.sum(axis=2) > 0) & ~edge).sum())


def heal(path, key=None, hard_tol=95, soft_tol=150):
    """Give a plate back what an overflowing keyer took. Three passes: (1) where the plate still stores
    the render's colour under its clear pixels, every pixel far from the key gets its alpha back and the soft
    band is recomputed against real background only — exact; (2) tiny enclosed clear patches are filled from
    their neighbours — downscaled plates store nothing under clear pixels, so this is what is left for them;
    (3) the key channels are capped on the outer edge, where the old despill stopped at the band.
    Returns pixels changed (0 = nothing to do)."""
    from PIL import Image
    np = _np()
    im = Image.open(path).convert("RGBA")
    rgba = np.asarray(im).astype(np.int32)
    out = rgba.copy()
    key = plate_key(rgba) or key
    changed = np.zeros(rgba.shape[:2], dtype=bool)
    rgb, alpha = rgba[:, :, :3], rgba[:, :, 3].astype(float)
    pad = (alpha == 0) & (rgb.sum(axis=2) == 0)
    if key and plate_key(rgba):                                                   # pass 1: exact, colour still there
        kc = np.array(KEYS[key], dtype=np.int32)
        dist = np.sqrt(((rgb - kc) ** 2).sum(axis=2).astype(float))
        bg = key_mask(rgb, key, dist, hard_tol) & ~pad
        near = _dilate(bg | pad)
        band = ~bg & ~pad & near & (dist <= soft_tol)
        wrong = ~pad & ~bg & ~near & (alpha < 255)                               # next to real background it is the (despilled) band
        ramp = np.clip((dist - hard_tol) / max(1.0, soft_tol - hard_tol), 0.0, 1.0)
        band_alpha = 255.0 * (0.25 + 0.75 * ramp)
        low_band = band & (alpha < band_alpha - 1)
        out[:, :, 3][wrong] = 255
        out[:, :, 3][low_band] = band_alpha[low_band].astype(np.int32)
        r, g, b = rgb[:, :, 0], rgb[:, :, 1], rgb[:, :, 2]
        capped = wrong & (((r == g + 40) | (b == g + 40)) if key == "magenta" else (g == np.maximum(r, b) + 40))
        changed |= wrong | low_band
        fill = capped
    else:
        fill = np.zeros_like(changed)
    speck = _speck_mask(out[:, :, 3])                                              # pass 2: tiny holes, any plate
    if key and plate_key(rgba):
        speck &= ~((alpha < 16) & key_mask(rgb, key, np.sqrt(((rgb - np.array(KEYS[key])) ** 2).sum(axis=2).astype(float)), hard_tol))   # real gaps stay
    if speck.any():
        out[:, :, 3][speck] = 255
        fill |= speck & ((alpha < 16) | (rgb.sum(axis=2) == 0))                    # nothing usable stored there
        changed |= speck
    if fill.any():                                                                  # refill from untouched neighbours
        good = (out[:, :, 3] == 255) & ~fill
        cur = out[:, :, :3].astype(float)
        for _ in range(8):
            acc = np.zeros_like(cur); cnt = np.zeros(cur.shape[:2], dtype=float)
            for dy in (-1, 0, 1):
                for dx in (-1, 0, 1):
                    if dy or dx:
                        sh = np.roll(np.roll(good, dy, axis=0), dx, axis=1)
                        acc += np.roll(np.roll(cur, dy, axis=0), dx, axis=1) * sh[:, :, None]; cnt += sh
            now = fill & ~good & (cnt > 0)
            if not now.any():
                break
            cur[now] = acc[now] / cnt[now][:, None]
            good |= now
        out[:, :, :3] = cur.round().astype(np.int32)
    if key:                                                                         # pass 3: edge despill, 3 px in
        edge = (out[:, :, 3] < 255) | _dilate(out[:, :, 3] < 16, 3)
        edge &= out[:, :, 3] > 0
        r, g, b = out[:, :, 0], out[:, :, 1], out[:, :, 2]
        if key == "magenta":
            cap = g + 40
            hit = edge & ((r > cap) | (b > cap))
            r[hit] = np.minimum(r[hit], cap[hit]); b[hit] = np.minimum(b[hit], cap[hit])
        else:
            cap = np.maximum(r, b) + 40
            hit = edge & (g > cap)
            g[hit] = np.minimum(g[hit], cap[hit])
        changed |= hit
    if not changed.any():
        return 0
    Image.fromarray(out.clip(0, 255).astype(np.uint8), "RGBA").save(path, optimize=True)
    return int(changed.sum())


def pixel_plate_ids(arts):
    """Plates made by `pixel` (the lead is pixel art) — never touched by heal / the speck check."""
    out = set()
    for art in arts:
        lead = (art.get("image") or "").replace("\\", "/")
        if lead and not lead.startswith("http") and os.path.isfile(os.path.join(RM, lead)) and is_pixel_art(os.path.join(RM, lead)):
            out.add(art["id"])
    return out


def cmd_heal(a):
    arts, _ = load()
    by_id = {x["id"]: x for x in arts}
    d = os.path.join(RM, PLATES)
    ids = a.ids or sorted(f[:-4] for f in os.listdir(d) if f.endswith(".png"))
    sprites = pixel_plate_ids(arts)
    fixed = 0
    for cid in ids:
        path = os.path.join(d, cid + ".png")
        if not os.path.isfile(path):
            print(f"  {cid}: no plate"); continue
        if cid in sprites:
            continue
        n = heal(path, key=a.key or (key_for(by_id[cid]) if a.ids and cid in by_id else None))
        if n:
            fixed += 1
            print(f"  {cid:<36} {n} px changed")
    print(f"heal: {fixed} plate(s) touched of {len(ids)}")


def cmd_defringe(a):
    key = tuple(a.key) if a.key else None
    touched = 0
    for p in a.paths:
        path = p if os.path.exists(p) else os.path.join(RM, p)
        if not os.path.isfile(path):
            print(f"  {p}: no such file")
            continue
        before = fringe_count(path)
        facts = defringe(path, key=key)
        touched += 1
        print(f"  {os.path.basename(path):<34} key {facts['key']}  band {facts['fixed']:5d} px  fringe {before} -> {fringe_count(path)}")
    print(f"defringe: {touched} plate(s) touched of {len(a.paths)}")
    return 0
    return 0


# --------------------------------------------------------------- sheet ----
def cmd_sheet(a):
    from PIL import Image, ImageDraw, ImageFont
    arts, by_sheet = load()
    ids = a.ids or [x["id"] for x in arts if (x.get("fullBody") or "").replace("\\", "/").startswith(PLATES)]
    by_id = {x["id"]: x for x in arts}
    cell, cols = a.cell, a.cols
    rows = (len(ids) + cols - 1) // cols
    sheet = Image.new("RGB", (cols * cell, rows * (cell + 14)), "#5a7d5a")
    d = ImageDraw.Draw(sheet)
    font = ImageFont.load_default(size=11)
    for i, cid in enumerate(ids):
        art = by_id.get(cid, {})
        rel = (art.get("fullBody") or art.get("image") or "").replace("\\", "/")
        if os.path.isfile(os.path.join(RM, PLATES, cid + ".png")):   # the plate on disk, wired or not yet
            rel = f"{PLATES}/{cid}.png"
        x, y = (i % cols) * cell, (i // cols) * (cell + 14)
        try:
            im = Image.open(os.path.join(RM, rel)).convert("RGBA")
            im.thumbnail((cell - 4, cell - 4))
            sheet.paste(im, (x + 2, y + 2), im)
        except Exception as exc:  # noqa: BLE001
            d.text((x + 4, y + 4), f"n/a {exc}"[:30], fill="red", font=font)
        d.text((x + 2, y + cell), cid[:30], fill="white", font=font)
    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    sheet.save(a.out, quality=85)
    print(f"sheet: {len(ids)} plates -> {a.out} {sheet.size}")
    return 0


# -------------------------------------------------------------- render ----
COMFY_URL = os.environ.get("COMFY_URL") or ""                     # empty = probe COMFY_PORTS
COMFY_PORTS = (8188, 8000, 8189, 8190)                             # Comfy Desktop instances / classic installs default to 8188
#                                                                    (the legacy electron desktop app used 8000; "use next port" bumps 8188 up)
RENDER_LOG = "render-log.json"

# The official Qwen-Image-Edit template as ComfyUI's API format (ComfyUI >= 0.3.51). Model file names are the
# ones the ComfyUI docs ship; override with --unet/--clip/--vae/--lora or hand the tool your own exported
# workflow (--workflow): it finds the sampler, follows its positive link to the prompt node, fills every
# LoadImage with the reference and the SaveImage prefix with the id.
BUILTIN_QWEN_EDIT = {
    "37": {"class_type": "UNETLoader", "inputs": {"unet_name": "qwen_image_edit_fp8_e4m3fn.safetensors", "weight_dtype": "default"}},
    "38": {"class_type": "CLIPLoader", "inputs": {"clip_name": "qwen_2.5_vl_7b_fp8_scaled.safetensors", "type": "qwen_image", "device": "default"}},
    "39": {"class_type": "VAELoader", "inputs": {"vae_name": "qwen_image_vae.safetensors"}},
    "78": {"class_type": "LoadImage", "inputs": {"image": "reference.png"}},
    "93": {"class_type": "FluxKontextImageScale", "inputs": {"image": ["78", 0]}},
    "88": {"class_type": "VAEEncode", "inputs": {"pixels": ["93", 0], "vae": ["39", 0]}},
    "76": {"class_type": "TextEncodeQwenImageEdit", "inputs": {"prompt": "", "clip": ["38", 0], "vae": ["39", 0], "image": ["93", 0]}},
    "77": {"class_type": "TextEncodeQwenImageEdit", "inputs": {"prompt": "", "clip": ["38", 0], "vae": ["39", 0], "image": ["93", 0]}},
    "66": {"class_type": "ModelSamplingAuraFlow", "inputs": {"shift": 3.0, "model": ["75", 0]}},
    "75": {"class_type": "CFGNorm", "inputs": {"strength": 1.0, "model": ["37", 0]}},
    "3": {"class_type": "KSampler", "inputs": {"seed": 0, "steps": 20, "cfg": 2.5, "sampler_name": "euler", "scheduler": "simple", "denoise": 1.0,
                                               "model": ["66", 0], "positive": ["76", 0], "negative": ["77", 0], "latent_image": ["88", 0]}},
    "8": {"class_type": "VAEDecode", "inputs": {"samples": ["3", 0], "vae": ["39", 0]}},
    "60": {"class_type": "SaveImage", "inputs": {"filename_prefix": "token-plates/plate", "images": ["8", 0]}},
}
# Qwen-Image-2.1 (ComfyUI >= 0.37): one checkpoint for text-to-image and editing, native RGBA output, reference
# images spliced into the text encoder (`<image1>` in the prompt). The filenames are the Comfy-Org repackage.
QWEN21_MODELS = {"unet": "qwen_image_2.1_int8_convrot.safetensors", "clip": "qwen3vl_8b_int8_convrot.safetensors",
                 "vae": "qwen_image_2.1_vae_bf16.safetensors"}
BUILTIN_QWEN21 = {
    "451": {"class_type": "UNETLoader", "inputs": {"unet_name": QWEN21_MODELS["unet"], "weight_dtype": "default"}},
    "453": {"class_type": "CLIPLoader", "inputs": {"clip_name": QWEN21_MODELS["clip"], "type": "qwen_image", "device": "default"}},
    "454": {"class_type": "VAELoader", "inputs": {"vae_name": QWEN21_MODELS["vae"]}},
    "469": {"class_type": "QwenImage21Cache", "inputs": {"model": ["451", 0], "device": "auto", "dtype": "default"}},
    "470": {"class_type": "LoadImage", "inputs": {"image": "reference.png"}},
    "474": {"class_type": "TextEncodeQwenImage21", "inputs": {"clip": ["453", 0], "vae": ["454", 0], "prompt": "", "negative_prompt": "",
                                                              "resolution": 1024, "images.image_1": ["470", 0]}},
    "458": {"class_type": "KSampler", "inputs": {"seed": 0, "steps": 25, "cfg": 1.0, "sampler_name": "euler", "scheduler": "simple", "denoise": 1.0,
                                                 "model": ["469", 0], "positive": ["474", 0], "negative": ["474", 1], "latent_image": ["474", 2]}},
    "457": {"class_type": "VAEDecode", "inputs": {"samples": ["458", 0], "vae": ["454", 0]}},
    "461": {"class_type": "SaveImage", "inputs": {"filename_prefix": "token-plates/plate", "images": ["457", 0]}},
}
ENGINES = {"qwen21": ("TextEncodeQwenImage21", BUILTIN_QWEN21, {"unet": "451", "clip": "453", "vae": "454"}),
           "qwen-edit": ("TextEncodeQwenImageEdit", BUILTIN_QWEN_EDIT, {"unet": "37", "clip": "38", "vae": "39"})}
REMOVE_BG_PROMPT = "Remove the background, and output a PNG image"
NEGATIVE = ("scenery, floor, ground shadow, text, letters, watermark, border, frame, cropped, bust crop, portrait crop, extra figures, "
            "extra limbs, elongated body")
PROMPT_FIELDS = ("prompt", "text")
SAMPLERS = ("KSampler", "KSamplerAdvanced")
REF_SIZES = {"qwen21": (832, 1216), "qwen-edit": (1024, 1024)}   # the edit canvas is the reference's: portrait for a standing biped (plan_canvas)


class Comfy:
    """The little HTTP the ComfyUI server speaks (urllib only, so it runs where start.py runs)."""

    def __init__(self, url=None):
        self.url = (url or COMFY_URL or "http://127.0.0.1:%d" % COMFY_PORTS[0]).rstrip("/")
        import uuid
        self.client = uuid.uuid4().hex

    @classmethod
    def discover(cls, url=None):
        """The server to talk to: the one given, else the first of COMFY_PORTS that answers."""
        if url or COMFY_URL:
            return cls(url or COMFY_URL)
        for port in COMFY_PORTS:
            c = cls("http://127.0.0.1:%d" % port)
            if c.alive():
                return c
        return cls("http://127.0.0.1:%d" % COMFY_PORTS[0])

    def engine(self):
        """Which builtin graph this server can run: qwen21 (Qwen-Image-2.1), qwen-edit (Qwen-Image-Edit), or None."""
        for name, (node, _, _) in ENGINES.items():
            if self.has_node(node):
                return name
        return None

    def choices(self, class_type, field):
        """The files a loader node offers (the server's own model folders)."""
        try:
            info = self._json("/object_info/" + class_type)[class_type]["input"]["required"][field][0]
            return list(info) if isinstance(info, list) else []
        except Exception:  # noqa: BLE001
            return []

    def run(self, workflow, dst, timeout=900):
        """Queue, wait, download — one image."""
        pid = self.queue(workflow)
        return self.download(self.wait(pid, timeout=timeout), dst)

    def _json(self, path, data=None, method=None):
        import urllib.error
        import urllib.request
        body = json.dumps(data).encode("utf-8") if data is not None else None
        req = urllib.request.Request(self.url + path, data=body, method=method or ("POST" if body else "GET"),
                                     headers={"Content-Type": "application/json"} if body else {})
        try:
            with urllib.request.urlopen(req, timeout=60) as r:
                raw = r.read()
        except urllib.error.HTTPError as exc:
            # ComfyUI answers a bad graph with 400 + JSON that names the node and the field: say that, not "Bad Request"
            detail = exc.read().decode("utf-8", "replace")[:1500]
            try:
                j = json.loads(detail)
                msgs = [j.get("error", {}).get("message") if isinstance(j.get("error"), dict) else j.get("error")]
                for node, err in (j.get("node_errors") or {}).items():
                    for e in err.get("errors", []):
                        msgs.append(f"node {node} ({err.get('class_type', '?')}): {e.get('message')} {e.get('details', '')}".strip())
                detail = "; ".join(m for m in msgs if m)
            except ValueError:
                pass
            raise RuntimeError(f"ComfyUI rejected the request ({exc.code}): {detail}") from None
        return json.loads(raw.decode("utf-8")) if raw else {}

    def alive(self):
        try:
            self._json("/system_stats")
            return True
        except Exception:  # noqa: BLE001
            return False

    def has_node(self, class_type):
        try:
            return class_type in self._json("/object_info/" + class_type)
        except Exception:  # noqa: BLE001
            return False

    def upload(self, path, name):
        import urllib.request
        boundary = "----waluipedia%s" % self.client
        data = open(path, "rb").read()
        parts = []
        for field, value in (("type", "input"), ("overwrite", "true"), ("subfolder", "token-plates")):
            parts.append(("--%s\r\nContent-Disposition: form-data; name=\"%s\"\r\n\r\n%s\r\n" % (boundary, field, value)).encode())
        parts.append(("--%s\r\nContent-Disposition: form-data; name=\"image\"; filename=\"%s\"\r\nContent-Type: image/png\r\n\r\n" % (boundary, name)).encode())
        parts.append(data)
        parts.append(("\r\n--%s--\r\n" % boundary).encode())
        req = urllib.request.Request(self.url + "/upload/image", data=b"".join(parts), method="POST",
                                     headers={"Content-Type": "multipart/form-data; boundary=" + boundary})
        with urllib.request.urlopen(req, timeout=120) as r:
            info = json.loads(r.read().decode("utf-8"))
        sub = info.get("subfolder") or ""
        return (sub + "/" if sub else "") + info["name"]

    def queue(self, workflow):
        out = self._json("/prompt", {"prompt": workflow, "client_id": self.client})
        if out.get("node_errors"):
            raise RuntimeError("ComfyUI rejected the workflow: %s" % json.dumps(out["node_errors"])[:800])
        return out["prompt_id"]

    def wait(self, prompt_id, timeout=900, poll=2.0):
        import time
        t0 = time.time()
        while time.time() - t0 < timeout:
            hist = self._json("/history/" + prompt_id).get(prompt_id)
            if hist:
                status = hist.get("status") or {}
                if status.get("status_str") == "error":
                    raise RuntimeError("ComfyUI reported an error: %s" % json.dumps(status.get("messages", []))[:800])
                if hist.get("outputs"):
                    return hist["outputs"]
            time.sleep(poll)
        raise TimeoutError("ComfyUI did not finish %s in %ds" % (prompt_id, timeout))

    def download(self, outputs, dst):
        import urllib.parse
        import urllib.request
        for node in outputs.values():
            for im in node.get("images", []):
                if im.get("type") not in (None, "output"):
                    continue
                q = urllib.parse.urlencode({"filename": im["filename"], "subfolder": im.get("subfolder", ""), "type": "output"})
                with urllib.request.urlopen(self.url + "/view?" + q, timeout=120) as r:
                    open(dst, "wb").write(r.read())
                return dst
        raise RuntimeError("the workflow produced no output image (is there a SaveImage node?)")


def workflow_fill(wf, prompt, image_name, prefix, seed, negative=NEGATIVE):
    """Fill an API-format workflow: the sampler's positive prompt, its negative, every LoadImage, the SaveImage prefix, the seed."""
    wf = json.loads(json.dumps(wf))
    samplers = [k for k, v in wf.items() if v.get("class_type") in SAMPLERS]
    if not samplers:
        raise SystemExit("render: no KSampler in the workflow — export the API format of a workflow that samples")
    for sid in samplers:
        inp = wf[sid]["inputs"]
        for field in ("seed", "noise_seed"):
            if field in inp:
                inp[field] = seed
        for role, text in (("positive", prompt), ("negative", negative)):
            link = inp.get(role)
            if isinstance(link, list):
                node = wf.get(str(link[0]), {})
                fields = ("negative_prompt",) if role == "negative" and "negative_prompt" in node.get("inputs", {}) else PROMPT_FIELDS
                for f in fields:
                    if f in node.get("inputs", {}):
                        node["inputs"][f] = text
    for v in wf.values():
        if v.get("class_type") == "LoadImage":
            v["inputs"]["image"] = image_name
        if v.get("class_type") == "SaveImage":
            v["inputs"]["filename_prefix"] = prefix
    return wf


def workflow_tune(wf, steps=None, resolution=None, cfg=None, models=None, engine=None, cache=True):
    """Dial a builtin graph: sampler steps / cfg, the 2.1 reference budget, loader filenames, the optional cache node."""
    wf = json.loads(json.dumps(wf))
    for v in wf.values():
        if v.get("class_type") in SAMPLERS:
            if steps:
                v["inputs"]["steps"] = int(steps)
            if cfg is not None:
                v["inputs"]["cfg"] = float(cfg)
        if v.get("class_type") == "TextEncodeQwenImage21" and resolution is not None:
            v["inputs"]["resolution"] = int(resolution)
    if models and engine in ENGINES:
        ids = ENGINES[engine][2]
        for key, field in (("unet", "unet_name"), ("clip", "clip_name"), ("vae", "vae_name")):
            if models.get(key):
                wf[ids[key]]["inputs"][field] = models[key]
    if not cache and "469" in wf and wf["469"].get("class_type") == "QwenImage21Cache":
        src = wf["469"]["inputs"]["model"]
        del wf["469"]
        for v in wf.values():
            if v.get("inputs", {}).get("model") == ["469", 0]:
                v["inputs"]["model"] = src
    return wf


def qwen21_t2i_prompt(art, transparent=True):
    """No usable reference: 2.1 draws the figure from the record (name, title, race, the look line). Flagged in the
    log and the caption, because nothing anchors the face."""
    name = art.get("name", art["id"])
    title = (art.get("title") or "").strip()
    race = re.split(r"[;.]", (art.get("race") or "").strip())[0].strip()
    if re.match(r"^(unknown|unfiled|corrupted copy)\b", race, re.I) and " — " in race:
        race = race.split(" — ", 1)[1].strip()
    elif re.match(r"^(unknown|unfiled)\b", race, re.I):
        race = ""
    who = name + (f", {title}" if title and title.lower() not in name.lower() else "") + (f" ({race})" if race else "")
    look = look_of(art)
    plan, build = body_plan_of(art)
    body = f"A full-body character illustration of {who}. "
    if look:
        body += f"{look}. "
    body += (f"The whole figure, nothing cropped, built exactly the way this character is built: {build}. "
             "Facing the viewer and turned slightly, holding their weapon or tool if they carry one"
             + ("; no legs, feet or human proportions the character does not have. " if plan != "biped" else ". ")
             + "Painterly illustration with clean edges. One figure only, centred, "
             "with empty space on every side; no floor, no cast shadow, no scenery, no text, no border. ")
    body += ("Transparent background: output a PNG image with an alpha channel and nothing behind the figure." if transparent
             else "The entire background is plain solid flat bright magenta.")
    return body


def prep_reference(src, dst, key, full_body, size=(1024, 1024), plan="biped"):
    """The reference the edit model sees: the figure on a key-colour canvas — a full-body plate with a margin, a
    bust in the upper part with empty key colour below it, which is where the rest of the body gets drawn. The
    canvas is also the edit's output size (2.1 samples at the first reference's size): portrait for a standing
    biped, square for every other build (plan_canvas), and the bust sits lower and larger the less body there is
    to add (PLAN_BUST) — a Boo's "bust" is the whole Boo."""
    from PIL import Image
    kc = KEYS[key]
    im = Image.open(src).convert("RGBA")
    w, h = size
    canvas = Image.new("RGBA", (w, h), kc + (255,))
    if full_body:
        im = fit(im, int(w * 0.86), int(h * 0.88))
        canvas.paste(im, ((w - im.width) // 2, (h - im.height) // 2), im)
    else:
        bw, bh, top = PLAN_BUST.get(plan, PLAN_BUST_DEFAULT)
        im = fit(im, int(w * bw), int(h * bh))
        canvas.paste(im, ((w - im.width) // 2, int(h * top)), im)
    canvas.convert("RGB").save(dst)
    return dst


def fit(im, bw, bh, up_to=3.0):
    """Scale the reference into a box — down, or UP to three times (thumbnail() only shrinks, so a 268 px lead sat
    as a speck at the top of a 1216 px canvas with a page of empty field under it to fill with body)."""
    from PIL import Image
    scale = min(bw / im.width, bh / im.height, up_to)
    if abs(scale - 1) < 1e-6:
        return im
    return im.resize((max(1, round(im.width * scale)), max(1, round(im.height * scale))), Image.LANCZOS)


def qwen21_prompt(entry, full_body, transparent=True):
    """The 2.1 instruction: the reference is <image1>; ask for the PNG with alpha the model can draw natively."""
    colour = "bright magenta" if entry["key"] == "magenta" else "bright green"
    plan, build = entry.get("plan") or "unknown", entry.get("build") or BODY_PLANS["unknown"]
    body = (f"Show the character from <image1> whole, nothing cropped, built exactly the way this character is built: {build}. "
            "Facing the viewer and turned slightly, holding their weapon or tool if they carry one. "
            "Keep exactly the same face, colours, wardrobe and art style as <image1>. ")
    if not full_body:
        if plan == "biped":
            body += "<image1> shows only the upper body: continue the body downward and draw the legs and feet to match, nothing cropped. "
        else:
            body += ("<image1> is cropped: continue the body downward only as far as this build goes and no further — "
                     "do not add legs, feet, a neck or human proportions the character does not have. ")
    look = entry.get("look") or ""
    if look:
        body += f"Established look: {look}. "
    body += "One figure only, centred, with empty space on every side; no floor, no cast shadow, no scenery, no text, no border. "
    if transparent:
        body += "Transparent background: output a PNG image with an alpha channel and nothing behind the figure."
    else:
        body += f"The entire background is plain solid flat {colour}."
    return body


def render_prompt(entry, full_body):
    """The edit instruction: an edit model wants to be told what to change, not what to paint."""
    colour = "bright magenta" if entry["key"] == "magenta" else "bright green"
    plan, build = entry.get("plan") or "unknown", entry.get("build") or BODY_PLANS["unknown"]
    body = (f"Keep this character exactly as they are — same face, colours, wardrobe and art style — and show the whole "
            f"figure, nothing cropped, built exactly the way this character is built: {build}. Relaxed neutral pose facing the "
            f"viewer, turned slightly, weapon or tool held if they carry one. ")
    if not full_body:
        if plan == "biped":
            body += "Extend the body downward from what is shown so the figure is complete, feet included, nothing cropped. "
        else:
            body += ("Extend the body downward only as far as this build goes and no further — do not add legs, feet, a neck or "
                     "human proportions the character does not have. ")
    look = entry.get("look") or ""
    if look:
        body += f"Established look: {look}. "
    body += (f"The entire background stays plain solid flat {colour}, with no floor, no cast shadow, no scenery, no text, "
             f"no border. One figure only, centred, with empty {colour} space on every side.")
    return body


def render_qc(raw_path, facts, plan="biped"):
    """Did the render come back usable? (keyed field present, border clear after the cut, nothing touching the frame,
    the figure tall enough for its build — 45 % of the frame for a biped, 28 % for a Boo or a Goomba)"""
    from PIL import Image
    np = _np()
    why = []
    if facts["keyed"] < 0.25:
        why.append("background is not the key colour")
    if facts["border_clear"] < BORDER_CLEAR:
        why.append("border not clear after the cut")
    im = Image.open(raw_path)
    fig = None
    if facts["key"] == "alpha":
        fig = np.asarray(im.convert("RGBA"))[:, :, 3] > 16
    elif facts["key"] in KEYS:
        arr = np.asarray(im.convert("RGB")).astype(int)
        fig = np.sqrt(((arr - np.array(KEYS[facts["key"]])) ** 2).sum(axis=2)) > 95
    if fig is not None:
        h, w = fig.shape
        m = max(2, h // 50)
        if fig[:m, :].mean() > 0.02 or fig[-m:, :].mean() > 0.02:
            why.append("figure touches the top or bottom edge (cropped)")
        if fig[:, :m].mean() > 0.02 or fig[:, -m:].mean() > 0.02:
            why.append("figure touches a side edge")
        rows = np.where(fig.any(axis=1))[0]
        least = plan_min_height(plan)
        if len(rows) and (rows[-1] - rows[0]) < least * h:
            why.append("figure is under %d%% of the frame tall (%d px) — a bust?" % (round(least * 100), rows[-1] - rows[0]))
    return why


def reference_for(art, row):
    """(relative path or "", full_body?) — the art the edit model is shown: the plate if there is one, else the lead."""
    cid = art["id"]
    fb = (art.get("fullBody") or "").replace("\\", "/")
    if cid in NO_REFERENCE:
        return "", False
    ref = fb if fb and os.path.isfile(os.path.join(RM, fb)) else (art.get("image") or "").replace("\\", "/")
    if not ref or ref.startswith("http") or not os.path.isfile(os.path.join(RM, ref)):
        return "", False
    # the plate itself is the whole figure; a lead stands in for a missing plate on its own merits
    full_body = ref == fb or (row or {}).get("status") == "SMALL" or plate_facts(os.path.join(RM, ref))[2] >= BORDER_CLEAR
    return ref, full_body


def default_prompt(art, row, engine, transparent=True):
    ref, full_body = reference_for(art, row)
    plan, build = body_plan_of(art)
    entry = {"id": art["id"], "key": key_for(art), "look": look_of(art), "plan": plan, "build": build}
    if engine == "qwen21":
        return qwen21_prompt(entry, full_body, transparent=transparent)
    return render_prompt(entry, full_body)


class Renderer:
    """One ComfyUI, one graph, many characters: upload the prepared reference, queue, wait, download, cut, QC."""

    def __init__(self, comfy, engine=None, workflow=None, models=None, steps=None, resolution=None, cache=True, timeout=900):
        self.comfy = comfy
        self.engine = engine or ("custom" if workflow else comfy.engine())
        if workflow:
            self.wf = workflow
        else:
            if self.engine not in ENGINES:
                raise RuntimeError("this ComfyUI has neither TextEncodeQwenImage21 (Qwen-Image-2.1) nor TextEncodeQwenImageEdit — update ComfyUI, or export your own edit workflow and pass --workflow")
            self.wf = workflow_tune(ENGINES[self.engine][1], steps=steps, resolution=resolution, models=models, engine=self.engine,
                                    cache=cache and comfy.has_node("QwenImage21Cache"))
        self.timeout = timeout

    def prompt_for(self, art, row, transparent=True):
        return default_prompt(art, row, self.engine, transparent=transparent)

    def can_text_only(self):
        return self.engine == "qwen21"

    def text_only_workflow(self, plan="biped"):
        """The 2.1 graph without a reference: no LoadImage, the encoder's image slot gone, an EmptyLatentImage of the
        build's canvas feeding the sampler (what the template's switch does when image_1 is empty)."""
        wf = json.loads(json.dumps(self.wf))
        w, h = plan_canvas(plan, "qwen21")
        wf["456"] = {"class_type": "EmptyLatentImage", "inputs": {"width": w, "height": h, "batch_size": 1}}
        for k in [k for k, v in wf.items() if v.get("class_type") == "LoadImage"]:
            del wf[k]
        for v in wf.values():
            if v.get("class_type") == "TextEncodeQwenImage21":
                for key in [k for k in v["inputs"] if k.startswith("images.")]:
                    del v["inputs"][key]
            if v.get("class_type") in SAMPLERS:
                v["inputs"]["latent_image"] = ["456", 0]
        return wf

    def render(self, art, row, raw_dir, seed, prompt=None, transparent=True, raw_name=None, reference=None, text_only=False):
        """Returns (raw_path, facts_or_None, why[]) — facts from the cut when the render came back usable.
        `text_only` lets a 2.1 server draw a character that has no usable reference from its record instead."""
        cid = art["id"]
        ref_rel, full_body = reference_for(art, row)
        plan = body_plan_of(art)[0]
        wf = self.wf
        if reference:
            ref_src, full_body = reference, True
        elif ref_rel:
            ref_src = os.path.join(RM, ref_rel)
        elif text_only and self.can_text_only():
            ref_src = None
            wf = self.text_only_workflow(plan)
            prompt = prompt or qwen21_t2i_prompt(art, transparent=transparent)
        else:
            return None, None, ["no usable reference — an edit model needs one; render this one by hand"]
        key = key_for(art)
        raw = os.path.join(raw_dir, raw_name or (cid + ".png"))
        if ref_src:
            ref_png = os.path.join(raw_dir, cid + ".ref.png")
            prep_reference(ref_src, ref_png, key, full_body, size=plan_canvas(plan, self.engine), plan=plan)
            prompt = prompt or self.prompt_for(art, row, transparent=transparent)
            name = self.comfy.upload(ref_png, f"{cid}.png")
        else:
            name = ""
        self.comfy.run(workflow_fill(wf, prompt, name, f"token-plates/{cid}", seed), raw, timeout=self.timeout)
        tmp = os.path.join(raw_dir, cid + ".cut.png")
        try:
            facts = cut(raw, tmp, "auto" if transparent else key)
        except SystemExit as exc:
            return raw, None, [str(exc)]
        if facts["key"] not in ("alpha", key) and transparent:
            facts = cut(raw, tmp, key)            # the model ignored the alpha request: key the field it drew
        why = render_qc(raw, facts, plan)
        return raw, facts, why

    def remove_background(self, src, dst, seed=1):
        """A second pass through the model with the official instruction — for a render that came back opaque."""
        name = self.comfy.upload(src, "removebg-" + os.path.basename(src))
        wf = workflow_fill(self.wf, REMOVE_BG_PROMPT, name, "token-plates/removebg", seed, negative="")
        return self.comfy.run(wf, dst, timeout=self.timeout)


def cmd_render(a):
    import random
    import time
    arts, by_sheet = load()
    by_id = {x["id"]: x for x in arts}
    rows = statuses(arts, by_sheet)
    if a.full:                      # the hands-off run: everything, every tier, keep the best attempt, draw the reference-less from the record
        a.tier, a.keep_best, a.text_only = None, True, True
    todo = [r for r in rows if r["status"] in ("GENERATE", "SMALL") and (not a.tier or r["tier"] <= a.tier)]
    if a.ids:
        todo = [r for r in rows if r["id"] in set(a.ids)]
    if a.limit:
        todo = todo[:a.limit]
    raw_dir = os.path.abspath(os.path.expanduser(a.raw_dir))
    os.makedirs(raw_dir, exist_ok=True)
    log_path = os.path.join(raw_dir, RENDER_LOG)
    log = json.load(open(log_path, encoding="utf-8")) if os.path.isfile(log_path) else {}
    workflow = None
    if a.workflow:
        workflow = json.load(open(a.workflow, encoding="utf-8"))
        if "nodes" in workflow and "links" in workflow:
            raise SystemExit("render: that is the UI save, not the API format — in ComfyUI turn on Dev mode and use 'Save (API Format)'")
    if a.dry_run:
        print(f"render: {len(todo)} to do (dry run, nothing sent)")
        for r in todo:
            print(f"  {r['id']:<36} tier {r['tier']} {r['status']}")
        return 0
    comfy = Comfy.discover(a.url)
    if not comfy.alive():
        raise SystemExit(f"render: no ComfyUI answering at {comfy.url} (tried ports {', '.join(map(str, COMFY_PORTS))}) — open Comfy Desktop / start ComfyUI, or pass --url; the queue is untouched")
    models = {"unet": a.unet, "clip": a.clip, "vae": a.vae}
    try:
        rend = Renderer(comfy, engine=None if a.model == "auto" else a.model, workflow=workflow, models=models, steps=a.steps,
                        resolution=a.resolution, timeout=a.timeout)
    except RuntimeError as exc:
        raise SystemExit(f"render: {exc}")
    if a.lora and rend.engine == "qwen-edit":
        wf = rend.wf
        wf["89"] = {"class_type": "LoraLoaderModelOnly", "inputs": {"lora_name": a.lora, "strength_model": 1.0, "model": ["37", 0]}}
        wf["75"]["inputs"]["model"] = ["89", 0]
        wf["3"]["inputs"]["steps"] = a.steps or 4
        wf["3"]["inputs"]["cfg"] = 1.0
    mode = "full run — every tier, best attempt kept, reference-less drawn from the record" if a.full else "QC-gated"
    print(f"render: {len(todo)} character(s) to do through {comfy.url} ({rend.engine}; {mode}); raws + log in {raw_dir}")
    done = failed = eyes = 0
    plated_now = []
    dead = 0                                   # consecutive characters with no image at all: the server went away, or the graph is wrong
    for n, r in enumerate(todo, 1):
        cid = r["id"]
        art = by_id[cid]
        plate = os.path.join(RM, PLATES, cid + ".png")
        if os.path.isfile(plate) and not a.redo and plate_facts(plate)[2] >= BORDER_CLEAR:
            continue
        text_only = not reference_for(art, r)[0]
        if text_only and not (a.text_only and rend.can_text_only()):
            print(f"[{n}/{len(todo)}] {cid}: no usable reference — an edit model needs one; render this one by hand (or --text-only on a 2.1 server)")
            log[cid] = {"skipped": "no reference"}
            json.dump(log, open(log_path, "w", encoding="utf-8"), indent=1)
            failed += 1
            continue
        ok = False
        why = []
        attempts = []                          # (why, cut_path, seed, facts) of the attempts that came back as an image
        got_image = False
        for attempt in range(1, (a.retries or 0) + 2):
            seed = random.randint(1, 2 ** 31 - 1)
            t0 = time.time()
            try:
                raw, facts, why = rend.render(art, r, raw_dir, seed, transparent=not a.opaque, text_only=text_only)
            except KeyboardInterrupt:
                print("\nrender: stopped between characters — run again to resume"); json.dump(log, open(log_path, "w", encoding="utf-8"), indent=1); return 130
            except Exception as exc:  # noqa: BLE001
                why = [f"{type(exc).__name__}: {str(exc)[:300]}"]
                raw, facts = None, None
            got_image = got_image or bool(raw)
            secs = time.time() - t0
            if not why:
                os.replace(os.path.join(raw_dir, cid + ".cut.png"), plate)
                print(f"[{n}/{len(todo)}] {cid}: ok in {secs:.0f}s (seed {seed}, attempt {attempt}{', from the record' if text_only else ''}) -> {PLATES}/{cid}.png")
                log[cid] = {"ok": True, "seed": seed, "attempt": attempt, "seconds": round(secs), "engine": rend.engine, "textOnly": text_only}
                ok = True
                break
            print(f"[{n}/{len(todo)}] {cid}: attempt {attempt} not usable — {'; '.join(why)}")
            if raw and os.path.isfile(raw):
                os.replace(raw, os.path.join(raw_dir, f"{cid}.rejected-{attempt}.png"))
            cut_path = os.path.join(raw_dir, cid + ".cut.png")
            if facts and os.path.isfile(cut_path):
                keep = os.path.join(raw_dir, f"{cid}.cut-{attempt}.png")
                os.replace(cut_path, keep)
                attempts.append((why, keep, seed, facts))
        notes = {}
        if not ok and a.keep_best and attempts:
            # the full run leaves nobody without a plate: the least-bad attempt goes on the sheet, flagged for the eye
            why_b, keep, seed, facts = best_attempt(attempts)
            os.replace(keep, plate)
            fw, fh, clear, _ = plate_facts(plate)
            if clear >= BORDER_CLEAR:
                ok = True
                eyes += 1
                notes[cid] = f"best of {len(attempts)} attempt(s), QC flagged: {'; '.join(why_b)} — needs eyes; rendered"
                log[cid] = {"ok": True, "needsEyes": True, "seed": seed, "why": why_b, "engine": rend.engine, "textOnly": text_only}
                print(f"[{n}/{len(todo)}] {cid}: kept the best of {len(attempts)} (seed {seed}) — needs eyes: {'; '.join(why_b)}")
            else:
                os.remove(plate)
        for _, keep, _, _ in attempts:
            if os.path.isfile(keep):
                os.remove(keep)
        if ok:
            done += 1
            plated_now.append(cid)
            dead = 0
            if text_only and cid not in notes:
                notes[cid] = "drawn from the record alone (no reference) — needs eyes; rendered"
            cmd_apply(argparse.Namespace(date=a.date, notes=notes))
        else:
            failed += 1
            log[cid] = {"ok": False, "why": why}
            dead = 0 if got_image else dead + 1
        json.dump(log, open(log_path, "w", encoding="utf-8"), indent=1)
        if dead >= 3:
            print(f"render: no image came back for {dead} characters in a row ({why[0] if why else 'no detail'}) — the server is gone or the graph is wrong; stopping here, run again to resume")
            return 3
    if plated_now and (a.full or len(plated_now) >= 10):
        out = os.path.join(raw_dir, "run-sheet.png")
        try:
            cmd_sheet(argparse.Namespace(out=out, ids=plated_now, cell=160, cols=10))
        except Exception as exc:  # noqa: BLE001
            print(f"render: contact sheet skipped ({exc})")
    print(f"render: {done} plated ({eyes} flagged for eyes), {failed} not plated (see {log_path}); run 'check' and the sheets suite next")
    if a.full:
        print("render: review with `git status` / the contact sheet; take a bad one back with `make-token-plates.py drop --ids <id>` and re-render it with `render --ids <id> --redo`")
    return 0 if not failed else 2


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("plan"); p.add_argument("--manifest"); p.add_argument("--tier", type=int); p.add_argument("--ids", nargs="*")
    p.add_argument("--grid", nargs=2, type=int, metavar=("ROWS", "COLS"))
    p = sub.add_parser("cut"); p.add_argument("--id"); p.add_argument("--src"); p.add_argument("--key", default="auto"); p.add_argument("--flat", action="store_true"); p.add_argument("--raw-dir"); p.add_argument("--ids", nargs="*")
    p.add_argument("--grid-sheet"); p.add_argument("--rows", type=int); p.add_argument("--cols", type=int)
    p = sub.add_parser("apply"); p.add_argument("--date")
    p = sub.add_parser("drop"); p.add_argument("--ids", nargs="+", required=True); p.add_argument("--raw-dir", default=os.path.join(ROOT, "..", "token-renders"))
    p = sub.add_parser("check"); p.add_argument("--check", action="store_true")
    p = sub.add_parser("pixel"); p.add_argument("--ids", nargs="*")
    p = sub.add_parser("heal"); p.add_argument("--ids", nargs="*"); p.add_argument("--key", choices=list(KEYS))
    p = sub.add_parser("defringe"); p.add_argument("paths", nargs="+"); p.add_argument("--key", nargs=3, type=int, metavar=("R", "G", "B"))
    p = sub.add_parser("render"); p.add_argument("--url", default=None); p.add_argument("--workflow"); p.add_argument("--tier", type=int)
    p.add_argument("--model", choices=["auto", "qwen21", "qwen-edit"], default="auto"); p.add_argument("--resolution", type=int); p.add_argument("--opaque", action="store_true")
    p.add_argument("--full", action="store_true", help="the hands-off run: every tier, keep the best attempt when none passes QC, draw the reference-less from the record; review in git")
    p.add_argument("--keep-best", action="store_true"); p.add_argument("--text-only", action="store_true")
    p.add_argument("--ids", nargs="*"); p.add_argument("--limit", type=int); p.add_argument("--retries", type=int, default=2); p.add_argument("--timeout", type=int, default=900)
    p.add_argument("--raw-dir", default=os.path.join(ROOT, "..", "token-renders")); p.add_argument("--redo", action="store_true"); p.add_argument("--dry-run", action="store_true")
    p.add_argument("--unet"); p.add_argument("--clip"); p.add_argument("--vae"); p.add_argument("--lora"); p.add_argument("--steps", type=int); p.add_argument("--date")
    p = sub.add_parser("sheet"); p.add_argument("--out", required=True); p.add_argument("--ids", nargs="*"); p.add_argument("--cell", type=int, default=160); p.add_argument("--cols", type=int, default=10)
    a = ap.parse_args(argv)
    return {"plan": cmd_plan, "cut": cmd_cut, "apply": cmd_apply, "drop": cmd_drop, "check": cmd_check, "sheet": cmd_sheet, "pixel": cmd_pixel, "heal": cmd_heal, "defringe": cmd_defringe, "render": cmd_render}[a.cmd](a)


if __name__ == "__main__":
    sys.exit(main())
