#!/usr/bin/env python3
"""Split Players.json into one untouched original per actor.

Feeds the existing ``originals -> sanitize -> import-ready`` pipeline:
each ``Reputation-Matrix2/actors/original-fvtt-Actor-<slug>-<_id>.json``
is JSON-equal to its entry in Players.json (the split only re-indents
the standalone file).  Run ``tools/rebuild-actors.py`` afterwards, or
use ``--watch`` to keep the import-ready files fresh while Players.json
is being edited.

Skipped entries (documented, never silent):
  - "Wario's Motorbike": stays generated by tools/build-wario-motorbike.py
    (verified item-identical to the live export; the split test fails on
    drift so a divergence can never slip through quietly).

Foundry honesty note: this bridge refreshes the import-ready FILES on
disk.  Nothing here can push data into a live Foundry world — the DM
still imports the fvtt-Actor-*.json files by hand.

Run from the repo root:
  python3 tools/split-players.py            # one-shot split
  python3 tools/split-players.py --watch    # re-split + rebuild on change
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLAYERS = ROOT / "Players.json"
ACTORS_DIR = ROOT / "Reputation-Matrix2" / "actors"

# actor name -> reason it is not split into an original
SKIP = {
    "Wario's Motorbike": "stays generated (tools/build-wario-motorbike.py)",
}


def slugify(name: str) -> str:
    slug = name.lower().replace("'", "")
    slug = re.sub(r"[^a-z0-9]+", "-", slug).strip("-")
    return slug


def split() -> tuple[list[str], list[str]]:
    """Returns (written_or_fresh, skipped) line lists for reporting."""
    actors = json.loads(PLAYERS.read_text(encoding="utf-8"))
    assert isinstance(actors, list), "Players.json must be a root-level list"
    fresh: list[str] = []
    skipped: list[str] = []
    for actor in actors:
        name = actor.get("name", "?")
        if name in SKIP:
            skipped.append(f"skip {name} ({SKIP[name]})")
            continue
        actor_id = actor.get("_id")
        assert actor_id, f"actor {name!r} has no _id"
        filename = f"original-fvtt-Actor-{slugify(name)}-{actor_id}.json"
        # Same on-disk style as the hand-committed originals.
        content = json.dumps(actor, indent=2, ensure_ascii=False)
        target = ACTORS_DIR / filename
        if target.exists() and target.read_text(encoding="utf-8") == content:
            fresh.append(f"fresh {filename}")
        else:
            target.write_text(content, encoding="utf-8")
            fresh.append(f"write {filename}")
    return fresh, skipped


def rebuild() -> int:
    proc = subprocess.run(
        [sys.executable, "tools/rebuild-actors.py"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    return proc.returncode


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Split Players.json into originals.")
    parser.add_argument(
        "--watch",
        nargs="?",
        const=5,
        type=int,
        default=None,
        metavar="SECONDS",
        help="poll Players.json every N seconds (default 5) and re-split + "
        "rebuild the import-ready files on change",
    )
    args = parser.parse_args(argv)

    fresh, skipped = split()
    for line in fresh + skipped:
        print(line)

    if args.watch is None:
        print("split done: run tools/rebuild-actors.py to refresh import-ready files")
        return 0

    print(f"watching Players.json every {args.watch}s (Ctrl-C to stop) ...")
    last_mtime = PLAYERS.stat().st_mtime
    try:
        while True:
            time.sleep(args.watch)
            mtime = PLAYERS.stat().st_mtime
            if mtime == last_mtime:
                continue
            last_mtime = mtime
            print("--- Players.json changed: re-splitting ---")
            fresh, skipped = split()
            for line in fresh + skipped:
                print(line)
            rc = rebuild()
            print(f"--- rebuild {'OK' if rc == 0 else 'FAILED'} ---")
    except KeyboardInterrupt:
        print("watch stopped.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
