// map-data/kivotos/AL_haoung.js
export const alhaoungPois = [
    { id: 'poi_ah_shanhaijing_central', x: 18.0, y: 55.0, type: 'capital_city', name: "Shanhaijing Central Academy", subRegion: 'al_haoung', description: "The heart of the Shanhaijing district. A beautiful academy of traditional architecture, serene gardens, and fierce martial arts dojos.", factionId: 'shanhaijing_senior_secondary_school', intelReq: 10, political_influence: 8, economic_value: 7, military_strength: 8, population: 8000 },
    { id: 'poi_ah_plum_blossom_garden', x: 16.0, y: 52.0, type: 'landmark', name: "Plum Blossom Garden", subRegion: 'al_haoung', description: "The student council's meeting place. A picturesque garden where political alliances are formed and broken over games of Go and cups of tea.", factionId: 'shanhaijing_senior_secondary_school', intelReq: 25, political_influence: 9, economic_value: 4, military_strength: 5, population: 50 },
    { id: 'poi_ah_xuanlong_office', x: 20.0, y: 50.0, type: 'barracks', name: "Xuanlong Office", subRegion: 'al_haoung', description: "The headquarters for Shanhaijing's elite enforcers. They are masters of espionage and information warfare, often clashing with Millennium's Veritas.", factionId: 'shanhaijing_senior_secondary_school', intelReq: 30, political_influence: 7, economic_value: 3, military_strength: 8, population: 200 },
    { id: 'poi_ah_black_tortoise_promenade', x: 22.0, y: 58.0, type: 'market', name: "Black Tortoise Promenade", subRegion: 'al_haoung', description: "A bustling market street known for its exotic food stalls, alchemy shops, and traditional medicine merchants. A hub of commerce and information.", factionId: 'unaligned', intelReq: 5, political_influence: 4, economic_value: 9, military_strength: 3, population: 3000 },
    { id: 'poi_ah_alchemist_society', x: 15.5, y: 58.0, type: 'workshop', name: "Alchemist Society Workshop", subRegion: 'al_haoung', description: "A workshop filled with bubbling cauldrons and strange ingredients, where students practice the esoteric arts of potion-making and alchemy.", factionId: 'shanhaijing_senior_secondary_school', intelReq: 20, political_influence: 5, economic_value: 6, military_strength: 4, population: 300 },
    { id: 'poi_ah_training_dojo', x: 23.0, y: 53.0, type: 'barracks', name: "Martial Arts Training Dojo", subRegion: 'al_haoung', description: "A large dojo where students practice various forms of martial arts. The training is intense and the discipline is absolute.", factionId: 'shanhaijing_senior_secondary_school', intelReq: 15, political_influence: 4, economic_value: 2, military_strength: 7, population: 800 },
    { id: 'poi_ah_archive_pagoda', x: 14.5, y: 50.0, type: 'library', name: "The Archive Pagoda", subRegion: 'al_haoung', description: "A tall pagoda that serves as the academy's library, housing ancient scrolls on philosophy, history, and the mystical arts.", factionId: 'shanhaijing_senior_secondary_school', intelReq: 20, political_influence: 6, economic_value: 3, military_strength: 4, population: 50 },
    { id: 'poi_ah_bamboo_forest', x: 19.0, y: 62.0, type: 'forest', name: "Whispering Bamboo Forest", subRegion: 'al_haoung', description: "A serene but maze-like bamboo forest on the outskirts of the district. A perfect place for ambushes or secret training.", factionId: 'unaligned', intelReq: 10, political_influence: 1, economic_value: 2, military_strength: 3, population: 0 },
    { id: 'poi_ah_eastern_gate', x: 24.5, y: 48.0, type: 'watchtower', name: "The Eastern Gate", subRegion: 'al_haoung', description: "A grand, ornate gate that marks the main entrance to the Shanhaijing district. It is heavily guarded by Xuanlong agents.", factionId: 'shanhaijing_senior_secondary_school', intelReq: 10, political_influence: 4, economic_value: 3, military_strength: 7, population: 100 },
    { id: 'poi_ah_hot_pot_paradise', x: 17.0, y: 47.0, type: 'inn', name: "Hot Pot Paradise", subRegion: 'al_haoung', description: "A famous restaurant known for its legendary, and rumored to be magically enhanced, hot pot. A neutral ground for all students.", factionId: 'unaligned', intelReq: 5, political_influence: 3, economic_value: 6, military_strength: 2, population: 80 },
];
export const alhaoungData = {
    pointsOfInterest: alhaoungPois,
    fogOfWar: []
};
