// map-data/kivotos/grand_latin.js

const pois = [
    { id: "poi_gl_senate_hall", x: 70, y: 58, type: "capital_city", subRegion: "grand_latin", name: "The Senate Hall", description: "A grand, columned building where student councils from various traditionalist schools in the district meet to debate policy. Nominally aligned with Trinity's values.", factionId: "trinity_general_school", intelReq: 20, political_influence: 8, economic_value: 4, military_strength: 5, population: 500 },
    { id: "poi_gl_aetherium_library", x: 71.15, y: 52.57, type: "library", subRegion: "grand_latin", name: "Aetherium Library", description: "An ancient library rumored to hold forbidden texts and pre-GSU history. Its archives are vast but poorly organized and guarded by a stern librarian golem.", factionId: "unaligned", intelReq: 35, political_influence: 5, economic_value: 3, military_strength: 4, population: 50 },
    { id: "poi_gl_artisan_quarter", x: 69.91, y: 60.45, type: "market", subRegion: "grand_latin", name: "Artisan Quarter", description: "A district known for its skilled craftspeople and luxury goods. A hub for Trinity's more artistically inclined students.", factionId: "trinity_general_school", intelReq: 10, political_influence: 4, economic_value: 8, military_strength: 3, population: 2000 },
    { id: "poi_gl_remedial_knights_hq", x: 72.19, y: 55.74, type: "barracks", subRegion: "grand_latin", name: "Remedial Knights HQ", description: "The headquarters and primary hospital for Trinity's medical and emergency response club. A place of healing and sanctuary.", factionId: "trinity_general_school", intelReq: 15, political_influence: 6, economic_value: 4, military_strength: 6, population: 800 },
    { id: "poi_gl_justice_task_force_hq", x: 68.0, y: 55.0, type: "fortress", name: "Justice Task Force HQ", subRegion: "grand_latin", description: "The imposing headquarters of Trinity's primary peacekeeping force. From here, they dispatch patrols to enforce the academy's strict code of conduct.", factionId: "trinity_general_school", intelReq: 25, political_influence: 7, economic_value: 3, military_strength: 9, population: 1000 },
    { id: "poi_gl_trinity_cathedral", x: 65.0, y: 50.0, type: "temple", name: "Trinity Grand Cathedral", subRegion: "grand_latin", description: "The magnificent, soaring cathedral at the heart of the Trinity district. It is a symbol of their faith and tradition, and a place of quiet contemplation.", factionId: "trinity_general_school", intelReq: 5, political_influence: 9, economic_value: 5, military_strength: 6, population: 1200 },
    { id: "poi_gl_riveria_park", x: 67.8, y: 51.9, type: "landmark", name: "Riveria Park", subRegion: "grand_latin", description: "A beautiful, meticulously maintained park that often serves as a neutral ground for meetings between Trinity and Gehenna students. The site of many 'duels'.", factionId: "unaligned", intelReq: 5, political_influence: 3, economic_value: 2, military_strength: 2, population: 300 },
    { id: "poi_gl_sisterhood_priory", x: 62.5, y: 54.0, type: "monastery", name: "The Sisterhood Priory", subRegion: "grand_latin", description: "A secluded priory where members of the Sisterhood live a life of prayer and study. They are the keepers of Trinity's most sacred texts and traditions.", factionId: "trinity_general_school", intelReq: 40, political_influence: 6, economic_value: 2, military_strength: 5, population: 100 },
    { id: "poi_gl_tea_party_garden", x: 64.3, y: 47.8, type: "landmark", name: "The Tea Party's Garden", subRegion: "grand_latin", description: "An exclusive, beautifully manicured garden where the leaders of Trinity's factions meet. A place of immense political power and subtle intrigue.", factionId: "trinity_general_school", intelReq: 50, political_influence: 9, economic_value: 3, military_strength: 6, population: 20 },
    { id: "poi_gl_make_up_work_club", x: 73.4, y: 62.1, type: "outpost", name: "Make-Up Work Club Hideout", subRegion: "grand_latin", description: "A ramshackle, fortified clubhouse that is the base for a club of students who have been held back. They are surprisingly effective problem-solvers.", factionId: "trinity_general_school", intelReq: 15, political_influence: 4, economic_value: 3, military_strength: 5, population: 5 },
    { id: "poi_gl_trinity_library", x: 66.2, y: 49.5, type: "library", name: "Trinity Great Library", subRegion: "grand_latin", description: "The main library of Trinity, containing vast collections on history, philosophy, and theology. Its head librarian is notoriously strict about overdue books.", factionId: "trinity_general_school", intelReq: 10, political_influence: 7, economic_value: 4, military_strength: 4, population: 300 },
    { id: "poi_gl_vigilante_crew_hideout", x: 61.8, y: 61.3, type: "lair", name: "Vigilante Crew Hideout", subRegion: "grand_latin", description: "A hideout in the old city ruins for a self-proclaimed 'vigilante' group from Trinity. They mean well, but their methods often cause more problems than they solve.", factionId: "trinity_general_school", intelReq: 20, political_influence: 2, economic_value: 1, military_strength: 4, population: 20 },
    { id: "poi_gl_eastern_gate", x: 75.0, y: 65.0, type: "watchtower", name: "The Eastern Gate", subRegion: "grand_latin", description: "A fortified gate marking the border of the Trinity district. It is heavily guarded by the Justice Task Force to prevent incursions from Gehenna.", factionId: "trinity_general_school", intelReq: 15, political_influence: 4, economic_value: 2, military_strength: 8, population: 150 },
    { id: "poi_gl_ancient_aqueducts", x: 60.0, y: 45.0, type: "ruins", name: "Ancient Aqueducts", subRegion: "grand_latin", description: "The crumbling remains of a massive aqueduct system. Its shadowed archways provide cover for those looking to move unseen through the district.", factionId: "unaligned", intelReq: 20, political_influence: 1, economic_value: 2, military_strength: 2, population: 0 }
];

export const grandLatinPois = pois;
