// map-data/kivotos/NewAmerica.js
export const newAmericaPois = [
    { id: 'poi_na_rabbit_squad_camp', x: 86.0, y: 32.0, type: 'outpost', name: "Kouzen Park (RABBIT Squad Camp)", subRegion: 'new_america', description: "The current base of operations for the RABBIT Squad after SRT Academy was closed. They survive here using their advanced military training and whatever they can scavenge.", factionId: 'unaligned', intelReq: 25, political_influence: 3, economic_value: 2, military_strength: 6, population: 4 },
    { id: 'poi_na_srt_academy_ruins', x: 80.0, y: 28.0, type: 'ruins', name: "Abandoned SRT Academy", subRegion: 'new_america', description: "The former elite academy, now shut down by the GSU. The campus is locked down and patrolled by Valkyrie police, but holds valuable equipment and data.", factionId: 'general_student_union', intelReq: 30, political_influence: 4, economic_value: 5, military_strength: 5, population: 20 },
    { id: 'poi_na_valkyrie_checkpoint', x: 88.0, y: 36.0, type: 'watchtower', name: "Valkyrie Security Checkpoint", subRegion: 'new_america', description: "A checkpoint set up by the Valkyrie Police Academy to monitor traffic in and out of the district and to prevent the RABBIT Squad from causing trouble.", factionId: 'general_student_union', intelReq: 15, political_influence: 3, economic_value: 2, military_strength: 6, population: 30 },
    { id: 'poi_na_survival_training_ground', x: 78.0, y: 35.0, type: 'barracks', name: "Survivalist Training Ground", subRegion: 'new_america', description: "An old training ground where the RABBIT squad hones their survival skills, practicing trapping, foraging, and camouflage.", factionId: 'unaligned', intelReq: 20, political_influence: 1, economic_value: 2, military_strength: 4, population: 0 },
    { id: 'poi_na_black_market_vending', x: 90.0, y: 30.0, type: 'market', name: "Black Market Vending Machine", subRegion: 'new_america', description: "A discreetly located vending machine that sells illegal ammunition and military rations. A vital, if expensive, supply point for the RABBIT squad.", factionId: 'freelancer_underworld', intelReq: 20, political_influence: 2, economic_value: 5, military_strength: 1, population: 1 },
    { id: 'poi_na_old_comms_tower', x: 83.0, y: 38.0, type: 'landmark', name: "Old Comms Tower", subRegion: 'new_america', description: "A derelict communications tower that, if repaired, could be used to intercept Valkyrie communications or broadcast messages.", factionId: 'unaligned', intelReq: 15, political_influence: 2, economic_value: 3, military_strength: 2, population: 0 },
    { id: 'poi_na_hunting_grounds', x: 77.0, y: 38.0, type: 'forest', name: "Wilderness Hunting Grounds", subRegion: 'new_america', description: "A stretch of rugged wilderness where the RABBIT squad hunts for food. The area is also home to dangerous, mutated wildlife.", factionId: 'unaligned', intelReq: 10, political_influence: 1, economic_value: 3, military_strength: 3, population: 0 },
    { id: 'poi_na_forgotten_bunker', x: 81.0, y: 31.0, type: 'dungeon_entrance', name: "Forgotten Military Bunker", subRegion: 'new_america', description: "A sealed underground bunker from a previous conflict. It may contain valuable supplies or dangerous old technology.", factionId: 'unaligned', intelReq: 40, political_influence: 1, economic_value: 5, military_strength: 3, population: 0 },
    { id: 'poi_na_freedom_statue', x: 92.0, y: 34.0, type: 'landmark', name: "Statue of the 'Fox of Justice'", subRegion: 'new_america', description: "A local landmark depicting a legendary vigilante. The RABBIT squad sees it as a symbol of their own struggle for justice.", factionId: 'unaligned', intelReq: 5, political_influence: 2, economic_value: 1, military_strength: 1, population: 0 },
    { id: 'poi_na_scrap_heap', x: 76.0, y: 32.0, type: 'ruins', name: "Urban Scrap Heap", subRegion: 'new_america', description: "A junkyard of old vehicles and electronics. A source for spare parts to repair the RABBIT squad's high-tech equipment.", factionId: 'unaligned', intelReq: 10, political_influence: 1, economic_value: 4, military_strength: 1, population: 10 },
];
export const newAmericaData = {
    pointsOfInterest: newAmericaPois,
    fogOfWar: []
};
