// map-data/kivotos/NewCairo.js
export const newCairoPois = [
    { id: 'poi_nc_abydos_high', x: 65.0, y: 25.0, type: 'academy', name: "Abydos High School", subRegion: 'new_cairo', description: "The main building of the debt-ridden school. It's old and in disrepair, but the five remaining students of the Foreclosure Task Force defend it with their lives.", factionId: 'abydos_high_school', intelReq: 10, political_influence: 4, economic_value: 2, military_strength: 5, population: 5 },
    { id: 'poi_nc_foreclosure_task_force_office', x: 78.0, y: 30.0, type: 'outpost', name: "Kaiser PMC Loan Office", subRegion: 'new_cairo', description: "The local office for the Kaiser Corporation's loan division, which holds Abydos's massive debt. It is heavily fortified and staffed by PMCs.", factionId: 'freelancer_underworld', intelReq: 20, political_influence: 6, economic_value: 8, military_strength: 7, population: 100 },
    { id: 'poi_nc_sand_sea', x: 70.0, y: 18.0, type: 'landmark', name: "The Great Sand Sea", subRegion: 'new_cairo', description: "The vast, empty desert that has slowly swallowed the rest of the Abydos district. It is known for its harsh sandstorms and hidden dangers.", factionId: 'unaligned', intelReq: 5, political_influence: 1, economic_value: 2, military_strength: 2, population: 0 },
    { id: 'poi_nc_hoshino_napping_spot', x: 62.0, y: 28.0, type: 'landmark', name: "Hoshino's Secret Napping Spot", subRegion: 'new_cairo', description: "A surprisingly comfortable spot behind a half-buried billboard where the lazy but powerful leader of the Task Force, Hoshino, can often be found sleeping.", factionId: 'abydos_high_school', intelReq: 15, political_influence: 1, economic_value: 1, military_strength: 1, population: 1 },
    { id: 'poi_nc_shibasedo_ramen', x: 68.0, y: 32.0, type: 'inn', name: "Ramen Shop 'Shibasedo'", subRegion: 'new_cairo', description: "The Abydos students' favorite ramen shop. The owner is friendly and often helps them out, making it a safe haven and informal base of operations.", factionId: 'unaligned', intelReq: 10, political_influence: 3, economic_value: 5, military_strength: 2, population: 10 },
    { id: 'poi_nc_abandoned_bank', x: 75.0, y: 25.0, type: 'ruins', name: "Abandoned Bank", subRegion: 'new_cairo', description: "A sand-filled bank that was abandoned during the debt crisis. It is rumored to hold data that could help alleviate Abydos's debt, but is also a hideout for local delinquents.", factionId: 'unaligned', intelReq: 25, political_influence: 2, economic_value: 6, military_strength: 3, population: 30 },
    { id: 'poi_nc_desert_oasis', x: 58.0, y: 20.0, type: 'oasis', name: "Desert Oasis", subRegion: 'new_cairo', description: "A rare and vital source of fresh water in the desert. Control of this oasis is a strategic priority for anyone operating in the region.", factionId: 'unaligned', intelReq: 10, political_influence: 2, economic_value: 5, military_strength: 2, population: 0 },
    { id: 'poi_nc_ancient_ruins', x: 60.0, y: 18.0, type: 'ruins', name: "Ancient Desert Ruins", subRegion: 'new_cairo', description: "The crumbling ruins of a civilization that predates Kivotos. They are filled with strange artifacts and dangerous automated defense systems.", factionId: 'unaligned', intelReq: 40, political_influence: 2, economic_value: 6, military_strength: 4, population: 0 },
    { id: 'poi_nc_makeshift_firing_range', x: 72.0, y: 35.0, type: 'barracks', name: "Makeshift Firing Range", subRegion: 'new_cairo', description: "An area in the abandoned city outskirts where the Abydos students practice their marksmanship, using old signs and wrecked cars for targets.", factionId: 'abydos_high_school', intelReq: 10, political_influence: 1, economic_value: 1, military_strength: 3, population: 0 },
    { id: 'poi_nc_helmet_gang_outpost', x: 80.0, y: 22.0, type: 'lair', name: "Helmet Gang Oasis Outpost", subRegion: 'new_cairo', description: "A fortified outpost used by the Helmet Gang to control a smaller oasis and run their smuggling operations in the desert.", factionId: 'freelancer_underworld', intelReq: 15, political_influence: 2, economic_value: 4, military_strength: 4, population: 80 },
];
export const newCairoData = {
    pointsOfInterest: newCairoPois,
    fogOfWar: []
};
