// map-data/kivotos/SouthernAureanPole.js
export const southernAureanPolePois = [
    { id: 'poi_sp_nameless_priests_ruins', x: 20.0, y: 86.0, type: 'ruins', name: "Ruins of the Nameless Priests", subRegion: 'southern_aurean_pole', description: "The vast, cryptic ruins of a forgotten religion. These ruins are a source of immense power and are central to the plans of the enigmatic group Gematria.", factionId: 'unaligned', intelReq: 70, political_influence: 3, economic_value: 6, military_strength: 6, population: 0 },
    { id: 'poi_sp_decagrammaton_anomaly', x: 40.0, y: 90.5, type: 'ley_line', name: "Decagrammaton Anomaly Point", subRegion: 'southern_aurean_pole', description: "A location where reality is thin, causing strange physical and magical phenomena. A source of cryptic prophecies from the AI prophet Decagrammaton.", factionId: 'cybernetic_collectives', intelReq: 75, political_influence: 4, economic_value: 5, military_strength: 5, population: 0 },
    { id: 'poi_sp_ark_of_atrahasis', x: 30.0, y: 88.0, type: 'landmark', name: "The Ark of Atrahasis", subRegion: 'southern_aurean_pole', description: "A colossal, half-buried object of unknown origin, believed to be a superweapon or a sanctuary from an ancient, forgotten civilization.", factionId: 'unaligned', intelReq: 80, political_influence: 3, economic_value: 7, military_strength: 7, population: 0 },
    { id: 'poi_sp_gematria_observation_post', x: 15.0, y: 88.0, type: 'outpost', name: "Gematria Observation Post", subRegion: 'southern_aurean_pole', description: "A hidden, high-tech outpost from which the members of Gematria observe and manipulate events across Kivotos.", factionId: 'cosmic_jesters', intelReq: 95, political_influence: 6, economic_value: 3, military_strength: 6, population: 4 },
    { id: 'poi_sp_crystalline_forest', x: 5.0, y: 88.0, type: 'forest', name: "Unexplained Crystalline Forest", subRegion: 'southern_aurean_pole', description: "A forest where all the trees and wildlife have been transformed into shimmering, sentient crystal. The cause of the phenomenon is unknown.", factionId: 'unaligned', intelReq: 30, political_influence: 1, economic_value: 5, military_strength: 4, population: 0 },
    { id: 'poi_sp_automata_graveyard', x: 50.0, y: 91.0, type: 'ruins', name: "Automata Graveyard", subRegion: 'southern_aurean_pole', description: "A vast dumping ground for defunct and destroyed combat androids from all over Kivotos. A rich source for scavengers, but guarded by rogue, malfunctioning units.", factionId: 'unaligned', intelReq: 25, political_influence: 1, economic_value: 6, military_strength: 5, population: 20 },
    { id: 'poi_sp_reality_rift', x: 60.0, y: 91.5, type: 'portal', name: "Rift in Reality", subRegion: 'southern_aurean_pole', description: "An unstable, shimmering tear in the fabric of spacetime that occasionally spits out strange objects or creatures from other dimensions.", factionId: 'unaligned', intelReq: 60, political_influence: 2, economic_value: 4, military_strength: 6, population: 0 },
    { id: 'poi_sp_sanctum_of_false_gods', x: 25.0, y: 90.0, type: 'dungeon_entrance', name: "Sanctum of the False Gods", subRegion: 'southern_aurean_pole', description: "An underground temple complex where powerful entities mimicking angels and demons are imprisoned. A place of immense danger and forbidden power.", factionId: 'unaligned', intelReq: 85, political_influence: 3, economic_value: 6, military_strength: 8, population: 0 },
    { id: 'poi_sp_library_of_unseen', x: 10.0, y: 86.0, type: 'library', name: "The Library of the Unseen", subRegion: 'southern_aurean_pole', description: "A mythical library said to contain all the truths of Kivotos that have been forgotten or deliberately erased. Its location is a secret known to very few.", factionId: 'unaligned', intelReq: 90, political_influence: 5, economic_value: 5, military_strength: 3, population: 1 },
    { id: 'poi_sp_silent_leviathan', x: 45.0, y: 88.0, type: 'lair', name: "The Silent Leviathan", subRegion: 'southern_aurean_pole', description: "The colossal, petrified remains of a creature so large that it forms a small mountain range. Its origins and the cause of its demise are a complete mystery.", factionId: 'unaligned', intelReq: 35, political_influence: 2, economic_value: 4, military_strength: 3, population: 0 },
];
export const southernAureanPoleData = {
    pointsOfInterest: southernAureanPolePois,
    fogOfWar: []
};
