// map-data/middle-earth/AlHaoung.js

export const alHaoungData = {
    pointsOfInterest: [
        { id: 'poi_ah_jade_palace', x: 19.31, y: 55.02, type: 'capital_city', name: "The Jade Palace", description: "The magnificent palace of the ruling Emperor, carved from a single, colossal block of jade. A place of intricate courtly politics and serene beauty.", factionId: 'unaligned', intelReq: 10, political_influence: 9, economic_value: 8, military_strength: 7 },
        { id: 'poi_ah_shrouded_monastery', x: 18.56, y: 62.65, type: 'monastery', name: "Shrouded Mountain Monastery", description: "A hidden monastery perched high in the mist-shrouded mountains. Its monks are masters of a mystical martial art.", factionId: 'unaligned', intelReq: 35, political_influence: 4, economic_value: 2, military_strength: 6 },
        { id: 'poi_ah_cherry_grove', x: 14.86, y: 50.55, type: 'forest', name: "The Whispering Cherry Grove", description: "An ancient grove of cherry trees that are said to whisper prophecies to those who listen. A place of great spiritual significance.", factionId: 'unaligned', intelReq: 20, political_influence: 3, economic_value: 3, military_strength: 2 },
        { id: 'poi_ah_terracotta_legion', x: 24.44, y: 47.23, type: 'barracks', name: "The Terracotta Legion's Barrows", description: "Vast underground pits containing thousands of life-sized terracotta soldiers, built to guard the first Emperor in the afterlife. Some say they can be awakened.", factionId: 'unaligned', intelReq: 45, political_influence: 2, economic_value: 5, military_strength: 8 },
        { id: 'poi_ah_silk_market', x: 15.67, y: 58.18, type: 'market', name: "The Silk Market", description: "A bustling, vibrant market where the finest silks, spices, and teas are traded. A hub of commerce and a source of valuable rumors.", factionId: 'freelancer_underworld', intelReq: 15, political_influence: 4, economic_value: 10, military_strength: 3 },
        { id: 'poi_ah_river_of_lanterns', x: 18.19, y: 50.55, type: 'river', name: "The River of a Thousand Lanterns", description: "A wide, gentle river that flows through the heart of the kingdom. During festivals, thousands of paper lanterns are released onto its waters.", factionId: 'unaligned', intelReq: 5, political_influence: 2, economic_value: 5, military_strength: 2 },
        { id: 'poi_ah_bamboo_maze', x: 13.62, y: 56.85, type: 'landmark', name: "The Bamboo Forest Maze", description: "A dense forest of giant bamboo that forms a natural, ever-changing labyrinth. It is said to be impossible to navigate without a guide.", factionId: 'unaligned', intelReq: 25, political_influence: 1, economic_value: 2, military_strength: 3 },
        { id: 'poi_ah_ancestral_shrine', x: 22.48, y: 65.31, type: 'shrine', name: "Shrine of the Ancestors", description: "A grand shrine where the Emperor and his people pay respects to their ancestors. A place of deep cultural importance and quiet power.", factionId: 'unaligned', intelReq: 10, political_influence: 7, economic_value: 2, military_strength: 3 },
        { id: 'poi_ah_onyx_hand_outpost', x: 25.65, y: 47.56, type: 'lair', name: "Onyx Hand Outpost", description: "A secret, hidden courtyard house that serves as a base of operations for the Onyx Hand, who seek to corrupt the kingdom's nobility from within.", factionId: 'onyx_hand', intelReq: 50, political_influence: 3, economic_value: 2, military_strength: 5 },
        { id: 'poi_ah_great_wall', x: 21.08, y: 60.33, type: 'fortress', name: "The Great Wall Segment", description: "A section of a massive, ancient wall built to protect the kingdom from nomadic horsemen from the plains. It is manned by elite soldiers.", factionId: 'unaligned', intelReq: 20, political_influence: 4, economic_value: 3, military_strength: 8 },
        { id: 'poi_ah_dragon_spire', x: 24.81, y: 52.88, type: 'mountain_pass', name: "The Dragon's Spire", description: "The highest mountain peak in the kingdom, shaped like a coiled dragon. It is said to be the home of a wise and ancient celestial dragon.", factionId: 'unaligned', intelReq: 60, political_influence: 2, economic_value: 4, military_strength: 5 },
        { id: 'poi_ah_rice_paddies', x: 14.65, y: 44.74, type: 'farm', name: "The Endless Rice Paddies", description: "Vast, terraced rice paddies that feed the nation. A testament to the people's harmony with the land.", factionId: 'unaligned', intelReq: 5, political_influence: 2, economic_value: 9, military_strength: 1 },
        { id: 'poi_ah_forbidden_city', x: 19.96, y: 50.55, type: 'castle', name: "The Forbidden City", description: "An inner sanctum of the Jade Palace, accessible only to the Emperor and his most trusted advisors. A place of immense secrecy and power.", factionId: 'unaligned', intelReq: 70, political_influence: 8, economic_value: 4, military_strength: 6 },
        { id: 'poi_ah_tea_house', x: 13.06, y: 54.53, type: 'inn', name: "The Whispering Tea House", description: "An elegant tea house known for its serene atmosphere and as a neutral ground where rivals can meet to negotiate without fear of violence.", factionId: 'unaligned', intelReq: 15, political_influence: 4, economic_value: 5, military_strength: 2 },
        { id: 'poi_ah_fireworks_workshop', x: 22.11, y: 45.41, type: 'workshop', name: "Master Lee's Fireworks Workshop", description: "The workshop of the greatest fireworks master in the land. His creations are works of art, but also surprisingly potent explosives.", factionId: 'unaligned', intelReq: 10, political_influence: 2, economic_value: 6, military_strength: 3 },
    ],
    fogOfWar: []
};
