// map-data/middle-earth/Austelarassia.js

export const austelarassiaData = {
    pointsOfInterest: [
        { id: 'poi_au_sunstone_capital', x: 31.96, y: 71.93, type: 'capital_city', name: "Sunstone Capital", description: "A bustling coastal city known for its vibrant arts scene and its lucrative trade in rare desert opals. A beacon of civilization on an untamed continent.", factionId: 'unaligned', intelReq: 10, political_influence: 7, economic_value: 9, military_strength: 5 },
        { id: 'poi_au_great_sandy', x: 38.07, y: 66.80, type: 'landmark', name: "The Great Sandy Desert", description: "A vast, scorching desert that covers much of the continent's interior. It is home to giant sandworms and nomadic tribes.", factionId: 'unaligned', intelReq: 20, political_influence: 1, economic_value: 3, military_strength: 4 },
        { id: 'poi_au_uluru_monolith', x: 37.12, y: 72.93, type: 'ley_line', name: "Uluru Monolith", description: "A colossal, red rock that rises from the desert floor. It is a place of immense spiritual power, sacred to the nomadic tribes.", factionId: 'unaligned', intelReq: 40, political_influence: 4, economic_value: 2, military_strength: 2 },
        { id: 'poi_au_great_billabong', x: 34.23, y: 75.26, type: 'oasis', name: "The Great Billabong", description: "A massive, permanent waterhole surrounded by lush vegetation. A vital oasis for both wildlife and travelers in the arid lands.", factionId: 'unaligned', intelReq: 5, political_influence: 2, economic_value: 6, military_strength: 1 },
        { id: 'poi_au_didgeridoo_caves', x: 32.28, y: 67.46, type: 'cave_entrance', name: "Didgeridoo Deep Caves", description: "A network of limestone caves where the wind creates a constant, low humming sound. The caves are filled with ancient paintings.", factionId: 'unaligned', intelReq: 25, political_influence: 2, economic_value: 3, military_strength: 2 },
        { id: 'poi_au_emu_plains', x: 40.02, y: 71.29, type: 'farm', name: "The Emu Plains", description: "Wide, grassy plains that are home to massive flocks of aggressive, flightless birds. Their eggs are a valuable food source.", factionId: 'unaligned', intelReq: 10, political_influence: 1, economic_value: 5, military_strength: 3 },
        { id: 'poi_au_kangaroo_point', x: 43.09, y: 74.60, type: 'outpost', name: "Kangaroo Point", description: "A rugged coastal outlook known for its population of giant, muscular kangaroos who are known to challenge visitors to boxing matches.", factionId: 'unaligned', intelReq: 15, political_influence: 1, economic_value: 2, military_strength: 4 },
        { id: 'poi_au_wreck_endeavour', x: 44.59, y: 76.91, type: 'shipwreck', name: "Wreck of the Endeavour II", description: "The wreck of an Imperial exploration vessel that ran aground centuries ago. A potential source of salvageable magitek.", factionId: 'unaligned', intelReq: 35, political_influence: 1, economic_value: 6, military_strength: 1 },
        { id: 'poi_au_nomad_camp', x: 39.93, y: 64.98, type: 'village', name: "Nomad Camp", description: "A temporary camp of the desert-dwelling nomadic tribes. They are masters of survival and know the secrets of the outback.", factionId: 'unaligned', intelReq: 10, political_influence: 3, economic_value: 2, military_strength: 3 },
        { id: 'poi_au_opal_mines', x: 35.53, y: 66.80, type: 'mine', name: "The Opal Mines", description: "A series of dangerous, unstable mines that are the world's primary source of fire opals. Controlled by a ruthless mining guild.", factionId: 'freelancer_underworld', intelReq: 30, political_influence: 2, economic_value: 9, military_strength: 4 },
        { id: 'poi_au_croc_river', x: 34.42, y: 70.45, type: 'river', name: "The Croc-Infested River", description: "A wide, muddy river that is home to colossal, prehistoric crocodiles. Crossing it is a perilous endeavor.", factionId: 'unaligned', intelReq: 15, political_influence: 1, economic_value: 2, military_strength: 5 },
        { id: 'poi_au_spider_forest', x: 31.06, y: 74.77, type: 'forest', name: "Spider-Silk Forest", description: "A forest where the trees are draped in the webs of giant, bird-eating spiders. Their silk is incredibly strong and valuable.", factionId: 'unaligned', intelReq: 25, political_influence: 1, economic_value: 5, military_strength: 5 },
        { id: 'poi_au_gorge', x: 42.16, y: 68.96, type: 'mountain_pass', name: "The Great Dividing Gorge", description: "A massive canyon that splits the continent. A key strategic chokepoint, with few safe crossings.", factionId: 'unaligned', intelReq: 10, political_influence: 2, economic_value: 1, military_strength: 3 },
        { id: 'poi_au_dreamtime_nexus', x: 42.44, y: 72.60, type: 'ley_line', name: "Dreamtime Nexus", description: "A sacred site where the veil to the spirit world is thin. Tribal shamans come here to commune with ancestors and the spirits of the land.", factionId: 'unaligned', intelReq: 50, political_influence: 4, economic_value: 2, military_strength: 2 },
        { id: 'poi_au_outback_fortress', x: 30.04, y: 79.40, type: 'fortress', name: "The Outback Fortress", description: "A fortified settlement built by desperate colonists, constantly under siege by the harsh environment and its monstrous inhabitants. A bastion of grim determination.", factionId: 'unaligned', intelReq: 20, political_influence: 3, economic_value: 2, military_strength: 6 },
    ],
    fogOfWar: []
};
