// map-data/middle-earth/Eriador.js

export const eriadorData = {
    pointsOfInterest: [
        // --- MOVED & REPOSITIONED POIs ---
        {
            id: 'poi_me_rivendell',
            x: 48.00, y: 28.00,
            type: 'capital_city',
            subRegion: 'eriador',
            name: "The Hidden Valley of Rivendell (Imladris)",
            description: "The Last Homely House East of the Sea, the home of Elrond Half-elven. A hidden valley of peace and ancient wisdom, protected by Elven magic. A sanctuary for the wise and the weary.",
            factionId: 'elves_of_lindon',
            intelReq: 60,
            political_influence: 9,
            economic_value: 5,
            military_strength: 7,
            population: 400,
            age_of_antiquity: 10,
            magical_resonance: 10,
            crime_rate: 1,
        },
        {
            id: 'poi_me_bree',
            x: 35.00, y: 36.00,
            type: 'town',
            subRegion: 'eriador',
            name: "The Town of Bree",
            description: "A bustling town of Men and Hobbits, located at the crossing of the Great East Road and the Greenway. Its centerpiece is the famous inn, 'The Prancing Pony'. A place where all paths seem to meet.",
            factionId: 'unaligned',
            intelReq: 10,
            political_influence: 4,
            economic_value: 7,
            military_strength: 3,
            population: 1500,
            age_of_antiquity: 7,
            magical_resonance: 2,
            crime_rate: 4,
        },
        {
            id: 'poi_me_fornost_ruins',
            x: 35.00, y: 20.00,
            type: 'ruins',
            subRegion: 'eriador',
            name: "Ruins of Fornost Erain",
            description: "The sprawling, dead ruins of the former capital of the northern kingdom of Arnor. Now known as Deadmen's Dike, it is a place of great evil, haunted by Orcs and darker things.",
            factionId: 'mordor',
            intelReq: 30,
            political_influence: 3,
            economic_value: 4,
            military_strength: 6,
            population: 0,
            age_of_antiquity: 9,
            magical_resonance: 8,
            crime_rate: 9,
        },
        {
            id: 'poi_me_shire',
            x: 28.00, y: 37.00,
            type: 'farm',
            subRegion: 'eriador',
            name: "The Shire",
            description: "A peaceful and idyllic land, home to the Hobbits. A land of rolling hills, small woods, and quiet farms. Its borders are watched by Rangers, but the Hobbits themselves are largely unaware of the dangers of the outside world.",
            factionId: 'unaligned',
            intelReq: 10,
            political_influence: 2,
            economic_value: 7,
            military_strength: 1,
            population: 10000,
            age_of_antiquity: 6,
            magical_resonance: 3,
            crime_rate: 1,
        },
        {
            id: 'poi_me_white_towers',
            x: 23.00, y: 35.00,
            type: 'watchtower',
            subRegion: 'eriador',
            name: "The White Towers of Emyn Beraid",
            description: "Three ancient and tall towers built upon the Tower Hills. The tallest, Elostirion, holds a Palantír, a seeing-stone that looks only west, back towards the Undying Lands.",
            factionId: 'elves_of_lindon',
            intelReq: 35,
            political_influence: 6,
            economic_value: 3,
            military_strength: 6,
            population: 30,
            age_of_antiquity: 10,
            magical_resonance: 9,
            crime_rate: 1,
        },
        {
            id: 'poi_me_trollshaws',
            x: 42.00, y: 32.00,
            type: 'forest',
            subRegion: 'eriador',
            name: "The Trollshaws",
            description: "A dark and dangerous forest, named for the three stone trolls who were turned to stone by Gandalf. It is a wild and untamed land, where foolish travelers can easily lose their way.",
            factionId: 'unaligned',
            intelReq: 25,
            political_influence: 1,
            economic_value: 2,
            military_strength: 4,
            population: 0,
            age_of_antiquity: 8,
            magical_resonance: 5,
            crime_rate: 8,
        },
        {
            id: 'poi_me_sarn_ford',
            x: 31.00, y: 45.00,
            type: 'landmark',
            subRegion: 'eriador',
            name: "Sarn Ford",
            description: "A stony ford across the Baranduin (Brandywine) River, marking the traditional southern border of the Shire. It is guarded by Rangers of the North to protect the Hobbits from the dangers of the south.",
            factionId: 'kingdom_of_gondor',
            intelReq: 20,
            political_influence: 2,
            economic_value: 3,
            military_strength: 5,
            population: 10,
            age_of_antiquity: 8,
            magical_resonance: 2,
            crime_rate: 2,
        },
        {
            id: 'poi_me_tharbad',
            x: 42.00, y: 45.00,
            type: 'ruins',
            subRegion: 'eriador',
            name: "The Ruins of Tharbad",
            description: "The sprawling ruins of a once-great city straddling the Gwathló. The great bridge that was its heart is now broken, and the city is a haunted place, a testament to the long decay of the North-kingdom.",
            factionId: 'unaligned',
            intelReq: 25,
            political_influence: 3,
            economic_value: 5,
            military_strength: 4,
            population: 100,
            age_of_antiquity: 9,
            magical_resonance: 6,
            crime_rate: 8,
        },
        {
            id: 'poi_me_lond_daer',
            x: 32.00, y: 50.00,
            type: 'ruins',
            subRegion: 'eriador',
            name: "Lond Daer Enedh (The Great Middle Haven)",
            description: "The ancient, ruined port built by the Númenóreans in the Second Age. Once a great haven, it is now a windswept ruin sinking into the marshes, haunted by the memory of the great forests that were destroyed to build its fleets.",
            factionId: 'unaligned',
            intelReq: 40,
            political_influence: 2,
            economic_value: 4,
            military_strength: 3,
            population: 0,
            age_of_antiquity: 10,
            magical_resonance: 7,
            crime_rate: 6,
        },
        {
            id: 'poi_me_eryn_vorn',
            x: 30.00, y: 45.00,
            type: 'forest',
            subRegion: 'eriador',
            name: "Eryn Vorn (The Dark Forest)",
            description: "A dark and foreboding forest on a cape jutting into the sea. It is one of the few remnants of the ancient forests of Eriador and is home to a reclusive, unfriendly people, said to be kin to the Folk of Haleth.",
            factionId: 'unaligned',
            intelReq: 35,
            political_influence: 3,
            economic_value: 2,
            military_strength: 4,
            population: 500,
            age_of_antiquity: 10,
            magical_resonance: 5,
            crime_rate: 7,
        },
        {
            id: 'poi_me_blue_mountains_north',
            x: 26.00, y: 22.00,
            type: 'mountain_pass',
            subRegion: 'eriador',
            name: "Northern Passes of the Blue Mountains (Ered Luin)",
            description: "The western passes of the ancient Blue Mountains, home to several reclusive Dwarven holds. These mountains form a formidable barrier between Forlindon and the lands to the east.",
            factionId: 'kingdoms_of_the_dwarves',
            intelReq: 10,
            political_influence: 4,
            economic_value: 7,
            military_strength: 6,
            population: 1500,
            age_of_antiquity: 10,
            magical_resonance: 5,
            crime_rate: 4,
        },
        {
            id: 'poi_me_blue_mountains_south',
            x: 26.50, y: 32.00,
            type: 'mountain_pass',
            subRegion: 'eriador',
            name: "Southern Passes of the Blue Mountains",
            description: "The southern passes of the Ered Luin, where several major Dwarven cities such as Nogrod and Belegost once stood. The passes are still used for trade, though the great cities are now ruins.",
            factionId: 'kingdoms_of_the_dwarves',
            intelReq: 10,
            political_influence: 4,
            economic_value: 6,
            military_strength: 5,
            population: 500,
            age_of_antiquity: 10,
            magical_resonance: 5,
            crime_rate: 5,
        },
        {
            id: 'poi_me_belegost_ruins',
            x: 25.50, y: 20.00,
            type: 'ruins',
            subRegion: 'eriador',
            name: "Ruins of Belegost",
            description: "The ruins of the second great Dwarven city. Belegost was known for its masons and its famed Dragon-helm. The city fell into ruin after the War of Wrath, but its stone halls remain, a testament to Dwarven craft.",
            factionId: 'kingdoms_of_the_dwarves',
            intelReq: 40,
            political_influence: 2,
            economic_value: 6,
            military_strength: 4,
            population: 0,
            age_of_antiquity: 10,
            magical_resonance: 6,
            crime_rate: 7,
        },
        {
            id: 'poi_me_nogrod_ruins',
            x: 26.00, y: 30.00,
            type: 'ruins',
            subRegion: 'eriador',
            name: "Ruins of Nogrod",
            description: "The delvings of one of the two great Dwarven cities of the Blue Mountains, now a ruin. It was famed for its master smiths, and it is said that lost treasures still lie buried in its deepest halls, guarded by Orcs.",
            factionId: 'kingdoms_of_the_dwarves',
            intelReq: 40,
            political_influence: 2,
            economic_value: 6,
            military_strength: 4,
            population: 0,
            age_of_antiquity: 10,
            magical_resonance: 6,
            crime_rate: 8,
        },

        // --- NEW POIs ---
        {
            id: 'poi_me_hobbiton',
            x: 27.00, y: 36.00,
            type: 'village',
            subRegion: 'eriador',
            name: "Hobbiton-on-the-Hill",
            description: "A quintessential Hobbit village nestled in the rolling hills of the Shire. Known for its cozy Hobbit-holes with round doors, the Green Dragon Inn, and the famous Bag End.",
            factionId: 'unaligned',
            intelReq: 10,
            political_influence: 1,
            economic_value: 5,
            military_strength: 1,
            population: 600,
            age_of_antiquity: 6,
            magical_resonance: 2,
            crime_rate: 1,
        },
        {
            id: 'poi_me_prancing_pony',
            x: 35.20, y: 36.50,
            type: 'inn',
            subRegion: 'eriador',
            name: "The Prancing Pony Inn",
            description: "A famous and ancient inn in the town of Bree, a meeting place for Men, Hobbits, and the occasional Dwarf or Wizard. A place where news from all corners of the world can be heard.",
            factionId: 'unaligned',
            intelReq: 15,
            political_influence: 4,
            economic_value: 6,
            military_strength: 2,
            population: 50,
            age_of_antiquity: 8,
            magical_resonance: 1,
            crime_rate: 5,
        },
        {
            id: 'poi_me_barrow_downs',
            x: 33.00, y: 39.00,
            type: 'haunted_place',
            subRegion: 'eriador',
            name: "The Barrow-downs",
            description: "A series of ancient, rolling hills east of the Old Forest, crowned with the burial mounds of the first kings of Men. The area is haunted by malevolent spirits known as Barrow-wights.",
            factionId: 'unaligned',
            intelReq: 35,
            political_influence: 1,
            economic_value: 3,
            military_strength: 5,
            population: 0,
            age_of_antiquity: 10,
            magical_resonance: 8,
            crime_rate: 9,
        },
        {
            id: 'poi_me_tom_bombadil_house',
            x: 31.00, y: 39.00,
            type: 'landmark',
            subRegion: 'eriador',
            name: "House of Tom Bombadil",
            description: "A small, cheerful house under the side of a hill on the edge of the Old Forest. It is the home of Tom Bombadil, an ancient and powerful being who is master of the woods, water, and hill.",
            factionId: 'unaligned',
            intelReq: 70,
            political_influence: 3,
            economic_value: 2,
            military_strength: 10,
            population: 2,
            age_of_antiquity: 10,
            magical_resonance: 10,
            crime_rate: 1,
        },
        {
            id: 'poi_me_old_forest',
            x: 31.00, y: 37.00,
            type: 'forest',
            subRegion: 'eriador',
            name: "The Old Forest",
            description: "A dark, ancient forest on the border of the Shire. The trees are said to be alive and hostile, and the paths within shift and change to confuse travelers. A place of deep, strange magic.",
            factionId: 'unaligned',
            intelReq: 30,
            political_influence: 1,
            economic_value: 3,
            military_strength: 4,
            population: 0,
            age_of_antiquity: 10,
            magical_resonance: 7,
            crime_rate: 8,
        },
        {
            id: 'poi_me_amon_sul',
            x: 40.50, y: 34.80,
            type: 'watchtower',
            subRegion: 'eriador',
            name: "Amon Sûl (Weathertop)",
            description: "The great watchtower that once crowned the Weather Hills. Now only a ring of broken stone remains, but it still offers an unparalleled view of the surrounding lands and is of great strategic importance.",
            factionId: 'kingdom_of_gondor',
            intelReq: 25,
            political_influence: 2,
            economic_value: 1,
            military_strength: 6,
            population: 0,
            age_of_antiquity: 9,
            magical_resonance: 6,
            crime_rate: 6,
        },
        {
            id: 'poi_me_last_bridge',
            x: 44.00, y: 33.00,
            type: 'bridge',
            subRegion: 'eriador',
            name: "The Last Bridge",
            description: "The ancient stone bridge that carries the Great East Road over the river Hoarwell. It marks the edge of the Trollshaws and is a key chokepoint guarded by the Rangers.",
            factionId: 'unaligned',
            intelReq: 20,
            political_influence: 2,
            economic_value: 2,
            military_strength: 5,
            population: 0,
            age_of_antiquity: 9,
            magical_resonance: 2,
            crime_rate: 5,
        },
        {
            id: 'poi_me_mount_gram',
            x: 40.00, y: 19.00,
            type: 'lair',
            subRegion: 'eriador',
            name: "Mount Gram",
            description: "A grim, lonely mountain in the north that is a known stronghold of Orcs and Goblins. From here, they launch raids into the lands of Men.",
            factionId: 'mordor',
            intelReq: 45,
            political_influence: 2,
            economic_value: 2,
            military_strength: 7,
            population: 1500,
            age_of_antiquity: 7,
            magical_resonance: 3,
            crime_rate: 10,
        },
        {
            id: 'poi_me_annuminas',
            x: 30.00, y: 25.00,
            type: 'ruins',
            subRegion: 'eriador',
            name: "Ruins of Annúminas",
            description: "The ancient city of the Kings of Arnor, now silent and empty on the shores of Lake Evendim. It is a place of ghosts and memories, where the treasures of the lost kingdom are said to lie.",
            factionId: 'kingdom_of_gondor',
            intelReq: 50,
            political_influence: 4,
            economic_value: 6,
            military_strength: 4,
            population: 0,
            age_of_antiquity: 9,
            magical_resonance: 8,
            crime_rate: 6,
        },
        {
            id: 'poi_me_lake_evendim',
            x: 31.00, y: 24.00,
            type: 'landmark',
            subRegion: 'eriador',
            name: "Lake Evendim (Nenuial)",
            description: "A large, beautiful lake whose waters are said to be clear as glass. The ruins of Annúminas lie upon its shores, and the air is filled with a sense of peace and ancient power.",
            factionId: 'unaligned',
            intelReq: 20,
            political_influence: 2,
            economic_value: 3,
            military_strength: 2,
            population: 0,
            age_of_antiquity: 10,
            magical_resonance: 7,
            crime_rate: 2,
        },
        {
            id: 'poi_me_bucklebury_ferry',
            x: 30.00, y: 38.00,
            type: 'trade_post',
            subRegion: 'eriador',
            name: "Bucklebury Ferry",
            description: "A small ferry that crosses the Brandywine River, connecting the Shire to the lands of Buckland. It is a vital link for Hobbits and a symbol of their close-knit community.",
            factionId: 'unaligned',
            intelReq: 10,
            political_influence: 1,
            economic_value: 4,
            military_strength: 1,
            population: 10,
            age_of_antiquity: 5,
            magical_resonance: 1,
            crime_rate: 1,
        },
        {
            id: 'poi_me_midgewater_marshes',
            x: 38.00, y: 37.00,
            type: 'swamp',
            subRegion: 'eriador',
            name: "The Midgewater Marshes",
            description: "A vast, murky swamp east of Bree, known for its thick fogs and swarms of biting midges. A difficult and unpleasant land to cross, it is largely avoided by travelers.",
            factionId: 'unaligned',
            intelReq: 15,
            political_influence: 0,
            economic_value: 1,
            military_strength: 2,
            population: 0,
            age_of_antiquity: 9,
            magical_resonance: 3,
            crime_rate: 5,
        },
        {
            id: 'poi_me_cardolan_ruins',
            x: 38.00, y: 48.00,
            type: 'ruins',
            subRegion: 'eriador',
            name: "The Desolation of Cardolan",
            description: "The sparsely populated and ruined lands of the former kingdom of Cardolan. The region was devastated by plague and war, and is now a land of silent ruins and lonely fields.",
            factionId: 'unaligned',
            intelReq: 30,
            political_influence: 1,
            economic_value: 2,
            military_strength: 3,
            population: 100,
            age_of_antiquity: 9,
            magical_resonance: 5,
            crime_rate: 7,
        },
        {
            id: 'poi_me_rhudaur_ruins',
            x: 45.00, y: 37.00,
            type: 'ruins',
            subRegion: 'eriador',
            name: "The Angle of Rhudaur",
            description: "The wild, hilly lands of the former kingdom of Rhudaur. It became a thrall of Angmar long ago and is now a savage land, home to hill-men and other evil creatures.",
            factionId: 'mordor',
            intelReq: 35,
            political_influence: 1,
            economic_value: 2,
            military_strength: 5,
            population: 200,
            age_of_antiquity: 9,
            magical_resonance: 6,
            crime_rate: 9,
        },
        {
            id: 'poi_me_ettenmoors',
            x: 47.00, y: 24.00,
            type: 'lair',
            subRegion: 'eriador',
            name: "The Ettenmoors",
            description: "A high, cold plateau north of Rivendell, infested with Trolls and Orcs. A dangerous and forbidding land that serves as a buffer against the evil of the north.",
            factionId: 'mordor',
            intelReq: 40,
            political_influence: 1,
            economic_value: 2,
            military_strength: 6,
            population: 0,
            age_of_antiquity: 10,
            magical_resonance: 4,
            crime_rate: 9,
        },
    ],
    fogOfWar: [

    ]
};