// map-data/middle-earth/GrandLatin.js

export const grandLatinData = {
    pointsOfInterest: [
        { id: 'poi_gl_colosseum_ruins', x: 67.87, y: 50.55, type: 'ruins', name: "Colosseum Ruins", description: "The magnificent, crumbling ruins of a grand colosseum. The ghosts of gladiators are said to still battle in its arena on moonless nights.", factionId: 'unaligned', intelReq: 15, political_influence: 4, economic_value: 4, military_strength: 3 },
        { id: 'poi_gl_burnt_forum', x: 68.91, y: 55.08, type: 'ruins', name: "The Burnt Forum", description: "The political heart of the old empire, now a field of shattered marble and toppled statues. A place of immense historical significance.", factionId: 'unaligned', intelReq: 20, political_influence: 5, economic_value: 3, military_strength: 2 },
        { id: 'poi_gl_mount_vesuvio', x: 70.97, y: 49.38, type: 'volcano', name: "Mount Vesuvio", description: "A dormant, but still smoking, volcano that looms over the ruins. Its eruption is what sealed the empire's fate.", factionId: 'unaligned', intelReq: 30, political_influence: 1, economic_value: 4, military_strength: 5 },
        { id: 'poi_gl_sunken_library', x: 70.52, y: 58.74, type: 'library', name: "Sunken Library of Scipio", description: "The marsh-swallowed ruins of the greatest library of the old world. Lost knowledge and powerful scrolls may still be preserved within its flooded halls.", factionId: 'unaligned', intelReq: 60, political_influence: 3, economic_value: 6, military_strength: 2, library_summary: "The library is flooded and in ruins, but some waterproofed scrolls may yet contain the military strategies and philosophical treatises of the fallen empire.", libraryStockKey: 'provincial_archives' },
        { id: 'poi_gl_aqueduct', x: 67.54, y: 60.10, type: 'landmark', name: "Aqueduct of the Ancients", description: "A massive, miraculously intact aqueduct that still carries fresh water from the mountains. A testament to the empire's engineering prowess.", factionId: 'unaligned', intelReq: 10, political_influence: 2, economic_value: 5, military_strength: 1 },
        { id: 'poi_gl_legates_palace', x: 65.25, y: 57.69, type: 'castle', name: "Legate's Palace", description: "The ruined palace of the last emperor. It is rumored to be haunted and to contain a hidden vault with the imperial treasury.", factionId: 'unaligned', intelReq: 45, political_influence: 4, economic_value: 7, military_strength: 3 },
        { id: 'poi_gl_gladiator_pits', x: 66.01, y: 52.88, type: 'barracks', name: "Gladiator Training Pits", description: "The training grounds for the colosseum's gladiators. Now a camp for a brutal band of Rebel Clans who follow a similar code of combat.", factionId: 'rebel_clans', intelReq: 25, political_influence: 3, economic_value: 2, military_strength: 5 },
        { id: 'poi_gl_oracle_cave', x: 69.94, y: 63.32, type: 'cave_entrance', name: "The Oracle's Cave", description: "A hidden cave where a mysterious oracle once gave cryptic prophecies to the emperors. Faint magical energy still lingers here.", factionId: 'unaligned', intelReq: 50, political_influence: 2, economic_value: 3, military_strength: 1 },
        { id: 'poi_gl_imperial_road', x: 71.34, y: 53.05, type: 'trade_post', name: "The Old Imperial Road", description: "A remarkably well-preserved stone road that once connected the entire empire. It is now a dangerous but direct route for travelers.", factionId: 'unaligned', intelReq: 5, political_influence: 2, economic_value: 4, military_strength: 1 },
        { id: 'poi_gl_catacombs', x: 63.15, y: 58.02, type: 'dungeon_entrance', name: "The Catacombs", description: "A sprawling network of tombs beneath the ancient capital. Now a den for ghouls and other foul creatures.", factionId: 'unaligned', intelReq: 30, political_influence: 1, economic_value: 2, military_strength: 4 },
        { id: 'poi_gl_watchtower', x: 63.81, y: 54.27, type: 'watchtower', name: "Fallen Watchtower", description: "A ruined watchtower that once guarded the northern approach. It offers a commanding view of the surrounding plains.", factionId: 'unaligned', intelReq: 10, political_influence: 1, economic_value: 1, military_strength: 2 },
        { id: 'poi_gl_thermal_baths', x: 60.91, y: 78.24, type: 'landmark', name: "The Grand Thermal Baths", description: "Geothermally heated public baths, now in ruins. The waters are still warm and are said to have healing properties.", factionId: 'unaligned', intelReq: 20, political_influence: 2, economic_value: 4, military_strength: 1 },
        { id: 'poi_gl_manticore_lair', x: 80.00, y: 80.00, type: 'lair', name: "Manticore Lair", description: "The high, inaccessible cliffs are the nesting ground of a fierce Manticore that preys on any who venture too deep into the ruins.", factionId: 'unaligned', intelReq: 40, political_influence: 1, economic_value: 2, military_strength: 6 },
        { id: 'poi_gl_vineyards', x: 65.58, y: 84.21, type: 'farm', name: "The Overgrown Vineyards", description: "The vineyards that produced the empire's legendary wine. The grapes now grow wild, and are jealously guarded by territorial beasts.", factionId: 'unaligned', intelReq: 15, political_influence: 1, economic_value: 5, military_strength: 2 },
        { id: 'poi_gl_imperial_quarry', x: 74.79, y: 86.37, type: 'quarry', name: "Imperial Marble Quarry", description: "The quarry that supplied the pristine white marble for the empire's grand structures. It is now abandoned and eerily silent.", factionId: 'unaligned', intelReq: 10, political_influence: 1, economic_value: 4, military_strength: 1 },
    ],
    fogOfWar: []
};
