// map-data/middle-earth/Minhiriath.js

export const minhiriathData = {
    pointsOfInterest: [
        {
            id: 'poi_me_tharbad',
            x: 42.5, y: 32.0,
            type: 'ruins',
            subRegion: 'minhiriath',
            name: "The Ruins of Tharbad",
            description: "The sprawling ruins of a once-great city straddling the Gwathló. The great bridge that was its heart is now broken, and the city is a haunted place, a testament to the long decay of the North-kingdom.",
            factionId: 'unaligned',
            intelReq: 25,
            political_influence: 3,
            economic_value: 5,
            military_strength: 4,
            population: 100,
            age_of_antiquity: 9,
            magical_resonance: 6,
            crime_rate: 8,
        },
        {
            id: 'poi_me_lond_daer',
            x: 39.0, y: 39.5,
            type: 'ruins',
            subRegion: 'minhiriath',
            name: "Lond Daer Enedh (The Great Middle Haven)",
            description: "The ancient, ruined port built by the Númenóreans in the Second Age. Once a great haven, it is now a windswept ruin sinking into the marshes, haunted by the memory of the great forests that were destroyed to build its fleets.",
            factionId: 'unaligned',
            intelReq: 40,
            political_influence: 2,
            economic_value: 4,
            military_strength: 3,
            population: 0,
            age_of_antiquity: 10,
            magical_resonance: 7,
            crime_rate: 6,
        },
        {
            id: 'poi_me_eryn_vorn',
            x: 28.0, y: 44.0,
            type: 'forest',
            subRegion: 'minhiriath',
            name: "Eryn Vorn (The Dark Forest)",
            description: "A dark and foreboding forest on a cape jutting into the sea. It is one of the few remnants of the ancient forests of Eriador and is home to a reclusive, unfriendly people, said to be kin to the Folk of Haleth.",
            factionId: 'unaligned',
            intelReq: 35,
            political_influence: 3,
            economic_value: 2,
            military_strength: 4,
            population: 500,
            age_of_antiquity: 10,
            magical_resonance: 5,
            crime_rate: 7,
        },
        {
            id: 'poi_me_sarn_ford',
            x: 32.0, y: 37.0,
            type: 'landmark',
            subRegion: 'minhiriath',
            name: "Sarn Ford",
            description: "A stony ford across the Baranduin (Brandywine) River, marking the traditional southern border of the Shire. It is guarded by Rangers of the North to protect the Hobbits from the dangers of the south.",
            factionId: 'unaligned',
            intelReq: 20,
            political_influence: 2,
            economic_value: 3,
            military_strength: 5,
            population: 10,
            age_of_antiquity: 8,
            magical_resonance: 2,
            crime_rate: 2,
        },
        {
            id: 'poi_me_haleth_village_1',
            x: 35.0, y: 42.0,
            type: 'village',
            subRegion: 'minhiriath',
            name: "The Settlement of the Wood-folk",
            description: "A small, secretive village of Men who live on the fringes of Eryn Vorn. They are a remnant of the pre-Númenórean peoples and are fiercely independent and suspicious of outsiders.",
            factionId: 'unaligned',
            intelReq: 30,
            political_influence: 2,
            economic_value: 3,
            military_strength: 3,
            population: 300,
            age_of_antiquity: 9,
            magical_resonance: 4,
            crime_rate: 4,
        },
        {
            id: 'poi_me_greenway_watch',
            x: 41.0, y: 28.0,
            type: 'ruins',
            subRegion: 'minhiriath',
            name: "Ruined Greenway Watchtower",
            description: "The crumbling remains of a watchtower along the old North-South Road. It now serves as a den for bandits and other unsavory creatures who prey on the few travelers in these empty lands.",
            factionId: 'unaligned',
            intelReq: 15,
            political_influence: 1,
            economic_value: 1,
            military_strength: 2,
            population: 20,
            age_of_antiquity: 8,
            magical_resonance: 2,
            crime_rate: 9,
        },
        {
            id: 'poi_me_gwathlo_marshes',
            x: 40.0, y: 37.0,
            type: 'swamp',
            subRegion: 'minhiriath',
            name: "The Swanfleet Marshes (Nîn-in-Eilph)",
            description: "Vast marshes at the confluence of the Gwathló and Glanduin rivers, known for their large population of swans. The area is treacherous and largely uninhabited, save for strange creatures of the bog.",
            factionId: 'unaligned',
            intelReq: 20,
            political_influence: 1,
            economic_value: 2,
            military_strength: 2,
            population: 0,
            age_of_antiquity: 10,
            magical_resonance: 5,
            crime_rate: 3,
        },
        {
            id: 'poi_me_dunlending_camp',
            x: 44.0, y: 30.0,
            type: 'bandit_camp',
            subRegion: 'minhiriath',
            name: "Dunlending Raider Camp",
            description: "An encampment of wild hill-men from Dunland. They often cross the Gwathló to raid the desolate lands of Minhiriath, driven by ancient hatred for the descendants of Númenor.",
            factionId: 'unaligned',
            intelReq: 25,
            political_influence: 2,
            economic_value: 1,
            military_strength: 5,
            population: 150,
            age_of_antiquity: 2,
            magical_resonance: 1,
            crime_rate: 9,
        }
    ],
    fogOfWar: [

    ]
};
