// map-data/middle-earth/NewAmerica.js

export const newAmericaData = {
    pointsOfInterest: [
        { id: 'poi_na_i95_fortress', x: 77.24, y: 35.12, type: 'fortress', name: "I-95 Fortress", description: "A massive fortress built from the wreckage of a multi-lane highway overpass. A key strategic chokepoint controlled by a well-armed survivor faction.", factionId: 'the_unchained', intelReq: 20, political_influence: 6, economic_value: 4, military_strength: 8 },
        { id: 'poi_na_rust_bowl', x: 80.22, y: 25.17, type: 'village', name: "Rust Bowl Stadium Settlement", description: "The ruins of a massive sports stadium, now a fortified, self-sufficient settlement. A hub of trade and a beacon of fragile civilization in the wastes.", factionId: 'unaligned', intelReq: 10, political_influence: 5, economic_value: 6, military_strength: 5 },
        { id: 'poi_na_concrete_jungle', x: 83.40, y: 24.84, type: 'ruins', name: "The Concrete Jungle", description: "The skeletal remains of a dense downtown area, its skyscrapers now crumbling, vine-choked towers. A dangerous place to scavenge, full of mutated beasts.", factionId: 'unaligned', intelReq: 25, political_influence: 1, economic_value: 4, military_strength: 4 },
        { id: 'poi_na_the_mall', x: 79.52, y: 30.15, type: 'market', name: "The Grand Mall", description: "A sprawling, semi-intact shopping mall that has become the primary black market for the region. Run by the Ratchet Raiders, it's the best place to find scrap and pre-fall tech.", factionId: 'ratchet_raiders', intelReq: 15, political_influence: 3, economic_value: 8, military_strength: 4 },
        { id: 'poi_na_washington_obelisk', x: 86.99, y: 35.12, type: 'landmark', name: "The Broken Obelisk", description: "The cracked and leaning remains of a towering monument from the old world. A symbol of a lost age of power and unity.", factionId: 'unaligned', intelReq: 5, political_influence: 2, economic_value: 1, military_strength: 1 },
        { id: 'poi_na_ghoul_town', x: 89.26, y: 30.15, type: 'haunted_place', name: "Ghoul Town", description: "A suburban area that was hit hard by whatever destroyed the old world. It is now infested with feral, irradiated ghouls.", factionId: 'unaligned', intelReq: 30, political_influence: 0, economic_value: 2, military_strength: 6 },
        { id: 'poi_na_freedom_radio', x: 75.65, y: 39.10, type: 'watchtower', name: "Freedom Radio Tower", description: "An old radio tower, re-purposed by The Unchained to broadcast messages of rebellion and hope across the wasteland.", factionId: 'the_unchained', intelReq: 25, political_influence: 4, economic_value: 1, military_strength: 3 },
        { id: 'poi_na_scrap_barons_fort', x: 77.99, y: 31.48, type: 'lair', name: "The Scrap Baron's Fort", description: "The personal fortress of the most powerful Ratchet Raider leader, built entirely from scavenged military hardware.", factionId: 'ratchet_raiders', intelReq: 35, political_influence: 4, economic_value: 5, military_strength: 7 },
        { id: 'poi_na_potomac_river', x: 84.81, y: 35.12, type: 'river', name: "The Irradiated Potomac River", description: "A wide, sluggish river with a sickly green glow. Its waters are highly toxic, but it serves as a formidable defensive barrier.", factionId: 'unaligned', intelReq: 10, political_influence: 1, economic_value: 1, military_strength: 2 },
        { id: 'poi_na_vault_76', x: 93.38, y: 37.45, type: 'dungeon_entrance', name: "Vault 76", description: "The sealed entrance to a massive underground vault, said to hold pristine, pre-fall technology and knowledge. Opening it is the dream of every scavenger.", factionId: 'unaligned', intelReq: 60, political_influence: 2, economic_value: 9, military_strength: 5 },
    ],
    fogOfWar: []
};
