// map-data/middle-earth/NewCairo.js

export const newCairoData = {
    pointsOfInterest: [
        { id: 'poi_nc_pyramid_hub', x: 70.83, y: 17.54, type: 'capital_city', name: "The Great Pyramid Data-Hub", description: "The center of New Cairo. A colossal pyramid made of shimmering data--blocks that serves as the city's power source, central server, and government seat.", factionId: 'unaligned', intelReq: 10, political_influence: 9, economic_value: 9, military_strength: 8 },
        { id: 'poi_nc_cyber_sphinx', x: 67.35, y: 22.02, type: 'landmark', name: "The Cyber-Sphinx", description: "A gigantic, robotic sphinx that guards the entrance to the Data-Hub. It is a powerful war machine that asks deadly riddles of all who would seek entry.", factionId: 'unaligned', intelReq: 30, political_influence: 3, economic_value: 3, military_strength: 7 },
        { id: 'poi_nc_holographic_bazaar', x: 64.09, y: 21.19, type: 'market', name: "Holographic Bazaar of Khan el-Khalili", description: "A chaotic, bustling marketplace where vendors sell everything from cybernetic upgrades to rare data-spices via holographic storefronts.", factionId: 'freelancer_underworld', intelReq: 15, political_influence: 4, economic_value: 10, military_strength: 3 },
        { id: 'poi_nc_digital_nile', x: 78.43, y: 31.14, type: 'river', name: "The Digital Nile", description: "A great river of pure, flowing data that irrigates the city's information economy. To fall in is to have your consciousness digitized and scattered.", factionId: 'unaligned', intelReq: 20, political_influence: 2, economic_value: 7, military_strength: 2 },
        { id: 'poi_nc_silicon_kings', x: 76.96, y: 34.79, type: 'dungeon_entrance', name: "The Valley of the Silicon Kings", description: "The vast server farms where the consciousnesses of the city's founding AIs are stored. A digital necropolis guarded by rogue Anubis-bots.", factionId: 'unaligned', intelReq: 50, political_influence: 3, economic_value: 6, military_strength: 6 },
        { id: 'poi_nc_alexandria_aic', x: 74.53, y: 24.50, type: 'library', name: "The Alexandria.aic Library", description: "A digital library that aims to contain a copy of every piece of data ever created. It is maintained by a benevolent, but fiercely protective, Librarian AI.", factionId: 'unaligned', intelReq: 25, political_influence: 6, economic_value: 5, military_strength: 4, library_summary: "A digital library containing copies of all known public texts. Its AI librarian can be... particular about due dates.", libraryStockKey: 'internet' },
        { id: 'poi_nc_scarab_bots', x: 65.30, y: 38.61, type: 'workshop', name: "Scarab-Bot Factories", description: "Factories that produce swarms of beetle-like utility bots. They maintain the city's infrastructure but can be repurposed for military use.", factionId: 'unaligned', intelReq: 20, political_influence: 2, economic_value: 7, military_strength: 5 },
        { id: 'poi_nc_data_merchant_embassy', x: 58.86, y: 26.50, type: 'trade_post', name: "Data Merchant Guild Embassy", description: "The regional headquarters of the Data Merchant Guilds. From here, they seek to control the flow of information and profit from the city's unique data resources.", factionId: 'data_merchant_guilds', intelReq: 30, political_influence: 5, economic_value: 8, military_strength: 4 },
        { id: 'poi_nc_mummy_crypts', x: 55.04, y: 27.83, type: 'haunted_place', name: "The Cryo-Mummy Crypts", description: "Ancient tombs where the city's founders are kept in perfect cryo-stasis. A malfunction has caused their digital ghosts to haunt the facility.", factionId: 'unaligned', intelReq: 40, political_influence: 2, economic_value: 4, military_strength: 3 },
        { id: 'poi_nc_solar_barge_docks', x: 80.60, y: 27.66, type: 'port', name: "Solar Barge Docks", description: "Docks for the great solar-powered sand-skiffs that traverse the surrounding deserts. A hub for trade and transport.", factionId: 'unaligned', intelReq: 10, political_influence: 3, economic_value: 6, military_strength: 2 },
        { id: 'poi_nc_ra_cult_temple', x: 84.14, y: 22.69, type: 'temple', name: "Temple of the Sun-God Ra.AI", description: "A temple where a cult of tech-priests worships the city's primary power core as a living god, believing its light is the source of all life and data.", factionId: 'unaligned', intelReq: 25, political_influence: 4, economic_value: 2, military_strength: 3 },
        { id: 'poi_nc_iron_legion_outpost', x: 54.76, y: 20.53, type: 'outpost', name: "Iron Legion Observation Post", description: "A discreet, heavily-shielded outpost where the Iron Legion monitors the technological advancements of New Cairo with great interest.", factionId: 'iron_legion', intelReq: 45, political_influence: 3, economic_value: 1, military_strength: 6 },
        { id: 'poi_nc_mirage_projectors', x: 58.58, y: 30.65, type: 'landmark', name: "The Mirage Projectors", description: "A series of powerful holographic projectors that create a shimmering, illusory dome over the city, protecting it from the harsh desert sun and concealing it from outsiders.", factionId: 'unaligned', intelReq: 20, political_influence: 2, economic_value: 4, military_strength: 3 },
        { id: 'poi_nc_set_gang_hideout', x: 60.35, y: 33.13, type: 'lair', name: "Set's Gang Hideout", description: "The hideout of a dangerous gang of data-thieves who worship the chaotic trickster god-program, Set. They seek to bring down the city's ordered system.", factionId: 'freelancer_underworld', intelReq: 35, political_influence: 2, economic_value: 3, military_strength: 5 },
        { id: 'poi_nc_obelisk_of_light', x: 75.47, y: 12.57, type: 'watchtower', name: "The Great Obelisk of Light", description: "A towering obelisk that serves as the city's primary communications antenna, broadcasting data across the deserts. A key strategic asset.", factionId: 'unaligned', intelReq: 15, political_influence: 3, economic_value: 5, military_strength: 4 },
    ],
    fogOfWar: []
};
