// map-data/middle-earth/SouthernAureanPole.js

export const southernAureanPoleData = {
    pointsOfInterest: [
        { id: 'poi_sp_singularity_anomaly', x: 30.60, y: 87.89, type: 'portal', name: "The Singularity Anomaly", description: "A point of collapsed spacetime that defies all known laws of physics. It appears as a perfect sphere of blackness that absorbs all light. Its purpose and origin are a terrifying mystery.", factionId: 'unaligned', intelReq: 90, political_influence: 1, economic_value: 5, military_strength: 7 },
        { id: 'poi_sp_aurora_obelisks', x: 42.07, y: 90.02, type: 'ley_line', name: "The Aurora Obelisks", description: "A ring of colossal, crystalline obelisks that pulse in time with the southern aurora. They are a source of immense, uncontrolled magical energy.", factionId: 'unaligned', intelReq: 40, political_influence: 2, economic_value: 6, military_strength: 3 },
        { id: 'poi_sp_subglacial_city', x: 19.50, y: 85.37, type: 'ruins', name: "Sub-Glacial City of Hyperborea", description: "The perfectly preserved ruins of a precursor city, located in a vast cavern beneath miles of ice. It is accessible only via a single, treacherous geothermal vent.", factionId: 'unaligned', intelReq: 60, political_influence: 2, economic_value: 8, military_strength: 4 },
        { id: 'poi_sp_silent_outpost', x: 55.43, y: 91.18, type: 'outpost', name: "The Silent Research Outpost", description: "An Imperial research station that went silent decades ago. Its logs speak of a 'sound from the ice' before communications ceased. It is now a frozen tomb.", factionId: 'unaligned', intelReq: 35, political_influence: 1, economic_value: 4, military_strength: 2 },
        { id: 'poi_sp_magnetic_nexus', x: 67.35, y: 91.67, type: 'landmark', name: "The Southern Magnetic Nexus", description: "The southern magnetic pole. The intense geomagnetic forces here disrupt all forms of magical and technological scrying, making it a perfect place to hide.", factionId: 'unaligned', intelReq: 20, political_influence: 2, economic_value: 2, military_strength: 1 },
        { id: 'poi_sp_mountain_of_madness', x: 8.95, y: 90.02, type: 'mountain_pass', name: "The Mountains of Madness", description: "A range of impossibly high, non-Euclidean peaks that are said to drive any who gaze upon them for too long to insanity.", factionId: 'unaligned', intelReq: 70, political_influence: 1, economic_value: 2, military_strength: 6 },
        { id: 'poi_sp_leviathan_graveyard', x: 2.15, y: 95.02, type: 'landmark', name: "Leviathan Graveyard", description: "A place where colossal, ancient sea creatures are flash-frozen in the icebergs. A source of valuable alchemical components and a grim spectacle.", factionId: 'unaligned', intelReq: 25, political_influence: 1, economic_value: 5, military_strength: 2 },
        { id: 'poi_sp_onyx_hand_refuge', x: 0.56, y: 88.36, type: 'lair', name: "Onyx Hand Refuge", description: "A hidden refuge for ancient vampire elders who have grown weary of the endless politics of the Onyx Hand. They sleep in the ice, waiting for the world to end.", factionId: 'onyx_hand', intelReq: 75, political_influence: 3, economic_value: 3, military_strength: 5 },
        { id: 'poi_sp_ice_storm', x: 85.20, y: 93.33, type: 'landmark', name: "The Perpetual Ice Storm", description: "A massive, stationary hurricane of ice and snow that rages eternally. At its eye is a place of unnatural calm, but reaching it is considered impossible.", factionId: 'unaligned', intelReq: 30, political_influence: 1, economic_value: 1, military_strength: 7 },
        { id: 'poi_sp_star_fall_crater', x: 10.55, y: 136.51, type: 'landmark', name: "Star-Fall Crater", description: "An ancient crater from a fallen star, its rim laced with strange, unearthly metals. The crater floor is a garden of bizarre, crystalline flora.", factionId: 'unaligned', intelReq: 40, political_influence: 1, economic_value: 7, military_strength: 3 },
    ],
    fogOfWar: []
};
