// map-data/pokemon/kalos.js
export const kalosPois = [
    { id: 'poi_ka_lumiose', x: 79.00, y: 35.00, type: 'capital_city', name: "Lumiose City", description: "The massive, sprawling capital of the Kalos region. A hub of fashion, culture, and technology, its central Prism Tower serves as a major Pokémon League landmark and a symbol of regional power.", factionId: 'pokemon_league', intelReq: 5 },
    { id: 'poi_ka_prism_tower', x: 79.20, y: 34.50, type: 'landmark', name: "Prism Tower", description: "The iconic symbol of Lumiose City. While it houses a gym, its primary strategic value is as the central power and communications hub for the entire region.", factionId: 'pokemon_league', intelReq: 15 },
    { id: 'poi_ka_santalune', x: 74.00, y: 44.00, type: 'town', name: "Santalune City", description: "A quaint city known for its beautiful gardens and the Santalune Forest to its south, a key training ground for new trainers.", factionId: 'pokemon_league', intelReq: 5 },
    { id: 'poi_ka_cyllage', x: 72.50, y: 29.00, type: 'town', name: "Cyllage City", description: "A coastal city famous for its steep hills and professional cycling culture. Its port is a major point of entry for goods into western Kalos.", factionId: 'unaligned', intelReq: 10 },
    { id: 'poi_ka_geosenge', x: 74.50, y: 38.00, type: 'village', name: "Geosenge Town", description: "A mysterious town built around a circle of ancient monoliths. It holds a deep secret and is the primary base of operations for Team Flare's ultimate weapon project.", factionId: 'unaligned', intelReq: 30 },
    { id: 'poi_ka_flare_cafe', x: 79.50, y: 35.50, type: 'lair', name: "Team Flare Secret HQ (Café)", description: "A seemingly normal café in Lumiose City that serves as the public front for Team Flare's secret headquarters. Access to the labs below is heavily guarded.", factionId: 'team_flare', intelReq: 40 },
    { id: 'poi_ka_flare_labs', x: 74.80, y: 38.50, type: 'workshop', name: "Team Flare Secret Labs", description: "The hidden, underground laboratory beneath Geosenge Town where Team Flare is developing and powering up the ultimate weapon.", factionId: 'team_flare', intelReq: 60 },
    { id: 'poi_ka_pokeball_factory', x: 83.00, y: 31.00, type: 'workshop', name: "Poké Ball Factory", description: "The primary manufacturing plant for all Poké Balls in the Kalos region. Its production is vital to the entire trainer economy and is a key strategic asset.", factionId: 'pokemon_league', intelReq: 20 },
    { id: 'poi_ka_kalos_power_plant', x: 80.00, y: 26.00, type: 'landmark', name: "Kalos Power Plant", description: "A massive power plant in the desert that supplies energy to Lumiose City and the surrounding areas. Often targeted by Team Flare for its energy needs.", factionId: 'unaligned', intelReq: 25 },
    { id: 'poi_ka_amorette', x: 75.00, y: 26.00, type: 'town', name: "Ambrette Town", description: "A coastal town with a major fossil research lab. The cliffs nearby are a rich source of ancient Pokémon fossils.", factionId: 'unaligned', intelReq: 10 },
    { id: 'poi_ka_reflection_cave', x: 75.50, y: 34.00, type: 'cave_entrance', name: "Reflection Cave", description: "A beautiful but confusing cave where the crystalline walls act like perfect mirrors. Its disorienting nature makes it a good place for a clandestine meeting.", factionId: 'unaligned', intelReq: 20 },
    { id: 'poi_ka_shalour', x: 71.50, y: 30.50, type: 'town', name: "Shalour City", description: "A coastal city that is home to the Tower of Mastery, a key site for understanding the secrets of Mega Evolution. A place of great interest to the Trainer Guild.", factionId: 'trainer_guild', intelReq: 15 },
    { id: 'poi_ka_tower_of_mastery', x: 71.00, y: 30.00, type: 'landmark', name: "Tower of Mastery", description: "An ancient tower that holds the secrets to Mega Evolution. A sacred site for trainers seeking to unlock their Pokémon's ultimate potential.", factionId: 'trainer_guild', intelReq: 45 },
    { id: 'poi_ka_coumarine', x: 74.00, y: 27.50, type: 'port', name: "Coumarine City", description: "A large port city divided by a cliff, connected by a monorail. It is a major trade hub and is fiercely independent.", factionId: 'unaligned', intelReq: 10 },
    { id: 'poi_ka_kalos_league', x: 88.00, y: 25.50, type: 'capital_city', name: "Kalos Pokémon League", description: "The headquarters of the Kalos League, housed in a magnificent castle. It serves as the final challenge for trainers and the ultimate symbol of the League's authority.", factionId: 'pokemon_league', intelReq: 50 },
    { id: 'poi_ka_victory_road', x: 86.00, y: 26.00, type: 'dungeon_entrance', name: "Kalos Victory Road", description: "A series of daunting caves and ancient ruins that a trainer must traverse to reach the Pokémon League. Patrolled by the League's strongest trainers.", factionId: 'pokemon_league', intelReq: 40 },
    { id: 'poi_ka_couriway', x: 85.00, y: 37.00, type: 'town', name: "Couriway Town", description: "A town built around a railway station, known for its scenic waterfalls and the strong bond between its people and Pokémon.", factionId: 'unaligned', intelReq: 15 },
    { id: 'poi_ka_snowbelle', x: 81.50, y: 39.00, type: 'town', name: "Snowbelle City", description: "A city located in a cold, snowy region. It is known for its challenging Ice-type gym and its proximity to the mysterious Winding Woods.", factionId: 'pokemon_league', intelReq: 20 }
];