export const BOOK_DATA = {
    title: "Magitek Theory Vol. IV: Arcane Capacitors",
    pages: [
        `...from the preface by Artificer Prime Kael.\n\nThe primitive mage treats magic as a fleeting, unpredictable force. They supplicate, they bargain, they perform their crude rituals. The magitek engineer, however, sees magic for what it is: a fundamental energy of the universe, no different from lightning or heat. It can be captured, stored, and discharged. It can be made to serve. This volume details the principles of the Arcane Capacitor, the heart of all modern magitek.`,
        `...from Chapter 2: The Mycelian Capacitor\n\nThe Ironshroom (Ferrum myces) of the Midlands presents a fascinating case study. Its metallic properties allow it to passively absorb and store ambient magical energy. While inefficient, it demonstrates the core principle: a material lattice can be attuned to hold arcane charge. Early experiments in smelting the fungus with iron led to the creation of Mycelian Steel, which retains a minor charge, giving it its superior strength.`,
        `...from Chapter 5: Crystal Matrix Attunement\n\nModern capacitors rely on precisely-cut crystals, often quartz or amethyst, attuned to a specific frequency of magical energy. The crystal matrix acts as a 'magical battery'. The challenge is not in storing the energy, but in preventing 'arcane bleed' - the slow, steady leakage of power back into the ambient environment. The use of silver filaments has proven to be an effective, if costly, insulator.`,
        `...from Chapter 8: The 'Vigilance' Power Core (Theoretical)\n\nThe power core of the IMS Vigilance represents the pinnacle of capacitor technology. It is not a single crystal, but a harmonized network of a dozen master-crystals, each handling a different aspect of the ship's power needs. The true innovation, however, is the central regulation unit, which can shunt power between capacitors instantaneously. The theoretical power output is sufficient to level a small city. The consequences of a catastrophic failure are... best left uncalculated.`,
        `...from a recently declassified addendum on Iron Legion field technology.\n\n- The 'Iron Binding' Seal: A tactical magitek application developed by the Legion's Siege Engineers. It uses a portable, single-use resonance rod to impose a 'Forge Seal' on an enemy's magical artifact or power source. This creates a harmonic dissonance that temporarily chokes the artifact's power output, reducing it by approximately 50%. The seal is unstable and typically degrades within a few hours. Its primary use is to neutralize powerful magical threats on the battlefield long enough for conventional forces to overwhelm them. The Legion is also rumored to be experimenting with using sealed artifacts to temporarily 'overcharge' their own troops, granting them a brief but powerful surge of arcane energy.`
    ]
};